### ISSUE TITLE
What happened to ARC_SANDBOX_ENABLE_CORS environment variable for the sandbox?

### ISSUE THREAD

**Issue by neilhoff** [architect/architect#1008]
I upgraded to Architect 8.2.1 and this fix for cors in the sandbox web server isn't available anymore.

The original fix was put into place with this pull request: https://github.com/architect/architect/pull/327

Was there a work-a-round or better practice put into place? How do you deal with cors in the sandbox now?

**Comment by filmaj** [comment]
I haven't tested locally, but the code you linked to in that PR is still in place here: https://github.com/architect/sandbox/blob/master/src/http/middleware/_cors.js, and it seems to be behind the same env var?

**Comment by neilhoff** [comment]
That is weird....when I used Github search it didn't find it in the code:
![image](https://user-images.githubusercontent.com/1918319/99728380-fafc0b80-2a7e-11eb-8fef-00cce45ddbac.png)

Anyway....

I am running into these cors issues again after I upgraded to 8.2.1. Do we need to set it up differently in the .arc-env file?

`arc env testing ARC_SANDBOX_ENABLE_CORS true`

**Comment by brianleroux** [comment]
wrong repo! you wanted to do an org level search https://github.com/search?q=org%3Aarchitect+ARC_SANDBOX_ENABLE_CORS&type=code

**Comment by filmaj** [comment]
@neilhoff any chance you could put together a project or gist with an arc app that shows off the incorrect behaviour?

**Comment by neilhoff** [comment]
@brianleroux Thanks!

@filmaj Will do. I am busy the rest of the day but will try and get something tomorrow morning. Thanks for the help!

**Comment by filmaj** [comment]
@neilhoff awesome! Ya busy on my end too so repro steps / a gist / a quick project I can use to reproduce would go a long ways to identifying the issue and then fixing it. Thank you!

**Comment by neilhoff** [comment]
I finally got around to debugging...

I upgraded to version 8.3.5 and created a new project using `arc init` in a folder named 'test'
Started the local server with `arc sandbox`
Navigating to http://localhost:3333 works great.

I added the environment variable for cors: `arc env testing ARC_SANDBOX_ENABLE_CORS true`
Start the local server with `arc sandbox` and everything appears normal but...

Now when I attempt to navigate to http://localhost:3333 it gets stuck at pending until it times out and fails with 
_localhost refused to connect_

System Details:

- Windows 10
- Architect 8.3.5
- Node v12.19.1

**Comment by neilhoff** [comment]
I am going to close this issue and create a new one based on ARC_SANDBOX_ENABLE_CORS causing Sandbox to hang.
