### ISSUE TITLE
websocket app upgraded from pre-8.3 to 8.3 breaks WS connect handshake

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1015]
**Describe the issue**
If you have an arc app built and deployed with a version of arc before 8.3 (i.e. 8.2.1), then upgrade to 8.3, and re-deploy it, any websocket handlers you have defined won't work. In particular, the initial connect / handshake will explode on the client with:

> WebSocket connection to 'wss://y3b0squy9b.execute-api.us-east-2.amazonaws.com/staging' failed: Error during WebSocket handshake: Unexpected response code: 500

Took me a while to dig into this. There is no trace of any invocations from the WS Connect lambda, though if you look at the 'Dashboard' of the Web Socket API Gateway instance, you can see there _are_ invocations there. I had to jump through a few hoops to get access logging from API Gateway to introspect into this. In particular I had to:

- expand the arc generated Role to have a "Trust Relationship" (who the fuck names these things?) with API Gateway (as per [this StackOverflow answer](https://stackoverflow.com/questions/46767947/aws-api-gateway-error-api-gateway-does-not-have-permission-to-assume-the-provid/46768332#46768332))
- drop the Role's ARN into the "CloudWatch log role ARN" in the Settings of the Web Socket API Gateway instance
- under the Web Socket API Gateway instance's Stages section, under the Logs/Tracing tab, set up CloudWatch logging and access logs

**Steps to reproduce**
1. Clone this handy repro repo: https://github.com/filmaj/arc-ws
2. `cd` into it and ensure the arc dependency is set to 8.2.1 in the `package.json`.
3. `npm install`
4. `arc deploy`
5. Load up the app URL, and see that you can type things into the text box, and the (web socket) server will respond with your message in ALL CAPS.
6. Now, set the arc dependency to 8.3.0 in the `package.json`.
7. `npm install`
8. `arc deploy`
9. Load up the URL again but note that things don't work. You'll see the 500 error in the browser's console.

**Expected behavior**
WebSocket stuff should work after upgrading to 8.3.0.

**Additional context**
The clue for this one was, after enabling the APIG logging, I was able to see logs like the following (on a different app so the identifiers and ARNs are different but bear with me):

```
(WlJo4EWeCGYFtwQ=) Sending request to https://lambda.eu-west-3.amazonaws.com/2015-03-31/functions/arn:aws:lambda:eu-west-3:934973137291:function:ConduitStaging-WebsocketConnect-RMG0HH229UAF/invocations
(WlJo4EWeCGYFtwQ=) Execution failed due to configuration error: Invalid permissions on Lambda function
```

The issue is that the ARN identifier used in the first line is not found in my CloudFormation stack, so API Gateway was forwarding the WS request to a non-existent Lambda. The correct Lambda name, post-upgrade, for my "Conduit" example above here, was `ConduitStaging-ConnectWSLambda-WLYYCLUKXRY6`.

After `arc destroy --force`ing the app and re-deploying, things worked again! So something with the upgrade and possibly renaming of assets due to the introduction of `inventory`?

**Comment by ryanblock** [comment]
Possibly resource name related, I'm going to look at this immediately. Thank you for flagging this!

**Comment by ryanblock** [comment]
Turns out: this was an API Gateway + CloudFormation bug on AWS's side. tldr: 8.3 introduced some CloudFormation resource name changes, which results in Lambda names changed. So CloudFormation updates the API Gateway, wires it to the new Lambdas, sets all the permissions... then doesn't deploy the API. So certain invocations wind up referencing old Lambdas from old deployments until you (or in this case, Architect) redeploy the API. So now that's happening here: https://github.com/architect/deploy/blob/master/src/sam/02-after/04-deploy-ws.js
