### ISSUE TITLE
arc 8.3: direct (dirty) deploy if your app uses `@static` blows up

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1016]
**Describe the issue**
When trying to direct deploy a single function, if your arc file uses `@static`, you will see an error of the form:

```
Error [TypeError]: Cannot read property 'endsWith' of null
    at /Users/filmaj/src/Conduit/node_modules/@architect/deploy/src/direct/deploy.js:44:41
    at Array.some (<anonymous>)
    at /Users/filmaj/src/Conduit/node_modules/@architect/deploy/src/direct/deploy.js:44:20
    at Array.filter (<anonymous>)
    at /Users/filmaj/src/Conduit/node_modules/@architect/deploy/src/direct/deploy.js:42:38
```

I added a `console.log` right before the offending line and it looks like this:

```
{
  name: 'get /*',
  config: {
    timeout: 5,
    memory: 1152,
    runtime: 'nodejs12.x',
    handler: 'index.handler',
    state: 'n/a',
    concurrency: 'unthrottled',
    layers: [],
    policies: [],
    shared: false,
    env: true,
    views: false
  },
  src: null,
  handlerFile: null,
  handlerFunction: 'handler',
  configFile: null,
  arcStaticAssetProxy: true,
  method: 'get',
  path: '/*'
}
```

**Steps to reproduce**
1. Create an arc app with the following `app.arc` using architect 8.3.0 or newer:

```
@app
arc-dirty

@http
get /yo

@static
```

2. `arc create && arc deploy`
3. Your app works, noice
4. Now try `arc deploy dirty src/http/get-yo`
5. 💥 

**Expected behavior**
That it works 😄  if you remove `@static`, it does work!

**Additional context**
Seems like the dirty deploy filtering code where the exception is happening assumes that the inventory object for each lambda contains a `src` property that is a string. In the case of the greedy `get /*` route, which I guess is what arc builds for you under the hood when you use `@static`, the inventory object for it contains a `src` property that is null. That's likely related to the root of the issue.

**Comment by filmaj** [comment]
I'm taking a look at this / adding tests along the way

**Comment by filmaj** [comment]
I've sent a PR for this here but the entire test suite fails when I added my test suite 😒 https://github.com/architect/deploy/pull/287

**Comment by ryanblock** [comment]
Confirmed fix and patched up tests, thank you Fil! Will ship today in 2.2.2 via https://github.com/architect/deploy/pull/286
