### ISSUE TITLE
Single-argument commands passed to @sandbox startup blows up

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1019]
**Describe the issue**
If you have single-argument commands in the sandbox startup scripts defined in your `preferences.arc`, sandbox will explode on startup like so:

```
⚬ Sandbox Running startup scripts
/Users/filmaj/src/Conduit/node_modules/@architect/sandbox/src/sandbox/_startup-scripts.js:16
        let command = `${cmd} ${args.join(' ')}`
                                     ^
```

**Steps to reproduce**
1. Create a new arc app
2. Add a `preferences.arc` with the following content:

```
@sandbox
startup
  echo 'Hi there!'
```
3. Run `arc sandbox`

**Expected behavior**
No explosions

**Additional context**
I'm running arc 8.3.2. A workaround I found is to provide a second argument. i.e. `echo 'Hi There!' 'really?'`. The issue seems to be that when a startup command is fed with only a single argument, [the `args` type in the sandbox startup script code](https://github.com/architect/sandbox/blob/0e2bb0738bfed7003b309b3e41dbbad604e5e732/src/sandbox/_startup-scripts.js#L13-L15) is a string. As soon as you provide two arguments, `args` turns into an array. So the assumption that `args` is an array on Line 15 in that module is the culprit here.

**Comment by ryanblock** [comment]
Hmm, this isn't reproducing for me! Will keep looking.
![image](https://user-images.githubusercontent.com/200964/100520225-8ea19c00-3151-11eb-8014-fd95f8c6203f.png)
![image](https://user-images.githubusercontent.com/200964/100520229-93fee680-3151-11eb-9430-4449088f8275.png)

**Comment by ryanblock** [comment]
Was able to repro with:
```
@sandbox
startup
  echo
```

**Comment by ryanblock** [comment]
Ok, traced this back to an order-dependence irregularity in the parser (which caused some wrong expectations in Sandbox startup script runner). Check it out:

```
# breaks
@sandbox
startup
  ls
  echo 'Hi there!'
```
```
# works
@sandbox
startup
  echo 'Hi there!'
  ls
```

Chatting with @brianleroux about how to handle this moving fwd!

**Comment by ryanblock** [comment]
Partial fix in 3.2.1: https://github.com/architect/sandbox/commit/5150868ce81a7f44bbe9057ebc99cccddad87df1

### Summary of the issue in parserland

Array case:
```
startup
  ls
  echo 'Hi there!'
```
As the first item is a string with no spaces, `startup` is parsed as an array, so you'd receive: `startup: [ 'ls', 'echo' ]` (note: lossy `'Hi there!'`)

Object case:
```
startup
  echo 'Hi there!'
  ls
```
As the first item is a string with spaces, `startup` is parsed as an object, so you'd receive:
```startup: {
 echo: [ 'Hi', 'there!' ],
 ls: []
}
```

Sounds like @brianleroux thinks a change to that behavior could be breaking and might not work, and may want to have the parser throw in these cases. Anyway, I'll let him speak to this in his own time, but I think we can close this for now with the given change, wdyt @filmaj?

**Comment by filmaj** [comment]
Ya if the parser can't be changed, then this is fine, though couldn't we wrap the (single) arg in an array and continue execution as normal instead of throwing an error?

**Comment by ryanblock** [comment]
Shouldn't be necessary – as long as the list of Sandbox startup commands begin with a multi-arg line, all other lines, even if only a single arg, will work. Under the hood, the parser is determining whether it's an object or array based on the shape of the first entry. Per above, will close for now (but definitely do not take that as a signal that we can't keep discussing)!
