### ISSUE TITLE
support additional entry files for deno runtime

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1022]
our deno runtime currently supports the following entry files: https://github.com/smallwins/begin-deno-runtime/blob/master/src/runtime.ts#L9-L17

but the sandbox only looks for `index.ts` currently; we should align these capabilities

**Comment by ryanblock** [comment]
Identified the regression, will be patched in Sandbox 3.3.1. Code is here: https://github.com/architect/sandbox/pull/532/commits/9481d33c00c53cb41a4ed18eac2802e791139421
