### ISSUE TITLE
`arc sandbox --port 8888` does not work in 8.3.5

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1023]
**Describe the issue**
You cannot provide CLI flags to sandbox using arc 8.3.5.

**Steps to reproduce**
1. Create an arc app
2. Run `arc sandbox --port 8888`
3. Sandbox still running on port 3333

**Expected behavior**
Sandbox honours the port specification

**Additional context**
I did a bit of tracing, looks like [this line](https://github.com/architect/sandbox/blob/master/src/http/index.js#L38) in sandbox's HTTP server startup module is looking for port options as a destructured object, but the CLI options are actually provided on as an array under the `options` property of the passed-in `options` parameter.. hope that makes sense.

**Comment by filmaj** [comment]
More context: the module that serves as `@architect/architect`'s entry point calls into the `sandbox/src/cli/index.js` without providing `port` explicitly as an argument on the params object (see [here](https://github.com/architect/sandbox/blob/master/src/cli/arc.js#L14-L19)), whereas the sandbox module that can be invoked directly from the cli (`sandbox/src/cli/cli.js`) [does](https://github.com/architect/sandbox/blob/master/src/cli/cli.js#L46-L52). I think that's the root of the issue.

**Comment by Munawwar** [comment]
I can confirm the same issue on v8.4.10 as well

But something even more odd happening on my machine though.
```
arc sandbox -p 3001
...
Error: Port 5000 is already in use, cannot start Sandbox
...
```
The default port is 3333. And the port specified is 3001. I am not sure why is it checking port 5000.

**Comment by filmaj** [comment]
Hmm, port in use is a different behaviour than the original issue reported here. I will try to help, but I would suggest we spin your report out into a different issue thread @Munawwar.

[Sandbox uses a few different ports](https://github.com/architect/sandbox/blob/master/src/lib/ports.js) for setting up its various local development supporting services. Port 5000 is used by default for setting up dynalite, the in-memory local version of DynamoDB. Also, some environment variables instruct sandbox to load these various port-consuming services on different ports.

Do you have any environment variables with `PORT` in its name exported? Does anything show up when you run `env | grep -i port` (assuming *nix system)?

**Comment by ryanblock** [comment]
Resolved in https://github.com/architect/sandbox/pull/629!
