### ISSUE TITLE
Sandbox does not enforce limit on response payload size

### ISSUE THREAD

**Issue by andybee** [architect/architect#1026]
**Describe the issue**
If an HTTP function returns a body larger than 6MB (the limit Lambda enforces for a payload size), it returns as normal with no warning. This means you can develop an application that breaches this limit and not be aware of an issue until deploying to AWS.

**Steps to reproduce**
1. Create a basic Architect app and in the index handler, add:
```
exports.handler = async () => ({
  statusCode: 200,
  body: [...Array(10000000)].map(() => `.`).join(''),
});
```
2. Call the `/` handler in a browser and see the response, but observe that it has a size of 10MB.

**Expected behavior**
An error to be thrown by Sandbox, similar to the error AWS will throw.

**Comment by ryanblock** [comment]
Will be released in Sandbox 3.3.0 + Arc 8.3.6 today!
