### ISSUE TITLE
arc env should notify user to update gitignore

### ISSUE THREAD

**Issue by rbethel** [architect/architect#1033]
When you upgrade to 8.3.7 from prior versions of Arc the `arc env` command will generate a new `preferences.arc` file and add environment variables to it. It would be helpful if Arc alerted users that they should add preferences.arc to gitignore so that they don't inadvertently commit api keys etc. to source control.

**Comment by ryanblock** [comment]
Patched in https://github.com/architect/env/pull/311, will ship in the next release!
