### ISSUE TITLE
Provide better control over files uploaded during deploymeny

### ISSUE THREAD

**Issue by BenoitAverty** [architect/architect#1034]
**Is your feature request related to a problem? Please describe.**

The problem is that my javascript serverless function is too big. I had deployments fail because the unzipped file was over 256mb, and this size is caused by the dev dependencies of my project.

Removing dev dependencies is easy, but doing it in the context of the arc deployment is harder because `arc deploy` executes `npm ci`, which adds the dev dependencies as well. 

**Describe the solution you'd like**

The best solution in my opinion would be to have support for a .arcignore file in each lambda folder (as discusses in #247 , I opened a new issue for visibility and opening the discussion to other potential solutions)

This solution has the advantage to be agnostic of the runtime used for the lambda.

**Describe alternatives you've considered**

First, I looked for an option so that arc deploy only installs production deps (`npm ci --production`) but that doesn't seem to exist. Moreover, this would force the user to reinstall dev deps after each deploy if it's done locally (not a problem in CI env)

Then, I added `npm prune --production` to my postinstall script, but then I can't install dev deps at all because running `npm install` executes the postinstall script. I currently use this solution with a conditional so the pruning only occurs during `arc deploy` (and it still forces me to reinstall deps after, but it'll only be done in CI soon)

**Comment by BenoitAverty** [comment]
Another solution would be to allow opting-out of hydrating when `arc deploy` is run, that way the user would be responsible to remove extraneous dependencies before deploying.

**Comment by ryanblock** [comment]
npm ci does not install dev deps, I suspect you have something else going on here. Can you present repro steps, or even better, a reduced test case repo?

Fwiw I'd suggest putting all dev deps in root anyway.

Lastly, this problem will probably go away for you in Arc 8.4, where we will start managing your Node.ja deps automatically per-function (so long as you aren't using dynamic require).

**Comment by BenoitAverty** [comment]
NPM ci only skips dev deps if NODE_ENV is set to production, which is not the case when I deploy.

Maybe there's another problem with my config ? I noticed NODE_ENV and ARC_ENV are always set to "testing" when i deploy, even with deploy --production.

**Comment by ryanblock** [comment]
What version of npm are you using? Because if it's 7, npm has a bug: https://github.com/npm/cli/issues/2017

**Comment by BenoitAverty** [comment]
I'm still on npm 6
```
> npm --version
6.14.9
```

I just tested by creating a new package (`npm init`) and then installing react (`npm i -S react`) and babel core as dev dep (`npm i -D @babel/core`)

Then,` rm -rf node_modules && npm ci `installs 43 packages including babel core and its deps, while `NODE_ENV=production npm ci` installs only 4 packages (same with `npm ci --production`)

When I do arc deploy the dev deps are here, but it may be because I have to do something for architect to use the production flag.

The issue you're linking specifically talks about the case with the production flag. I think architect does not set it for me.

Anyway putting dev deps in the root i a good idea so I'll try that but there is something going on, either because architect does not set the flag or because I misconfigured something.

**Comment by ryanblock** [comment]
Thanks, looks like at some point npm ci changed behavior (again).

In the next release I'll make sure we are using `npm i --production` and `npm ci --production` commands during dependency hydration.

In the meantime, the workaround remains the same: put your dev-deps in root (generally a better idea for speed and determinism) and you'll be good!

**Comment by ryanblock** [comment]
8.4 RC is now out if you'd like to check out both fixes! `npm i @architect/architect@RC` – this includes `--production` by default, as well as enabling dependency management from your root package.json!

**Comment by ryanblock** [comment]
Released in 8.4!
