### ISSUE TITLE
`ws` doesn't seem to work in `package.json`

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#1039]
**Describe the issue**
`ws` in `package.json` breaks. Using the syntax defined at https://v8.arc.codes/docs/en/reference/app.arc/ws

**Steps to reproduce**

There is a reproduction case at https://github.com/mikemaccana/fullstack-serverless-starter-kit/tree/websockets-package-json - it uses `package.json` to define `ws` and websockets break - responses don't come back in to the app.

But undo the last commit (which swaps from `app.arc` to `package.json`) and websockets work.

**Expected behavior**
The `default` websocket event code is run, and sends a response.

**What happens instead**
The `default` websocket event code is run, but the `arc.ws.send()` never comes back. The HTTP catchall gets a 404 request where `request.rawPath` is `/__arc`!

**Desktop**
Please complete the following information (if appropriate):
 - OS: Linux, Arc 8.3

**Comment by ryanblock** [comment]
Will be patched in a few minutes in Sandbox 3.3.3 + Arc 8.4.3!

**Comment by mikemaccana** [comment]
Thanks! Suspect the fix will be useful for anyone who uses websockets, as they'll probably have a 404 handler too.

**Comment by ryanblock** [comment]
One thing, I noticed in the dust a call to `../../utils`, which is outside the Lambda I think!

**Comment by mikemaccana** [comment]
Hah thanks for spotting that I'll check it out!
