### ISSUE TITLE
@scheduled function not firing with 8.4.2, but works fine with 7.0.7

### ISSUE THREAD

**Issue by alexbepple** [architect/architect#1040]
**Describe the issue**
@scheduled function not firing with 8.4.2, but works fine with 7.0.7

**Steps to reproduce**
As far as I can see it is as basic as just adding a @scheduled function.

Cp. https://github.com/alexbepple/improvmx-failure-reporter/blob/main/app.arc

Downgrading fixed the issue for me.
https://github.com/alexbepple/improvmx-failure-reporter/commit/93e15a501f11ad45ed7fd39a1b0cad937e732eb2

**Screenshots**

I am no AWS expert (that's the appeal of Architect ;) ). 8.4.2 (and 8.4.1) for that matter seem not to add the trigger for the Lambda. From comparing the two stacks, the permission seems to be missing.

<img width="708" alt="8 4 2 lambda" src="https://user-images.githubusercontent.com/159355/102823867-fdce8100-43db-11eb-87f0-42c52e219d1d.png">
<img width="910" alt="8 4 2 resources" src="https://user-images.githubusercontent.com/159355/102823870-ff984480-43db-11eb-8e01-271269b3b336.png">
<img width="696" alt="7 0 7 lambda" src="https://user-images.githubusercontent.com/159355/102823875-01fa9e80-43dc-11eb-9321-2f1fa72c86d7.png">
<img width="909" alt="7 0 7 resources" src="https://user-images.githubusercontent.com/159355/102823880-03c46200-43dc-11eb-85a0-42401d282ef3.png">

**Comment by ryanblock** [comment]
Good catch, on it!

**Comment by ryanblock** [comment]
Fix confirmed, will be released in 8.4.3 in a few minutes, thank you for the heads up @alexbepple and apologies for the regression! This was related to the fix for #1038.

**Comment by alexbepple** [comment]
Thanks for the quick fix, @ryanblock.

**Comment by ryanblock** [comment]
I broke it, I bought it. 😎
