### ISSUE TITLE
A few lines still print when starting sandbox with ARC_QUIET

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#1045]
**Describe the issue**
A few lines still print when starting sandbox with ARC_QUIET

**Steps to reproduce**
During `await sandbox.start();` 

**Expected behavior**
During `await sandbox.start();`, with the env var `ARC_QUIET` set to 'true' (I know any string works), 3 lines still print: 

```
 console.log

          http://localhost:3333


      at _started (node_modules/@architect/sandbox/src/http/index.js:118:21)

    console.log
      ✓ Sandbox Started in 84ms

      at Object.done (node_modules/@architect/utils/updater/index.js:81:27)

    console.log
      ✈︎ Local environment ready!

      at Array._ready (node_modules/@architect/sandbox/src/sandbox/start.js:96:17)
```

**Desktop**
`@architect/sandbox@3.3.3`

**Comment by mikemaccana** [comment]
As mentioned in Slack

**Comment by ryanblock** [comment]
Patched in https://github.com/architect/sandbox/pull/538, will be in next Sandbox / Arc release. Thanks!
