### ISSUE TITLE
Problem reading app.arc: map key is not a string

### ISSUE THREAD

**Issue by xariusdrake** [architect/architect#1046]
**Describe the issue**
Cannot run sandbox. Display error `Problem reading app.arc: map key is not a string `

**Steps to reproduce**
Run command line
`arc sandbox`

**Screenshots**
![Screen Shot 2021-01-08 at 2 23 42 AM](https://user-images.githubusercontent.com/22252984/103935032-8ed18600-5158-11eb-810a-6423b9d5aaaa.png)
![Screen Shot 2021-01-08 at 2 25 07 AM](https://user-images.githubusercontent.com/22252984/103935165-bf192480-5158-11eb-9d8a-9c130d1d1195.png)

**Desktop**
Please complete the following information (if appropriate):
 - MacOS: 11.1

**Comment by brianleroux** [comment]
eh there; can you try making the `@tables` and `@indexes` indentation 2 spaces ?

**Comment by xariusdrake** [comment]
> eh there; can you try making the `@tables` and `@indexes` indentation 2 spaces ?

I just tried it. Didn't work.

**Comment by brianleroux** [comment]
err, ok, so what did you see as an error ? same thing ?

**Comment by xariusdrake** [comment]
yes. same error

**Comment by brianleroux** [comment]
is this source available somewhere? Sorry I'm not reproducing locally with the same app.arc so I'm missing some steps to reproduce.

**Comment by xariusdrake** [comment]
I just compressed it. Thank you.
![Screen Shot 2021-01-08 at 2 44 27 AM](https://user-images.githubusercontent.com/22252984/103937533-7151eb80-515b-11eb-87a7-54a3210a1a11.png)


[infras.zip](https://github.com/architect/architect/files/5783644/infras.zip)

**Comment by brianleroux** [comment]
ok it works! just remove two of the spaces under the `@indexes` and `@tables` like so:

```
@app
react-arc

@http
get /
get /posts
get /posts/postID
post /posts
delete /posts/postID

@tables
posts
  postID *String

@indexes
posts
  type *String

@aws
profile default
region us-west-1

@macros
arc-macros-no-bucket
```
