### ISSUE TITLE
Template format error: Unresolved resource dependencies [StaticBucket] in the Resources block of the template

### ISSUE THREAD

**Issue by xariusdrake** [architect/architect#1047]
**Describe the issue**
I tried to deploy but I got the error message Template format error: Unresolved resource dependencies [pk-bucket] in the Resources block of the template

**Steps to reproduce**
1. Setup /.aws/credentials
2. Deploy `arc deploy`

**Screenshots**
![Screen Shot 2021-01-08 at 4 52 31 AM](https://user-images.githubusercontent.com/22252984/103949837-766c6600-516e-11eb-99a7-824f9ab21acb.png)

**Comment by ryanblock** [comment]
Can you share your project manifest?

**Comment by xariusdrake** [comment]
Sorry. I forget it. I tried to paste it here but it looks messy.

[arc.zip](https://github.com/architect/architect/files/5784222/arc.zip)

**Comment by ryanblock** [comment]
I see the issue, and it's with the Macro you're using. The workaround for now is to disable that Macro – soon we'll be baking the ability to disable a static asset bucket directly into Architect.

**Comment by ryanblock** [comment]
Ok, this will be patched properly in `8.4.5` – just use the following instead of the `arc-macro-no-bucket` macro:
```
@static
false
```
