### ISSUE TITLE
Prefer for arc not to write env vars to preferences.arc

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1050]
**Is your feature request related to a problem? Please describe.**
Kind of... I check in the `preferences.arc` file into revision control because I have sandbox startup scripts encoded in that file that I want to be part of the local developer experience (the sandbox startup script seeds the local db).

If I use `arc env`, my secrets get written to the `preferences.arc` file. I do not want that, since I am revisioning this file.

**Describe the solution you'd like**
I am not prescribing a solution, but one potential solution that was floated in Slack was to check for the existence of a `.env` file, and write secrets there (and read from there, too, to inject into functions running locally in sandbox).

**Describe alternatives you've considered**
The old `.arc-env` file worked great for me, for what it's worth. The key for me is to not put secrets into the same location as where we store non-secret, but important, project stuff, like `preferences.arc`.

**Additional context or notes**
Leveraging the `.env` file seems to be a common convention across all three main runtimes arc supports (node, python, ruby), and has good tooling support in these ecosystems, too.

**Comment by ryanblock** [comment]
Quick followup from Slack: I forgot that I already built this. If you have .env, we read/write to that first over prefs.arc: https://github.com/architect/env/blob/master/src/_write/dotenv.js

So just to be clear, the default is still prefs.arc, but the moment you touch .env we'll start using that for all local env var related stuff in `arc env` and `arc sandbox`.

**Comment by filmaj** [comment]
This is so awesome! Exactly what I was looking for! Thank you!
