### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by kevin4dhd** [architect/architect#1052]
**Describe the issue**
when executing arc init it gives the following message: let leading = new RegExp (`^ $ {sep}`)
                         ^
SyntaxError: Invalid regular expression: / ^ \ /: \ at end of pattern

**Steps to reproduce**
1. npm i -g @architect/architect
2. mkdir testapp
3. cd testapp
4. arc init
5. See error that says 'SyntaxError: Invalid regular expression: /^\/: \ at end of pattern'

**Expected behavior**
A clear and concise description of what you expected to happen

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):
 - OS: Windows 10
 - Browser Chrome
 - Version Architect 8.4.5

**Additional context**
![image](https://user-images.githubusercontent.com/22886367/104854993-07161500-58d8-11eb-8a67-4a76e0669bc2.png)

**Comment by ryanblock** [comment]
Thanks! Fix will be released in Arc 8.4.6 asap!
