### ISSUE TITLE
Flag to not hydrate on deploy

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1054]
**Is your feature request related to a problem? Please describe.**
Since I have a build step (using typescript and parcel) in my project, I would like for the option to not hydrate on deploy. With the auto-install and tree-shaking bits in place, it makes it hard to manage this kind of project without this feature, as otherwise package.json files get created for me inside my functions.

**Describe the solution you'd like**
A CLI flag, perhaps `--no-hydrate`, i.e. `arc deploy --no-hydrate`.

**Describe alternatives you've considered**
???

**Additional context or notes**
Happy to implement this! Let me know what y'all think.

**Comment by mawdesley** [comment]
Wow! This is extremely serendipitous. I made a fork and implemented this change on Friday and was just coming to raise an issue now :joy:

Here's my branch: https://github.com/mawdesley/deploy/tree/feat/skip-hydrate

Let me know if you'd like me to raise a PR 👍

**Comment by filmaj** [comment]
Oh nice ! I [raised a PR](https://github.com/architect/deploy/pull/294) too, and it looks like our changeset is pretty much identical, other than the flag name 😂

**Comment by mawdesley** [comment]
`--no-hydrate` is cleaner than `--skip-hydrate` imo, I yield to your superior PR.

**Comment by filmaj** [comment]
FYI `@architect/architect` v8.4.7 is published which has the `arc deploy --no-hydrate` flag!
