### ISSUE TITLE
Add custom stage name support to `arc destroy`

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1055]
**Is your feature request related to a problem? Please describe.**
`arc deploy` allows you to provide a `--name` parameter that gets appended to the CloudFormation Stack name, effectively allowing you to create as many separate environments of your app as you wish. It would be nice to also have `arc destroy` support this flag, so that you can deploy and destroy custom named Stacks using arc.

**Describe the solution you'd like**
`destroy` already requires a `--name` parameter before executing, though this is different from the `arc deploy --name` flag. So perhaps a different flag is required for destroy. Maybe `--stage`?

**Comment by ryanblock** [comment]
Fixed in 8.5.10!
