### ISSUE TITLE
Unusual cookie behaviour

### ISSUE THREAD

**Issue by andybee** [architect/architect#1057]
**Describe the issue**
When setting the cookie response value to an array, the behaviour of Sandbox differs from AWS and in such a way that browsers don't see multiple cookies.

**Steps to reproduce**
1. Create a handler function that returns `cookies: ['a=1;', 'b=2;']` as part of their response object.
2. Launch sandbox and hit the endpoint.
3. Observe the response header as `set-cookie: a=1;; b=2;`

**Expected behavior**
When performing the same test with a deployed Lambda function, the headers include:
```
set-cookie: a=1;
set-cookie: b=2;
```
Therefore I believe Sandbox is incorrectly merging these values when it should be setting multiple `set-cookie` headers.

**Comment by ryanblock** [comment]
I believe this may be a node/express limitation.

**Comment by andybee** [comment]
Doesn't look like Sandbox is using Express under the hood, just the plain ol' HTTP server, which allows an array to be passed to `res.setHeader` which will then set multiple headers of the same name with each value.

https://github.com/andybee/sandbox/commit/7e160c56b07f6370aff645fec35351d8ce4fdd82

Two things I'm not sure of that prevented me making this a PR - what did the logic achieve in removing the secure/path bits - is that to stop you trying to set a "secure" cookie that won't work in our HTTP-only Sandbox world? Also, I couldn't find a sensible existing place to slot a test in to cover this change, the most relevant test is specifically checking on header formats - whereas the `cookie` response property isn't within headers. Is this a possible crack in the tests that let this one slip through? If so, perhaps it's worth having a unit test just for `_res-cookies` or similar...?

**Comment by ryanblock** [comment]
Thanks again for the patience! To speak to your question: Arc Functions sets secure cookies, so we had to remove that for HTTP local dev. Good news though, someone else did get to this fix and it was released this week!

See: https://github.com/architect/sandbox/pull/554
