### ISSUE TITLE
RFC: Arc Plugins (macros, expanded)

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1062]
# Is your feature request related to a problem?

It would be nice for arc users to be able to author their own extensions (dubbed plugins from here on out) to arc's various capabilities. While macros already allow for extending generated CloudFormation JSON, it would be great to allow arc users to hook into other arc capabilities.

Two such arc capabilities are examined as use cases:

- the ability for arc users to define cloud functions (AWS Lambda) that are not provided out-of-the-box by arc. For example:
  - functions that are triggered by [AWS IoT Rules](https://docs.aws.amazon.com/iot/latest/developerguide/iot-rules.html) (a macro, [`macro-iot-rules`](https://github.com/copperinc/macro-iot-rules/), already exists for this)
  - [functions that process records in an AWS Kineses data stream](https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html).
  - use [functions to integrate with AWS Lex conversation bots](https://docs.aws.amazon.com/lambda/latest/dg/services-lex.html).
- the ability for arc users to hook into the local development sandbox
  - for an arc plugin author who is extending arc with custom cloud functions, it would be great if their plugin could also provide a local development experience via `arc sandbox`
  - for certain other kinds of plugins, the ability to wire into the existing services sandbox provides out of the box would be helpful. For example, a Cognito Authorizer function is one that would integrate into API Gateway and thus has an impact on arc `@http` routes. To emulate Cognito Authorizers locally, one would need access to the http server `arc sandbox` manages.

# Describe the solution you'd like

This proposal is broken down into two sections:

1. Plugin Interfaces: The interfaces exposed to plugin authors (probably of more interest to future plugin authors and current users of arc)
2. Changes to `@architect/inventory` (probably of more interest to existing arc maintainers)

### Goals

This proposal aims to:

- maintain `@macros` be forwards-compatible with `@plugins`. That is, existing macros will be automatically plugged in to the new plugins system with no changes required by macro authors. All new plugin features not already supported by macros are therefore additive.
- provide plugin authors with helper functions giving them more powerful access to arc's internals in order to enable more complex use cases. arc's maintainers also commit to leveraging these same plugin authoring helpers to implement arc's core functionality. This paves the way for a fully pluggable future arc architecture.

### Interface

> NOTE: all names / properties are TBD; if you have a suggestion on a better name, please comment!

Plugin authors will be expected to implement a module that exports the following interface (node.js only at this stage):

```
module.exports = {
  package: async function cloudFormationExtender ({arc, cloudformation, stage='staging', inventory}) { },
  pluginFunctions: async function newFunctionsThisPluginAdds ({ arc, inventory }) { },
  sandbox: {
    start: async function sandboxServiceThisPluginWillCreate ({arc, inventory, services}) { },
    end: async function sandboxServiceThisPluginWilDestroy ({arc, inventory, services}) { }
  }
}
```

#### `package({arc, cloudformation, stage='staging', inventory})` function

This method encapsulates [arc's existing functionality provided by macros](https://arc.codes/docs/en/guides/extend/custom-cloudformation): extending arc's generated CloudFormation `sam.json` with your own custom extensions. This method's signature is [the same as the one provided to macros today](https://arc.codes/docs/en/guides/extend/custom-cloudformation). arc will maintain compatibility between macros and plugins by mapping old macro functionality to this plugin `package` method.

**As a plugin author, if you intend for your plugin to create cloud functions**, you would be expected to leverage the plugin author helper method `createLambdaJSON` (described below) to painlessly create CloudFormation-compatible JSON representing your new cloud functions. Leveraging this helper methods gives the plugin functions support for [arc's per-function runtime configuration via the `config.arc` file](https://arc.codes/docs/en/reference/config.arc/aws) transparently.

##### Example `package` implementation

An example implementation of this method is listed below, under the Plugin Author Helper Methods' `createLambdaJSON` section.

#### `pluginFunctions(inventory)` function

The plugin author would implement this method if the plugin defines new cloud functions. It should return an array of objects, each object representing a new cloud function being defined by the plugin. Each object should have the following format:

```
{
  src: '/Users/filmaj/src/my-arc-project/src/rules/rule-one',
  body: 'exports.handler = async function (ruleEvent) { console.log(ruleEvent) }'
}
```

The `src` property should be a string containing a fully qualified absolute path to the source code location for the cloud function.

The `body` property should be a string containing template code for the cloud function handler.

> ⚠️ TODO: The `body` implementation above is not runtime-agnostic / multi-runtime friendly, I don't think...

arc would use this method in the following arc sub-modules:

- [`@architect/create`](https://github.com/architect/create/), which would locally generate the cloud function source directories and files for the user if these directories and files do not exist (via the CLI `arc create` or `arc init`).
- [`@architect/logs`](https://github.com/architect/logs), which would allow for users to pull cloud function execution logs for these plugin-generated functions (via the CLI `arc logs`).
- [`@architect/hydrate`](https://github.com/architect/hydrate), which would allow for arc to install any cloud function dependencies required on a per-function basis (via the CLI `arc hydrate`).

##### Example `pluginFunctions` Implementation

```
let path = require('path')

module.exports = {
  pluginFunctions: async function ({ arc, inventory }) {
    if (!arc.rules) return []
    const cwd = inventory.inv._project.src
    return arc.rules.map((rule) => {
      let rulesSrc = path.join(cwd, 'src', 'rules', rule[0])
      return {
        src: rulesSrc,
        body: `exports.handler = async function (event) {
  console.log(event);
};`
      }
    })
  }
}
```

The above would instruct arc to look for (and `create`, `hydrate` and search for `logs` for) functions under `src/rules/<function>` inside the arc project directory hierarchy. With the above `pluginFunctions` method and given `app.arc` contents like so:

```
@rules
rule-one
rule-two
```

... running:

- `arc create` would create the folders `src/rules/rule-one` and `src/rules/rule-two`, with `index.js` files in each containing the contents of the `body` specified in `pluginFunctions`
- `arc hydrate` would also hydrate these two folders
- `arc logs src/rules/rule-one` would pull in any execution logs for these functions if they exist

#### `sandbox.start({ arc, inventory, service }, callback)` function

The plugin author would implement this method if the plugin wants to hook into the startup routine for `arc sandbox`. This would allow plugin authors to emulate the cloud services their plugin provides in order to provide a local development experience for consumers of their plugin. It would also allow to modify behaviour of any of `arc sandbox`'s built-in local development services (for `@http`, `@events`, `@queues` and `@tables`) - or plugin-registered ones - via the `services` argument.

This method should itself return a function that takes a single callback argument. This callback should be invoked once the plugin sandbox service has started.

A helper method, `invokeLambda` (described below under the Plugin Author Helper Methods section), is provided by the `@architect/sandbox` package in order to allow plugin authors to invoke specific lambdas from their plugin sandbox service code.

##### Example `sandbox.start` Implementation

An example implementation of this method is listed below, under the Plugin Author Helper Methods' `invokeLambda` section.

#### `sandbox.end({ arc, inventory, services })` function

If the plugin author implements a `sandbox.start` method, then they should also implement a `sandbox.end` method. In the same manner as `start`, `end` must return a function that takes a callback as a single argument. `end` should then invoke the callback once the plugin service has been gracefully shut down. Optionally, the callback can be invoked with an error object to signify to `sandbox` that an errors has occurred. 

### Plugin Author Helper Methods

In order to enable more complex extensions to arc, some of arc's internals need to be exposed in a consistent way to enable a simpler authoring experience for plugin developers.

#### `@architect/package/createLambdaJSON`

> `createLambdaJSON({ inventory, src })`

Intended to be leveraged by plugin authors inside their plugin's `package` method in order to easily and consistently define CloudFormation JSON representing cloud functions created by plugins.

Arguments:

- `inventory`: an arc project's [inventory](https://github.com/architect/inventory) object (which is passed into all plugin interface methods for convenience)
- `src`: a string representing the path where code for the cloud function exists locally in the arc project and user filesystem

**It would return** a tuple (array of two objects), containing a string representing an AWS-friendly Lambda resource name (based on the path to the function code), and a JSON object that can be assigned to a CloudFormation `sam.json`'s `Resources` section, effectively defining a cloud function that arc would instruct CloudFormation to create.

This method provides the added benefit of reading [per-cloud-function configuration files](https://arc.codes/docs/en/reference/config.arc/aws) transparently for you and ensuring those configurations are properly expressed in the CloudFormation JSON. For example, per-cloud-function configurations for [concurrency](https://arc.codes/docs/en/reference/config.arc/concurrency), [function timeout](https://arc.codes/docs/en/reference/config.arc/timeout), and [memory](https://arc.codes/docs/en/reference/config.arc/memory) are provided to plugin authors.

##### Example usage of `createLambdaJSON`

```
let createLambdaJSON = require('@architect/package/createLambdaJSON')
let path = require('path')

module.exports = {
  package: async function IoTRulesLambdas ({ arc, cfn, stage = 'staging', inventory }) {
    if (arc.rules) {
      const cwd = inventory.inv._project.src
      arc.rules.forEach(rule => {
        let code = path.join(cwd, 'src', 'rules', rule[0])
        let [functionName, functionDefn] = createLambdaJSON({ inventory, code })
        cfn.Resources[functionName] = functionDefn
      })
    }
    return cfn
  }
}
```

#### `@architect/sandbox/invokeLambda`

> `invokeLambda({ src, payload }, callback)`

Intended to be leveraged by plugin authors inside their plugin's `sandbox.start` method in order to easily invoke their cloud functions locally within an `arc sandbox` local development runtime context.

Arguments:

- `src`: a string representing the path where code for the cloud function exists locally in the arc project and user filesystem
- `payload`: JSON payload to deliver to the function
- `callback`: function with signature `function(error, result)` that is invoked with either the error or the result from the local function invocation

##### Example usage of `invokeLambda`

```
let path = require('path')
let prompt = require('prompt')

module.exports = {
  pluginFunctions: async function ({ arc, inventory }) {
    if (!arc.rules) return []
    const cwd = inventory.inv._project.src
    return arc.rules.map((rule) => {
      let rulesSrc = path.join(cwd, 'src', 'rules', rule[0])
      return {
        src: rulesSrc,
        body: `exports.handler = async function (event) {
  console.log(event);
};`
      }
    })
  },
  sandbox: {
    start: async function IoTRulesServiceStart ({ arc, inventory, services }) {
      let rules = module.exports.pluginFunctions({ arc, inventory }).map(rule => rule.src);
      process.stdin.on('keypress', async function IoTRulesKeyListener (input, key) {
        if (input === 'I') {
          const response = await prompt([ {
            type: 'select',
            name: 'rule',
            message: 'Which IoT Rule do you want to trigger an event for?',
            choices: rules
          }, {
            type: 'input',
            name: 'payload',
            message: 'Type out the JSON payload you want to deliver to the rule (must be valid JSON!):',
            initial: '{}',
            validate: function (i) {
              try {
                JSON.parse(i);
              }
              catch (e) {
                return e.message;
              }
              return true;
            },
            result: function (i) {
              return JSON.parse(i);
            }
          } ]);
          invokeLambda(response.rule, response.payload, function (err, result) {
            if (err) console.error(`Error invoking lambda ${response.rule}!`, err);
            else console.log(`${response.rule} invocation result:`, result);
          });
        }
      });
      console.log('IoT Rules Sandbox Service Started; press "I" (capital letter) to trigger a rule.');
      callback();
    }; 
  }
};
```

## Changes to `@architect/inventory`

Two changes are proposed to the `inventory` module:

1. Adding a new `_project.plugins` property which would be a map of plugin names to the `require`d plugin module. This would allow other core arc sub-modules to easily pull in plugin modules where needed.
2. Adding a new `inv.plugins` property which is an array of plugin-registered lambdas.

`inventory` would use plugin modules' `pluginFunctions` method to populate its `lambdaSrcDirs` and `lambdasBySrcDir` properties. This would allow for `arc hydrate` and `arc logs` to be able to accomplish their capabilities with plugin-authored cloud functions.

# Conclusion

That's it! Phew I'm tired after writing that up. Comments, suggestions, etc. welcome!

**Comment by filmaj** [comment]
Added first pass at plugin-author-facing documentation here: https://github.com/architect/arc.codes/pull/324

**Comment by thelinuxlich** [comment]
Would love a Cognito plugin!

**Comment by filmaj** [comment]
`@plugins` support is live as a release candidate, published under @architect/architect@8.5.0-RC.0! The docs for this are live (on staging, at the moment) over here: https://staging.arc.codes/docs/en/guides/extend/architect-plugins

Please give it a go if you want to author extensions to arc that can feature your own Lambda functions doing cool stuff!
If you do give it a try and see some issues, please let me know about them either in Slack or in this issue.

Hoping to bake this for a little bit before we merge into mainline.

**Comment by ryanblock** [comment]
A thing I was thinking about re. Sandbox services was the potential ability to register individual plugins as services to be started or stopped via the API, which might be helpful for ensuring performance during testing. But that level of granularity might be burdensome to implement and/or unnecessary for an mvp. That said, if we wanted to look at it, examples below.

How it works today:
```
let { start, end, http, events, tables } = require('@architect/sandbox')
start() // starts all services
end() // ends all services

http.start() // starts only @http
http.end() // starts only @http

// same for events, tables
```

An "easy" way to handle plugins, all at once (prob at a [high level here](https://github.com/architect/sandbox/blob/master/src/index.js)):
```
plugins.start()
plugins.end()
```

A slightly deeper way, nesting individual plugins into a `plugins` service object (probably [here](https://github.com/architect/sandbox/blob/master/src/sandbox/index.js#L13-L17)?):
```
plugins.start()
plugins.end()
plugins.myPlugin.start()
plugins.myPlugin.end()
```

A deep, granular way to handle plugins, with each registering itself at the highest level of Sandbox (idk, maybe weird):
```
let { myPlugin } = require('@architect/sandbox')
myPlugin.start()
myPlugin.end()
```

Some other related considerations / notes:
- Sandbox's service factory does some funky stuff to register services in global scope but also fire them with async so they're populated with Inventory; this can probably be improved so we aren't running Inventory for each service, but it was fiddly and I haven't gotten around to it
- What if a given plugin needs a Sandbox service to be running (e.g. `myPlugin` needs the `http` service but my app doesn't use `@http`?)

**Comment by filmaj** [comment]
Sounds good @ryanblock, I'll mull over this for a bit but LGTM. I've updated the original post in here to try to reflect the changes to the sandbox services your comment introduces.

> What if a given plugin needs a Sandbox service to be running (e.g. `myPlugin` needs the `http` service but my app doesn't use `@http?`)

We could possibly introduce a concept of plugin dependencies down the road, but my initial gut reaction at this stage is to pass responsibility of checking that to the plugin author.

**Comment by filmaj** [comment]
BTW, yesterday I pushed up architect 8.5.0-RC.3, which changes the plugin interface a little: instead of positional arguments to the various plugin methods, they are now an options bag. This:

> `pluginFunctions(arc, inventory)`

... is now:

> `pluginFunctions({ arc, inventory })`

**Comment by ryanblock** [comment]
For reference, all `@plugins` PRs are here: https://github.com/architect/inventory/pull/15

**Comment by filmaj** [comment]
BTW, for those interested, there is a discussion ongoing in https://github.com/architect/architect/issues/1091 about how plugins could allow for service discovery within an arc app, i.e. if your plugin adds a new bit of infrastructure (a new database, a new S3 bucket, whatever), how would you share that information with the rest of your arc app, like Lambdas at runtime? Comments welcome!

**Comment by filmaj** [comment]
Was thinking about how plugins should manage their dependencies, figured maybe this is a conversation worth bringing up in here.

At first, I thought adding `package`, `sandbox` and other `@architect` packages as npm `dependencies` made sense. However, as I've built progressively more complex plugins, I realize that this may be overkill. For a simple plugin with nothing more than a plugin `package` method implemented, this may be sufficient and not harmful. However, for a larger plugin with a runtime client / library component, this may not be ideal if we want consumers of the plugin to pull it in as a dependency to a runtime Lambda function (we don't want our runtime functions packaging `sandbox` in with them, for example!).

(As a related tangent here, I know [@ankcorn has built a plugin](https://github.com/Ankcorn/arc-buckets-plugin) that writes files to `src/shared` to distribute a runtime client - which is a cool approach - but assumes the use of `src/shared` in an arc project. One client I am working with is bundling all their Lambda functions and uses a separate folder relative to the root of the arc project, `lib/`, as the `src/shared` equivalent. So I am hesitant to go all-in on this technique, though I think it is a cool one!)

To get back to the topic of plugin dependencies and what to bundle: what if plugins didn't need to put the architect packages providing the plugin authoring helper functions (`createLambdaJSON` from `package` and `invokeLambda` from `sandbox`) in their dependencies, and instead these methods were injected into the plugin methods as function arguments, dependency-injection style? So we'd change the `sandbox.start`'s signature to:

> `sandbox.start({ arc, inventory, service, invoke }, callback)`

... where `invoke` is the `invokeLambda` helper, and we'd change the `package` method signature to:

> `package({arc, cloudformation, stage='staging', inventory, createLambdaJSON})`

This way if someone consumes my, say, s3 bucket plugin in their app, it has a smaller payload, and if they require my plugin in their runtime functions to use the client library it comes with, their runtime functions now won't pull `sandbox` and `package`.

**Comment by filmaj** [comment]
This is now live as architect 8.5.0! Closing this issue. Woot!

One thing worth mentioning is that the next phase of plugin support development will be nailing down service discovery, to enable rich runtime capabilities for any plugins. Discussion and brainstorming for that is happening here: https://github.com/architect/architect/issues/1091
