### ISSUE TITLE
Handle file watcher limit reached errors

### ISSUE THREAD

**Issue by mawdesley** [architect/architect#1068]
**Is your feature request related to a problem? Please describe.**

When our CI server is really busy we're occasionally seeing file watcher errors when running `arc sandbox`.

```
Error: ENOSPC: System limit for number of file watchers reached
```

**Steps to reproduce**
1. [Lower your file watch limit](https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit), I set mine to 200 to test this
2. Open a large arc project
3. Run `arc sandbox`
4. Sandbox should crash after hydration

**Describe the solution you'd like**
File watchers don't matter in a CI environment as there shouldn't be any changes made to a build whilst it's tested.

If a file watcher error occurs, the sandbox should not crash. Instead a warning should be printed to the console so users know that the file watching functionality is disabled.

I made a PR: https://github.com/architect/sandbox/pull/546

**Describe alternatives you've considered**
File watch limit could be increased, but this isn't an option in our environment 😢

**Comment by filmaj** [comment]
This was fixed in arc 8.4.10, thank you @mawdesley for the PR and fix!
