### ISSUE TITLE
add name fallback for package.json parse in inventory

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1069]
currently when we parse `package.json` we treat 'arc' or 'architect' key just like an embedded json arcfile. this is cool but its kinda ugly to have `package.json` with a `name` key and then essentially the same thing with `arc.app` (or `architect.app`) nested key. 

this is a proposal to use `package.json` key `name` if `app` is not defined in the `arc` or `architect` document.

**Comment by ryanblock** [comment]
I considered this, but ultimately intentionally left it out (for now). The reason being:
- package.json's `name` may not be present
- and if `name` is present it may not be an appropriate app name
- and if it is an appropriate app name, package.json's [`name` schema](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#name) may not meet our validation for that field

I like this idea, but it felt like the practical realities of doing so were blockers. Happy to reconsider, anyone else want this? (If not, maybe will just close for now and reopen later if it comes up.)
