### ISSUE TITLE
Extend `destroy` to remove the deployment bucket, all SSM params and cloudwatch logs

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1076]
**Is your feature request related to a problem? Please describe.**
I would like for `destroy` to be able to remove all traces of an architect-deployed application from my AWS account. Typically, when I run `arc destroy --force --name myApp`, the deployment bucket (the bucket where the CloudFormation template was deployed to) is always left behind. 

**Describe the solution you'd like**
Would it be possible for `--force` to also:
- [x] find, wipe and remove the deployment bucket
- [x] remove all SSM secure strings dropped in by `arc env`
- [x] remove all cloudwatch log groups if possible

**Comment by filmaj** [comment]
Weird, there seems to be logic in `@architect/destroy` for deleting the static bucket contents, at least. Going to dig in to see why that has not worked for me in a long time.

**Comment by filmaj** [comment]
Hmm.. emptying out the static bucket works in my recent test... not sure why I've had an issue on some apps with this before. Going to ignore that bit for now and narrow the scope of this issue down to just 'can we remove the deployment bucket with `destroy`?'

**Comment by brianleroux** [comment]
the deploy bucket != the web server bucket for static assets !

**Comment by filmaj** [comment]
Correct! In this issue I am aiming for not having any dangling instances of anything left over from an arc app after a `destroy --force`.

Just noticed that there is also a parameter of type `SecureString` with a name like `/<app-name>/deploy/bucket` and value being the deploy bucket name left over in SSM.

IMHO, ideally `destroy` would remove both this parameter as well as the deployment bucket. WDYT?

**Comment by ryanblock** [comment]
Yeah, would love to kill that deploy bucket from SSM. I'd been meaning to get around to that.

An idea of why asset deletion may not have been working for you AND a thing we need to do anyway: enable S3 pagination during object deletion! https://github.com/architect/destroy/blob/master/src/_delete-bucket-contents.js#L15-L17

**Comment by filmaj** [comment]
@ryanblock noice, well, I'll take a stab at this!

I filed #1077 re: paginate during bucket wiping.

One last thing: also looks like secure parameters from `arc env` are left dangling in SSM. Delete those too, ya?

**Comment by ryanblock** [comment]
I don't see any reason to leave any SSM params, personally!

**Comment by filmaj** [comment]
I now realize there's only one deployment bucket used across all stages, eh? I still think any invocation of `destroy` should remove that bucket (`deploy` will transparently create a new one anyways) as we don't know how many stages a user deployed for their app.

**Comment by filmaj** [comment]
Oooooo and what about CloudWatch log groups? I'll take a look at that...

**Comment by ryanblock** [comment]
Good call on both!

**Comment by ryanblock** [comment]
Also: I have some code laying around for mass destroying CloudWatch logs if you want!

**Comment by filmaj** [comment]
If it's handy, sure, that'd be great!

**Comment by ryanblock** [comment]
Here it is! Will need some adaptation of course, but I've used this to destroy loads of CloudWatch log entries: https://gist.github.com/ryanblock/bbe13e3fab9d1b5385754d548429b497

Note that (janky) 500ms throttle, may be a bit conservative but there is def a limit to how quickly you can destroy logs. I think it's 3TPS but 2TPS never failed in practice.

Unfortunately I don't think there's a bulk delete method for many log groups, so if there's a lot, it's going to take a while. Best to alert the user with `update.start('Deleting n Lambda logs...')` or something!

**Comment by filmaj** [comment]
Thanks! I'll play around with it

**Comment by filmaj** [comment]
Works well btw! Got the functionality in place, need to work on the unit tests but hopefully ready this weekend.

**Comment by filmaj** [comment]
I can finally clean up my AWS account of all its random arc app artifacts 😅

**Comment by filmaj** [comment]
Landed in `destroy` v1.1.0, and `architect` v8.4.9 - which is building now and should be available on npm in a few mins.
