### ISSUE TITLE
npm init --runtime deno flag not working

### ISSUE THREAD

**Issue by pchinjr** [architect/architect#1078]
**Describe the issue**
Creating a new project with `npm init @architect --runtime deno` does not set the arc.config file to the deno runtime.

**Steps to reproduce**
1. create a new arc project with `npm init @architect --runtime deno ./my-deno-app`

**Expected behavior**
I expected a boilerplate function that is running the deno runtime.

**Comment by filmaj** [comment]
I just ran this with `@architect/create` 1.4.0, and a project was created, and the `app.arc` file did have `@aws runtime deno` set correctly. However, even though the generated `app.arc` had an `@http get /` route defined, no `src/` folder was generated in the project folder.

Going to dig into this a bit.

**Comment by filmaj** [comment]
Update: no matter what runtime you set, this same problem is exhibited. The `@aws runtime` is set appropriately in the `app.arc` file for all runtimes, though.

**Comment by filmaj** [comment]
I think I see the issue regarding the missing `src/` folder. We are not regenerating the arc inventory after creating the new project directory and `app.arc` file, so create is going off an "empty" inventory in this situation when it is supposed to fill out and create the project contents. I will work on a fix today.

**Comment by filmaj** [comment]
Arc 8.5.3 is on its way up to npm, should be public shortly. This issue should be fixed in arc 8.5.3.
