### ISSUE TITLE
Add a verbose mode to `destroy`

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1079]
**Is your feature request related to a problem? Please describe.**
`destroy` does a while bunch of stuff that creeps outside the scope of CloudFormation stack destruction: wiping S3 buckets and (soon) removing SSM parameters (arc env vars). As a user, would be nice to get insight into that from the command line.

**Describe the solution you'd like**
A `--verbose` flag or some such that will post more granular deletion updates, step by step, as `destroy` goes through its motions.

**Comment by filmaj** [comment]
Closing this, I think `destroy` should be verbose by default. At most it'll be like, 7 output lines to the console.

**Comment by ryanblock** [comment]
Fwiw I tend to agree, it's nice to see what got destroyed.
