### ISSUE TITLE
"SyntaxError: Unexpected end of JSON input" and exit when making unusual requests to :3334

### ISSUE THREAD

**Issue by andybee** [architect/architect#1084]
**Describe the issue**
Due to some misconfiguration on my part, I ended up with Sandbox on the standard port :3333 but the web-app it was hosting referring to WebSockets on :3334, which in the default port setup is a listener port for Architect. When the browser tries to connect to :3334 as if it's a web socket, it causes an internal error which crashes Sandbox.

**Steps to reproduce**
1. Create a bare bones Architect project.
2. Edit your index handler to return some HTML which attempts to open a WebSocket to port :3334.
3. Try and load the page, Sandbox will crash with an error similar to:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (node_modules/@architect/sandbox/src/events/_listener.js:25:24)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
```

**Expected behavior**
The browser would report some kind of connection error for the WebSocket request but Sandbox would carry on regardless, rather than exit.

**Comment by filmaj** [comment]
Sandbox creates a few servers in the background. One of these is an event bus for `@events`. By default this server runs on port 3334 (see [the list of env vars sandbox supports](https://github.com/architect/sandbox/#environment-variables)). 

Sandbox [creates an http server on this port](https://github.com/architect/sandbox/blob/master/src/events/index.js#L57). I'm not sure how we could gracefully handle this situation... maybe in the [event listener where it parses JSON](https://github.com/architect/sandbox/blob/master/src/events/_listener.js#L25) we wrap it all with a `try/catch`? But then what do we return?

**Comment by andybee** [comment]
If it’s an HTTP server, an HTTP friendly response to the error? (Maybe just a relevant status code and no body for simplicity?)

Anything other than causing Sandbox to tilt ideally. 😄

**Comment by filmaj** [comment]
Makes sense. Perhaps a 400 status code and a body explaining that the sandbox event bus failed to parse JSON (i.e. "Sandbox `@event` bus exception parsing request body")?

**Comment by andybee** [comment]
Feels nice. Always nice to document what's going on even on secret squirrel internal servers, just for the random time you implement something wonky and that hits that internal server and you're scratching your head about what's going on? (Although presumably that's handled by the fact that Sandbox falls over with the JSON error.)

**Comment by filmaj** [comment]
I'll fix it today!

**Comment by filmaj** [comment]
Just gonna wrap up another PR in the `inventory` package and get both that and the sandbox fix in. I will comment back here once a new release is cut and up on npm.

**Comment by filmaj** [comment]
Alright the 8.4.10 architect tag was pushed up; should be available on npm in a few minutes.
