### ISSUE TITLE
"arc deploy" doesn't require an arc-file

### ISSUE THREAD

**Issue by buffpojken** [architect/architect#1085]
**Describe the issue**
If you by mistake run ```arc deploy``` in the wrong folder, it still performs a deploy even if the folder doesn't contain an arc-file. 

**Steps to reproduce**
1. Install arc as recommended.
2. From any folder, run ```arc deploy```
3. Something is deployed (presumable as a static site since the error-message is a missing ```index.html``` from S3).

**Expected behavior**
I would expect arc to complain about a missing arc-file and abort.

**Comment by ryanblock** [comment]
Sandbox also starts without an Arc file. This is a feature, the intention is to streamline creating a new project so you can see **something** if you happened to have not set up a manifest.

**Comment by buffpojken** [comment]
Hmm, I see. 

My spontaneous though is that the drawback outweighs the benefit here? Since you'll need a manifest anyway to do more or less anything, isn't it a better idea to get people used to that from the get-go? Even if it only contains an app name? 

That way you at least need to state intent that a given folder is a valid arc app? 

(If this has been extensively discussed already, I definitely respect that and will close this issue.)

**Comment by buffpojken** [comment]
Also, what sandbox would that be? 

The "Quickstart" on the website runs ```arc init``` which does provide an arc-file, doesn't it?

**Comment by ryanblock** [comment]
> Also, what sandbox would that be?

Any time we'd mention Sandbox in the context of Architect, that'd be in reference to Architect Sandbox (`npx arc sandbox`). And yes, `arc init` should create an Architect project manifest, so if you follow our quickstart, you wouldn't ever see this anyway.

I wouldn't say the default project is something I personally feel super strongly about, but it also hasn't been something we've gotten a lot of feedback on (aside from the early feedback we heard letting us know that Arc failing without a manifest felt discouraging).

Of course, that doesn't mean it isn't confusing folks, but in terms of squeaky wheels getting grease, this one hasn't been especially noisy. I'm going to close this but if anyone else has strong feels about scrapping the default project (cc @brianleroux, @filmaj), happy to field that and we can investigate further1

**Comment by buffpojken** [comment]
Fair enough - have a great weekend!

**Comment by ryanblock** [comment]
Likewise @buffpojken!
