### ISSUE TITLE
Wrong handling of multiple cookies in sandbox

### ISSUE THREAD

**Issue by zaverden** [architect/architect#1090]
**Describe the issue**
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie):
> To send multiple cookies, multiple Set-Cookie headers should be sent in the same response.

`@architect/sandbox` joins multiple cookies into a single `set-cookie` header. A browser (google chrome at least) parses only the first cookie, ignoring the rest. 

Deployed app is not affected, issue is only in local runs with `@architect/sandbox`.

**Steps to reproduce**
1. from any HTTP handler return a response with several cookies
2. start app with `@architect/sandbox`
3. open a link to the handler in browser
4. check response in Network tab in devtools

**Expected behavior**
response contains several set-cookie headers

**Screenshots**
![image](https://user-images.githubusercontent.com/13230284/110197854-d6d30780-7e80-11eb-96e2-8f72766bde9b.png)
![image](https://user-images.githubusercontent.com/13230284/110197880-0550e280-7e81-11eb-99d8-1d7967cc4463.png)

**Comment by ryanblock** [comment]
Right on, we should do this provided that actually does match the API Gateway behavior. Can we confirm how API Gateway (REST, HTTP v1, HTTP v2) do it in the various cases (res with `headers`, res with `cookies`, res with `headers` + `cookies`)?

**Comment by zaverden** [comment]
@ryanblock 
For HTTP v2.
I have checked, the API Gateway behavior matches expected behavior I described. In addition here is a quote from [AWS spec](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format):
> In the response to the client, each cookie becomes a set-cookie header


For REST / HTTP v1.
Spec does not include `cookies` field. And `set-cookie` header is handled with a respect to multiple values:
https://github.com/architect/sandbox/blob/204003896fdd71b4d8a977a908ddcebc767001ab/src/http/invoke-http/rest/_res-fmt.js#L50-L54


For deprecated Arc <6 response formatter
I don't know where to find a spec for it, but looks like it does not expect to get multiple values there:
https://github.com/architect/sandbox/blob/204003896fdd71b4d8a977a908ddcebc767001ab/src/http/invoke-http/deprecated/_res-fmt.js#L25-L29
I think it is a good idea to not touch this part unless someone point an issue with this code.

**Comment by zaverden** [comment]
Fix itself is trivial. I've sent the PR https://github.com/architect/sandbox/pull/554

**Comment by filmaj** [comment]
Just pushed up arc 8.5.1 with your fix for Sandbox in it @zaverden, should be on npm shortly. Thanks again!

**Comment by ryanblock** [comment]
Thank you for your patience @zaverden, I've been on leave. And thanks to @filmaj for landing this!
