### ISSUE TITLE
Arc create isn't initializing routes found in `package.json`

### ISSUE THREAD

**Issue by ShawnHosea** [architect/architect#1095]
When defining lambdas using the new configurable file paths feature, running `arc hydrate`, `arc create`, and `arc init` does not update the project folder structure defined within `package.json`.

**Steps to reproduce**
1. Create a new project with Architect or Begin.
2. Define a few routes inside of your package.json using the configurable file path syntax.
3. Try running running `arc hydrate`, `arc create`, or `arc init` to automatically update your projects folders with the new routes.
4. According to this bug, you will not see any updates.

**Expected behavior**
The expected behavior is for the defined routes to create new folders within the project after hydrating.

example of configurable file path `package.json`

```json
{
  "arc": {
    "app": "begin-app",
    "http": {
      "get": "/",
      "post": "/api"
    }
  },
  "name": "begin-app",
  "version": "0.0.0",
  "description": "A simple Begin app with the minimum necessary file structure",
  "scripts": {
    "start": "npx sandbox"
  },
  "devDependencies": {
    "@architect/sandbox": "^3.3"
  }
}
```

**Comment by ryanblock** [comment]
Fixed in 8.4.11, thank you Shawn!
