### ISSUE TITLE
Sandbox http server does not start without the @http pragma

### ISSUE THREAD

**Issue by Ankcorn** [architect/architect#1099]
**Describe the issue**
A clear and concise description of the bug
When using the sandbox in a WebSockets project the websocket client fails to connect with the following error

```
Error: connect ECONNREFUSED 127.0.0.1:3333
```

**Steps to reproduce**
https://github.com/Ankcorn/testbin

run `npm start`

run `node ws-client.js`

**Expected behavior**
A clear and concise description of what you expected to happen
I would expect the websocket client to connect to the server

**Additional context**
Add any other context or notes about the problem here
https://github.com/architect/sandbox/blob/8699e130b7df344248278abc2334fad9656228eb/src/sandbox/_service-factory.js#L11

I think this is the offending line

**Comment by filmaj** [comment]
Just pushed up arc 8.5.1 with your fix for Sandbox in it, should be on npm shortly. Thanks again!
