### ISSUE TITLE
Sandbox throws error in deno projects when mod.js is used for handler function

### ISSUE THREAD

**Issue by kristoferjoseph** [architect/architect#1105]
## Description
When running architect/sandbox in deno projects it throws an error saying `index.js` not found

## Steps to repro
1. Go to https://github.com/begin-examples/deno-crud/
2. Clone the repo locally
3. run npm i
4. run npm start
5. Open the network tab in dev-tools and inspect the response from `GET /todos`

## Expected behavior
Requests to `/todos` should execute the handler function in `mod.js`

## Actual behavior
An error is thrown saying `index.js` is not found for the route being requested

## Screenshots
<img width="657" alt="Screen Shot 2021-03-26 at 3 13 20 PM" src="https://user-images.githubusercontent.com/76308/112698040-0e145300-8e46-11eb-88a0-05dadd5e323b.png">

**Comment by kristoferjoseph** [comment]
Solution was to update the app by moving `.arc-config` to `config.arc` and updated app to use `export function handler(){}`

**Comment by ryanblock** [comment]
Hmm, the `.arc-config` to `config.arc` should be a red herring, Inventory doesn't care what the filename is. It sounds like the fix was `export function handler(){}`!
