### ISSUE TITLE
least privilege redux (need to upgrade docs to explain admin access for authortime is required)

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1112]
there is a common misconception that authortime requires least privilege. this is incorrect. **runtime** requires least privilege and authors require admin access. we should update https://arc.codes/docs/en/guides/get-started/detailed-aws-setup to reflect this. 

account security is also a topic! might want to inc the AWS whitepapers on multi account security.

**Comment by ryanblock** [comment]
Fixed in https://github.com/architect/arc.codes/pull/462
