### ISSUE TITLE
sandbox: websocket send includes inventory object

### ISSUE THREAD

**Issue by pgte** [architect/architect#1121]
When using the sandbox, sending a websocket message injects the inventory into the payload:

https://github.com/architect/sandbox/blob/master/src/http/register-websocket/send.js#L7

I could ignore this in the client, but I wonder what is the reason behind this. Are you mimicking some AWS behaviour?

**Comment by ryanblock** [comment]
Hmm, not sure where that came from, will take a look. Thanks for letting us know!

**Comment by ryanblock** [comment]
Traced back to this change (by me): https://github.com/architect/sandbox/commit/02b4db8818675b2a050bb3099c1da38954754b73#diff-987a2edc0eeb14aa9dfc8300163ec3bdf2d3b3d79d684e9995de650a212dfb4b

Must not have been careful enough at tracing that particular code path's requirement for inventory. Thanks, patched in https://github.com/architect/sandbox/pull/573, will be in the next Sandbox release!

**Comment by filmaj** [comment]
Just pushed the arc 8.5.11 tag, should be live on npm in a few minutes and that release includes this fix.

**Comment by pgte** [comment]
@filmaj Brilliant, thank you!
