### ISSUE TITLE
how to make custom statuscode and header api response in ruby? and how to get event body and event path param in ruby?

### ISSUE THREAD

**Issue by yeukfei02** [architect/architect#1125]
lets say i have these func

post: createCake
```
require 'json'
require 'logger'

def handler
  logger = Logger.new($stdout)

  {
    message: 'createCake'
  }
end
```

get getCakeById
```
require 'json'
require 'logger'

def handler
  logger = Logger.new($stdout)

  {
    message: 'getCakeById'
  }
end
```

from the documation, I cant see `def handler(event:, context:)`
2 questions:
 - how do I get the request body and request path param?
 - how to make custom statusCode and headers? I already tried like this the below but not working.
 
```
{
    statusCode: 200,
    headers: {
      'content-type': 'application/json'
    },
    body: JSON.generate({
       'message': 'test'
    })
 }
```

Thanks for the help!

**Comment by brianleroux** [comment]
hey there! I setup a quick endpoint for you to test/see this for yourself

source: https://github.com/brianleroux/ruby-test
deployed: https://donut-e3t-staging.begin.app

lmk if you have any more questions or if you run into any issues; love ruby!

**Comment by ryanblock** [comment]
Also please see this example code here: https://github.com/architect/create/blob/master/src/lambda/templates/http.js#L98-L107

You may also refer to Amazon for this stuff as well: https://aws.amazon.com/blogs/compute/announcing-ruby-support-for-aws-lambda/

**Comment by yeukfei02** [comment]
@brianleroux @ryanblock 

finally i work like this:

```
require 'json'

def handler
  {
    statusCode: 200,
    headers: {
      'content-type': 'application/json'
    },
    body: {
      message: 'main'
    }.to_json
  }
end
```

btw can you guy update the ruby doc in arc.codes website?
this will help other developers much easier to work on.
thanks!
