### ISSUE TITLE
rails style crudl generators

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1128]
we should rip whatever rails did and just do that…I hear about this every day so its overdue!

**Comment by Ankcorn** [comment]
This would indeed be super useful!

I had a play with blitz.js the other day and they do this too. Was pretty convenient but also really helped me understand how things fit together. I think it could help people get started building architect apps which would be awesome.

This is what they did

when creating an entity it creates a bunch of routes

* GET /{entityName} - Lists all the items by their ID. Clicking the link takes you to the items page. Also contains a link to a form where you can create an item.
* POST /{entityName} - A form to create item. On submit takes you to the model's page. Has a link to take you to the list of items.
* GET /{entityName}/{entityID} - The page displaying json data for a item. Has a back and update link
* PUT /{entityName}/{entityID} - A form to update the item. On submit takes you to the items page, it also has a button to go back to the list item page.

Technically it would be really easy to generate these routes within an architect application with a plugin. The data source could in theory be anything though right? Does anyone have a good idea of how these data sources could be defined? 

Graphql maybe? :D

**Comment by filmaj** [comment]
This project may be of interest to you https://github.com/davejohnson/ergo

**Comment by brianleroux** [comment]
resolved in https://enhance.dev !
