### ISSUE TITLE
sandbox: queue event handler can't access env vars

### ISSUE THREAD

**Issue by pgte** [architect/architect#1139]
In the local sandbox, a queue handler lambda does not have access to the same environment variables as the http ones.

1. Define an env var on the root `.env` file.
2. Print it on a http lambda and invoke it. The value should appear.
3. Print it on a queue lambda and invoke it. The value does not appear.

I expect the queue handler to have access to the same env vars.

 - OS: macOS 11.3
 - Version: Architect v8.5.5

**Comment by pgte** [comment]
I suspect this is due to the way the sandbox spawns lambda processes in the events server, which I believe is different from the http one.

**Comment by ryanblock** [comment]
How are you invoking the event function?

**Comment by pgte** [comment]
@ryanblock using `arc.queues.publish({ name, payload })`.

**Comment by ryanblock** [comment]
Great, will check it out ASAP!

**Comment by ryanblock** [comment]
Hey there, I'm unable to get this to repro, please see: https://github.com/ryanblock/arc-1139
https://github.com/ryanblock/arc-1139/blob/main/src/events/event/index.js#L2-L3
![image](https://user-images.githubusercontent.com/200964/117207098-6b39e780-ada8-11eb-9641-a275a8452c22.png)

**Comment by pgte** [comment]
@ryanblock Thank you for your help. I did a fresh install and it's working now. No idea what happened.
Will reopen if I see this happening again.
