### ISSUE TITLE
MaxListenersExceededWarning with plugins support

### ISSUE THREAD

**Issue by andybee** [architect/architect#1142]
When using plugins, if you have a slow to complete async function in `sandbox.end` and hit CTRL+C multiple times, each keypress attaches a new `close` listener to the process. Because it's not clear what's happening with a slow shut down, it's easy to hit this a few times then get the following error:

```
(node:88902) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Server]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

Would it be better to have a flag to track that the shutdown process has been attempted and then only attach the listener when it's false, setting it to true?

**Comment by filmaj** [comment]
Ya, something like that makes sense.

Interesting re: the warning. For me, I get that mostly when I boot sandbox up, but I haven't filed an issue or dug into why yet. Good to know you get it to.

**Comment by andybee** [comment]
I’ve also seen it occasionally with long running events and never quite worked out if it’s my code or Sandbox, so not been able to report it.

**Comment by filmaj** [comment]
NM I'm able to reproduce by pulling the latest `master` branch from `architect/architect` and running the `arc version` command equivalent from within that module. Can even trace the warning in this way:

```
➜ node --trace-warnings src/index.js version
(node:7174) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at process.addListener (events.js:406:10)
    at Object.<anonymous> (/Users/filmaj/src/sandbox/node_modules/@architect/utils/updater/index.js:141:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/filmaj/src/sandbox/node_modules/@architect/utils/banner/init-aws.js:4:15)
      Version: Architect 8.5.10
 Installed to: /Users/filmaj/src/architect
          cwd: /Users/filmaj/src/architect
```

**Comment by filmaj** [comment]
Hmm, I guess my repro and @andybee's initial report are different warnings: Andy's for too many listeners to a `close` event on `[Server]` (whatever that is), and mine for too many listeners on SIGINT.

**Comment by filmaj** [comment]
One thing I've noticed here: if you specify the env var `CI=1` (to suppress the fancy terminal output), I don't get this warning anymore.

**Comment by andybee** [comment]
I've hit this again in an event. Interestingly adding `CI=1` had no impact on the issue. Though, this time it's a different object reported, which makes me wonder if this one is inside my event code.

```
(node:12438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:12438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:12438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:12438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(node:12438) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
```

**Comment by andybee** [comment]
This might be another timeout weirdness thing. I'm hitting this in this weird chain workaround I've somehow landed on where I have an event that just requires the code from a scheduled function and runs it. Just realised the timeout on the event was short, increasing it, it's now ploughing along.

**Comment by ryanblock** [comment]
Should we close this?

**Comment by andybee** [comment]
@ryanblock I've not hit this issue again in quite a while, so happy to close it in terms of tidying up. Can always re-open if I can replicate again/shed more light on the issue?

**Comment by ryanblock** [comment]
Of course, always!
