### ISSUE TITLE
Deno - the lambda layer uses an old version of Deno

### ISSUE THREAD

**Issue by hicksy** [architect/architect#1143]
(Architect 8.5.10)

The Deno layer `arn:aws:serverlessrepo:us-east-1:455488262213:applications/Deno` is using an old version of Deno. Is it possible to update this to `1.9.2`?

```javascript
//deno-lint-ignore require-await
export async function handler (event: object) {
    console.log(Deno.version)
    return {
        statusCode: 200,
        headers: {
          'cache-control': 'no-cache, no-store, must-revalidate, max-age=0, s-maxage=0',
          'content-type': 'text/html; charset=utf8'
        },
        body: 'hello world'
    };    
}
```

logs:

`{ deno: "0.26.0", v8: "8.0.192", typescript: "3.7.2" }`

**Comment by filmaj** [comment]
Ya should be! Forgive my ignorance, as I don't use deno on my projects, but I see the code that adds that to the sam.json/yaml is here: https://github.com/architect/package/blob/master/src/visitors/deno/index.js#L25

Any idea what the source of the embedded ARN is? Where is that revisioned / how did you figure out what ARN to use @brianleroux ?
