### ISSUE TITLE
Allow sandboxing just the tables

### ISSUE THREAD

**Issue by thislooksfun** [architect/architect#1151]
**Is your feature request related to a problem? Please describe.**
I'm trying to build an application using SvelteKit and I'd prefer to keep using their tooling for running a development server as it better fits my use case, but I also want to be able to use features of my application that rely on a database. Currently I have to choose between either running with the fast and hot-reloading native Svelte dev server but with no database, or running a slow and manual build after each change so I can run the compiled server with arc.

**Describe the solution you'd like**
What I want to be able to do is run something like `arc sandbox --tables-only` to spin up a local DynamoDB-esque interface that I can interact with from the native Svelte dev tools.

**Describe alternatives you've considered**
N/A

**Additional context or notes**
N/A

**Comment by filmaj** [comment]
So currently no such CLI flag exists, though I'm open to the idea of implementing that.

Workaround potential: what about dipping into the sandbox node API? You should be able to do something like the following to start the DynamoDB mock server:

    require('@architect/sandbox').tables.start({ quiet: true }, function (err, result) {
      console.log(err, result)
    })

... and similarly with `end` to stop it once you're done:

    require('@architect/sandbox').tables.end(function (err, result) {
      console.log(err, result)
    })

Both of the above can also be invoked with `await` if you prefer that style, i.e. `await sandbox.tables.start({quiet: true})`.

[The sandbox integration tests for the DynamoDB functionality](https://github.com/architect/sandbox/blob/master/test/integration/tables-test.js) use this exact technique:

1. [Start just the DynamoDB server](https://github.com/architect/sandbox/blob/master/test/integration/tables-test.js#L65)
2. [Run a bunch of tests](https://github.com/architect/sandbox/blob/master/test/integration/tables-test.js#L71-L168)
3. [Stop the DynamoDB server](https://github.com/architect/sandbox/blob/master/test/integration/tables-test.js#L172)

**Comment by thislooksfun** [comment]
@filmaj That looks like an excellent workaround. Do I need to run `tables.end()` before the program exits, or will it clean itself up?

**Comment by filmaj** [comment]
Depends on your purposes, I suppose. If you're running it as part of a development server and you are manually interacting with it and you can explicitly shut down the SvelteKit dev server, then maybe you don't need to call `end` as you will e.g. kill the SvelteKit + dynamodb mock server process manually with Ctrl+C.

If, however, you want to run this in a process to completion (say, as part of a continuous integration pipeline), then I think yes, you will need to explicitly run `tables.end` otherwise the node process won't complete (since there will be a DynamoDB mock server up and listening for connections).

**Comment by thislooksfun** [comment]
I realize what I said was ambiguous. What I meant was "will killing the process leave an orphaned database process floating around, or do I need to add a Ctrl+C handler to explicitly call `.tables.end()`?

**Comment by filmaj** [comment]
No I do not think so, the underlying mock DynamoDB server is all written and managed in node and is a simplified in-memory DynamoDB, so killing the process should shut all the underlying DB bits down too.
