### ISSUE TITLE
API symmetry improvement: support `pitr` in addition to `PointInTimeRecovery` for DynamoDB options

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1155]
This came out of the conversation in #1083, basically arc's DynamoDB support allows for specifying a `PointInTimeRecovery` property, but this doesn't line up with the casing we've been using in arc.

As such, we should add support for both `pitr` and `PointInTimeRecovery` and deprecate use of `PointInTimeRecovery`.

**Comment by ryanblock** [comment]
Fixed in Inventory 1.4.0 + Package 6.2.2 (and either Arc 8.7 or 9.0, whichever is released first!).
