### ISSUE TITLE
`static.json` file not being deployed correctly via hydrate without `src/shared` dir

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1170]
Repro example project:
```
# app.arc
@app
app

@http
get /

@static
fingerprint true
```
```
# project files
app.arc
src/http/get-index/index.js
public/some-file.js
public/static.json # generated by arc
```

This app will not ship `static.json` to the `get /` Lambda because the `src/shared` directory is not present. Here's why:

- Inventory tries to find `@shared` + `@views` settings and/or default folders to know whether it's enabled
- If the setting and/or default folder is not found, Inventory marks `@shared` and `@views` as `null` (which is Inventory's convention for deactivated pragmas/features)
- Meanwhile, the job of `@static fingerprint true` is ensure `$STATICDIR/static.json` finds its way into `src/http/get-index/node_modules/@architect/shared/static.json` for deployment
- In Hydrate, we use the `inv.shared.shared` (the list of functions that have `shared` / `views` enabled) to know where to do things like copy `@architect/shared` and, more specifically, `@architect/shared/static.json`
- If the user is not using shared code (e.g. `src/shared` does not exist), this sets `inv.shared` to `null`; without `inv.shared.shared`, Hydrate assumes there are no files to be shared, and does not inject `static.json` for deployment
- Thus, the workaround is just to create an empty `src/shared` folder (which is pretty janky)

My proposed fix is here:
- Hydrate: https://github.com/architect/hydrate/pull/140
- Inventory (optional): https://github.com/architect/inventory/pull/21

Summary of changes:
- I thought Inventory would need the changes in the PR above, and then when I got back to implementing in Hydrate I could do everything I needed in Hydrate without the Inventory PR; thus, it's optional (but could still be useful metadata to have in the future)!
  - Inventory PR thinking:
  - I don't want to change the "`null` is equivalent to deactivated" convention in Inventory, especially for a special case / esoteric bug
  - However, Hydrate still needs to be able to map out how to insert `static.json` without `src/shared` present
  - So just include the official set of Arc pragmas and Lambda pragmas [I recently added](https://github.com/architect/inventory/commit/576d2e9dc626868e02e5259aa54b25cecf2dfef8#diff-51785bcee6e59a7c4b04ec1dae4ae6c8f70521246cdfa18775fe97e33ea63ac6) to Inventory's `inv._arc` metadata object
  - This will allow a caller (such as Hydrate) to re-create the shared file map for this special case
- Actual implementation:
  - Just create separate hashtables for all functions (via `inv.lambdasBySrcDir`), vs functions that get `shared` and / or `views`, duh. 🙃 

Thanks for reporting, @tejnri!

**Comment by tejaswihidoc** [comment]
Thank you @ryanblock for quickly looking into this. It saved a lot of my time.

**Comment by ryanblock** [comment]
This will ship today in Arc 8.7!
