### ISSUE TITLE
Add named stage parameter to plugin methods

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1179]
**Is your feature request related to a problem? Please describe.**
Currently when writing the `package` or `variables` methods of plugins, you have access to a `stage` parameter that tells you whether the `arc deploy` invocation is for a staging or production environment. However, if you run an `arc deploy --name Something`, that named stage is not provided (in this example, `stage` is equal to `staging`).

**Describe the solution you'd like**
Either include the name in the `stage` environment, or provide a separate parameter that provides the stage name.

**Comment by ryanblock** [comment]
Hmm, does this issue conflate the stage (one of `testing`, `staging`, `production`) and the name (the ability to add an arbitrary CloudFormation stack name to your app deployment)? If so, how would we revise?

As of Arc 10 RC, Inventory objects now have a `inv._arc.deployStage` property set for `plugin.deploy.*` hooks.

**Comment by ryanblock** [comment]
Will close for now, but pls reopen if we aren't satisfied with how this is working!
