### ISSUE TITLE
Sandbox simulate @proxy configured for S3 Web Hosting 

### ISSUE THREAD

**Issue by snelgrove** [architect/architect#1206]
**Is your feature request related to a problem? Please describe.**
I'm building an Architect project which also has a browser based static front end. The static site is placed in the Architect project's `@static` directory and deployed along with the rest of the project. I use `@proxy` to forward browser requests to the `http://<bucket>.s3-website-<region>.amazonaws.com` URLs of each environment.  

My problem has two elements: 
1. This use of proxy doesn't work locally, using the sandbox.
2. I need to run both client and server(less) in the sandbox to avoid CORS errors.

**Describe the solution you'd like**
I'd like [architect/sandbox](https://github.com/architect/sandbox) to support this configuration during local development, using the existing config, which works in staging and production:
```
@proxy
  testing http://localhost:3333/_static/
``` 
So a browser navigating to `http://localhost:3333/` will be served `http://localhost:3333/_static/index.html`

I have modified my sandbox with a minor change, and found that it works well (details below).  

**Describe alternatives you've considered**
- [x]  Run the front end dev server and sandbox (backend) independently.
This results in CORS problems (as each project runs on a different port).
- [x] Copy the front end code into the Architect project.
The static files are served under the `_static` path, which breaks internal links and hrefs within your client project.

**Additional context or notes**
I have made a change to my local sandbox which I'm happy to contribute if you're ok with my approach. Here's what I came up with:

Since`@proxy` is designed to capture any requests that are not handled by `@http`, it will also attempt to proxy any proxied requests that haven't been fulfilled; i.e. the requested file is genuinely missing. It will do this until it crashes. My solution is to watch for any request whose URL begins with the URL configured for the proxy (indicating it has already been forwarded once). Such requests should result in a 404. 

Modify the static-path middleware to append `index.html` not only to the base path, but any path that ends with a directory (since many front end architectures use links such as `/blog/`). This also matches S3's handling of paths.

**Comment by ryanblock** [comment]
Thanks, this issue really describes what's going on quite well.

Assuming you are using a recent version and not using a legacy `REST` API, Architect supports your use case out of the box without using the `@proxy` pragma.

Just add `@http` to your project manifest and you should be good to go!

**Comment by snelgrove** [comment]
Thanks Ryan. I am already using HTTP APIs, but perhaps I wasn't when I originally started learning Architect. Anyway, your response got me questioning my config! 

I think, several months ago, I may have used `@proxy` to bypass the greedy `GET /` route that the template supplies. At some point I removed that route, but not the proxy, which appeared to make everything work nicely anyway. Except in sandbox, obviously 🙄  

Since clearing that up, I found that API Gateway would only serve my root `index.html`, which may have also led me down the path of using `@proxy`. I found the `ARC_STATIC_SPA` env variable and set it `false` directly in the "GetCatchallHTTPLambda". Couldn't find this setting in the docs, and I'm wondering whether I can switch SPA off in `app.arc` instead?

**Comment by ryanblock** [comment]
You can indeed! Here are three ways to do that:
- Upgrade to Arc 9, where that is the new default setting
- `arc env ARC_STATIC_SPA false`
- Add this to your app.arc:
```
@static
spa false
```

**Comment by snelgrove** [comment]
Heh, I was holding off on upgrading from Arc 8.74 to 9 until I'd sorted out this problem, turns out Arc 9 fixed my latest issue by changing the default mode 🎉 

In summary - Running Arc 9, no `@proxy` and no greedy `@http GET /*`, arc sandbox serves my static site out of the box!  

Thanks again @ryanblock

**Comment by ryanblock** [comment]
👏🏼👏🏼👏🏼
