### ISSUE TITLE
Feedback Requested: Kill switch for a runaway apps (triggered by cost)

### ISSUE THREAD

**Issue by ryanbethel** [architect/architect#1215]
Serverless users want to limit the potential cost of a runaway project. With an infinitely scalable app they fear it could be infinitely expensive if something goes wrong. 

**Would you use a feature that could provide a strong assurance of a max cost if it meant your app resources might be deleted from AWS to accomplish it?** Data (including S3 and dynamoDB tables) could be preserved. The app would need to be redeployed to restart.

--- Alternatives and additional information --- 

There are two main use cases. Some users only want to be notified if the cost exceeds some threshold. Others want the system to take some action to shut the app down or limit the cost proactively. The second case is difficult given the flexibility of Architect apps. 

Three levels of intervention are being evaluated: 
1. Soft shutdown: all incoming requests are diverted to a static page
2. Intermediate shutdown: Disable all the compute, but keep resources in place (possibly by reducing concurrency to zero for every resource)
3. Hard shutdown: Delete the resources for the app (while still retaining data)

Tradeoffs: 
- 1 & 3: These two together are easy to implement. 3 provides a stronger guarantee to limit costs. The downside is it is difficult to debug a problem when the resources have been removed. To restart the app it would need to be redeployed. 
- 2: Seems ideal to shut down the app but not remove resources. Downside here is that there are may be more edge cases where this might fail.

**Comment by brianleroux** [comment]
I'm def in favor of option 2. If the user wants to destroy the app they can do that explicitly. 

Walking the stack resources finding anything that is a Lambda and dropping the concurrency to 0 should be pretty easy. Not sure what sort of new problems this creates but I'm sure we'll find out! (haha!) Whatever 'reset' algorithm we run we will also want an easy undo so the stack can be easily reset to the original concurrency/state.

**Comment by filmaj** [comment]
This is a pretty rad idea @ryanbethel !

> Soft shutdown: all incoming requests are diverted to a static page

What would a soft shutdown mean for non-HTTP resources like queues, events, or database read/write capacity?

**Comment by ryanbethel** [comment]
> What would a soft shutdown mean for non-HTTP resources like queues, events, or database read/write capacity?

@filmaj It wouldn't affect any other resources. It just shuts the front door. There would still be many ways for the app to run up cost with that alone. It looks like the preferred approach is 1 & 2 together. Surprisingly people don't like the idea of a tripwire automatically deleting their stuff.

**Comment by filmaj** [comment]
Just like @brianleroux I would be in favour of (2)

**Comment by ryanbethel** [comment]
This feature has been added with the help of a plugin [https://github.com/architect/plugin-budget-watch](https://github.com/architect/plugin-budget-watch).
