### ISSUE TITLE
Add a dry run flag to the params sent to a macro/plugin function

### ISSUE THREAD

**Issue by andybee** [architect/architect#1218]
I'm currently using a macro function to run a quick CloudFormation deployment of another stack prior to Architect doing its thing. Works great, but this deployment will always happen even if you're running deploy with a dry run flag.

If we could expose the fact a deployment is doing a dry-run to the function, then my logic can listen for it and not run the extra steps.

Not sure if this should be as simple as:

```
function myMacroFunction(arc, cf, stage, dryRun)
```

where `dryRun` is a boolean, or we create an `options` object literal so we don't start kitchen-sink'ing all the params in to the function itself, e.g.

```
function myMacroFunction(arc, cf, stage, options = {}) {
  console.log(options);
}

{ dryRun: true }
```

**Comment by ryanblock** [comment]
This is a great idea, will add it to the final Arc 10 release API for `deploy.start`. Unfortunately, it won't be available for Macros, as that API is settled.

**Comment by ryanblock** [comment]
Will be released in Arc 10 RC2 (likely tomorrow, Monday)! https://github.com/architect/deploy/pull/349/commits/297929cd601a9557c494280f85c43723c3bae481
