### ISSUE TITLE
Documentation says "node 12" and but actually requires 14

### ISSUE THREAD

**Issue by macornwell** [architect/architect#1224]
**Describe the issue**
Documentation says architect needs node 12, since it uses optional chaining it needs node 14.

**Steps to reproduce**
1. nvm install 12
2. npm i -g @architect/architect
3. arc version
4. You'll see it explode

**Expected behavior**
Either documentation should be updated or optional chaining removed.

**Additional context**
None

**Comment by ryanblock** [comment]
Good call. Minimum node version is now 14, will update the docs. Thank you!

**Comment by macornwell** [comment]
No problem! I noticed it in a few places.
One way to tackle/track this issue fairly easily is some basic "unit tests" / integration tests throught github actions, that use different versions of node. (I've found that quite useful in the past for really simple "does the application explode" tests)

**Comment by ryanblock** [comment]
This was a documentation issue, not a testing issue. I suspect you're being helpful with this advice, but yes, we are acquainted with automated testing. We also version control our code! 😜

**Comment by macornwell** [comment]
Just another way to think about it, using automated testing as documentation (call it proof).

**Comment by ryanblock** [comment]
PRs welcome!

In the mean time, fixed in https://github.com/architect/arc.codes/commit/3cae7e49111463abaec4f6ae0669d9adab35c1fd
