### ISSUE TITLE
`asap` throws fatal error when used inside another handler function

### ISSUE THREAD

**Issue by andybee** [architect/architect#1231]
**Describe the issue**
When using `asap` as part of another handler function, a fatal error is thrown because it's attempting to access `ARC_SANDBOX_PATH_TO_STATIC` which is not set in a new Architect 9.0.3 project.

**Steps to reproduce**
1. Create an Architect project, configure it for static hosting.
2. Add the following code to your index handler:
```
const asap = require('@architect/asap')();

exports.handler = async (event) => {
  // custom logic goes here

  return asap(event);
};
```

**Expected behavior**
`asap` should handle the supplied event as normal and attempt to proxy the request from S3.

**Comment by ryanblock** [comment]
Patched in 9.0.4, thank you @andybee!
