### ISSUE TITLE
The SvelteKit adapter can't be installed

### ISSUE THREAD

**Issue by mikenikles** [architect/architect#1236]
**Describe the issue**
Due to the `postinstall` script ([code](https://github.com/architect/sveltekit-adapter/blob/main/package.json#L10)), the SvelteKit adapter can't be installed.

```bash
gitpod /workspace/webstone-dev-app $ pnpm add -D @architect/sveltekit-adapter --filter ./services/web/
@webstone/cli is linked to /workspace/webstone-dev-app/node_modules from /workspace/webstone/packages/cli
.                                        |  +18 ++
Progress: resolved 326, reused 310, downloaded 0, added 0, done
node_modules/.pnpm/@architect+sveltekit-adapter@0.0.3/node_modules/@architect/sveltekit-adapter: Running postinstall script, failed in 22ms
.../@architect/sveltekit-adapter postinstall$ cd example/hn && npm install
│ sh: 1: cd: can't cd to example/hn
└─ Failed in 22ms
 ELIFECYCLE  Command failed with exit code 2.
```

**Steps to reproduce**
1. Create a new SvelteKit project with `npm init svelte@next`
2. Install the Architect adapter with `npm install @architect/sveltekit-adapter`

**Expected behavior**
The adapter is installed without errors.

**Screenshots**
N/A

**Desktop**
Please complete the following information (if appropriate):
N/A

**Mobile**
Please complete the following information (if appropriate):
N/A

**Additional context**

**Comment by ryanbethel** [comment]
@mikenikles 
Thanks for reporting the issue. I just pushed a fix @0.0.4. Let me know if you have any other problems.
