### ISSUE TITLE
Deploy standalone lambda functions

### ISSUE THREAD

**Issue by gregorym** [architect/architect#1239]
**Is your feature request related to a problem? Please describe.**
This a question related to the docs and understand a use case.

**Describe the solution you'd like**
I would like to create an HTTP endpoint that can trigger thousands of lambdas (~10,000) and after it's completion, trigger custom logic.
My understand is I could use Events to achieve a similar behavior, however I won't be able to know when all events have finished (afaik?).

Ideally, I wanted to be able to deploy a standalone lambda (not possible according to the docs) and from my http endpoint trigger N times my standalone lambda and then (async/await) run additional logic.

Is this possible, or you may have another recommendations using Events or Queues?

thank you!

**Comment by brianleroux** [comment]
(Feel free to reopen or open a new issue w any feedback as you progress!)
