### ISSUE TITLE
arc logs nuke [path/to/logs] no longer functioning

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1241]
running `arc logs nuke /src/http/get-index` expected it to destroy those logs; instead it displays them

might want to make this better anyhow. `arc logs --destroy /path/to/log` so its super clear

**Comment by brianleroux** [comment]
update! appears `arc logs` is now not functioning either (?) need to triage and setting this to remind myself

**Comment by ryanblock** [comment]
Appears to be a docs issue, `nuke` was phased out in favor of `destroy` as of earlier this year.
