### ISSUE TITLE
rename SESSION_TABLE_NAME to ARC_SESSION_TABLE_NAME

### ISSUE THREAD

**Issue by tbeseda** [architect/architect#1244]
Created during the maintainer call today.

related: https://github.com/architect/architect/issues/1222

**Comment by ryanblock** [comment]
Implemented in Arc 10, and noted in the changelog + upgrade guide. Related, `SESSION_TABLE_NAME` will continue to be supported if set by the user, but namespaced env vars will be preferred and used over their non-namespaced equivalents.
