### ISSUE TITLE
[@architect/sandbox] Node 16.10.0, npm 7.24.0 and ESLint 8.0.0

### ISSUE THREAD

**Issue by macdonst** [architect/architect#1262]
**Describe the issue**

npm test fails to run with the combination of:
- Node 16.10.0
- npm 7.24.0
- ESLint 8.0.1

If we upgrade to ESLink 8.1.0 then `npm test` succeeds. 

**Steps to reproduce**
1. Do a clean clone of the repo
2. Use node 16 and npm 7
3. Run `npm it` 
4. See error that says 

```
> @architect/sandbox@4.2.2 lint
> eslint . --fix


Oops! Something went wrong! :(

ESLint: 8.0.1

ESLint couldn't find the plugin "eslint-plugin-filenames".

(The package "eslint-plugin-filenames" was not found when loaded as a Node module from the directory "/Users/simonmacdonald/Developer/architect/sandbox".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-filenames@latest --save-dev

The plugin "eslint-plugin-filenames" was referenced from the config file in "package.json » @architect/eslint-config".
```

**Expected behavior**
Expect when you run npm install it will pull in all the dependencies that we need.

**Comment by ryanblock** [comment]
Known issue, npm 8.1.1 fixes it, see https://github.com/npm/cli/issues/3881#issuecomment-941718208
