### ISSUE TITLE
arc init/create won't scaffold arc.toml in some cases

### ISSUE THREAD

**Issue by tbeseda** [architect/architect#1263]
`arc init` fails to scaffold if a simple pragma like "static" is added to the top of `arc.toml`

```toml
[static]
fingerprint=true

ws=[
  "action",
  "connect",
  "default",
  "disconnect"
]

http=[
  ["get", "/"],
  ["get", "/likes"],
  ["post", "/likes"],
]

events=["hit-counter"]
```

will **not** create src/events, src/http, src/ws

but

```toml
ws=[
  "action",
  "connect",
  "default",
  "disconnect"
]

http=[
  ["get", "/"],
  ["get", "/likes"],
  ["post", "/likes"],
]

events=["hit-counter"]

[static]
fingerprint=true
```

will scaffold as expected.

I cannot reproduce with YAML or JSON. just TOML 🎉

**Comment by ryanblock** [comment]
Per https://github.com/architect/architect/discussions/1294, `toml` support will be removed in Arc 10. 👋
