### ISSUE TITLE
arc init ./foo fails

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1268]
`arc init ./foo` fails; expected it to create `./foo` with a default architect project
<img width="1018" alt="Screen Shot 2021-11-12 at 3 19 00 PM" src="https://user-images.githubusercontent.com/990/141594436-3d6c6c1b-a424-4ea8-be94-50ee31dff48a.png">

**Comment by ryanblock** [comment]
Just to confirm: `arc init edge` works (I hope)?

**Comment by brianleroux** [comment]
alas it does not ! <img width="1076" alt="Screen Shot 2021-11-12 at 4 25 36 PM" src="https://user-images.githubusercontent.com/990/141598073-4f2bb136-510a-456e-adc9-829c6ada8a07.png">

**Comment by ryanblock** [comment]
Oy, sorry! Will patch asap.
