### ISSUE TITLE
performance: way to add dynamodb table name(s) to lambda's env variable, use that in arc.tables()

### ISSUE THREAD

**Issue by stefangomez** [architect/architect#1280]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
While arc.tables() is a nice helper tool, it currently calls SSM parameter store to get the table name (on cold start). The table name should be known after sam/cf template generation, so ideally you could set an env variable name on the lambda for use with `arc.tables()` (or any other dynamodb client that requires the table name to do operations) without the extra call to SSM. Seems to only happen on cold starts which implies at least arc.tables() caches the table name. Sooo it's not a major issue, but cold start time optimization is always good right? Interestingly enough I discovered this from Sentry's tracing. 

**Describe alternatives you've considered**
Using aws-sdk directly, but still requires you to know the table name.

**Additional context or notes**
Sentry screenshot: ![sentry screenshot](https://drops.nafets.io/3EkgmOBZ4M.png)
Yes I'm coding on Thanksgiving.... Post food-coma. Happy turkey day! 🦃

**Comment by ryanblock** [comment]
Generally I personally like ideas such as this! However each Lambda only gets 4KB of env var data, so we’ve opted not to use it for this (and other similar purposes). I could see it being a plugin perhaps. There would be a fair amount of bookkeeping to make that work, fwiw.

**Comment by stefangomez** [comment]
Yep, totally get that env var data is limited. I think having the option to inject table name(s) as a env variable at least would be a nice feature. A plugin is a good idea. Maybe a macro is sufficient enough? I'll look into both, forgot about those. Thanks!

**Comment by ryanblock** [comment]
Macros are being retired in favor of plugins, fwiw. Package plugins are effectively just macros, however!

**Comment by stefangomez** [comment]
@ryanblock finally got around to creating an initial plugin for this: https://github.com/stefangomez/arc-plugin-lambda-env - but I did run into an issue, see: https://github.com/stefangomez/arc-plugin-lambda-env/issues/1 -- basically on architect 9.0.3 and above, my plugin doesn't work in sandbox. I did a little digging but couldn't figure it out quickly. Let me know if you know the right way to inject env vars into sandbox lambdas in newer versions of architect. thanks!

**Comment by ryanblock** [comment]
Right now there are two ways to populate env vars in Sandbox, via preferences file and via module API. Unfortunately no plugin hook yet!
- https://arc.codes/docs/en/reference/configuration/local-preferences#%40sandbox
- https://github.com/architect/sandbox#api

**Comment by ryanblock** [comment]
Good news: we've got a new plugin hook that will support this use case! In Arc 10, see `plugin.set.env`, which returns an object containing the keys/values you want to populate. Lmk if you'd like a hand in implementing!

**Comment by stefangomez** [comment]
@ryanblock - cool thanks. I modified my plugin to support v10 - mind taking a look? https://github.com/stefangomez/arc-plugin-lambda-env/pull/2/files

couple notes: `set.env` seems to set env variables for *all* environments. It'd be nice if we could set this *per* environment. Since it did that, I hacked a way to *only* set an env variable for sandbox/testing by still using `sandbox.start` and modifying the project env object which happens to be a referenced object for all environments...so it works. Is there a better way to do this?

**Comment by ryanblock** [comment]
Hmm, I knew this would be a feature request sooner or later, kinda glad it’s sooner!

Maas thinking that we could look for three reserved keys: testing, staging, production, and expect each to be an object containing env vars for that environment. Wdyt?

**Comment by stefangomez** [comment]
yeah that works! In fact that's what I assumed it would be. I tried returning an object with { testing: { ...envVars } } just to see if it would work. Guess I was just a bit early :)

**Comment by ryanblock** [comment]
@stefangomez ok, here it is: https://github.com/architect/inventory/pull/38/commits/6ff98144c5889bda6ec064efd58000f7ad445ee4 This should be out in Arc 10 RC2 likely tomorrow (Monday).

**Comment by ryanblock** [comment]
Hey, just wanted to check back on this! The Arc 10 API has settled for launch, how can I help you ship this plugin?

**Comment by stefangomez** [comment]
@ryanblock - cool - I updated my plugin and shipped a new version for Arc 10 support 😄  https://www.npmjs.com/package/arc-plugin-lambda-env

**Comment by ryanblock** [comment]
This is rad! Want to PR it to the architect/plugins repo?

**Comment by stefangomez** [comment]
@ryanblock oh nice. yeah will do now

**Comment by stefangomez** [comment]
Done

**Comment by ryanblock** [comment]
Just a heads up, this line (and related functionality) has problems in 10: `const tablesPort = Number(process.env.ARC_TABLES_PORT) || 5000;`

Arc 10 has dynamic port selection; those ports aren’t known until well after set.env runs (and the starting port changed too). For whatever that is worth!

**Comment by stefangomez** [comment]
@ryanblock - hmm. so moving it back to `sandbox.start` might be better like I had [here](https://github.com/stefangomez/arc-plugin-lambda-env/pull/2/commits/08b28b0a5e91c85a8f890c50fcc3ba36c335403d#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R48). Any chance it's defined somewhere in the `inventory` that's passed to `sandbox.start`?

**Comment by ryanblock** [comment]
Sandbox plugins (and all Lambdas) get an env var called ARC_SANDBOX, which is a JSON object that contains a ports property. So you may not need to set that env var anyway, as any Sandbox Lambda now has access to the local Dynamo port.

**Comment by stefangomez** [comment]
cool I just saw that. I'll try to add that to my readme so that users know they need to use `ARC_SANDBOX` to determine the DynamoDB local port since the purpose of this plugin is to not have to rely on the @architect/functions package

**Comment by stefangomez** [comment]
@ryanblock - cool updated plugin, README and sample app. works!

**Comment by ryanblock** [comment]
Nice! Shall we close this issue?

**Comment by stefangomez** [comment]
yep!
