### ISSUE TITLE
The support for "any" HTTP method is not documented

### ISSUE THREAD

**Issue by trsrm** [architect/architect#1281]
I spent more than hour trying to understand of how to handle multiple HTTP methods by a single Lambda. But, only when I investigated your sources, I found the ability to set "any". I think, this is not OK. 🙂

<img width="124" alt="image" src="https://user-images.githubusercontent.com/1160872/143894964-ccd13592-8895-4aaa-b188-a023af222125.png">

**Comment by ryanblock** [comment]
Yikes, this is a pretty gross oversight. Will aim to have it documented today. Thank you!
