### ISSUE TITLE
RFC: plugin API for Architect 10

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1295]
After the last few months of mulling this over in the background, and doing some additional research and prototyping, I've started working on the next iteration of the Architect plugins API, which I hope will ship as Architect 10[^1] in early 2021.

---

### Some plugin use cases from around the community

We started by collecting use cases from around the Architect world and seeing if / how they could fit into a plugin model. Here are a few that stood out:

- Plugins that automatically create fully-functional Architect primitives (example: "I want to add a plugin that resizes images at `get /_images/{name}` in my project", see [this project](https://github.com/ryanbethel/arc-image-plugin))
- Create generic Lambdas and augment / attach them to arbitrary services (see [this project](https://github.com/copperinc/plugin-iot-rules/))
- Create an arbitrary number of functions (example: "I want to have 200 `@events` functions without having 200 lines to maintain in my `app.arc` file")
- Add Cognito and custom authorizer support to API Gateway (see https://github.com/architect/sandbox/pull/477)
- Add more extensive Lambda lifecycle mocking
- End-to-end support for completely custom runtimes (example: "I want Architect to be able to fully work with the Lambda PHP runtime layer, including Sandbox", see #1226)
- Ship Architect projects to an AWS intermediary (e.g. Serverless Cloud or Begin[^2])
- Automatic integration with frontend (meta-)frameworks that may otherwise require a lot of manual intervention (see: Architect Discord, like, every day 😅)

---

# API approach

Below is the approach to interfacing with the Architect API:

- Plugins are authored in JS, and export an object containing methods for named workflow hooks (e.g. `plugin.sandbox.start`) and methods for setting pragma (and related) primitives (e.g. `plugin.set.http`)
  - We should assume CommonJS for the time being, as we [cannot mix `require` with ES Modules](https://nodejs.org/api/esm.html#require)
- Workflow hooks:
  - Correspond to lifecycle events in select Architect workflows (e.g. `plugin.deploy.start`, `plugin.sandbox.end`, etc.) 
  - Can be sync or async
- Setter hooks:
  - Create Architect primitives, mapping either to pragmas (e.g. `plugin.set.http` creates `@http` routes) or related primitives (e.g. `plugin.set.env` creates environment variables)
  - Are synchronous (and will throw if are async)
    - This is because unlike workflow methods, setter methods run within [Architect Inventory](https://github.com/architect/inventory/) and help build the project graph for every single Architect execution, so it needs to be super fast

---

# API methods

The following methods denoted "still scoping" are still currently the most subject to change. Please tear this to pieces!

## `deploy`

- `deploy.start` - run arbitrary pre-deploy operations + mutate CloudFormation
  - What used to be `@macros` (and is currently `plugins.package` in the current plugins beta)
    - Related: `@macros` will transparently work with `@plugins`
- `deploy.services` (currently `plugin.variables`) - hook into Architect service discovery to create references to custom resources, or populate configuration data
- `deploy.target` - use case: ship to an AWS intermediary (Serverless Cloud or Begin)
- `deploy.end` - run arbitrary post-deploy operations

## `hydrate`

- `hydrate.run` - [still scoping] run a given command against some or all Lambdas instead of existing Hydrate commands
  - Example: instead of the default `npm ci`, run `npm config set foo=bar && npm ci`
- `hydrate.copy` - copy a given file or folder into all functions at a given path

## `set`

- Lambda pragmas:
  - `set.events` - register an `@events` Lambda
  - `set.http` - register an `@http` Lambda
  - `set.queues` - register an `@queues` Lambda
  - `set.scheduled` - register an `@scheduled` Lambda
  - `set.tables-streams` - register an `@tables-streams` Lambda
  - `set.ws` - register an `@ws` Lambda
  - `set.customLambda` - register a custom, non-pragma Lambda for use with other services
- Other pragmas:
  - `set.shared` - set the `@shared` `src` setting
  - `set.static` - set `@static` settings
  - `set.views` - set the `@views` `src` setting
  - `set.tables` - register `@tables`
  - `set['tables-streams']` - register `@tables-streams`
  - `set['tables-indexes']` - register `@tables-indexes`
  - `set.proxy` - register `@proxy` URLs
  - Possibly also: `app`, `aws`
- Other primitives
  - `set.env` - programmatically populate environment variables
  - `set.customLambdas` - register a bare Lambda to be used with a custom event handler
  - `set.runtime` - register a custom Lambda runtime and related workflows; three use cases, `type`:
    - `interpreted` - [still scoping] example: PHP
    - `transpiled` - example: TypeScript → JS
    - `compiled` - [still scoping] example: [Rust + Lambda runtime](https://github.com/awslabs/aws-lambda-rust-runtime)

## `sandbox`

- `sandbox.start` - function(s) to run at Sandbox startup
- `sandbox.watcher` - function(s) to run on project filesystem events (e.g. `src/http/get-foo/auth.js` → `updated`)
- `sandbox.end` - function(s) to run at Sandbox shutdown
- `sandbox.invoke.start` - [still scoping] function(s) to run prior to Lambda invocation
- `sandbox.invoke.end` - [still scoping] function(s) to run after Lambda invocation

---

## Changes from the current plugin API implementation

Some method names and Inventory properties would be moved around:
- `inventory.inv.plugins` + `inventory.inv.pluginFunctions` would move to `inventory.inv.customLambdas`
- `inventory.inv._project.plugins` would move to `inventory.inv.plugins`
- `plugin.package` would move to `plugin.deploy.start`
- `plugin.env` would move to `plugin.set.env`

---

## Known or intentional limitations (thus far)

- Due to execution order dependence, setter plugins are passed an almost entirely empty `inventory` object; this is the current state of the `@plugins` beta, but I just wanted to call out that I don't think that will change
- Setter plugins must be synchronous; unlike workflow hooks, setter plugins should be assumed to run in any order and should not directly depend on one another
- Full mocking of the AWS Lambda Runtime API has presented some challenges in Sandbox based on how [AWS Lambda runtime libs sometimes work](https://github.com/awslabs/aws-lambda-rust-runtime/issues/390) today; I'm currently working on some ideas to work around these challenges
- I think `create` methods will not be necessary, as the setters should have interfaces for specifying boilerplate code.

---

## Etc.

This issue supersedes #1175. This issue should not conflict with goals specified in #1233.

---

[^1]: Yes, we've got our next mythological friend picked out – to be revealed soon!
[^2]: As you probably are aware, I am a cofounder at Begin; this is def a thing we have heard from Architect and Begin users alike!

**Comment by ajoslin** [comment]
Typescript general feedback / wishlist. I didn't go deep on the plugin arch above.

* I'd like to be able to set the directory architect reads from to something else - currently if I write TS in src, arc will put js files side by side. I've created a `source` folder and have tsc compile to `src`. Would be nice to instead have something like `@directory dist` under app, which will change architect's folder from src to dist.
* (Somehow?) add @architect/shared to tsconfig so typescript recognizes what you're importing from. I've added this to my tsconfig.json: 
```
    "paths": {
      "@architect/shared/*": ["./source/shared/*"]
    }
```

This should at least be added on typescript-project init.

* When compiling typescript in sandbox mode, add `--inlineSourceMap --inlineSources` so the sourcemaps show up in same file as comments, no clutter. 
* Add source map support via `require('source-map-support/register')` in compiled files. I have this command running alongside `arc sandbox`: `tsc-watch --onSuccess 'node ./scripts/add-source-map-support.js' --inlineSourceMap --inlineSources`. And add-source-map-support.js just adds the require to every transpiled JS file. Would be nice to do this per-file via a hook of some sort.

**Comment by ryanblock** [comment]
A few thoughts/questions:
- Setting the directory Arc reads from: I may have an even better approach with the plugin I'm writing (which I'll release alongside the first RC): you will add `.build` to your gitignore, and Arc's TS plugin will automatically build (and re-build with its file watcher hook) individual TS files into the handler's dir + `.build`
  - So while in Sandbox, modifying `./src/http/get-index/index.ts` will automatically rebuild `./src/http/get-index/.build/index.js` (and requests to `get /` will hit `.build/index.js`)
  - This should obviate your next point about `paths`, as Node's module lookup algorithm should find necessary modules within `./src/http/get-index/node_modules` or `./node_modules` (for Sandbox), and have them moved into `src/http/get-index/.build/` during final deployment (via Deploy hooks)
- Re. `--inlineSourceMap --inlineSources` – these are also options available to use in `tsconfig.json` files, yes? Would it be ok to just set those in the config file for all compilations?
- Re. source map support via `require('source-map-support/register')`, it sounds like you want [first-class support for this module](source-map-support); should that perhaps be a separate plugin from the official TypeScript module, as it's a separate concern? Fwiw, based on your description, that should be totally feasible with the Sandbox watcher API and other hooks.

**Comment by ajoslin** [comment]
All sounds great.

* inlineSourceMap and inlineSources: I don't want sourcemaps in deployed env, they use up HD space and will slow down cold boots. That's why I use them as CLI args for sandbox only
* First class support for source-map-support, watcher API sounds fine

**Comment by ryanblock** [comment]
Being that we're now over a year out since the launch of Architect 10, I think this is probably safe to close. Some of these will still be built in the future (I'm looking at you, `set.runtime` `interpreted` + `compiled`), but I think this is fairly settled territory now.
