### ISSUE TITLE
Accessing views from Post handler works in sandbox not in staging

### ISSUE THREAD

**Issue by ryanbethel** [architect/architect#1298]
**Describe the issue**
You can access code in the views directory from Post handlers in sandbox but this fails in production because they are only shared with Get handlers. I would prefer that views be available to Post handlers because they can return HTML, but the larger issue is that you don't find out about the error until it is in staging or production.

**Steps to reproduce**
1. Put a file in the views directory
2. Try to access it from a Post handler

**Expected behavior**
Should either work on both sandbox and staging or blow up on both.

**Comment by ryanblock** [comment]
Views is by default only for GETs!
