### ISSUE TITLE
SvelteKit Adapter fails to build on latest version

### ISSUE THREAD

**Issue by HexaCubist** [architect/architect#1303]
**Describe the issue**
When using the latest version of SvelteKit, the adapter fails to run due to changes in the API for adapters, instead returning `Cannot read property 'log' of undefined`

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Create SvelteKit project on version `1.0.0-next.254`
2. Install the Architect SvelteKit adapter: `https://github.com/architect/sveltekit-adapter`
3. Run `yarn build` or the equivalent

**Expected behavior**
Project builds into `/build` folder, ready for deployment

**Screenshots**
![image](https://user-images.githubusercontent.com/8563277/152073292-bde4339f-dd81-4195-86a0-b162f03f5f46.png)

**Desktop**
Please complete the following information (if appropriate):
 - OS: Windows
 - Versions of packages:
```
	"@architect/sandbox": "^4.5.2",
	"@architect/sveltekit-adapter": "^0.0.4",
	"@sveltejs/kit": "^1.0.0-next.254",
```

**Comment by ryanblock** [comment]
Hey @HexaCubist! Please refer to: https://github.com/architect/architect/issues/1279#issuecomment-985049047

I think we paused updating after breaking change 6 or 7, after which they broke it again a few more times (as recently as a couple weeks ago), so we're waiting and hoping they stabilize things. Sorry it's not a particularly satisfying answer!
