### ISSUE TITLE
RFC: making `arm64` the default Lambda architecture in Architect

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1304]
In preparation for the release of Architect 10, one of the changes I've been evaluating has been to make `arm64` the default Architecture for all Lambdas. This issue explores our reasoning, considerations, and current decision behind making `arm64` the default Lambda architecture in Architect.

## Reasoning

Over the last few years, AWS has made it clear that they believe that a tentpole of their cloud strategy lies in the proliferation of Graviton ARM processor-based systems. Like many ARM-based systems, Graviton provides faster per-watt performance over x86, runs cooler, is less expensive to manufacture, and is overall less expensive to operate. Everybody wins: AWS gets better unit economics and lessens its dependence on chip delivery timelines it cannot control from x86 manufacturers, and AWS users get faster, cheaper compute.

AWS continues to advise folks to make the transition to Graviton where possible; when it shipped to Lambda last year, Architect 9.1.0 shipped `arm64` support on launch day. We at Architect are bullish on this transition and are excited to make it the default for Architect users.

In our experience, Lambda `arm64` is ready to use in production workloads today, although there are some considerations to work through in making the decision to ship it as the new default Lambda architecture in Architect 10.

## Considerations

The following comprise the various considerations that came into play when evaluating making `arm64` the default in Architect:

### Layers and native modules

A wonderful property of Lambda `arm64` support is how easy it is to deploy in most common Architect use cases. If your functions use Node.js, Python, or Ruby, and do not rely on any 3rd party native modules or layers, switching to `arm64` is a completely transparent, instantaneous, drop-in configuration change.

However, if your Lambdas use native modules, or use layers that make use of native modules or other binaries, or are themselves compiled (e.g. [Rust](https://github.com/awslabs/aws-lambda-rust-runtime)), they must be recompiled for `arm64`. This is a known and expected consideration.

Unfortunately, at this time it's not yet a straightforward process to determine whether 3rd party layers being used by your Lambda have enabled `arm64` support. (See more [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-layers.html) + [here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).) Any Lambdas deployed with incompatible layer architectures will fail.

While we don't necessarily think this alone is a blocker to shipping `arm64` as default for Lambdas in Architect, a better story (and perhaps additional time) around publishing `arm64` binary assets would be beneficial to the transition.

### Regional rollout

Generally when AWS ships new (Lambda) features to production, they roll out globally at the same time – the magic of software! However, due to the fact that the `arm64` Lambda requires rolling out enormous amounts of physical infrastructure to AWS data centers, Lambda `arm64` shipped to only a subset of regions. Today, Lambda `arm64` is available in the following regions (grouped by geo):

- `us-east-1`, `us-east-2`
- `us-west-2`
- `ap-south-1`
- `ap-southeast-1`, `ap-southeast-2`
- `ap-northeast-1`
- `eu-central-1`
- `eu-west-1`, `eu-west-2`

This leaves the following regions unsupported (for the time being):

- `us-west-1`
- `af-south-1`
- `ap-east-1`
- `ap-northeast-3`, `ap-northeast-2`
- `ap-southeast-3`
- `ca-central-1`
- `eu-south-1`
- `eu-west-3`
- `eu-north-1`
- `me-south-1`
- `sa-east-1`
- `us-gov-east`, `us-gov-west`

We fully expect Lambda `arm64` to roll out worldwide in the months to come. However, if your app lives in `us-west-1` or `eu-west-3`, for example, and Architect made `arm64` the default for regions that suport it, the moment one of those regions activated `arm64`, your application could potentially break. (See above re. layers and native modules.)

This means a maximum of up to 14 potentially upstream breaking changes for Architect users around the world, all within the context of the [semver major](https://semver.org/#spec-item-8) of Architect 10. That level of unpredictability is, in our opinion, an unacceptable tradeoff.

In theory we could ship 14 semver major releases – one for each region that activates `arm64` – as they roll out, but we will not do that. Every semver major release of every library by necessity requires its user base to perform the labor of checking release notes to ensure they aren't broken by the change. That is far too much work to ask the Architect community to perform.

### Opt-in workaround

Since Lambda `arm64` shipped, Architect users have been able to manually opt-in to `arm64` by specifying the following setting in their project manifest:

```arc
@aws
architecture arm64
```

This continues to be the case. An additional measure for transitioning to `arm64` would be to add the above setting automatically to all newly created projects (in compatible regions) with `arc create` + `npm init @architect`.

# Conclusion

Architect has settled into an approximate cadence of annual major releases (with according and necessary breaking changes), and, if timing cannot be helped, when [Node.js retires a version](https://nodejs.org/en/about/releases/) in use by the framework itself.

At this time, given the above considerations and the workaround available, we feel the appropriate direction is to wait until Lambda `arm64` is fully rolled out to the vast majority of non-GovCloud regions (ideally all of them) before making it the default Lambda architecture.

My hope and expectation is that this will be the case by Architect 11 (ostensibly in 2023). In the mean time, we will continue to implement explicit defaults that enable easy opt-in/out, such as writing new boilerplate `app.arc` files with the `architecture arm64` option.

**Comment by ryanblock** [comment]
With the Arc 10 launch now imminent, I'm going to close this issue. Fingers crossed for a rapid rollout of `arm64`!

**Comment by ryanblock** [comment]
As of [this announcement](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-lambda-functions-graviton2-12-regions/), `arm64` is now available in the following regions not previously available in above:

- [x] `us-west-1`
- [x] `af-south-1`
- [x] `ap-east-1`
- [x] `ap-northeast-3`, `ap-northeast-2`
- [x] `ap-southeast-3`
- [x] `ca-central-1`
- [x] `eu-south-1`
- [x] `eu-west-3`
- [x] `eu-north-1`
- [x] `me-south-1`
- [x] `sa-east-1`
- [ ] `us-gov-east`, `us-gov-west`

With only `us-gov-east` + `us-gov-west` remaining, I think it's time to reopen and re-evaluate this issue.

**Comment by ryanblock** [comment]
To follow up the comment above, here's a non-breaking approach I'd like to propose that could enable Architect's immediate transition to (mostly) defaulting to `arm64`:
- To date, Architect has assumed `x86_64`, with a manual opt-in to using `arm64`; with the exception of Lambda layers (which are generally compiled to specific platform architectures), Arc userland code can all be expected to "just work" (ahem) by flipping the switch to `arm64`
- In a non-breaking (i.e. semver minor) change to Architect, we can inspect each Lambda's configuration, and if it has no layers, automatically flip it to `arm64`
- If the function does have layers, we continue to assume it's `x86_64` unless we are instructed otherwise via the [`@aws architecture` configuration setting](https://arc.codes/docs/en/reference/configuration/function-config#architecture)
- One potential pitfall: some Node.js modules may include binaries, and if so they would break upon next deployment unless steps were taken to ensure use of an `arm64` version.
  - We wouldn't really have any built-in way of knowing whether a function has modules with binaries, and probably the best we could do would be to read every file in your Lambda's `node_modules/**` and run it through something like [`isbinaryfile`](https://www.npmjs.com/package/isbinaryfile) to see if we get any hits (and if so, warn)
  - If we did the above, it would probably slow down deployment quite a bit, and be pretty expensive, but that's speculative – I hear computers are pretty fast these days!
  - We could also be a little more loose, and just scan `node_modules/.bin/*` for binaries, but that may miss warning about modules with binaries that are called from a JS entry. Not sure how common that scenario is, though; example: [`esbuild`](https://www.npmjs.com/package/esbuild) places its actual binary in `~/node_modules/.bin/esbuild`

Related: Architect 11 (which has no immediate plans or timeline) would be our next earliest chance to clean up any above conditional behavior by always assuming a default of `arm64` (with or without layers), and expecting folks to opt individual Lambdas into `x86_64` as necessary.

Would appreciate your thoughts!

**Comment by ryanblock** [comment]
Quick followup to the followup above: I ran some tests to see how gnarly it would be to check if a large node_modules folder had binaries, and how many binaries it would have.

The good news: on my machine (~2y old MBP) I can reliably scan a ~6k file, 120MB node_modules dir in under 500ms, so its relative expense shouldn't be much of a concern.

The bad news: way too many false positives to be useful. This folder had `esbuild` and `@architect/architect` installed, and returned the following binary file hits:

```
~/node_modules/.bin/esbuild
~/node_modules/@pnpm/network.ca-file/package-tar/pnpm-network.ca-file-1.0.1.tgz
~/node_modules/cpr/cpr.jpg
~/node_modules/esbuild-darwin-64/bin/esbuild
~/node_modules/esbuild/bin/esbuild
~/node_modules/fsevents/fsevents.node
~/node_modules/jszip/.jekyll-metadata
~/node_modules/leveldown/prebuilds/android-arm/node.napi.armv7.node
~/node_modules/leveldown/prebuilds/android-arm64/node.napi.armv8.node
~/node_modules/leveldown/prebuilds/darwin-x64/node.napi.node
~/node_modules/leveldown/prebuilds/linux-arm/node.napi.armv6.node
~/node_modules/leveldown/prebuilds/linux-arm/node.napi.armv7.node
~/node_modules/leveldown/prebuilds/linux-arm64/node.napi.armv8.node
~/node_modules/leveldown/prebuilds/linux-x64/node.napi.glibc.node
~/node_modules/leveldown/prebuilds/linux-x64/node.napi.musl.node
~/node_modules/leveldown/prebuilds/win32-ia32/node.napi.node
~/node_modules/leveldown/prebuilds/win32-x64/node.napi.node
~/node_modules/querystring/.History.md.un~
~/node_modules/querystring/.package.json.un~
~/node_modules/querystring/.Readme.md.un~
~/node_modules/querystring/test/.index.js.un~
~/node_modules/zip-dir/test/fixtures/sampleZip/tiny.gif
```
Note the image files, CI metadata, and other random crap. So I think the best we could do, realistically, would be to scan `node_modules/.bin/*` for binaries and warn on that.

**Comment by filmaj** [comment]
How would this work in the context of an `arc deploy` execution? Since `deploy` is executed from a development machine (e.g. my laptop), which has its own architecture that may differ from the target lambda architecture, would the implicit `arc hydrate` execution coming from `arc deploy` know to e.g. `npm install` with the correct target architecture?

**Comment by ryanblock** [comment]
@filmaj over at https://github.com/architect/architect/issues/1470 @clovis1122 has pointed out that npm now has a `--cpu` flag for later versions. If we bumped Architect's minimum Node.js version to 18 (from 16) it looks like we can make this happen (in theory!).
