### ISSUE TITLE
peerDependencies aren't added to hydrated node_modules

### ISSUE THREAD

**Issue by gopeter** [architect/architect#1305]
I'm using `graphql-request`, which has `graphql` as peer dependency. But the hydrating does not install the missing dependencies, even if I have them in my own package.json:

```
⚬ Hydrate Hydrating dependencies in 1 path
✓ Hydrate Hydrated server/
  | npm i --production: added 257 packages from 237 contributors and audited 264 packages in 8.169s
  | npm i --production: 39 packages are looking for funding
  | npm i --production: run `npm fund` for details
  | npm i --production: found 0 vulnerabilities
  | npm i --production: npm notice created a lockfile as package-lock.json. You should commit this file.
  | npm i --production: npm WARN @remix-run/architect@1.1.3 requires a peer of @architect/architect@^8.3.7 but none is installed. You must install peer dependencies yourself.
  | npm i --production: npm WARN graphql-tag@2.12.6 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
  | npm i --production: npm WARN graphql-request@4.0.0 requires a peer of graphql@14 - 16 but none is installed. You must install peer dependencies yourself.
```

Maybe we need a way to add additional server dependencies somewhere in the config?

**Comment by ryanblock** [comment]
I assume you're running npm 6? They changed this behavior in 7+, see: https://github.blog/2021-02-02-npm-7-is-now-generally-available/

**Comment by gopeter** [comment]
Yes, but according to [this document](https://arc.codes/docs/en/reference/project-manifest/aws), I can't choose anything above node 14.

**Comment by gopeter** [comment]
Ah, nevermind, `arc` (or rather the hydration step) uses the local node/npm for sure ... I'll try this again

**Comment by ryanblock** [comment]
Yeah, diff things. That document refers to the versions of Node.js available for running in AWS Lambda. Architect itself runs on any version of Node.js >=14.

**Comment by gopeter** [comment]
Yes, that was definitely my fault. But I've faced another issue (at least I think it is one): the version of my package-lock.json isn't used. The hydration seems to install the packages fresh from a new generate package.json, but does not lock the packages to the version of my project's lock file. Is there something we can do about this (except locking packages to fixed version numbers)?

**Comment by ryanblock** [comment]
I'm guessing this is probably what you're bumping into: https://github.com/architect/hydrate/blob/7d5066b4f501acb49e634ab485a4395ae803bbb3/src/actions/autoinstall/get-root-deps.js#L14-L23 Currently Lambda treeshaking supports `package-lock.json` version 1, not v2.

This isn't a big change, and I'd be happy to get it off the to-do list. Perhaps this issue should be closed and a fresh one opened?

**Comment by gopeter** [comment]
Yes, you're right, I've created another issue :)
