### ISSUE TITLE
package-lock.json v2 can't be used to hydrate dependencies

### ISSUE THREAD

**Issue by gopeter** [architect/architect#1306]
As discussed [here](https://github.com/architect/architect/issues/1305#issuecomment-1028938017), `arc`'s hydration [can't handle v2 package-lock.json files](https://github.com/architect/hydrate/blob/7d5066b4f501acb49e634ab485a4395ae803bbb3/src/actions/autoinstall/get-root-deps.js#L14-L23).

Would be great if this could be the case since not every dependency uses semver (correctly) and add breaking changes to minor releases as well.

**Comment by ryanblock** [comment]
> not every dependency uses semver (correctly) and add breaking changes to minor releases

So very disappointing, and so very true. 😅

**Comment by ryanblock** [comment]
Fixed in https://github.com/architect/hydrate/pull/153/commits/cda80ed861846d590d4815ef8893c38d022decd5; will ship in Arc 10 (RC4)!
