### ISSUE TITLE
Support configurable `app.arc` directories

### ISSUE THREAD

**Issue by dan-cooke** [architect/architect#1309]
**Is your feature request related to a problem? Please describe.**
It would be cool if users could configure where `arc` looks for their lambdas.

```
.
├── public .......... # Static assets (js, css, svg, images, etc.)
├── src
│   ├── shared ...... # Code shared by all Lambda functions
│   ├── views ....... # Code shared by HTTP GET Lambda functions
│   ├── macros ...... # Modify the generated CloudFormation
│   ├── http ........ # @http Lambda functions
│   ├── events ...... # @event Lambda functions
│   ├── queues ...... # @queue Lambda functions
│   ├── scheduled ... # @scheduled Lambda functions
│   ├── tables ...... # @table stream Lambda functions
│   └── ws .......... # @ws Lambda functions
└── app.arc
```

**Describe the solution you'd like**
`arc` could add some options to `preferences.arc` file that allow these directories to be configured.

First some quick global configs, useful for Typescript and other transpilers:

`baseLambdaDirectory` - the location to look for lambdas, defaults `./src`
`baseStaticDirectory` - the location to look for static assets, default `./public`

And then more granular config.

`sharedDirectory`
`viewsDirectory`
`macrosDirectory` 

etc.

**Describe alternatives you've considered**
Without this feature, users are forced to maintain a more verbose `app.arc` file.  As mentioned in the docs:

>Routes can use more verbose configuration to allow for [custom source paths](https://arc.codes/docs/en/guides/developer-experience/custom-source-paths) in your project. Provide a method and src for each route:
method - HTTP verb
src - path to the function source

Currently we have to explicitliy setup custom source paths for each of our lambdas inside `app.arc`, this is prone to error and requires more maintenance.

With this proposed feature, Typescript users could simply configure

`baseLambdaDirectory ./build`

And we could remove all of our configuration from `app.arc` in favour of file based config

**Comment by ryanblock** [comment]
It sounds to me like maybe the issue at hand here is less the configurability of directories and more about having a significantly better experience with JavaScript transpiling. Do you feel like that’s fair? If so I would direct you to check out Architect 10 and specifically the new TS plugin. I think you’ll find it resolves these issues!

https://github.com/architect/plugin-typescript

**Comment by dan-cooke** [comment]
@ryanblock 

Well now.

That pretty much solves all my problems. Awesome. Is this mentioned in the docs anywhere? The Typescript section does not mention this plugin

https://arc.codes/docs/en/guides/developer-experience/using-typescript

**Comment by ryanblock** [comment]
Arc 10 is in RC and will launch later this month, along with new docs.

**Comment by dan-cooke** [comment]
Awesome thanks
