### ISSUE TITLE
Static assets are missing when visiting the page while upload is still in progress

### ISSUE THREAD

**Issue by gopeter** [architect/architect#1312]
**Describe the issue**
Deploying an app with `arc deploy` often leads to broken frontends when users are visiting the page during the static file upload:

![image](https://user-images.githubusercontent.com/1242960/154267123-ffaf6e98-bf49-41f1-b5e5-01327ac29cd3.png)

In our case, the Lambda function returns HTML which refers to assets which still has to be uploaded:

```
✓ Deploy Generated CloudFormation deployment
⚬ Deploy Deploying & building infrastructure...
✓ Deploy Deployed & built infrastructure
✓ Success! Deployed app in 98.855 seconds

    https://myapp.execute-api.eu-central-1.amazonaws.com

⚬ Deploy Deploying static assets...
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/entry.client-WLSAW42P.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/root-HL4CN2BY.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/routes/index-QRRWFLHD.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/_shared/chunk-APIFPFMM.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/_shared/chunk-KTMFGWQX.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/_shared/chunk-OWLAKQ5B.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/_shared/chunk-W7F5SQDX.js
[  Uploaded  ] https://myapp.s3.eu-central-1.amazonaws.com/build/_shared/chunk-XLA7BSAK.js
✓ Deploy Skipped 8 files (already up to date)
```

Would it be possible to deploy the static assets before updating the Lambda code?

**Comment by ryanblock** [comment]
Yes, but that might cause other issues. For example, what if a user does not have fingerprinted assets, and deploys them before the rest of their application, and their CloudFormation fails deployment? (CloudFormation deployments fail all the time – fortunately they are safe and easily recoverable!)

In such a case, the assets would be updated on AWS, but the running application would be out of date, and this would also cause issues. Hence, the reason we deploy static assets after a successful application deployment is specifically to ensure that the deploy went well first.

Will have to give this a deeper think, but I'm open to ideas!

**Comment by gopeter** [comment]
Oh damn 😞 The current deployment strategy results in a few seconds of downtime for some users and since we are deploying multiple times a day, we have to get around this somehow 🤔 

> In such a case, the assets would be updated on AWS, but the running application would be out of date, and this would also cause issues. Hence, the reason we deploy static assets after a successful application deployment is specifically to ensure that the deploy went well first.

At the moment the `arc` deployment uploads assets to S3 without pruning old ones, so this wouldn't be a problem. The old and the new application could point to assets that are definitely there. But yeah, once the deployment fails, we would have orphan files.

Maybe I'll just upload to the S3 bucket by myself before I do `arc deploy`, because at the moment orphaned assets are not that bad as missing assets on new page views 😄

**Comment by ryanblock** [comment]
A few seconds of downtime each deploy is not good, and I would not consider that acceptable. When you say asset uploads occurs without pruning the old ones, is that because you do not have pruning enabled? Just want to make sure you're aware that pruning static assets during deployment is an option. (Just looking at our docs, it looks like we didn't document that option, which is unfortunate because we've supported it for years. Anyway, it's `@static prune true`.)

I can imagine a setting that enables Deploy to publish static assets before the rest of the app as an opt-in. It could also try to automatically infer asset-first deployment based on `fingerprint` + `prune` status, but idk, maybe that's too magical; maybe it'd be best to just make this an explicit option.

Do you check in an Arc preferences file? I'm thinking this might belong in `prefs.arc` `@deploy static-first true` (but open to ideas). It's specific to Deploy (but also kind of `@static`).

**Comment by ryanblock** [comment]
Had a chance to discuss further with @brianleroux about this, and took some time to dig further into the various known issues and considerations around API Gateway + CloudFormation, etc., especially in the context of blue-green deployments. The scope of that conversation is bigger than this issue, but we can narrow the scope to this particular case, which is prevalent in ways that things like environment variable changes may not be.

So I think we could safely make a static asset pre-deployment work, but it would have to meet all of the following criteria:
- A deploy containing a static bucket has already occurred
  - This another reason we deploy static assets last: we can't deploy assets to a bucket that doesn't yet exist!
- You have specified `@static fingerprint true` or `fingerprint external`, which indicates to Architect that unique assets are always being published
  - This ensures the safety of the currently published application in the event of a CloudFormation failure, as only new assets would have been published
- You have not specified or explicitly disabled `@static prune`
  - Similarly, this would ensure the safety of the currently published application by leaving assets in place that may be needed in the event of a deploy failure
  - We could also look at an approach where prune is allowed to be enabled, and we move prune into its own separate operation that only ever runs post-deployment

**Comment by ryanblock** [comment]
I was able to find a way to do this transparently, the only predicates required are `@static fingerprint true` or `fingerprint external`, and `prune` is disabled (which it is by default). The deploy flow should now automatically ship static assets first (if it can).

If `fingerprint` is set to `external` and some assets are not fingerprinted (say for example `index.html` is an un-fingerprinted file, while everything else is fingerprinted), there could be some danger in the event of a failed deploy. We'll note this caveat in https://arc.codes docs.

PR is here https://github.com/architect/deploy/pull/352; this will ship in Arc 10 today!

**Comment by gopeter** [comment]
Hi @ryanblock,
sorry for the slow response! Very impressed from your support 😃 I did an `arc deploy --static` before running `arc deploy` to ensure that all assets are uploaded, since I do not prune assets and have fingerprinting enabled. 

Now I'm trying to find a way to prune assets from the penultimate deployment 😄 🙈

**Comment by ryanblock** [comment]
I was going to advise that as of Arc 10 to achieve pruning, just reverse what you’re doing now: run a totally regular deployment, and then if successful, try running a post-deploy `npx arc deploy —static —prune`. I think that should take care of safely maintaining your bucket contents!
