### ISSUE TITLE
Arc deploy fails using AWS env vars

### ISSUE THREAD

**Issue by atomraymaker** [architect/architect#1314]
**Describe the issue**
arc deploy doesn't work with AWS env vars

**Steps to reproduce**
1. set the 3 env vars listed here: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html.
2. test that this works with `node -e 'var AWS = require("aws-sdk"); var s3 = new AWS.S3(); s3.listBuckets().promise().then((d) => console.log(d))'`
3. npx arc deploy fails with: `Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`

This looks to be an aws sdk error.

**Expected behavior**
arc deploy should work with environment variables like running any other node aws sdk command.

I have never set values in ~/.aws/credentials because I am always using a tool like awsume or aws-okta. I can't get the env vars set correctly for these to work with arc deploy. 

I have tried with the @aws settings commented out and with them not. 

I have tried adding the aws sdk value suggested AWS_SDK_LOAD_CONFIG=1.

Serverless framework and SAM CLI work using them with aws-okta or awsume so I assumed arc deploy would work the same way. 

At this stage I can't even run: `npx arc deploy --eject` and use SAM because I get the same error.

I was able to do the eject by adding the env vars to the credentials file and specifying a profile under @aws. These are temporary creds so I can't work with those, and they wouldn't work in the CICD system either since it runs off env vars. 

So, this is mostly an FYI for now, I will have to move forward with SAM instead. 

**Screenshots**
![Screen Shot 2022-02-23 at 9 53 00 AM](https://user-images.githubusercontent.com/475081/155343908-8c414778-1092-43a5-9f04-d5f4e360dd5f.png)

**Desktop**
Please complete the following information (if appropriate):
 - OS: OSX
 - iTerm

**Additional context**
Add any other context or notes about the problem here

**Comment by ryanblock** [comment]
Hey there! I think you have introduced some issues with some of your tooling or aspects of your environment. Architect absolutely supports AWS credentials via env vars, and many apps, including Arc’s web site, ships this way. See: https://github.com/architect/arc.codes/blob/0faf2ea393802d6f9c333cf32f918b798a3cc7bd/.github/workflows/build.yml#L97

Can you please provide detailed steps to reproduce?

**Comment by atomraymaker** [comment]
Yeah, that is what I am looking for...I guess I will try some other things. This was just a fresh remix install with the architect option. Local server works fine. I using architect with npx, not sure if that would make a difference. Maybe it is using a different version of the aws-sdk than what I get when I run node -e.

**Comment by ryanblock** [comment]
It's possible dueling banjo node modules; `aws-sdk` generally acts like a singleton. If you or one of your package instantiates `aws-sdk` separately from Architect and then mutates env vars, Architect may be left out in the cold on your run.

**Comment by truggeri** [comment]
For anyone else that has a similar issue, I have found that architect is not honoring the [AWS order for credential resolution](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html). In my case I had two different credentials present,

1.  Default profile in `~/.aws/credentials`
2. Terminal environment variables.

Based on [AWS documentation on the node sdk](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html), the environment variables should be used _before_ the default profile credentials file. After deleting my credentials file (be sure you won't lose a key in doing this), the architect command (`npx arc deploy --eject` in my case) worked using credentials from ENV.

If you are trying to use ENV on a dev machine or assume-role, this could trip you up.
