### ISSUE TITLE
Sandbox `src/invoke-lambda/exec/spawn.js` not detecting lambda return when all data arrives in one chunk

### ISSUE THREAD

**Issue by mawdesley** [architect/architect#1319]
**Describe the issue**
When the runtime returns both the `__ARC_META__` and `__ARC__` data in the same chunk the `maybeShutdown` function, and by extension the `done` functions are not triggered.

This causes the timeout code to trigger, so it appears that there was a fault in the lambda.

I think this issue only applies to lambdas which don't automatically exit after returning. In my case the lambda holds a redis connection open, which stops the sandbox child process exiting.

**Steps to reproduce**
1. run the sandbox
2. hit a lambda that holds open a resource / will somehow prevent the child process from automatically exiting
3. look for timeout errors in the sandbox log

**Expected behavior**
It should recognise that the `__ARC__` segment is present in the chunk & trigger `maybeShutdown` 

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS 12.1
 - Arc Version: 10.0.2

**Additional context**
This return on line 234 is the culprit. 
https://github.com/architect/sandbox/blob/main/src/invoke-lambda/exec/spawn.js#L234

It prevents this block from running, so the lambda end is never detected
https://github.com/architect/sandbox/blob/main/src/invoke-lambda/exec/spawn.js#L236-L240

Will raise a PR to fix tomorrow ✌️

**Comment by ryanblock** [comment]
Hey! I'm not sure how a user would even create that scenario; the execution functions are abstracted from userland code. What's more, the data + meta payloads are flushed separately, specifically so this can't happen. See:
- https://github.com/architect/sandbox/blob/e9f7dcb279e9912715cd86acbab074d7a1dd7d9c/src/invoke-lambda/exec/runtimes/deno.js#L21-L22
- https://github.com/architect/sandbox/blob/e9f7dcb279e9912715cd86acbab074d7a1dd7d9c/src/invoke-lambda/exec/runtimes/node-esm.js#L27-L28
- https://github.com/architect/sandbox/blob/e9f7dcb279e9912715cd86acbab074d7a1dd7d9c/src/invoke-lambda/exec/runtimes/node.js#L102-L103
- https://github.com/architect/sandbox/blob/e9f7dcb279e9912715cd86acbab074d7a1dd7d9c/src/invoke-lambda/exec/runtimes/python.py#L18-L19
- https://github.com/architect/sandbox/blob/e9f7dcb279e9912715cd86acbab074d7a1dd7d9c/src/invoke-lambda/exec/runtimes/ruby.rb#L27-L28

Before we try to PR, I'd like to better understand what the supposed problem is, and to understand why this does not replicate across the thousands of successful Lambda executions in Sandbox's test suite.

**Comment by mawdesley** [comment]
Here's a video of the issue & source code: https://github.com/mawdesley/sandbox-issue-1319-repro

https://user-images.githubusercontent.com/44057041/156053134-98f7f253-f0ad-43c5-967c-de4263b1bd94.mov

I've just used `setTimeout` to keep the process alive for longer than the lambda timeout (simulating something like a db conn)

**Comment by mawdesley** [comment]
> Before we try to PR, I'd like to better understand what the supposed problem is, and to understand why this does not replicate across the thousands of successful Lambda executions in Sandbox's test suite.

It doesn't cause any failures in the test suite because there isn't a test that covers this scenario.

I've raised a PR https://github.com/architect/sandbox/pull/671 with a new test to cover the scenario.

**Comment by ryanblock** [comment]
Wonderful, thanks! Will take another look asap!

**Comment by ryanblock** [comment]
Fix looks solid, thank you for getting it + the integration tests together, this will ship in 10.0.5!
