### ISSUE TITLE
Non-interactive environment variable setting (e.g. CI pipeline)

### ISSUE THREAD

**Issue by gpmcadam** [architect/architect#1325]
If I am using `arc` to deploy an app via a CI pipeline and I want to add environment variables to my Lambda, should I be doing this like so:

```sh
$ arc deploy
$ arc env -e <environment> --add FOO bar
```

If so, when this command runs in CI, it hangs because the `arc env` command is requesting input:

```sh
Env Would you like to create a local preferences file? [Y|n]
```

Is there a better way to deploy with these environment variables via CI, or is there a non-interactive mode? Should `arc` pick up on the presence of a `CI` environment variable from my pipeline and not prompt for such interactions?

**Comment by thescientist13** [comment]
Was just wondering about this myself.  I know in the past when scripting CI / CD scripts before, at least on Ubuntu, I could add a `-y` flag to auto answer, which seemed to work.

Will be try myself in the next few days so will let you know.

----

Related, I assume you are uploading your secrets to your CI server, then "forwarding" the values from that system into your shell to make them available for `arc env` at build time?  (just thinking out-loud to myself in anticipation of setting up my own CI pipeline)

ex:
```sh
arc env -e <environment> --add FOO CI_SECRETS_FOO
```

**Comment by ryanblock** [comment]
We can add a flag to suppress that behavior, for sure. However, how you're doing it above is not correct or necessary. Here's how env vars flow through the system (broadly):
- You add an env var with `arc env` command
- Architect saves that env var to your app's SSM namespace
- You deploy your app with `arc deploy`
- Architect queries your app's SSM namespace for all the env vars you added to a given environment (eg `staging`) prior to deployment, then adds them to your CloudFormation template
- Architect then deploys your app environment with its environment-specific env vars

Architect does not update live env vars in your running application when you run `arc env`. Those env vars don't go live until the next deployment.

Hopefully that addresses your question as well, @thescientist13, but just to be clear: no secrets are uploaded to mysterious servers / services, Architect safely and securely stores your env vars in your app's own secured SSM store within AWS, and those env vars are only accessed by your creds at deploy time.

**Comment by thescientist13** [comment]
Ah, thanks for the clarification @ryanblock ! 

So, only thing I would need then is to just expose my AWS credentials in my CI environment for `arc deploy` then?  (In my case, looking to use GitHub Actions)

**Comment by ryanblock** [comment]
@thescientist13 that's right! If you need an example of how we do it: https://github.com/architect/arc.codes/blob/main/.github/workflows/build.yml#L89-L103

**Comment by gpmcadam** [comment]
@ryanblock Thanks for the clarification.

**Comment by ryanblock** [comment]
Semi-related: https://github.com/architect/architect/issues/1347
