### ISSUE TITLE
Enable generating `.mjs` templates from `prefs.arc`

### ISSUE THREAD

**Issue by austincrim** [architect/architect#1330]
Currently, `arc init` (or `autocreate true`) will generate a plain `.js` file even when the `prefs.arc` template file is `.mjs` or `.cjs`.

**Describe the solution you'd like**
Respect the file extension of the specified JavaScript template function when generating new lambda functions.

**Describe alternatives you've considered**
Manually renaming files.

**Additional context or notes**
Relevant code could be [here](https://github.com/architect/inventory/blob/272da975d1c0beaa374767b488962845e7df8d10/src/config/pragmas/populate-lambda/get-handler.js#L48).

**Comment by ryanblock** [comment]
If I'm understanding what this is asking for, this behavior is slightly tricker than it sounds. Handler selection logic isn't really Architect's choice, per se – we have to follow both Node's rules, as well as the Lambda Node runtime's handler bootstrap. So your template may be an ESM handler in `tmpl/http.js`, but what gets written to disk wouldn't actually work in Lambda (which needs either an `index.mjs` file, or an `index.js` file with a `package.json` file with a `type` property set to `module`).

Anyway, if the goal here is to bias towards writing `.mjs` handlers (and I think it is), that's what we're about to ship in 10.6!

**Comment by ryanblock** [comment]
Ok, ESM handler provisioning by default is now live in 10.6, hopefully this helps resolve the root issue at hand on this one.
