### ISSUE TITLE
Missing documentation regarding configuring table ports for @sandbox

### ISSUE THREAD

**Issue by jcohenho** [architect/architect#1334]
The Architect documentation is [missing information](https://discord.com/channels/880272256100601927/884128391341678742/961078544778285127) regarding port configuration for @tables in sandbox. 

The following config works and makes the ports available in the `ARC_SANDBOX` environment variable: 

```
# preferences.arc
@sandbox
ports
  tables 1234
```

**Comment by tbeseda** [comment]
Thanks for filing @jcohenho 
I forgot to update you in Discord that I filed an issue on arc.codes here https://github.com/architect/arc.codes/issues/536
And I've got a PR with the changes if you want to check it out https://github.com/architect/arc.codes/pull/537/files

**Comment by jcohenho** [comment]
@tbeseda awesome thank you!
