### ISSUE TITLE
Support deploying without profile

### ISSUE THREAD

**Issue by kabo** [architect/architect#1342]
Currently architect requires that `profile` is set in `app.arc` in order to deploy.
From the [docs](https://arc.codes/docs/en/reference/project-manifest/aws).
![image](https://user-images.githubusercontent.com/357601/167273566-12b1cbe7-5765-4b7b-8f63-bc545ce41e89.png)
This was also brought up in #1314 

How to reproduce
![image](https://user-images.githubusercontent.com/357601/167273831-c8431760-c066-45d1-83b3-039529321b99.png)

**Describe the solution you'd like**
Using profiles shouldn't be a requirement. When working with the AWS CLI or AWS SDK it is [not a requirement](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html).
It should be enough to set
- AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY in case of user credentials
- AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY + AWS_SESSION_TOKEN in case of temporary credentials
- AWS_ROLE_ARN + AWS_WEB_IDENTITY_TOKEN_FILE in case of OIDC credentials
- or any other credentials that AWS CLI/SDK supports out of the box

**Comment by kabo** [comment]
Should have showed it in the first screen shot, but interacting with AWS CLI works fine.

![image](https://user-images.githubusercontent.com/357601/167274052-265732ba-5106-47bb-b223-f5ca52f3cd1a.png)

**Comment by truggeri** [comment]
I have not had this exact issue, but the inconsistency around profile and ENV settings is surprising and confusing for those new to architect that have used the AWS sdk before. Goo documentation about how to use ENV would be a good first step.

**Comment by ryanblock** [comment]
This should (finally!) be resolved by the transition to `aws-lite` in Arc 11!
