### ISSUE TITLE
arc10: prune flag is removing the static files of the current deployment

### ISSUE THREAD

**Issue by GiancarlosIO** [architect/architect#1349]
**Describe the issue**
When using the prune flag (`arc deploy --production --prune`) the current static files are deleted just after they were created.

![image](https://user-images.githubusercontent.com/17274950/170844654-127f17fd-b2c6-4ac6-882b-85765490316d.png)
 
All the static URLs give the following errors

````text
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>95WQWT4B81DB7R53</RequestId>
<HostId>czAJk7Zq87gRd+FZxZDNh2Mkc+X7U0uCnphhaj0hNs6kcCDQWN8YAdsXtNlWhjgV+QH08iE0gZo=</HostId>
</Error>
````

**Steps to reproduce**
1. run `npx create-remix --template remix-run/grunge-stack`
2. cd to the project created
3. run `npm run build`
4. run `arc deploy --staging --prune`
5. Open the final deployment URL and there you can see that all of the static files give 404 errors 😢 

**Expected behavior**

The --prune option flag only deletes old files.

**Screenshots**
![image](https://user-images.githubusercontent.com/17274950/170844654-127f17fd-b2c6-4ac6-882b-85765490316d.png)

**Desktop**
Please complete the following information (if appropriate):
 - OS: Windows 10
 - Browser Chrome v101
 - Arc version: 10.3.3

**Additional context**
Add any other context or notes about the problem here

**Comment by tbeseda** [comment]
Thanks for the steps to reproduce here @GiancarlosIO -- definitely seems like a bug. We'll try to confirm in our Windows environment next and get to fixing.

@macdonst when you have capacity can you try these steps to recreate? ty

**Comment by ryanblock** [comment]
This is not reproducing for me. @GiancarlosIO, can you confirm the same thing happens for your project when following those steps in !Windows?
