### ISSUE TITLE
direct deploy no longer functioning

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1350]
with a global install

<img width="941" alt="Screen Shot 2022-05-30 at 1 24 29 PM" src="https://user-images.githubusercontent.com/990/171055690-5957b310-3325-4d61-a805-0cc7f4bec514.png">
l

**Comment by brianleroux** [comment]
note, it does work with `--direct` flag so its just the allies that is broken
<img width="966" alt="Screen Shot 2022-05-30 at 1 29 26 PM" src="https://user-images.githubusercontent.com/990/171056103-722e7492-46f9-45e5-9bf4-77df42c6e9a0.png">

**Comment by ryanblock** [comment]
I think this is a help bug; `-d` is the debug flag. I believe I removed this from docs, will remove from command help as well.
