### ISSUE TITLE
ability for userland to override set plugins 

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1352]
currently if you define functions w `set` plugins they always win; it would be nice to have `set` plugins allow for uesrland to override plugins that set default functions (so for example a set plugin might create `get /about` which shows plugin info but if the user creates their own `get /about` in their arcfile it always 'wins'.

**Comment by ryanblock** [comment]
This should resolve it, just need to settle on whether we want the final property name to be `_override`, which I don't love, or something else. https://github.com/architect/inventory/pull/41/commits/1ef70c78ee52bd7d1e6267871c31a2ca034491a5

**Comment by ryanblock** [comment]
Ok, per feedback this will now function as follows:
- By default, Lambdas generated by setter plugins are able to be overridden by the project manifest
- Doing so happens automatically/quietly
- If the plugin developer requires a Lambda to exist (e.g. it should not be overridden by the userland manifest) they can set a `required: true` flag on their Lambda; should a conflict arise, a detailed error will be presented to the user

See: https://github.com/architect/inventory/pull/41/commits/b5f6144ad079ea8d7fccfd7825548bde7378356c + https://github.com/architect/inventory/pull/41/commits/7b70daaae5019a1d4bfd0bf3e75d5b8d6704b6ad

This will ship very soon in Inv 3.2 + Arc 10.4!
