### ISSUE TITLE
Warning: Expected server HTML to contain a matching <script> in <body>. script

### ISSUE THREAD

**Issue by vonkoff** [architect/architect#1354]
**Describe the issue**

This is the error I am getting when I run my remix build in production and with `npm run dev`

```
Warning: Expected server HTML to contain a matching <script> in <body>.
script
LiveReload2@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:3071:16
body
html
App
RemixRoute@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:2525:5
Routes2@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:2508:27
Router@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:740:12
RemixCatchBoundary@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:1019:18
RemixErrorBoundary@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:944:10
RemixEntry@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:2405:24
RemixBrowser@http://localhost:3333/_static/build/_shared/chunk-ULEDQN53.js:3108:33
```

Some friends who saw the site while it was live were getting this error:
<img width="1250" alt="Screen_Shot_2022-06-27_at_11 13 16_PM" src="https://user-images.githubusercontent.com/16548992/176189307-d27b9152-b3e3-4e44-a1b6-0b760e713286.png">

I'm putting my package.json below in case this is where I could have the silly issue happens.
```
  "scripts": {
    "build": "run-s build:*",
    "build:css": "npm run generate:css -- --minify",
    "build:remix": "remix build",
    "dev": "remix build && rm -rf ./server/node_modules && run-p dev:*",
    "dev:arc": "cross-env NODE_ENV=development arc sandbox",
    "dev:css": "npm run generate:css -- --watch",
    "dev:remix": "remix watch",
    "generate:css": "npx tailwindcss -i ./styles/tailwind.css -o ./app/styles/tailwind.css",
    "start": "cross-env NODE_ENV=production arc sandbox"
  },
  ```

I also tried to take everything out from my root.tsx and index.tsx files, but the issue still persisted.

**Steps to reproduce**
1. Install architect framework when setting up application through `npx create-remix@latest`
2. Build application
3. Go to localhost of site and see the error posted above in the console log.

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):

OS: MacOS Monterey
Browser: Chrome 102.0.5005.115 and Safari 15.4

**Comment by vonkoff** [comment]
Also, went through making a new application that's bare bones. 

```
 npx create-remix@latest
Ok to proceed? (y) y
? Where would you like to create your app? ./fix-architect-issues
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets.
Architect (AWS Lambda)
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```

Still getting the console error issue when I open it up.

**Comment by tbeseda** [comment]
I believe this is a React-specific error where your server-rendered DOM does not match what React expects on the client. I noticed that there was some guidance provided for this specific case over on Remix's Discord.

I'm closing this issue as it's not Arc-specific. But if you can reproduce without React/Remix, feel free to open this issue back up with steps to reproduce.

**Comment by vonkoff** [comment]
Just adding in for everyone who is looking for the answer. You just need to run `arc env -e testing --add NODE_ENV password`. Do this for testing, staging, and production so the error goes away.
