### ISSUE TITLE
Architect's hydrate fails when using the `node:` prefix for core modules

### ISSUE THREAD

**Issue by tbeseda** [architect/architect#1358]
Newer Node.js allows namespaced import/require of Node core modules with the `node:` prefix
```js
import fs from 'node:fs'
const fs = require('node:fs')
```
https://nodejs.org/api/modules.html#core-modules

Hydrate assumes 'node:fs' is a package it should hydrate and fails when running `npm install`

It might be easiest to ignore package name strings `/^node:/`

**Comment by ryanblock** [comment]
Fixed here: https://github.com/architect/hydrate/pull/156/commits/a88a5074ff6db153090ba4696ecf185b15550296

Will be released in 10.4!
