### ISSUE TITLE
How to provide bucket name, domain name and cdn in architect?

### ISSUE THREAD

**Issue by sridhar562345** [architect/architect#1360]
I have gone through the docs, but coudn't find any advanced usage options.

**Comment by ryanblock** [comment]
You can provide custom bucket names for Arc's built-in `staging` and `production` environments with the following options:
```
@static
staging your-staging-bucket
production your-prod-bucket
```
Currently CDN + domain name are left to users to determine for themselves how they'd like to be set up an operate.

**Comment by brianleroux** [comment]
This is an older macro (plugin) that demos adding DSN stuff w Route53 and may be helpful; generally we've found people want to use other registrars and CDNs so didn't make this 'core' to Architect but I'm open to it. Are you aiming to use Route53 and CloudFront?

https://github.com/brianleroux/arc-macro-dns

**Comment by sridhar562345** [comment]
@brianleroux Yes, I am trying to use Route53 and Cloudfront with a custom domain. Will [arc-macro-dns](https://github.com/brianleroux/arc-macro-dns) suit my usecase?

**Comment by brianleroux** [comment]
hey @sridhar562345 this issue has gone pretty stale / let me know if you need help with this still in our discord !
