### ISSUE TITLE
Incorrect CloudFormation bucket SSM parameter name in projects using _ create new bucket on each deploy

### ISSUE THREAD

**Issue by DocLM** [architect/architect#1363]
Hi,
I found an issue in projects that contains `_` in their names.

Architect creates parameters as `<appname>/deploy/<something>`.
CloudFormation template bucket SSM parameter is created with `_` replaced with `-` but the same transformation is missing when reading the parameter during the next deploy.
This make Architect to create a new CloudFormation template bucket on every deploy.

1. Create a project with `_` in name
2. Deploy
3. Deploy another time
4. See the duplicate bucket in AWS console

**Expected behavior**
Reusing the old bucket from previous deploy

**Screenshots**
Project is called `<something>_identity_client`
![screenshot](https://user-images.githubusercontent.com/2318483/181210899-6c38d463-1bc6-45d5-a3a8-26b79acf11c4.jpg)

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS
 - Version: 12.5

**Comment by ryanblock** [comment]
Yikes / ew. I'll see if I can get this knocked out in time for the 10.4 release. Thank you for the heads up, will circle back with any questions!

**Comment by ryanblock** [comment]
Fixed in https://github.com/architect/deploy/pull/356/commits/569478ce1630183d6007bf99eb966a042a75dc9d and should be released in 10.4 today!
