### ISSUE TITLE
Switching from index.js to index.mjs requires a restart

### ISSUE THREAD

**Issue by andybee** [architect/architect#1366]
**Describe the issue**
When you start Sandbox and a route has an `index.js` file, renaming that to `index.mjs` will cause that route to fail with a cannot a "Lambda handler not found" error until Sandbox is restarted. The reverse (starting up with index.mjs and renaming to index.js) also triggers the same issue.

**Steps to reproduce**
1. Create a new Architect project, add a single HTTP route and start Sandbox.
2. Rename `index.js` to `index.mjs` and make the necessary tweaks to be an ESM handler function.
3. Attempt to load the route in the browser.

**Expected behavior**
Flipping from CommonJS to ESM doesn't require a Sandbox restart.

**Comment by ryanblock** [comment]
This is a tricky one. When I wrote all the related logic, I assumed sooner or later this feature request would appear! Here's why this is a bit funky:

- When Architect starts up, Inventory traverses and discovers everything there is to know about the project, including what Lambda `nodejs1_.x` version it is, and if it's 14, whether it's in CJS or ESM mode
- This logic [is a bit complicated (but not too gnarly)](https://github.com/architect/inventory/blob/main/src/config/pragmas/populate-lambda/get-handler.js#L42-L57) and is shared by both Sandbox and Deploy (hence it being centralized into Inventory)
- In the case of Sandbox, with that knowledge at invocation time, Sandbox knows how to start up Node in ESM or CJS versions, which have pretty different means of starting up and other capabilities, see:
  - [CJS invocation](https://github.com/architect/sandbox/blob/main/src/invoke-lambda/exec/runtimes/node.js)
  - [ESM invocation](https://github.com/architect/sandbox/blob/main/src/invoke-lambda/exec/runtimes/node-esm.js)
- Thus, currently if we were to detect a change to ESM vs CJS in a Lambda handler, we'd need to re-Inventory the project

In theory, we could automatically do a warm Sandbox restart based on filesystem events, but right now I'm not sure we can deterministically know when you've changed from CJS to ESM mode, as the [Node fs watcher doesn't consistently emit rename events](https://nodejs.org/api/fs.html#caveats) (and such a change may not come in the form of a file rename anyway).

One idea I had a while back was to maybe create a library out of the handler detection logic which could run independently, but even that could have issues. For example, if you switch from `nodejs12.x` (which didn't support CJS) to `nodejs14.x` in a function, Inventory wouldn't re-run then either, and thus not trigger the handler detection logic.

I'm open to other ways of thinking about this and approaching it!

**Comment by andybee** [comment]
Appreciate the difficulty in resolving this “properly”. It’s not a big issue for me, typically hit when I first start refactoring a project, then remember to do the initial switch with sandbox closed and then start it again.

Could it be simpler to emit a warning when a rename event is seen that makes a .js file .mjs or vice-versa and suggest a restart on the console? I realise it’s not going to solve all possible switches and that the FS watcher itself can be unreliable, but if it softens the hard edges for a bunch of possibilities quickly - it might be an easy win?

**Comment by ryanblock** [comment]
Perhaps simpler still: just default to ESM, and prob very few will need to swap out (except when refactoring legacy codebases, I guess, which is probably rare by comparison)?

**Comment by andybee** [comment]
Just to clarify, this is in reference to the template/boilerplate magic when Sandbox creates a new route from a definition in `app.arc`? If so, that works?

How hard would it be to be a `preferences.arc` setting to not do that, for legacy projects?

**Comment by ryanblock** [comment]
Any function (or project) using Node 12 would still default to cjs, so specifying that for legacy projects would be a matter of defining that runtime. (That said, 12 isn’t long for Lambda; phase 1 deprecation starts in November, and phase 2 is in December.)

We can probably also add a handler option for Arc init for anyone who wants to keep using cjs.

**Comment by ryanblock** [comment]
Actually, I also forgot that Arc projects can have custom handler boilerplate in `preferences.arc` – I think we worked on that feature together @andybee? See:

```
@create
templates
  events tmpl/events-tmpl.js
  http tmpl/http-tmpl.js
```

With this existing feature, any project that wants to continue provisioning CJS can do so in any way they wish.

Anyhow, I think provisioning ESM handlers by default is going to be 10.6, stand by for that release!

**Comment by ryanblock** [comment]
Ok, getting pretty close! I think this could land as soon as tomorrow. Primary PRs here if you (or anyone) want to futz around with local patching:
- https://github.com/architect/inventory/pull/44
- https://github.com/architect/create/pull/81

**Comment by ryanblock** [comment]
Ok, ESM handler provisioning by default is now live in 10.6, hopefully this helps resolve the root issue at hand here!
