### ISSUE TITLE
Keep SSM secure strings when stage is destroyed

### ISSUE THREAD

**Issue by Xiphe** [architect/architect#1368]
**Describe the issue**

I use a flow where I use varying named stages to preview PR's and a singe production stage.
The preview stages are destroyed when they're integrated into main/production. 

As with https://github.com/architect/architect/issues/1076, when any named stage is destroyed, it also clears the Staging env vars so when a new stage is created in the future the env must be re-created. 

**Steps to reproduce**

1. add a staging secret `arc env -e staging --add TEST psssst`
2. deploy a single named stage with `arc deploy --name my-stage`
3. destroy that stage with `arc destroy --name my-stage --app my-app --force`
4. watch as your environment variables are being deleted with `Destroy Deleting SSM parameters...`
5. run `arc env` to see `Env Staging env vars: None found!`
6. Optional: deploy another stage with `arc deploy --name my-second-stage` and watch it fail since required variables are not present

**Expected behavior**

Since the stage environment variables are shared across all named stages I would expect that they're not deleted when I destroy a named stage.
I would expect that the variables are cleared when I either destroy my unnamed stage or destroyed the last stage used

At minimum I would expect to have an option for keeping these on destroy `arc destroy --name my-stage --app my-app --force --keep-env`

**Comment by brianleroux** [comment]
oof this sucks! sorry @Xiphe / will look at fixing ASAP

**Comment by Xiphe** [comment]
No worries. Thanks for taking care! Let me know when I can help!

**Comment by ryanblock** [comment]
Released in 10.5!
