### ISSUE TITLE
Document which AWS permissions are needed to deploy an application

### ISSUE THREAD

**Issue by christian-bromann** [architect/architect#1379]
**Is your feature request related to a problem? Please describe.**
Hey, I just started using architect for an application and wanted to have a dedicated AWS user that has all necessary permissions needed to deploy an application. It would be helpful if there is a way to identify which these are and document them. I am currently adding permissions based on error messages I get but now I just see `Access Denied` which is not very helpful.

**Describe the solution you'd like**
Ideally a json file with AWS permissions needed to deploy an application so that I can create a policy for it.

**Describe alternatives you've considered**
n/a

**Additional context or notes**
I am not a very proficient AWS user so excuse me if this query is silly.

**Comment by ryanblock** [comment]
Please see: https://arc.codes/docs/en/get-started/detailed-aws-setup#credentials

**Comment by christian-bromann** [comment]
mhm 🤔  I ended up giving the user `AdministratorAccess` but it seems like not ideal for me to have a user with full access to all AWS resources. I am not sure how often the tool changes its needs for access to different AWS resources but it seems like a reasonable idea to say like: create a user, assign a new policy with this JSON content to it and off you go.

**Comment by christian-bromann** [comment]
Ah sorry, not sure why I missed that 🙈

**Comment by ryanblock** [comment]
All good!
