### ISSUE TITLE
set.customLambdas with custom pragma fails on `arc init`

### ISSUE THREAD

**Issue by buffpojken** [architect/architect#1382]
**Describe the issue**
Following the [guide](https://arc.codes/docs/en/guides/plugins/set#set.customlambdas) for `set.customLambdas` and then running `arc init` results in an error due to pragma being null, thus resulting in an undefined property when setting runtime for code generation. 
 
**Steps to reproduce**
1. Add a custom plugin with the following code: 
```
module.exports = {
  set: {
    customLambdas ({arc, inventory}){
      let customs = arc['custom-lambdas']

      if (!customs || !Array.isArray(customs)) return
      
      let lambdas = customs.map((item) => {
        return {
          name: item,
          src: `src/custom-lambdas/${item}`,
          config: {
            runtime: 'nodejs16.x'
          }
        }
      })

      return lambdas
    }
  }
```
2. Add a pragma matching the plugin to arc-file: 
```
@app
hippodamus

@plugins
custom-infra

@custom-lambdas
inbox-bucket-event-receiver

@aws
profile co
region eu-north-1
runtime nodejs16.x
```
4. Run `arc init`
5. See error that says:
```
init failed! Cannot read properties of undefined (reading 'node')
TypeError: Cannot read properties of undefined (reading 'node')
    at writeCode (/Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect/node_modules/@architect/create/src/write-functions/write-code.js:42:22)
    at /Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect/node_modules/@architect/create/src/write-functions/index.js:19:7
    at Array.forEach (<anonymous>)
    at writeFunctions (/Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect/node_modules/@architect/create/src/write-functions/index.js:12:8)
    at create (/Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect/node_modules/@architect/create/src/index.js:99:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect/src/index.js:75:7)
    at async /Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect/src/index.js:91:5
```

**Expected behavior**
I expect a placeholder to be generated for a userspace custom lambda according to the guide at https://arc.codes/docs/en/guides/plugins/set#set.customlambdas.

**Desktop**
Please complete the following information (if appropriate):
 - OS:  macOS 12.6
 - Arc version: 
 ```
      Version: Architect 10.7.0
 Installed to: /Users/buffpojken/.nvm/versions/node/v16.13.2/lib/node_modules/@architect/architect
          cwd: /Users/buffpojken/projects/arc/hippodamus
``` 

**Additional context**
I have, by reading the source from the stack trace, deduced that the `pragma`-variable is null, resulting in the selection of body for the template-file to crash with a read on undefined.

**Comment by buffpojken** [comment]
My casual read of the source code in `write-code.js`#33-42 is that another conditional case specifically covering customLambdas would be required, since presumably pragma would always be null in that case, but I'm not familiar enough with the source code to understand if that would yield undesired side effects?

Something along the lines of: 
```
  if (!body && pragma === 'http') {
    body = handlerModuleSystem
      ? types[pragma][run][handlerModuleSystem](handler)
      : types[pragma][run](handler)
  }
  else if (!body && pragma) {
    body = handlerModuleSystem
      ? types[pragma][run][handlerModuleSystem]
      : types[pragma][run]
  }else if(!body && !pragma){
    body = handlerModuleSystem
      ? types["customLambdas"][run][handlerModuleSystem]
      : types["customLambdas"][run]
}
```

**Comment by buffpojken** [comment]
I have digged a bit further into the suggestion above and I don't find any unwarranted side effects. Would a PR on that be welcome or am I missing something?

**Comment by ryanblock** [comment]
PR is def welcome, I was going to be taking a look at this today either way. Just let me know if you're putting one together!

**Comment by buffpojken** [comment]
If you (or someone familiar with the source code) could confirm if there's any other cases when we could expect pragma to be null, I'll be happy to make a PR for this - but I'm not terribly familiar with the code base (especially since I only use Architect with nodejs), so I hesitate to assume that's the case.

**Comment by ryanblock** [comment]
I don't think so, but I'll have a PR ready in a few minutes, stand by!

**Comment by ryanblock** [comment]
See: https://github.com/architect/create/pull/82 – this will be out in 10.7.1 later this morning!

**Comment by buffpojken** [comment]
Just tested this and works wonderfully - cheers!
