### ISSUE TITLE
Custom Name for CloudFormation Stack

### ISSUE THREAD

**Issue by chanesteves** [architect/architect#1385]
**Is your feature request related to a problem? Please describe.**
Currently, I can't find a way to customize the name of the _CloudFormation_ stack generated by `arc deploy`. The name always results to [Appname][Env] - pascal case.

**Describe the solution you'd like**
Looking for a way to customize the name of the _CloudFormation_ stack generated by `arc deploy` (e.g. name with all letters in lowercase)

**Describe alternatives you've considered**
N/A

**Additional context or notes**
N/A

**Comment by ryanblock** [comment]
This is the AWS-y (and CloudFormation) way of doing things. Perhaps we can delve a bit deeper into the problem that needs to be solved here?
