### ISSUE TITLE
EndpointTypes REGIONAL or EDGE

### ISSUE THREAD

**Issue by maitriyogin** [architect/architect#1387]
Hi,
I'm just trying out Architect having come from using the server less framework.
I can't seem to work out how to set an ```endpointType``` ?
At the moment lambda deploys are to lambda@Edge, I'd like to deploy them regionally.
In SF you can just set provider.endpointType to either REGIONAL or EDGE ...

Any help would be much appreciated,
Stephen.

**Comment by ryanblock** [comment]
Welcome! (And hi again!)

Endpoint type is a legacy setting for `REST` APIs, which AWS still technically supports but has effectively put into maintenance mode. [`HTTP` APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html) are now the recommended API type, which Architect uses by default; the endpoint type setting does not apply to `HTTP` APIs.

One thing to note: setting the endpoint type to `edge` is NOT the same as `Lambda@Edge` – they are completely different systems and products (confusing as that may be). `Lambda@Edge` is a pared-down version of Lambda running inside of [CloudFront](https://aws.amazon.com/lambda/edge/); it's not the same Lambda, not the same API Gateway req/res payloads, and doesn't necessarily involve or use API Gateway `REST` / `edge` APIs.

Anyhow, head here to learn more about the differences between `HTTP` vs. `REST` APIs: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html

Architect continues to maintain Sandbox support for `REST` APIs with the [`@aws apigateway rest` setting](https://arc.codes/docs/en/reference/project-manifest/aws#apigateway), and Deploy support via the [REST plugin](https://github.com/architect/plugin-rest-api). By default, that plugin provisions regional `REST` APIs, but that can be easily altered with a [`deploy.start` plugin](https://arc.codes/docs/en/guides/plugins/deploy#deploy.start).

Hope that helps!
