### ISSUE TITLE
proposal: new @buckets primitive

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#1393]
this use case is incredibly common; we have a great plugin for this already and think its time we paved it. proposal syntax:

```arc
@app
myapp

@buckets
my-bucket
```

runtime discovery

```javascript
let arc = require('@architect/functions')

let services = await arc.services()
// { buckets: {mybucket:'arn:aws:s3:::mblsdfklasdfoj' }
```

runtime helper

```javascript
let arc = require('@architect/functions')
let buckets = await arc.buckets()
console.log(buckets.mybucket)
// logs { list, put, get, head, delete, copy } shim
```

**Comment by filmaj** [comment]
Yeah I'm all for this!

This can start a deep rabbit hole, depending on which properties/features of S3 we want to support. I have a plugin that exposes some of that here: https://github.com/filmaj/arc-plugin-s3-image-bucket - though it is focussed on image storage within buckets, it supports configuring things like CORS, static website, and Lambda notifications (trigger lambda executions based on S3 events in your bucket).

Probably makes sense to start with a slim feature set and additively build out any additional features we want to support slowly.

**Comment by TreyOverton** [comment]
> we have a great plugin for this already

Where is this great plugin?

**Comment by ryanblock** [comment]
https://www.npmjs.com/package/@architect/plugin-storage-public
https://www.npmjs.com/package/@architect/plugin-storage-private

**Comment by brianleroux** [comment]
ok! created a new issue for this: https://github.com/architect/architect/issues/1475
