### ISSUE TITLE
Sandbox forgets port preference when `app.arc` is updated

### ISSUE THREAD

**Issue by andybee** [architect/architect#1395]
**Describe the issue**
In an Architect project, if you launch Sandbox with `--port 3335`, then make a change to `app.arc`, the Sandbox reload forgets the port preference and moves back to `:3333` (or crashes if you happen to be running something else on `:3333` to use this flag in the first place).

**Steps to reproduce**
1. Create a new project (`npm init @architect your-app`, `cd your-app`).
2. Start Sandbox on a non-standard port via arguments (`npx arc sandbox --port 3335`) and verify a page loads (`http://localhost:3335/`).
3. Modify `app.arc` (e.g. add a new route) and see `Sandbox reloaded` on the console.
4. Refresh `http://localhost:3335/` and see a connection failure.

**Expected behavior**
When Sandbox triggers a reload on project manifest update, it should respect the launch port configuration.

**Additional context**
This does not happen if you use the `PORT` environment variable.

**Comment by ryanblock** [comment]
Fixed in [Sandbox 5.5.1](https://github.com/architect/sandbox/pull/692) + Arc 10.10.1. This also now affords dynamic port changes while working, so if you update your `prefs.arc` file with new Sandbox ports, that will be instantly respected.
