### ISSUE TITLE
Advice on emptying deployments bucket

### ISSUE THREAD

**Issue by alexbepple** [architect/architect#1398]
I got a warning from AWS about my S3 usage approaching the free-tier limit. After looking into the deployment bucket created by Architect (`xyz-cfn-deployments-9abcde`), it seems that the blobs of all the deployments are stored there. Is it safe to delete all of them? Only some of them? Is there any use at all for the blobs after the deployment is successful? Can you recommend a best practice for deleting unneeded blobs?

I would appreciate any advice.

**Comment by ryanblock** [comment]
Delete away! Unless you anticipate redeploying a build, everything in that bucket is safe to delete (that’s not actively being deployed).

I can also see Arc automatically destroying everything older than a week as a post deployment operation!l . Wdyt?

**Comment by alexbepple** [comment]
@ryanblock Thanks for the clear advice.
Yes, Arc automatically deleting old deployment artifacts would be amazing.
