### ISSUE TITLE
Idea: automatically delete old artifacts from deployment bucket

### ISSUE THREAD

**Issue by alexbepple** [architect/architect#1399]
**Is your feature request related to a problem? Please describe.**
Deployment artifacts accumulate in the S3 bucket (`xyz-cfn-deployments-9abcde`), incurring costs. See #1398.

**Describe the solution you'd like**
@ryanblock’s suggested solution (#1398#issuecomment-1367668113) sounds great: automatically delete artifacts older than a week in a post-deployment operation.

**Describe alternatives you've considered**
A user could of course set up such a rule themselves using S3 lifecycle rules. But this is an inferior solution, as every user would need to set this up themselves.

**Comment by ryanblock** [comment]
Shipped in 10.9.3!
