### ISSUE TITLE
Enable `pnpm` as a valid package manager for hydrate.

### ISSUE THREAD

**Issue by nicksrandall** [architect/architect#1403]
Enable `pnpm` as a valid package manager for hydrate in addition to `npm` and `yarn`;

**Comment by ryanblock** [comment]
There are a lot of package managers out there. Rather than trying to support everything, I kind of think we’d just be better off letting folks configure it for themselves. wdyt?

**Comment by ScottAwesome** [comment]
> There are a lot of package managers out there. Rather than trying to support everything, I kind of think we’d just be better off letting folks configure it for themselves. wdyt?


I can definitely understand this sentiment.

I think its important to consider support what [Corepack](https://nodejs.org/docs/latest-v18.x/api/corepack.html#enabling-the-feature) supports, which would be `yarn`, `npm`, and `pnpm` at the moment

I don't think there's really any other package manager on the horizon currently.

Alternatively, if the API is dead simple drop in, sure, allow an escape hatch so we can support our own.

**Comment by ryanblock** [comment]
That feels like a worthwhile criteria! Although worth noting that Corepack is not yet itself stable or enabled by default, so I'm not sure how that'll all eventually shake out, but all the same I'm totally open to a PR!

**Comment by ryanblock** [comment]
→ https://github.com/architect/hydrate/pull/170

**Comment by ryanblock** [comment]
Merged and will ship in the next version of Architect.
