### ISSUE TITLE
Sandbox services should only listen on localhost by default

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1406]
**Describe the issue**
Sandbox services should only listen on loopback addresses by default in order to keep users' local development environments secure (see architect/sandbox#676). However, a regression introduced in architect/sandbox#688 changed the default behavior so that sandbox services listen to the whole network (0.0.0.0).

This change in the default behavior was not mentioned in the Architect change log and it was not reflected in the documentation. The documentation still implies that the default behavior is to only listen on loopback.

**Steps to reproduce**
1. Run `arc sandbox` on one computer.
2. Navigate to your sandbox site from another computer.

**Expected behavior**
The sandbox site should not be reachable from another computer by default.

**Screenshots**
See attached screenshot of the documentation which shows that it still implies that the default behavior is to only listen on loopback.

![Screenshot 2023-02-08 at 12 48 44](https://user-images.githubusercontent.com/728407/217611228-b1b72368-6934-4ce4-9e88-237eacd6ade6.png)

**Desktop**
Please complete the following information (if appropriate):
 - OS: N/A
 - Browser: N/A
 - Version: 10.8.0

**Mobile**
Please complete the following information (if appropriate):
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Might be worth issuing a security advisory for this one.

**Comment by ryanblock** [comment]
**Some background**

Dating back to the very earliest days of Sandbox, the assumption was that Sandbox would listen on what Node.js refers to in its documentation as ["the unspecified IPv4 address"](https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback) (`0.0.0.0`). This does indeed make Sandbox available on any non-firewalled local interface, which is intended behavior. For example: you're working on your Arc project with Sandbox running on your machine, and want to load it from your phone to test your app in mobile.

In retrospect, I should not have merged [#676](https://github.com/architect/sandbox/pull/676/files), as that resulted in a breaking change that I hadn't considered at the time. (That merge also led to [#678](https://github.com/architect/sandbox/pull/678) and a handful of other changes to manually re-enable Sandbox to respond on all interfaces, later released 5.3.0.) This is also why the documentation is incorrect.

When Node.js 18 introduced a breaking change to how server host binding worked (thereby impacting 676), I issued 688 to patch it, and in doing so inadvertently restored the previous approach to Sandbox allowing connections.

**Next steps**

The assumption of Sandbox is that it's available to any clients able and allowed by your local firewall to access it, per the use-cases above. But we should be clearer about this, and more helpful in our advice to help lock Sandbox down for anyone.

I'll update Sandbox documentation to more clearly state expectations for its default behavior, and instruct folks to use `--host localhost` if they'd like to ensure only local connections will be accepted by Sandbox.

Additionally, if there's interest in doing so, I can see adding a [`prefs.arc` Sandbox setting](https://arc.codes/docs/en/reference/configuration/local-preferences#%40sandbox) to persist the host setting in local or global preferences. Thoughts on that feature?

**Comment by ryanblock** [comment]
Not sure I agree it's particularly risky default behavior. If you're working in an office, an intrusion would be necessary to launch an attack on your Sandbox instance. Same if you're working from home.

If you're working from an untrusted network (say, a cafe with WiFi that isn't set up in guest mode to isolate clients), Sandbox does not run on any standard, common ports by default, so it is unlikely to open its host to appearing in rudimentary network scans. If someone in an untrusted network acquires your IP and you don't have a local firewall enabled, then yes, at that point, they can run a full port scan. Depending on what kind of data you've seeded to your Dynamo tables or HTTP endpoints you've made accessible there could be some theoretical risk.

I do get the concern though, and always appreciate the tendency to err on the side of caution. I think most folks at first glance would not recognize the subtle technical differences between `0.0.0.0` and `localhost` and `127.0.0.1` in a URL, so how would you propose alerting folks to the mode in which Sandbox is bound to its local interface(s)?

**Comment by lpsinger** [comment]
> Not sure I agree it's particularly risky default behavior. If you're working in an office, an intrusion would be necessary to launch an attack on your Sandbox instance.

That makes the assumption that your office network blocks ingress on arbitrary ports. It's also only safe if you are on a small, tightly controlled office network. If you are on a large corporate intranet, then you are nearly as at risk as if you permitted ingress from the internet.

As I see it, `arc sandbox` is designed for local development. At least that is how I use it. What is the use case for having it listen to connections from the whole network? Is that use case the most common case?

**Comment by lpsinger** [comment]
> I think most folks at first glance would not recognize the subtle technical differences between `0.0.0.0` and `localhost` and `127.0.0.1` in a URL, so how would you propose alerting folks to the mode in which Sandbox is bound to its local interface(s)?

Something like, "Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks." See an [example in the OpenTelemetry source](https://github.com/open-telemetry/experimental-arrow-collector/blob/4ed00c89ee273a69e140544a99a4fbf922fc4f6f/config/internal/warning.go#L52).

I would also add a "Security Best Practices" section to the Architect manual, with a section titled "Safeguards against denial of service attacks" similar to [this OpenTelemetry example](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks).

Although, even better would be for the "best practice" to be the default configuration.

**Comment by ryanblock** [comment]
I believe I already enumerated the use case above, which is one we've employed many times during developing apps with Architect: you need to test local code out on a mobile (or other) device.

Although we may disagree on the severity of the risk at hand here, I think we're both on the same page of the why and how, so if it's cool with you I'm going to go ahead and close this issue. I think we can address this in Arc docs moving forward, and definitely welcome PRs!

**Comment by ryanblock** [comment]
Additional arc.codes documentation in https://github.com/architect/arc.codes/pull/668
