### ISSUE TITLE
Option to Omit Environment Variables from Lambdas

### ISSUE THREAD

**Issue by meza** [architect/architect#1409]
Especially when working with Remix, the server benefits the most from being on Lambda@Edge.
Functions cannot be distributed to the edge if they have environment variables. (It's an AWS limitation)

![image](https://user-images.githubusercontent.com/211977/220620281-61b0699b-ed25-4da2-be9f-5436fa4a97c2.png)

**Describe the solution you'd like**
- I'd like a configuration option in the `@aws` section to have the function env vars turned off. 
- That, or outright first class support for edge deployments

**Describe alternatives you've considered**
I've considered just not using Architect anymore but I do appreciate how much it helps with local dev

**Comment by ryanblock** [comment]
I don't necessarily agree that "the server benefits the most from being on Lambda@Edge"; as with so many things in technology, it really depends. While CF PoP proximity is nice, the quotas and capabilities of Lambda@Edge are still quite truncated by comparison to proper Lambda. (Refs: [quotas](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge), [restrictions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html))

In any event, you can turn off env vars on each individual function with the [`@arc env false` setting](https://arc.codes/docs/en/reference/configuration/function-config#%40arc). That said, Architect does not ship Lambda@Edge out of the box or emulate it in Sandbox, so if your plan is to use it in that context, you'll want to do so via [`deploy.start`](https://arc.codes/docs/en/guides/plugins/deploy#deploy.start) (and probably other) plugin APIs.
