### ISSUE TITLE
[TypeScript] Error when running `arc init` to generate new HTTP route

### ISSUE THREAD

**Issue by pachoclo** [architect/architect#1410]
Running `arc init` on a project configured with the TypeScript plugin results in an error.

1. Create a new arc project
2. Install TypeScript plugin
3. Change `get-index/index.mjs` -> `get-index/index.ts`
4. Add `get /names` http route to `app.arc`
5. Run `arc init`

-> 
- Folder `/get-names/` gets generated
- File `/get-names/index.ts` FAILS to be generated

The init command should run without errors and be able to generate the file  `/get-names/index.ts` 

**Screenshots**
<img width="1321" alt="Screenshot 2023-03-06 at 12 49 52 PM" src="https://user-images.githubusercontent.com/3608140/223195494-55c0e576-22ac-4dee-94b9-907332456120.png">

```
@app
arc-test-project

@http
get /
get /names

@aws
profile arc
region us-east-1
architecture arm64
runtime typescript 

@plugins
architect/plugin-typescript
```

**Comment by ryanblock** [comment]
Quick update: the fix for this is in progress, and is slated to ship in [Arc 10.12](https://github.com/architect/architect/milestone/25) alongside compiled runtime support! See also: https://github.com/architect/create/pull/86

**Comment by ryanblock** [comment]
Ok, this fix can now be tested with Arc 10.12 RC and the `@architect/plugin-typescript` v1.2 RC (see: https://github.com/architect/plugin-typescript/pull/13).

**Comment by pachoclo** [comment]
> Ok, this fix can now be tested with Arc 10.12 RC and the `@architect/plugin-typescript` v1.2 RC (see: [architect/plugin-typescript#13](https://github.com/architect/plugin-typescript/pull/13)).

Sorry for the noob question, but how can I test the RC versions?

**Comment by pachoclo** [comment]
Got it! It's working great :)

**Comment by pachoclo** [comment]
Tested with:

- @architect/architect@10.12.0-RC.1
- @architect/plugin-typescript@1.2.0-RC.0

**Comment by brenden-ef** [comment]
Hi @ryanblock - sorry for jumping into an old issue. Was the fix for this ever released beyond the rc? Installing `@architect/plugin-typescript` in a new project seems to be at v1.1.1 and the error is still thrown. If it was released I'm happy to open a new issue.
