### ISSUE TITLE
Running arc deploy with --tags parameter doesn't produce changes in sam.json

### ISSUE THREAD

**Issue by kethzi-gilbert** [architect/architect#1413]
When i deploy a architect project by passing the tags parameter for e.g: `arc deploy --tags type=test-architect-app`
Though the application is deployed with the correct tags on the resources (in my case lambda functions) I do not see the tags updated in the Sam.json/yaml file. 

**Steps to reproduce**

1. Configure a basic Architect app with a http lambda function 
2. Deploy the resources with tags  by running `arc deploy --tags type=architect-test-app`

**Current behaviour** 
The sam.json file which is produced doesn't contain configuration of the lambda function in the tags property as mentioned in [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html)

**Expected behavior**
The sam.json file which is produced should contain configuration of the lambda function in the tags property.

This use-case is especially needed when we use a dry run deploy, cause currently there doesn't seem to be any indicator that the tags are being applied.

**Comment by ryanblock** [comment]
I'm not sure if this was still replicating, but Deploy tags have been rebuilt and validated for the Arc 11 transition to `aws-lite`. Reference: https://github.com/architect/deploy/blob/aws-lite/src/sam/01-deploy/index.js#L40-L48
