### ISSUE TITLE
Aborting a deploy leaves local project in broken state

### ISSUE THREAD

**Issue by andybee** [architect/architect#1426]
If you terminate Architect during the deploy state, typically whilst it's hydrating project functions, it leaves the project in a state that any subsequent attempt will fail with an error from hydrate trying to read an undefined property. (Whilst this is an unusual situation, I'm finding it surprisingly easy to do by my mistake by closing a VSCode window which had the terminal running.)

1. With an existing Architect project, start a deployment.
2. Terminate Architect deploy during the hydration stage.
3. Attempt to start the deployment again and you should see an error.

**Expected behavior**
When accidentally terminating a deployment, I would expect to be able to restart the deployment without issue.

**Additional context**
I believe the problem is in an auto-generated `package.json` file in one of the handler directories having incomplete data. I run the following commands in the project root to reset if it gets in this state:

```
find ./src -type d -name node_modules | xargs rm -r
find ./src -type f -name package.json | xargs rm
find ./src -type f -name package-lock.json | xargs rm
```

**Comment by ryanblock** [comment]
I took a look at this today, and unfortunately I can't reproduce any errors with the above instructions. I cloned a large project, ran deploy (with the `--dry-run` flag, which should not make an impact on this issue), and canceled during hydration. This left a bunch of generated `package.json` files throughout the project, as expected. I then ran deploy again, and everything worked without error.

Given past experiences with package managers, dependency hydration, etc., I'm sure you're right and that there exist circumstances where something might break – but I'm currently unable to find them, so I can't really triangulate a fix. A couple diagnostic questions:
- Is this `npm`, `pnpm`, `yarn`, or something else? (What version?)
- What are the exact steps taken, and what are the errors generated?
- Anything else that might help clarify this?

**Comment by andybee** [comment]
I'm using npm 9.5.1 and I've just managed to replicate the issue locally as follows:

1. Run `npx arc deploy --dry-run`
2. During the hydration phase, kill `deploy` with CTRL+C
3. Run `npx arc sandbox`
4. Sandbox states it has "Found new functions to hydrate!" and completes that process, then immediately errors with the following:

```
path/to/project/node_modules/@architect/hydrate/src/hydrate.js:122
      if (lambdaHasManifest && lambda.config.runtime.startsWith('nodejs')) {
                                             ^

TypeError: Cannot read properties of undefined (reading 'runtime')
    at path/to/project/node_modules/@architect/hydrate/src/hydrate.js:122:46
    at Array.map (<anonymous>)
    at hydrator (path/to/project/node_modules/@architect/hydrate/src/hydrate.js:118:52)
    at Object.run (path/to/project/node_modules/@architect/hydrate/src/hydrate.js:33:5)
    at install (path/to/project/node_modules/@architect/sandbox/src/sandbox/maybe-hydrate.js:54:19)
    at Array._packageJson (path/to/project/node_modules/@architect/sandbox/src/sandbox/maybe-hydrate.js:64:17)
    at runSeries (path/to/project/node_modules/run-series/index.js:23:33)
    at Array.<anonymous> (path/to/project/node_modules/@architect/sandbox/src/sandbox/maybe-hydrate.js:56:9)
    at each (path/to/project/node_modules/run-series/index.js:20:24)
    at end (path/to/project/node_modules/run-series/index.js:11:15)
```

I stuck a `console.log` in at line 122 of `hydrate.js` to log `rel` in that context to see which function it was tripping over, and which ones it previously iterates over successfully and the difference I can see is that NPM install appears to have completed on the ones passed over, but not on the first one it hits and errors on (e.g. I can see `node_modules` and `package-lock.json` in a successful one, only the generated `package.json` in the error'ed function).
