### ISSUE TITLE
`getRemainingTimeInMillis()` function missing from Node.js `context` object passed to Lambda functions

### ISSUE THREAD

**Issue by andybee** [architect/architect#1427]
Within AWS, when a Lambda function is invoked, the second parameter supplied to the handler is `context`. It includes a function `getRemainingTimeInMillis()` which returns the remaining milliseconds for the function to execute before a timeout will occur.

This method is not defined in the `context` object passed to Lambda handler functions within Sandbox, meaning we have a divergence in behaviour between local and deployed environments.

The function is documented here: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html

**Comment by andybee** [comment]
Thanks!

**Comment by ryanblock** [comment]
Released in 10.12.5!

This was amazing though, ngl: https://github.com/architect/sandbox/pull/707#issuecomment-1544740249

**Comment by ryanblock** [comment]
Yeah, doesn't seem to matter, lol: https://github.com/architect/sandbox/actions/runs/4960885878/jobs/8876977072?pr=708
