### ISSUE TITLE
Add more robust timeout error handling to deploy's shelling out to `aws cloudformation deploy`

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1443]
**Is your feature request related to a problem? Please describe.**
Yes! See [this Discord thread about someone seeing a deploy unhelpfully fail with `StatusReason`](https://discord.com/channels/880272256100601927/1143354488124604466). It turns out that with very large CloudFormation templates, the `aws` CLI might error out after 15 minutes, even while the underlying CloudFormation changeset is still being created.

**Describe the solution you'd like**
One interesting tidbit that came out of the above Discord thread is this link to this same underlying problem in the aws-sam-cli issue tracker: https://github.com/aws/aws-sam-cli/issues/4681
In the original issue post, a workaround is posted that I think it would be good for `arc deploy` to adopt. While the workaround is posted in the form of a GitHub Action workflow, I think we should consider adopting the general approach, which consists of:

1. In the case that shelling out to `aws cloudformation deploy` fails, do one extra check: check the status of the last-created changeset for the CloudFormation Stack in question (`aws cloudformation list-change-sets  --stack-name $STACKNAME --query 'reverse(sort_by(Summaries,&CreationTime))[0].Status' --output text`)
2. In the case that this status is `CREATE_IN_PROGRESS`, don't end the `arc deploy` process, but rather, shell out to another `aws` process: `aws cloudformation wait` (this one is new to me!) via something like `aws cloudformation wait change-set-create-complete --stack-name $STACKNAME --change-set-name $CHANGESET_NAME`.
3. Once this process finishes, repeat the same status-check for the changeset to verify it is complete.
4. The downside is that in this more robust timeout/error handling code, we'd have to manually execute the created changeset as the original shelling out to `aws cloudformation deploy` has failed, so we kind of have to "wrap up" the CloudFormation deploy ourselves after the changeset has been created successfully. This would involve:
    1. Executing the changeset (`aws cloudformation execute-change-set --change-set-name $CHANGESET_NAME --stack-name $STACKNAME`)
    2. Waiting for the actual CloudFormation Stack updating to complete (`aws cloudformation wait stack-update-complete --stack-name $STACKNAME`)

**Additional context or notes**
This PR to the deploy repo is related to this: https://github.com/architect/deploy/pull/380

**Comment by frankleng** [comment]
@filmaj since it's difficult to get reason of failure from `aws cfn deploy`, whats the downside to adopting this by default?
seems like it can go directly into https://github.com/architect/deploy/blob/main/src/sam/01-deploy/index.js
without breaking changes

I'm happy to take a stab at it this wkend if u guys agree

**Comment by ryanblock** [comment]
Re. #4, might be simpler to use `cfn.listchangeSets()` → `cfn.describeChangeSet()` over using the CLI.

@frankleng I'd say go for it, lots of room for improvement in these edge cases!

**Comment by ryanblock** [comment]
I think this issue will be resolved by the move to `aws-lite`, as Deploy is no longer using the AWS CLI in any way, see: https://github.com/architect/deploy/blob/aws-lite/src/sam/01-deploy/index.js#L81-L107
