### ISSUE TITLE
Respect static prefix in sandbox mode

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1450]
**Is your feature request related to a problem? Please describe.**
Architect does not respect the static prefix setting when in sandbox mode. According to this excerpt from the [documentation](https://arc.codes/docs/en/guides/frontend/static-assets#prefix):

> Note: locally in Sandbox HTTP paths to assets will be /_static/archive.zip, but once deployed will look like /_static/downloads/archive.zip. Additionally, this setting is not accounted for in [@architect/functions’s static method](https://arc.codes/docs/en/reference/runtime-helpers/node.js#arc.static).

This requires awkward conditionals in some places, such as https://github.com/nasa-gcn/gcn.nasa.gov/pull/1318/files#diff-4126ba9d04c94e7f7f7a4b7891b3dfa63edc5925bb24b15680640272a548cd5fR42-R44.

**Describe the solution you'd like**
Respect the static prefix setting in sandbox mode.

**Describe alternatives you've considered**
See workaround above.

**Additional context or notes**
N/A

**Comment by ryanblock** [comment]
Seems reasonable! I wonder if that nit is less relevant after some of the more recent refactors of Sandbox.
