### ISSUE TITLE
Add option to suppress S3 bucket name and API Gateway URL in `arc deploy` output

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1452]
**Is your feature request related to a problem? Please describe.**
My open source project is deployed using GitHub Actions, and the actions log output is public. The output from `arc deploy` contains the name of my application's S3 bucket and the URL of its API Gateway. Although these pieces of information are not exactly sensitive, I would rather not disclose them unnecessarily because knowledge of them makes it possible for users to bypass my CloudFront distribution and hit my origin directly. This could result in excessive cloud costs to me because requests are not hitting the CDN's cache and are going straight to the origin.

**Describe the solution you'd like**
A CLI option for `arc deploy` to suppress the S3 bucket name and API Gateway URL in the output.

**Describe alternatives you've considered**
Pipe the output of `arc deploy` through a script to sanitize URLs.

**Comment by ryanblock** [comment]
I found the easiest way to accomplish this in GitHub Actions (and other CI systems) is add the URLs in question to the repo secrets, as secrets can be counted on to be stripped from any CI output. Let's reopen this issue if there are concerns outside CI.
