### ISSUE TITLE
arc env - problem setting values with spaces

### ISSUE THREAD

**Issue by kenhorn** [architect/architect#1454]
**Describe the issue**

   Version: Architect 10.14.2

npx arc env -e staging --add FOO "bar baz"

This does not set the FOO env var to the value "bar baz"

**Steps to reproduce**
Setting an env var which is not parsed as a single token (I think by minimist npm library)
npx arc env -e staging --add FOO "bar baz"

npx arc env 

FOO value missing in the list.

**Expected behavior**
A clear and concise description of what you expected to happen

The value should be listed, and written to preferences.arc

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):
Am running on ubuntu under WSL2 (ie bash shell / Windows), but expect not system specific.

**Additional context**
Add any other context or notes about the problem here

**Comment by kenhorn** [comment]
Just to add a concrete use case, for AWS Lambda, the NODE_OPTIONS var allow the process to receive extra arguments. For open telemetry activation / config, I was trying to add:
npx arc env -e staging --add NODE_OPTIONS "--require ./tracing.js"

This gets lost in the minimist call inside cli.js

node_modules/@architect/env/src/cli.js:24:  let args = minimist(process.argv.slice(2), { alias, boolean })

**Comment by ryanblock** [comment]
This issue is not reproducing for me. Here's running on my Mac:

```sh
$ npx arc env -e staging --add FOO "bar baz"
         App ⌁ deployTestHttp
      Region ⌁ us-west-2
     Profile ⌁ personal
     Version ⌁ Env 3.0.12
         cwd ⌁ /Users/ryan/git/architect/_test-projects/env

✓ Env Added FOO to staging environment
✓ Env Total environment variables found: 5
⚬ Env Staging env vars:
  | FOO bar baz
✓ Env Updated prefs.arc file with latest env vars

$ npx arc env
         App ⌁ deployTestHttp
      Region ⌁ us-west-2
     Profile ⌁ personal
     Version ⌁ Env 3.0.12
         cwd ⌁ /Users/ryan/git/architect/_test-projects/env

✓ Env Total environment variables found: 5
⚬ Env Testing env vars:
  | FOO baz
  | THING heyooooooo
  | THINGO hi from testing
  | foo bar
⚬ Env Staging env vars:
  | FOO bar baz
⚬ Env Production env vars:
  | None found! Add production env vars with: arc env --add --env production NAME value
⚠️ Warning: The environment variable "ARC_APP_SECRET" is not set - please set this in production to help mitigate potential session-related attacks!
✓ Env Updated prefs.arc file with latest env vars
```

Note the env vars: testing `THINGO` (spaces!) and staging `FOO`.

What shell are you using? I am guessing this may be WSL-related?

**Comment by kenhorn** [comment]
npx arc env -e staging --add NODE_OPTIONS "--require tracing.js"

Hmm, I was actually using the above, perhaps the double hyphen is confusing
the minimist parsing - FOO works as per your / my example.

One thing I see, is the output shows Version - Env, while mine shows
Version - Architect 10.10.3  , Profile: default

**Comment by ryanblock** [comment]
So there is no issue with spaces? The issue is now with dashes?

**Comment by kenhorn** [comment]
I think that might be the case, yes - sorry! I will try to narrow. I notice
that the argos to minimist vary across the architect sub-modules - might
well be correct, but just wondered if adding a def value would help. I will
try to get back to this asap.

**Comment by ryanblock** [comment]
I'm going to close this due to inactivity and inability to reproduce, but please do let me know if anyone can provide repro steps or further details!
