### ISSUE TITLE
Per-function config to disable or enable hydration

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1456]
**Is your feature request related to a problem? Please describe.**
I have a project that contains some JavaScript Lambdas that I am bundling and tree-shaking myself using esbuild, and some Python Lambdas. I want to disable hydration for the former but enable it for the latter.

**Describe the solution you'd like**
A per function configuration to enable or disable hydration.

**Describe alternatives you've considered**
???

**Comment by ryanblock** [comment]
A `package.json` file with just `{}` in those Lambda should do the trick! I'd also evaluate a PR for a proper config setting (in the same vein of what @andybee just did in https://github.com/architect/hydrate/pull/179), if you're so inclined.

**Comment by lpsinger** [comment]
> A `package.json` file with just `{}` in those Lambda should do the trick!

That isn't quite sufficient for my use case. I have _many_ Lambdas, and I want only _one_ of them to be hydrated. I would need real function config.

**Comment by ryanblock** [comment]
Ok! Another workaround would be to disable all hydration and just do your own with the hydrate.copy hook, maybe using the `@architect/hydrate` module. A PR is probably pretty straightforward though if you want to take a swing!
