### ISSUE TITLE
Add `ignoredDependencies` to function `config.arc`

### ISSUE THREAD

**Issue by andybee** [architect/architect#1458]
Sometimes there is a requirement to place a module inside a Lambda layer, rather than as a dependency in `package.json` (for example, wishing to use a compiled dependency and deploy to an ARM architecture Lambda function from an x86 local environment).

When installing the module on the local development machine it correctly compiles/installs an x86 version for the local environment. I can then `require()` the module as usual without issue. But, when deploying and adding a layer to provide the ARM version, Node.js inside the Lambda function will favour the tree-shook version in `/var/task` over the layer one in `/opt`, which is the x86 version bundled from the development machine.

To solve this, we could manually manage dependencies via individual `package.json` files in each function (eughzz), or alternatively we need a way to tell Architect to ignore a dependency within the function.

I'm proposing adding `ignoredDependencies` to `config.arc` inside a function, with the additional option inside `@arc` pragma:
```
@arc
ignoredDependencies
  better-sqlite3
```

**Comment by andybee** [comment]
I've made an attempt at implementing this, which takes place in the following PRs:

https://github.com/architect/inventory/pull/66
https://github.com/architect/hydrate/pull/179

**Comment by andybee** [comment]
Further thinking, I wonder if this would be handy to be available at root level or function level? e.g. in my particular case, I can identify the dependency that is problematic application wide. I did consider this whilst preparing the pull requests, but I couldn't find a suitable pragma to locate it in at root level (and introducing a new one felt a bit extreme).

**Comment by ryanblock** [comment]
Sorry for the lag in replying here! I think your hunch on implementation was spot-on – imo this is probably best as function-level configuration for now. We can always change that later if necessary, of course!

**Comment by ryanblock** [comment]
Sorry for the premature close – although this should be released today. @andybee can you please kick up a docs PR for arc.codes?

**Comment by ryanblock** [comment]
Shipped in 10.15!
