### ISSUE TITLE
Invoked Lambda function during plugin `sandbox.start` cannot read user-defined environment variables

### ISSUE THREAD

**Issue by andybee** [architect/architect#1459]
I'm invoking a custom lambda created by a plugin, within the plugin's `sandbox.start` call. This Lambda function provisions some resources. In production it's called as part of a custom resource in CloudFormation, but in local dev I call it via the plugin startup. However, when run via Sandbox, it's unable to read custom environment variables I've set via `arc env` (presumably because of the stage within startup it's called?)

Architect 10.14.1
Node 18.18.2
OS: macOS Monterey 12.6.9

**Comment by ryanblock** [comment]
Hmm, I'm unable to replicate this issue using both `.env` and `prefs.arc`. I used the following plugin and handler code, invoked with `@architect/plugin-lambda-invoker`; each time it printed both the Lambda/Sandbox system env vars, as well as the env vars found in `.env` or `prefs.arc`.

```js
module.exports = {
  set: {
    customLambdas: () => ({
      name: 'custom',
      src: 'src/custom-lambda/'
    })
  }
}
```
```js
// src/custom/lambda.js
exports.handler = async event => {
  let env = Object.keys(process.env).sort().reduce((a,b) => {
    a[b] = process.env[b]
    return a
  }, {})
  console.log(env)
}
```

**Comment by ryanblock** [comment]
@andybee are you still experiencing this issue?

**Comment by andybee** [comment]
@ryanblock Apologies, I'm struggling to find the specific project where I previously had this problem, so I tried it with a clean setup and failed to replicate it. I'll close this now.

But... I did find [another one](https://github.com/architect/architect/issues/1478) whilst trying to replicate.
