### ISSUE TITLE
Enable Server-Timing headers or detect and warn 

### ISSUE THREAD

**Issue by kristoferjoseph** [architect/architect#1461]
If a users tries to use a server timing header and it is not enabled then a 500 error is returned with information as to why. 

Can we either enable server timing headers or warn if they are being used but not enabled in their account?

**Comment by macdonst** [comment]
Minimal reproduction use case is up at https://github.com/macdonst/server-timings. If you deploy that with architect and hit the /headers route you will get the 500 error.

**Comment by macdonst** [comment]
The code was trying to set a header to an array. Using `join` to turn it into a string resolves the issue.
