### ISSUE TITLE
@architect/sandbox unit tests fail and hang on macOS

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1463]
**Describe the issue**
The tests fail and hang on macOS with the output here: https://gist.github.com/lpsinger/d445f68c95614d6c747aa41bc5921d55

**Steps to reproduce**
Clone architect/sandbox, run `npm install`, run `npm run coverage`.

**Expected behavior**
Tests should pass.

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS Ventura 13.6.1 (22G313)
 - Browser N/A
 - Version https://github.com/architect/sandbox/tree/88a6604c52f025510564895d4c93485161932ff9

**Comment by ryanblock** [comment]
Hmm. Can you ensure when running Sandbox's test suite that all other instances of Sandbox have been terminated?

**Comment by lpsinger** [comment]
Yes, they have.

**Comment by ryanblock** [comment]
Ok, what are the steps to reproduce these errors?

**Comment by lpsinger** [comment]
See "Steps to reproduce" above.

**Comment by ryanblock** [comment]
Please see: https://github.com/architect/architect/actions runs, which includes your steps, yet does not reproduce there or for me:
- https://github.com/architect/sandbox/blob/main/package.json#L7
- https://github.com/architect/sandbox/blob/main/.github/workflows/build.yml#L63-L66

The issue appears to be isolated to your machine, please let me know if you can determine further steps to reproduce!

**Comment by ryanblock** [comment]
I'm going to close this for now, lots of macOS builds still being run against Sandbox! Please do reopen if we can figure out how to isolate the issue.
