### ISSUE TITLE
`@static` asset route gets superseded by two-parameter HTTP route

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1467]
**Describe the issue**
If your arc app contains both a two-parameter HTTP GET route, e.g.:

```
@http
GET /:first/:second
```

.. _and_:

```
@static
```

Then you will not be able to load static assets once deployed to AWS. Sandbox works fine though!

I believe this is because of the way [API Gateway prioritizes route resolution when it comes to routing a request](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html#http-api-develop-routes.evaluation). In particular:

> After selecting a stage, API Gateway selects a route. API Gateway selects the route with the most-specific match, using the following priorities:
> 
> 1.    Full match for a route and method.
> 2.    Match for a route and method with a greedy path variable ({proxy+}).
> 3.    The $default route.

Given the above, I believe the double-parameterized HTTP route takes precedence (qualifies as (1)) over the static route (qualifies as (2) due to the presence of `{proxy+}`).

**Steps to reproduce**
1. Clone https://github.com/filmaj/arc-static-repro-case
2. `cd` into it and `npm i`
3. run `npx arc sandbox`. Sandbox works great! Load http://localhost:3333 and see a funny gif of a friend of mine double-fisting beers. You can even try loading http://localhost:3333/oompa/loompa and that page works great as well.
4. now deploy to AWS: `npx arc deploy`
5. load the APIG URL that `arc` spits out
6. Sadly, while the index route loads, you can see the image asset link is broken. Looking at the network tab, you can see that while the image asset URL returns an HTTP 200, the response is actually HTML, not image data, and it is the response associated to the double-parameterized HTTP route.

<img width="1341" alt="Screenshot 2023-11-27 at 18 54 50" src="https://github.com/architect/architect/assets/52645/6323cdf7-1837-4ebd-bba2-6c67222ba586">

**Expected behavior**
The image asset on the index route loads in both sandbox and when deployed.

**Comment by filmaj** [comment]
Awesome! That indeed does fix the issue in my repro project. Cool, I will use that as a workaround. Thanks a lot friend 😄 

Love the idea of a warning. At which point during development should that be raised? Just like, always flagged when it is detected in the .arc file - every command?

**Comment by ryanblock** [comment]
Reinstalling Arc (ensuring Inventory v3.6.4 is present) should resolve the Sandbox routing issue.

As for the warning: I wonder if perhaps during the banner print we should have a routine to present any potential project issues based on analysis of the current inventory object. I'm not sure what other issues might be though?
