### ISSUE TITLE
Installing binary packages on x86 and deploying to arm64

### ISSUE THREAD

**Issue by clovis1122** [architect/architect#1470]
**Is your feature request related to a problem? Please describe.**
I've been targeting arm64 for a while until I needed a binary package (sharp).

**Describe the solution you'd like**
I was under the impression that arc would install dependencies and build the code on the right architecture automatically (or at least warn if not possible). Would be great to have more guidance / more docs regarding arc + multi-platform.

**Describe alternatives you've considered**
Tried a few hacks such as `npm ci --cpu arm64 --force` but couldn't get it to work and I didn't like the direction that approach was taking.

**Comment by ryanblock** [comment]
> I was under the impression that arc would install dependencies and build the code on the right architecture automatically (or at least warn if not possible).

That seems reasonable to assume, but the reality is this is an npm problem, fundamentally – Architect has no way of knowing what dependencies have native binaries. 

I wasn't aware npm finally added a `--cpu` flag, which it looks like is [pretty recent](https://github.com/npm/cli/pull/6755). That's great, and probably worth using! I'm wondering how you attempted to use that hack, and why it didn't work?

It looks like that feature ships in npm 10.1, which should be available to Node.js 20 + 18 users. We do need to support Node 16 still (which runs npm 8) so we'd have to make that an optional enhancement based on the version of npm being run. Should be achievable, though.

**Comment by ryanblock** [comment]
Patched here: https://github.com/architect/hydrate/pull/185/commits/41783b8c3fa8d3a085d4f11e5f7e0f17a28896ab
