### ISSUE TITLE
Node.js 20.x as the default runtime

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1472]
Related to the transition to `aws-lite` (https://github.com/architect/architect/issues/1471), there is no longer any compelling reason to not make `nodejs20.x` the new default runtime in Architect 11.

This will be easily migrated for folks who do still rely directly on AWS SDK v2 dependencies in their Lambdas by way of setting `@aws runtime nodejs16.x`, however this is a short-term fix as AWS will be deprecating Node.js 16.x in Lambda in a few months.

**Comment by ryanblock** [comment]
https://github.com/architect/lambda-runtimes/commit/a1ca1a78b646872e0a9122233b1f42b7cd875a30

**Comment by MartinRamm** [comment]
@ryanblock the default runtime in the typescript plugin should probably also be updated: https://github.com/architect/plugin-typescript/blob/main/src/index.js#L20

**Comment by ryanblock** [comment]
@MartinRamm yeah, will have to do a sweep of all plugins to make sure we don't have any potential runtime or architecture-related issues!

**Comment by ryanblock** [comment]
@MartinRamm updated the TypeScript plugin to 2.0!
