### ISSUE TITLE
AVIF / Jpeg2000 support in ASAP

### ISSUE THREAD

**Issue by jessehattabaugh** [architect/architect#1474]
After adding avif and jpeg2000 files to my site the files appear broken in a browser

I would like to serve AVIF and JPEG2000 images with architect

[issue reproduced here](https://github.com/jessehattabaugh/asap-avif-support)

**Comment by ryanblock** [comment]
https://media4.giphy.com/media/s239QJIh56sRW/giphy.gif

j/k, will make sure this works!

**Comment by ryanblock** [comment]
Patched in ASAP 6.0.6, thank you for your patience! Please reinstall your modules / update package-lock.json if necessary to see the changes.

**Comment by jessehattabaugh** [comment]
Oops.. I meant JPEGXL, not JPEG2000 😆

**Comment by jessehattabaugh** [comment]
It's only supported by Safari though, so I can't even test it 🤷🏻  https://caniuse.com/jpegxl
