### ISSUE TITLE
SignatureDoesNotMatch error while deploying Remix application

### ISSUE THREAD

**Issue by Omdaprog** [architect/architect#1486]
**Describe the issue**
A clear and concise description of the bug
while deploying a remix application using github runnners im getting "`SignatureDoesNotMatch`" error coming from "`@aws-lite/client: S3.PutObject`".
full error : 
<img width="1167" alt="image" src="https://github.com/architect/architect/assets/43305769/5a39c057-c434-45d1-8604-aaf7c10f97b0">

**Steps to reproduce**
install arc package 
`npm i -g @architect/architect`

my arc file like bellow :
`@app
remix-architect-app-github-action-1

@aws
profile certor
region us-east-1
timeout 120

@http
/*
  method any
  src server

@plugins
plugin-remix
  src plugin-remix.js
@static`

runn deploy command : 
`arc deploy --production --prune`

getting an error :
`× SignatureDoesNotMatch: @aws-lite/client: S3.PutObject: The request signature we calculated does not match the signature you provided. Check your key and signing method.
SignatureDoesNotMatch: 
    at errorHandler (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/@architect/architect/node_modules/@aws-lite/client/src/error.js:13:46)
    at Object.PutObject (/opt/hostedtoolcache/node/20.13.1/x64/lib/node_modules/@architect/architect/node_modules/@aws-lite/client/src/client-factory.js:187:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`
    
   as a result of this error, my application are unable to to find one of static chunk that suppose to be stored in s3 bucket 
   
<img width="1167" alt="image" src="https://github.com/architect/architect/assets/43305769/945cb991-ec9b-432d-a358-c37b3fe30dd4">

**Expected behavior**
deploy the application without getting no error and every chunk should be all found 

**Desktop**
Please complete the following information (if appropriate):

**Additional context**
when i deploy my application on my local terminal it works smothly and one monthe before, deploying application using github runners wasn't return that error.

**Comment by ryanblock** [comment]
Please try again with Architect v11.0.13.
