### ISSUE TITLE
`sandbox.start` ignores `profile` setting in `.arc` file

### ISSUE THREAD

**Issue by sjorsrijsdam** [architect/architect#1495]
**Describe the issue**
When ran from code (i.e. tests) the Architect sandbox does not use the `.arc` file to get a valid value profile to use for interacting with mocked services. Manually setting `process.env.AWS_PROFILE` is needed to make errors go away.

**Steps to reproduce**
1. Make sure there is no `default` profile in `.aws/credentials`.
2. Make sure `AWS_PROFILE` environment variable isn't set in any other way (e.g. via `.bashrc`).
3. Make sure the `profile` setting under the `@aws` pragma in the `.arc` file is set to a valid profile
4. Create a script (see below for example) that starts the sandbox and interacts with a mocked AWS service (e.g. DynamoDB).
5. Run the script
6. See error that says `TypeError: Profile not found: default`

**Expected behavior**
Expected behaviour is for the sandbox to pick up on the value for `profile` under the `@aws` pragma in the `.arc` file.

**Additional context**
Sample script

```js
import sandbox from '@architect/sandbox';
import arc from '@architect/functions';

(async function () {
    //process.env.AWS_PROFILE = 'some-profile-in-credentials-file';
    await sandbox.start({
        'quiet': true,
    });

    let { some_table } = await arc.tables();
    await some_table.put({
        'foo': 'bar',
    });

    await sandbox.end();
})();
```

**Comment by ryanblock** [comment]
Sandbox does not make any claims about transferring the configured `@aws profile` to the `AWS_PROFILE` env var, and probably it should not. We treat that as per-environment, opt-in config.

Automatically setting `AWS_PROFILE` based on the project `@aws profile` would likely introduce bugs and other side effects. For example, once deployed to Lambda, that env var would not align with a meaningful value, as that environment does not use configuration files for credentials.

**Comment by brianleroux** [comment]
I would have expected that to work? Sandbox isn't deploy but having a valid there should win. Ack a bad value could result in a bad deploy.
