### ISSUE TITLE
extendable .arc config (via .js file execution)

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#223]
The problem: I need to create A LOT of lambdas programmatically. Like hundreds and thousands! As one could imagine the `.arc` file might get a bit unwieldy…

```
@app
testapp

@queues
customer001
customer002
customer003
# ...aahh
customer999
 ```

I can think of three solutions. I'm not advocating for a solution here but rather thinking out loud and seeking your feedback.

### Solution 1 
Care not. Treat `.arc` as a static declarative file, generate the names in a script and otherwise *do nothing else* that in `.arc` file (the namespace could be common with a larger app but broken into other repos). that's an ok option but it turns the `.arc` into a write only file (which is maybe ok for this use case…). Essentailly this is 'a docs solution' as we're advocating a specific process pattern to solve rather than offering a technical solution.

### Solution 2 
Add variables to `.arc`. This is a neat idea and not new. In the issue about adding tags we're discussing adding variables for tags. A variable that does sequences like the problem above is more of a function. So now we're sort of entering Velocity Templates territory here. We'd have to either invent a syntax or borrow one from somewhere familiar/portable like mustache perhaps. Either way this solution is lots of both code and docs to write.

```
@app
testapp

@queues
$seq('customer', 999) 
```
Fun bikeshed to paint tho. 🚲 

### Solution 3 
Make `.arc` execute an interpreter pass to mutate itself before being parsed. Sort of a combination macro and templating. The idea would be to allow JavaScript to be embedded into the template with JS template strings and we'd hit that static file with an interpreter pass before passing thru the normal parse codepath. This would allow people to embed full programs in the `.arc` file which is both dangerous and awesome. 🔥 

In this example I'm imagining that we have helpers `seq` and `zeropad` in the runtime. The real JS to do that is …something. 

```
@app
testapp

@queues
${seq(999).map(zeropad).join('\n')}
```

The real JS to do the above without helper functions would be something like `${[...Array(5).keys()].map(i=> `free${i.padStart('0', 4)}` ).join('\n')}` which is just yikes. 

It def makes me pause when thinking about this solution. Bash in YAML was uncool. Not just because it was unreadable but error recovery can be time consuming and frustrating. We do not want to create situations where people can get themselves into trouble like that.

**Comment by joshgillies** [comment]
Personally I'm quite hesitant toward the whole idea of extending the syntax to be more programatic.

Have you considered the notion of using something along the lines of `arc.js` as a way to programatically create/extend an `.arc` file?

A fairly naive sketch of what I'm thinking of would be along the lines of:

```text
# .arc
@app
test-app

@http
/

@queues
# queues added programatically though arc.js
```

```js
const arc = require('@architect/architect')
const plan = arc.parse('.arc')

plan.queues.push(...[...Array(5).keys()].map(i=> `free${i.padStart('0', 4)}`))

return plan
```

Any `arc` commands eg. `npx create` will then look for either an `.arc` file or `arc.js` giving preference to `arc.js` when available.

**Comment by filmaj** [comment]
I like @joshgillies' idea. I like that the 'rules' of the file formats are then baked into the arc parser module.

Reminds me of how you can define eslint rules via a `.eslintrc.json` or `.eslintrc.js` file.

**Comment by joshgillies** [comment]
@filmaj yeah exactly inline with how config via `.eslintrc.json` or `.eslintrc.js` works.

Obviously for `arc` this idea would need to be a little more defined, but ideally it's similar in scope to other types of dynamic config.

If the ability to extend `.arc` in a way similar to the above was available you could potentially go even further by supporting asynchronous tasks that run to completion before your infrastructure is deployed. 

For example maybe in the context of creating dynamic `@queues` you could store created queues in some table which you query on every deploy? You'd even be able to have `production` vs. `testing` config if that's your jam?

```js
// arc.js
const arc = require('@architect/architect')
const plan = arc.parse('.arc')

module.exports = async function () {
  if (process.env.NODE_ENV !== 'testing') {
    const queues = await getQueuesFromDatabase()

    plan.queues.push(...queues)
  } else {
    plan.queues.push('testing-queue')
  }

  return plan
}
```

**Comment by brianleroux** [comment]
yeah I really like this! 

its a nice opt in, solves this problem case with precision and we can define a fun higher level api on top of the format pretty easily.

**Comment by joshgillies** [comment]
Yeah I think `arc.parse` would be a bridge between worlds, and totally optional. As long as the exported  `.js` config function returns `arc-parse` compatible output you're golden.

**Comment by brianleroux** [comment]
Ok! Back on my bullshit… I'm terrible at designing OO apis but think this is def an interesting sketch:

https://runkit.com/brianleroux/5d50cb9233c7c3001acf8df6

**Comment by brianleroux** [comment]
Alright closing this issue for the moment. Think we could return but if anyone is interested the sketch I did in Aug still works and we now have a complete macros implementation so this is very doable today.
