### ISSUE TITLE
Sandbox: publishing events/queues as last step of event lambda loses requests

### ISSUE THREAD

**Issue by grncdr** [architect/architect#228]
When the last step of a lambda handler is to publish an event, the event will often be lost.

### minimal reproduction

```js
exports.handler = arc.events.subscribe(function (evt, callback) {
  // do something
  arc.events.publish({name: 'another-event', payload: {}}, callback)
})
```

In the above example, the local sandbox request to send `'another-event'` will not complete before the handler finishes and the subprocess is killed.

### how to fix (maybe)

Make the sandbox version of publish wait for a response. (I've done this in my fork, but in case I abandon it I wanted to report the bug here).

**Comment by ryanblock** [comment]
Just checking back on this one: do we know if this is still reproducing? Thanks!

**Comment by brianleroux** [comment]
hey @grncdr sorry to take so long on this one and thx for reporting. 🙏  I tried creating a repo to reproduce here https://github.com/brianleroux/fix-228 but it seems to work ok (tmp deployed here: https://h8bb44nf0f.execute-api.us-east-1.amazonaws.com/staging/ )

going to close but feel free to reopen if you think I'm missing something!
