### ISSUE TITLE
Inconsistent representation of request path

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#245]
This took us a while to find in production because in our own uses of Architect as we never really keyed on `req.path`, but depending on the scenario, your representation of `req.path` will be different.

Specifically, if your URL has a parameter (`/go/:doSomething`) you'll see it something like the following values for `req.path` in the following scenarios:

Sandbox:
- Using `arc.http`: `path: /go/hiking`
- Using Arc 4 bare functions: `path: /go/hiking`
- Using arc.middleware: `path: /go/hiking`

Lambda:
- Using `arc.http`: `path: /go/hiking`
- Using Arc 4 bare functions: `path: /go/{doSomething}`
- Using arc.middleware: `path: /go/{doSomething}`

When passing the req through `arc-functions`, it automatically interpolates the param values for you (yay!), but if you're not passing the `req` object through the interpolate helper method (i.e. `arc.http.helpers.interpolate(req)`), any production code relying on `req.path` is at risk of being broken.

In the immediate term, we need to do a better job of documenting / promoting `arc.http.helpers.interpolate()` for this circumstance. Another possibility could be handling this at a lower level in API Gateway's VTLs, but there be dragons.

The thrust of this issue: how do you think we should handle this and make it better?

Reference:
`interpolate`:
- https://github.com/arc-repos/arc-functions/blob/master/src/http/index.js#L127
- https://github.com/arc-repos/arc-functions/blob/master/src/http/_interpolate-params.js

APIGW templates:
- https://github.com/arc-repos/architect/blob/master/src/create/aws/_create-route/_create-resource/_request.vtl#L3
- https://github.com/arc-repos/architect/blob/master/src/create/aws/_create-route/_create-resource/_request-form-post.vtl#L57

**Comment by ryanblock** [comment]
Unlikely I'm going to get to this soon, but would love an assist! May close this soon if we can't get it knocked out.

**Comment by brianleroux** [comment]
closing now that we're moving to aws_proxy this problem goes away
