### ISSUE TITLE
Feature request: use FreeDesktop format (used by a bunch of OSS apps) for .arc?

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#250]
**Describe the bug**
https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s03.html is the format used by Linux - it's basically a modified, enhanced version of `.ini` files. It's used by Linux `.service` files on all distros as well as KDE/GNOME `.desktop` files and a bunch of other apps. 

It has sections, comments, etc and there are parsers everywhere

## Why

- It's an existing format which looks familiar to more people
- We wouldn't have to write/maintain a parser like we do now for the current custom format`.arc`

**Comment by mikemaccana** [comment]
Also `.aws/credentials` uses a similar format. And it supports comments. 🙂

**Comment by mikemaccana** [comment]
> Based on this line I'm assuming you are proposing we wholesale move from the existing .arc to FreeDesktop

Yep. I.e. reduce the unique code base for arc itself by removing the custom format and use the existing familiar FDO/ini-style format. I'd probably also remove the JSON /YAML support too as a single config file format for your app is easier for a bunch of reasons I'm sure you understand - most people hate YAML, JSON lacks comments, JSONC is great but nobody knows about it and editors don't support it out of the box. 

**The vision is a single, easy too understand, familiar looking config file.**

Yes, that would mean making a converter for older .arc files that still uses the custom format and maintaining that converter for a while.

**Comment by mikemaccana** [comment]
>  Indeed I contemplated INI, TOML and others…in all cases I found major issues that left me wanting something terse, easy to learn, and quick to author without needing to consult reference material.

Main thing here is: someone else has already done that. And using their format would require authors to know less reference material than `.arc`. does.

I don't want to add more formats as my ideal amount of config files for a single app is 0, followed by 1, followed by anything more! 😉 I understand you lean more on the side of having authors use whatever format they know and like best, and I can see the advantages of that, although I don't agree with it.

If that doesn't change your mind, cool -  let's not waste time discussing this.

**Comment by ryanblock** [comment]
I'd like to reopen for discussion – I'd propose we add support additively.

We currently ask people to run locally with a `.arc-env` file that is unusable by very common tools like [dotenv](https://www.npmjs.com/package/dotenv) (7mm d/l week). 

It's another (seemingly proprietary) thing to explain and document.

Having potentially two env formats side by side has been, for me, problematic; it's bitten me numerous times in personal Arc projects, where my local `.env` (used for testing individual files, scripts, etc.) was out of sync with my `.arc-env`, etc.

The ability to tell people to just create a `.env` file the likes of which closely resembles AWS's config env feels like it could be is a much lower bar, and improve interop.

Proposed format:
```
[testing]
foo=bar
bar=baz
baz=buz

[staging]
foo=bar
bar=baz
# baz=buz commented out
```

**Comment by brianleroux** [comment]
into it! can we make a new issue for this? `.arc-env` &rarr; `.env` ini files is a bit different than the `.arc` &rarr; `$X`

**Comment by ryanblock** [comment]
Wfm!
