### ISSUE TITLE
🐛 Environment variables not added to newly created functions

### ISSUE THREAD

**Issue by alexdilley** [architect/architect#288]
**Describe the bug**
Provisioned environment variables not added to newly `create`d functions.

**To Reproduce**
1. Follow base install [instructions](https://arc.codes/quickstart/install), including running `npx create`. After deployment add an environment variable:
```sh
npx env staging SESSION_SECRET `head -c20 /dev/urandom | base64`
```
2. Check the function in AWS console to confirm that the variable has been made available to the `get-index` Lambda.
3. Add a new route to the `.arc` file (e.g. `get /things`). Issue `npx create`.
4. Note in AWS console that `SESSION_SECRET` is not set on the `get-things` function.

**Additional context**
Running `npx env verify` will synchronize env vars with newly created functions but (a) this can be missed and (b) functions are at least momentarily absent of provisioned variables.

Aside: note that `SESSION_TABLE` is added (but subsequently removed after environments are correctly synced).

`v5.0.7`

**Comment by ryanblock** [comment]
Got bit by this again this week, so I'm just bumping this issue (probably for myself, heh).

**Comment by ryanblock** [comment]
Just writing another reminder (to myself mainly) about having gotten bitten by this bug again. Need to find some time for this.

**Comment by brianleroux** [comment]
Fixed in architect 6 which is in RC now. You can kick the tires following this: https://gist.github.com/brianleroux/63983d51be7cb053e6463eb07cf480e2

New WIP docs: https://arc.begin.com
