### ISSUE TITLE
Per-function role with .arc-config

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#294]
Similar to #181, we need to be able to define per-function IAM roles in .arc-config.

**Comment by ryanblock** [comment]
Possible dupe of https://github.com/arc-repos/architect/issues/224? Closing for now, hasn't come up and we support this another way in [`roles.json`](https://arc.codes/guides/iam).

**Comment by rmuellerjr** [comment]
Did the "roles.json" file get dropped at some point? I'm unable to find the file and the link is broken.

**Comment by ryanblock** [comment]
Hmm, appears to me it may not have been reimplemented in Architect 6:
- https://github.com/architect/package/blob/master/src/visitors/http/index.js#L60-L62
- https://github.com/architect/package/blob/master/src/visitors/events/index.js#L32-L34
- etc...

@brianleroux ?

**Comment by brianleroux** [comment]
yes we deprecated in 5 because we felt having one way to go beyond the defaults is probably the easiest to reason about [`@macros`](https://arc.codes/primitives/macros) 

(open to reopening this and adding it again though on the ground that the IAM config should live alongside the function code it applies to)

**Comment by rmuellerjr** [comment]
Ok -thanks. Trying to get some things tested. +1 for using a role (and advice on how to set)

**Comment by rmuellerjr** [comment]
Ok - thanks. +1 for interest in setting a role in the .arc file

**Comment by brianleroux** [comment]
Whipped up a quick macro to demo how you can tweak the CloudFormation to use SAM policies instead of the generated (least priv!) role. 

https://github.com/brianleroux/arc-example-macro-sam-policies
