### ISSUE TITLE
Enable HTTP keep-alive on Lambdae by default

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#302]
Neat optimization via the one and only @theburningmonk that we would be wise to implement into Architect: https://theburningmonk.com/2019/02/lambda-optimization-tip-enable-http-keep-alive/

tl;dr set `keepAlive: true` in AWS SDK to help recycle HTTP connections and massively reduce latency, especially under load.

**Comment by brianleroux** [comment]
Here https://github.com/arc-repos/arc-functions/blob/master/src/http/session/providers/ddb/_get-dynamo-doc-instance.js

Here

https://github.com/arc-repos/arc-data/blob/master/src/db.js

And here

https://github.com/arc-repos/arc-data/blob/master/src/doc.js

**Comment by brianleroux** [comment]
update: enabled in `architect/data` 3.x
