### ISSUE TITLE
Arc 5.5 breaks arc-example-ws, which stays on 'Loading...' on arc 5.5

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#312]
**Describe the bug**
Using Architect 5.0 https://github.com/arc-repos/arc-example-ws works fine
Using Architect 5.5 it fails., staying in 'Loading...' state forever.

![image](https://user-images.githubusercontent.com/172594/53189053-8de3e980-35fe-11e9-9b53-7cb75a427058.png)

**To Reproduce**
1. Clone https://github.com/arc-repos/arc-example-ws
2. `npm install @architect/architect@latest`

**Expected behavior**
The demo still works.

Windows 10.0.17763.0, Arc 5.0.6 works, Arc 5.5.4 fails.

**Comment by ryanblock** [comment]
Can you confirm whether this was fixed in `5.6.2`?

**Comment by mikemaccana** [comment]
arc-example-ws currently failing with a different error `index.mjs: Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.` working on that now

**Comment by mikemaccana** [comment]
OK fixed, yet confirmed good, I'll fix the index.mjs error elsewhere and also update everything so `arc-example-ws` works out of the box.

**Comment by mikemaccana** [comment]
Blocked on #27

**Comment by ryanblock** [comment]
Not sure I understand, @mikemaccana can you elaborate?

**Comment by mikemaccana** [comment]
@ryanblock See https://github.com/arc-repos/arc-functions/issues/27

**Comment by mikemaccana** [comment]
(I need to load a static asset, the docs at https://arc.codes/guides/static-assets are outdated, I'm not sure what the migration path is)

**Comment by ryanblock** [comment]
I have it on my list to get in there and fix that area up, is what's already in arc-repos/arc-functions#27 the issue at hand, or are there additional repro steps based on what you're experiencing right now?

**Comment by mikemaccana** [comment]
That's the only outstanding issue. If I hack static (so it works on sandbox but not anywhere else) the demo works again
