### ISSUE TITLE
Deploy to LocalStack?

### ISSUE THREAD

**Issue by alexbepple** [architect/architect#319]
I stumbled upon LocalStack today. https://localstack.cloud/
While the Architect sandbox is awesome, this might be an interesting enhancement for the more integrative aspects, e.g. building and deployment, but also `role.json`.

Of course, this presumes that LocalStack emulates the AWS environment sufficiently well. Unfortunately I cannot speak to that.

Do you find LocalStack an interesting deployment target?

**Comment by brianleroux** [comment]
Could be interesting. I think our sandbox is easier and faster (tho certainly less comprehensive).

**Comment by brianleroux** [comment]
closing for now / architect 6.x is fully AWS SAM compatible so in theory so is that branch of Architect
