### ISSUE TITLE
Suggestion: configure all ports required by sandbox

### ISSUE THREAD

**Issue by alexbepple** [architect/architect#320]
While the port for the HTTP server of the sandbox is configurable, the ports for the local event bus and the local database are hard-coded.

I find it desirable for them to be configurable as well. Prime use case: run automatic tests that use sandbox while the sandbox for manual testing remains open.

**Comment by ryanblock** [comment]
I like it. HTTP is configurable (but not really documented) via `PORT`, perhaps prefix `EVENTS_PORT`, etc. Please feel free to PR.
