### ISSUE TITLE
audit apply swallows errors in certain conditions

### ISSUE THREAD

**Issue by mikeal** [architect/architect#322]
I had put a policy ARN in one of my `role.json` files that didn’t actually exist (cause it’s totally intiutive that AWS managed policies sometimes have `/service-role/` in them and somethings they don’t, ugh) and `npm audit apply` would just exit without completing, no error would be displayed.

I started to throw debugging statements throughout the control flow and finally saw the error being passed to one of the callbacks noting that the policy didn’t exist. That was enough to fix my issue by changing my `role.json` file and I didn’t have time to hunt down exactly where the error is getting swallowed. It’s pretty clear that whatever bug in the control flow that is swallowing the error also never passes anything along to the next callback because the process exits cleanly in the first function where this bug exists.

**Comment by brianleroux** [comment]
command deprecated / architect 6.x generates an IAM using Cloudformation now. kick the tires here: https://gist.github.com/brianleroux/63983d51be7cb053e6463eb07cf480e2

new docs (should be out next week!) https://arc.begin.com
