### ISSUE TITLE
Changing the rate on a schedule does not change the CloudWatch Event

### ISSUE THREAD

**Issue by gerred** [architect/architect#326]
**Describe the bug**
After creating a scheduled function in the .arc file, given the same name with a different rate, the schedule is neither updated in AWS nor does it throw an error.

**To Reproduce**
1. Create a scheduled lambda with any given rate.
2. Create the resource with `npx create`
3. Update the rate
4. Run `npx create` again

**Expected behavior**
Either an error describing the issue (remove and remake) or the CloudWatch event to be updated with the new schedule.

**Additional context**
Maybe an `npx update` is the best way to go here, or an explicit `npx taint/purge`? 🤷🏻‍♂️Obviously some resources/fields in AWS can't be changed on an existing resource.

**Comment by ryanblock** [comment]
Yuck, gross. Should prob look at fixing this along with https://github.com/arc-repos/architect/issues/148 while we're in `@scheduled` functions.
