### ISSUE TITLE
src/views not hydrating on individual Lambda deployments

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#331]
**Describe the bug**
`src/views` shared code dir not hydrating during individual Lambda deployments

**To Reproduce**
1. Have a populated `src/views` dir
2. Deploy a single lambda
3. Everything will be hydrated properly except `src/views`

The same is not true for full deploys, so it's probably something dumb I did.

**Comment by brianleroux** [comment]
fixed in 6.x
