### ISSUE TITLE
Better error presentation when running npx create without valid credentials

### ISSUE THREAD

**Issue by jonathanstiansen** [architect/architect#339]
**Describe the bug**
When following the normal instructions for getting started, if you don't have a region or profile `arc` doesn't create all, or any local http files.

**To Reproduce**
From here: https://arc.codes/quickstart/install

```
mkdir testapp
cd testapp
npm init --yes
npm install @architect/architect
touch .arc
echo "@app
test

@html
get /
get /test1
get /test2" > .arc
npx create
```

Then I get:

```
test-arc master % npx create                             
        app ⌁ test
     region ⌁ us-west-2
    profile ⌁ xxx                
    version ⌁ 5.5.10                
                          
{ InvalidClientTokenId: The security token included in the request is invalid.
..
```

**Expected behavior**
I expect `src/` dir and the respective functions to be created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS

**Additional context**
N/A

**Comment by ryanblock** [comment]
Hmm, fair! We do have `npx create --local`, perhaps that should be called out. Want to open a PR in arc.codes repo? https://github.com/arc-repos/arc.codes

**Comment by jonathanstiansen** [comment]
@ryanblock you bet, but do you expect the workflow to completely fail when this happens? If so you can close this but otherwise, I think it's worth keeping open.

**Comment by ryanblock** [comment]
Yeah, I think so? Error message is kind of crappy, but if in that moment you expected Architect to create you some infra, and it can't because you haven't supplied creds, then it is definitely going to fail.

**Comment by ryanblock** [comment]
(Oh one other thing, `@html` pragma is no longer supported, be sure to use `@http`!)

**Comment by jonathanstiansen** [comment]
I honestly didn't even notice - probably best to not let anything run if it fines `http` then, because I can speak from experience developers make a lot of mistakes... ;-)
