### ISSUE TITLE
Verbose mode for create

### ISSUE THREAD

**Issue by roxeteer** [architect/architect#344]
Related to #343: It would be useful to see in detail what Architect is doing on AWS when running `npx create`. With a single `@http` endpoint it runs over 2 minutes and there's not very much information on what it's doing. If the process fails constantly like it did for me, it would be good to see if it always fails at the same point.

**Comment by brianleroux** [comment]
err, just reading this and it sounds like you have a bug? can you explain 'failing constantly' for me with steps to reproduce? this description isn't helpful.

**Comment by roxeteer** [comment]
It was the issue I referenced to, #343, in which deploying my Lambda failed probably because of a problem on the AWS side.

**Comment by brianleroux** [comment]
that issue didn't provide any steps to reproduce either. creating an endpoint `eu-north-1` is working fine for me following our standard hello world quickstart. you did see rate limit errors at least which is things working as expected (not failing silently). just a suggestion 'things failing constantly' isn't helpful for us to help you faster in the future.

**Comment by brianleroux** [comment]
ftr: I'm still super into adding `-v` flag to create for those interested in all the details. we def do a lot of work in create and have a tonne of rate limiting/retry code so it can run (ideally) to completion without error or, if there is an error, you WILL see it. (so I'll leave this open)

**Comment by roxeteer** [comment]
I understand I didn't provide any steps to reproduce the issue but that's because I didn't have any further information. This is why I proposed a verbose mode. My thinking was that extensive output could've helped me to investigate the issue on my own or could've produced enough details to give you and AWS support the steps to reproduce the error.

**Comment by brianleroux** [comment]
verbose added in architect 6.x! (hoping to release 🔜 )
