### ISSUE TITLE
Code sample for arc.proxy.read is incorrect

### ISSUE THREAD

**Issue by crtr0** [architect/architect#367]
The code sample here:

https://github.com/arc-repos/arc-example-proxy-plugins/blob/master/src/shared/ssr.js#L4

Does not match the current signature for `arc.proxy.read`:

https://github.com/arc-repos/arc-functions/blob/master/src/proxy/read.js#L24

**Comment by joshgillies** [comment]
You're right, seems as though the call signature was changed with: https://github.com/arc-repos/arc-functions/commit/ff8dbf436b276c1472b2ac2d8bce027cf20b05e7#diff-d2fc112ea6c716834fbfb60b2074410eR22

I guess the example from https://github.com/arc-repos/arc-example-proxy-plugins/blob/master/src/shared/ssr.js#L4 would actually be:

```diff
let arc = require('@architect/functions')

module.exports = async function ssr(req, config) {
-  let {headers, body} = await arc.proxy.read('index.html', config)
+  let {headers, body} = await arc.proxy.read({ Key: 'index.html', config })
  let ts = new Date(Date.now()).toISOString()
  body = body.replace('</body>', `<code>shared rendered ${ts}</code><br></body>`)
  return {headers, body} 
}
```

**Comment by brianleroux** [comment]
closing / dup of #368
