### ISSUE TITLE
Audit S3 path usage and fix prior to breaking changes in 2020

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#375]
Per this thread, AWS is making a breaking change to S3 path usage: https://forums.aws.amazon.com/ann.jspa?annID=6776

tl;dr, bucket name as part of the path (eg `//s3.amazonaws.com/<bucketname>/key`) will no longer be supported.

Although we have until September 2020 to make this fix, we should begin the process of ensuring that Architect, Functions, etc. aren't impacted.

**Comment by brianleroux** [comment]
Per the linked thread the change is delayed indefinitely. So we should be ok as long as we're mindful of this moving forward.
