### ISSUE TITLE
RFC: Static asset fingerprinting, CDN roadmap

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#379]
Working on a new, much requested feature: static asset fingerprinting. Would love your feedback! Let's dive right in.

# Fingerprinting

- Assumption: userland static filenames should not be changed; i.e. if you create `public/main.mjs`, that file will always be there, named that, in my repo; tl;dr we aren't going to rewrite your repo's asset names each time we fingerprint
- Upon `deploy` + `deploy --static`, we will SHA fingerprint all files within `public/` (if present), upload those files with a fingerprinted filename (e.g. `foo-6f1ed002.jpg`) and write a hash table manifest at `public/static.json`
- More about `static.json`:
  - The hydrator will make this file available at `@architect/shared/static.json`
  - This file will not be uploaded (like `readme.md`)
  - Mixed feelings about whether we think this file should or should not be checked in, as there's potential for merge conflicts – but incorrect data in static.json would result in broken builds. Open to thoughts on this!
- Static assets would be accessed via a new helper method in Arc Functions (`arc.static('filename.ext')`), or by writing your own helper against the `static.json` file
  - Static helper always returns file paths out of `/_static`, introduced in Arc 5.5 (i.e. `<img src="/_static/filename.ext">`)
- Files uploaded with fingerprinting enabled will have very long-lived caching headers set in S3
  - Argument to be made that with fingerprinting enabled, the default behavior should now be `deploy static --delete` which removes files not found in `public/` from S3, and prevents the accumulation of many old versions of the same file
    - If so, that could in theory break people and may necessitate a major bump (which I'd prefer not to do); thoughts?

---

## Arc Functions helper example
```js
arc.static('blah/foo.jpg')
// returns /_static/blah/foo-6f1ed002.jpg

`<img src="${arc.static('blah/foo.jpg')}">`
// returns <img src="/_static/blah/foo-6f1ed002.jpg">
```

---

## `static.json` manifest example:
```json
{
  "blah/foo.js": "blah/foo-6f1ed002.jpg",
  "blah/bar.css": "blah/bar-014ebf09.css",
}
```

## Enabling fingerprinting
Assuming fingerprinting is disabled by default, we'd add a new `@static` option: `fingerprint`. This would upload files with fingerprinted filenames, and set aggressive caching headers on S3
```
@static
fingerprint true # Enables fingerprinting
```

---

### Roadmap around delivering static assets even more efficiently

- It's still coming together, but we have likely plans for Architect to switch to provisioning regional APIs (instead of the edge APIs it provisions today)
  - In this case, the `@dns` pragma would provision CloudFront distributions instead of APIG custom domain configs; internally, we've been referring to this configuration as an `API edge`
  - Why? Because an infra stack wherein API Gateway lives behind a proper CDN edge is functionally equivalent to what Architect provisions today, but adds edge caching for static assets, more fine-grained control of the edge configuration, and a greater capacity of APIs per region
- Additionally, we're considering hot-pathed static asset delivery via cdn (what we're calling `static edge`)
  - This would be a similar configuration to the `API edge`, but it would use your S3 bucket as origin instead of API Gateway
  - Not sure yet, but this would either be configuration addition to `@static` (like specifying `stagingCDN staging.foostatic.com`), or a new `@cdn` pragma
    - Thoughts on these approaches are welcome!

**Basic diagrams**

API edge - can be used to load any assets and content
```
CDN (CloudFront) <> API (Regional API Gateway) <> Multiple origins, based on path (Lambda, S3)
```

Static edge - only used for static assets
```
CDN (CloudFront) <> Single origin (S3)
```

**Comment by brianleroux** [comment]
lets make the pragma 

```
@static
fingerprint true|false
```

**Comment by ryanblock** [comment]
With a default of?

**Comment by brianleroux** [comment]
Idk! What would folks expect I wonder.

**Comment by ryanblock** [comment]
I think we should:
- Enable fingerprinting by default
- Present an info notice for ~1-2mo (or one minor bump, whichever is sooner) that fingerprinting is now enabled by default, and how to use it or turn it off (and how to delete the fingerprinted files it just uploaded)
- Also present a warning that in n months the default behavior with fingerprinting enabled will be to 

New `@static` pragma directives:

**Comment by ryanblock** [comment]
I think we should:
- Enable fingerprinting by default
- Present an info notice for ~1-2mo (or one minor bump, whichever is sooner) that fingerprinting is now enabled by default, and how to use it or turn it off (and how to delete the fingerprinted files it just uploaded)
- Also present a warning that in n months the default behavior with fingerprinting enabled will switch over to deleting files not found in `public/`
  - Add an override to this in the `@static` settings
- Also add an ignore list

Proposed `@static` pragma directives:
```
@static
staging staging-bucket
production production-bucket
fingerprinting [true | false] # defaults to true
deleteOrphans [true | false] # defaults to false for now, will change to true soon 
ignore # basic string match in file path of any strings below
  tar
  zip
```

**Comment by herschel666** [comment]
First of all: I very much like this feature!

I think it's necessary for a user to be able to turn it on/off, set the handling of orphan files and exclude certain files via the `.arc`-file. It might even make sense to enable users to rather **include** a certain set of files.

But what worries me is the fact that the `@static`-section gets a little messy. What does `ignore` refer to here: files, that ought to end up in the bucket, or ones that ought to be fingerprinted?!

On the other hand, when I think about a dedicated `@fingerprint` section, this feels a little quirky, too. The term is rather generic and lacks a reference to what is supposed to be fingerprinted and how's this done.

Since there are (afaik) non sub-sections, I guess option names have to become a little more verbose then.

**Comment by brianleroux** [comment]
Yeah I'd like to quell config too. Think we could shorten to all lowcase and avoid camel case w `fingerprint true|false` and `prune true|false` at least. (Keeps it more language neutral.)

**Comment by ryanblock** [comment]
Hmm, I don't think I want to add a new pragma for use with a feature of another pragma.

I'm not sure what scenario you'd want to fingerprint some files but not others, but we can always add an include list – I'm thinking let's get this out and hear that feedback. 

An alternative (or additive) idea I've been considering was adding the `ignore` list to the `public/static.json` file instead of (or in addition to) the .arc file. Thoughts there?

I like `prune`, way better than `deleteOrphans`!

**Comment by brianleroux** [comment]
`.arc` format allows overloading too so you could reuse it for an more granular config and get both use cases satisfied:

```
fingerprint
  /index.js false
  /assets/index.scss true
```

Wanna consolidate all config in `.arc` for sure (including proxy which arguably could be a new pragma).

**Comment by filmaj** [comment]
If my static resources reference other static resources (for example, a CSS/XML/JS file referencing an image),  - I would need to disable fingerprinting, correct?

**Comment by ryanblock** [comment]
Yes, or just ignore those files specifically, or output the callers dynamically based on the fingerprinted filenames, and do a second upload. You bring up a great point though, v open to other ideas!

**Comment by ryanblock** [comment]
Some updates after chatting with @brianleroux and @kristoferjoseph this morning:
- We've still got lots to learn about how best to build Arc apps with fingerprinting, so initially I'm going to release this as a beta in the main release
- As such, `fingerprint` will default to disabled, and be opt-in
- Also going to make sure `static.json` is uploaded to S3

**Comment by filmaj** [comment]
Great news on making it disabled by default and opt-in. I'd probably consider keeping that in until a major release, docs are in place, blog post describing it, etc.

**Comment by ryanblock** [comment]
Merged this evening. Still more work to do here, but it's a start!
