### ISSUE TITLE
get-index lambda invoked for 404s

### ISSUE THREAD

**Issue by sentience** [architect/architect#389]
**Describe the bug**
If I create my app with a `get /` lambda, then request a URL for which there is no endpoint defined, my `get-index` lambda will be invoked. In order to actually return 404 errors for non-existent resources (including static files!), I need to check the URL in my `get-index` implementation.

If I remove the `get /` from my `@app` block, but leave the `get-index` implementation in my codebase, it _still_ gets used for requests that don't match another endpoint URL!

**To Reproduce**
1. Create a new app with a `get /`
2. Launch the local server with `npx sandbox`
3. Visit http://localhost:3333/_static/does_not_exist.png
4. See the output of the get-index/index.js script.

**Expected behavior**
A 404 error page of some kind should be displayed.

**Comment by ryanblock** [comment]
This is the new default behavior, implemented to enable statically generated sites / SPAs to be read through from S3.

To implement 404s, simply key on `path` from within your `get /` function and respond with `404` from there (or forward the requester onto somewhere else).

**Comment by sentience** [comment]
Thanks! Is this documented somewhere? Maybe it should be covered in https://arc.codes/guides/http

**Comment by ryanblock** [comment]
Hmm, we did blog about it, but I don't know if that was properly documented. Def open to PRs there!
