### ISSUE TITLE
Static files with spaces in their names are not found

### ISSUE THREAD

**Issue by sentience** [architect/architect#390]
In arc 3.x, I had a file named **Slack RGB.svg** in my **.static** directory, and it was correctly served by `npx sandbox` when requested. Having just upgraded to arc 5.x, this file (now in **public**) is no longer being served; `npx sandbox` routes requests for it to my **get-index/index.js** endpoint instead (see #389)!

**Comment by ryanblock** [comment]
Hmm, shouldn't be the case, will look into it. Are you using `arc.http.helpers.static` / `arc.static`?

**Comment by sentience** [comment]
I'm using `arc.http.helpers.static("/")` to get the “root” URL for all static assets, and then I'm appending the URL-ified filename (`Slack%20RGB.svg`) to this. This worked in 3.x, but isn't working in 5.x.

**Comment by ryanblock** [comment]
Was able to replicate and have a fix, will ship that tomorrow!

**Comment by ryanblock** [comment]
Should be fixed as of `5.9.3`, please reopen if for some reason you're still having trouble!
