### ISSUE TITLE
Websockets crash sandbox in 5.8.0+

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#392]
**Describe the bug**

`options.cwd` in Arc 5.8 will be something like

`C:\Users\mikem\Code\appless\src\ws\ws-$connect`

Note the extra random $. Whereas in 5.7 they're like

`C:\Users\mikem\Code\appless\src\ws\ws-connect`

This crashes invoking websockets with an ENOENT error.

**To Reproduce**

Install the websocket example on Windows. Run a websocket.

You can work around the error with this in `src/sandbox/http/spawn.js`:

```
  // HACK
  options.cwd = options.cwd.replace('$','')

  let child = spawn(command, args, options)
```

But I'm tracking down the cause now.

**Comment by mikemaccana** [comment]
OK so this comes from `src/sandbox/http/register-websocket.js:17`

`let $connect = cwd('ws-$connect')`

Why the $?

**Comment by mikemaccana** [comment]
Looks like it was added in https://github.com/architect/architect/commit/a694f5e1

It seems like confusion but I've asked just to double check.

**Comment by brianleroux** [comment]
_should_ be restored in + @architect/architect@5.9.16
