### ISSUE TITLE
small single purpose packages

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#395]
We are in the process of creating `architect/cli` which lead to the conclusion we want to reuse packages from the 'kitchen sink' of `architect/architect`. This issue captures that progress.

The packages should have tests. Ideally CI. Bonus if coverage is setup. Every package should be a module (not a cli tool) for max reuse. Some of this done for some of these!

- [x] `architect/parser`
- [x] `architect/sandbox`
- [x] `architect/hydrate`
- [x] `architect/env` (extract from `architect/cli`)
- [x] `architect/utils`
- [x] `architect/repl` (extract from `architect/cli`)
- [x] `architect/logs` (extract from `architect/cli`)
- [x] `architect/package`
- [x] `architect/deploy` (extract from `architect/cli`)
- [x] extract https://github.com/architect/architect/tree/master/src/create/validate into `architect/utils` for reuse
- [x] once-over the cli package

**Comment by filmaj** [comment]
Alright some thoughts here, from IMO most important to least:

- first order of business is extract the code and have each sub-repo work properly on its own independent of other pieces. this would include porting any tests from the master repo relevant to the extracted repo and ensuring CI is rocking on that. may include a once-over of any relevant repo-specific docs (like README at least?)
- once all the repos are humming independently, we'll need to look at re-integrating the bits into the parent repo. which one would this be? `architect/cli`? `architect/architect`? 
- any interest in continuous deployment? i.e. on a merge to master, if tests pass on master, automation will tag the repo and publish to npm
- any interest in setting up greenkeeper on these repos?
- https://github.com/architect/arc-parser has a `name` of `@architect/parser`. should we make the repo name line up with the package name? seems like the other repos follow this convention too. so i suggesting renaming the repo `arc-parser` to just `parser`
- stretch goal: whatever the 'master' repo is, add a set of integration tests to it. slow, long tests that execute against an actual AWS account and we use non-arc methods to validate resources are created as we expect them to (HTTP requests, AWS CLI). though this probably would mean expecting to invest some amount of $$$ into AWS infra costs for the open source project. we could limit the scope of when this executes by preventing these tests from executing on PRs from forked repos (in case someone maliciously wants to open a billion PRs and run up the AWS bill).

Please gut check me on the above @brianleroux!

**Comment by brianleroux** [comment]
>  first order of business is extract the code and have each sub-repo work properly on its own ...

# 👍 

> once all the repos are humming independently, we'll need to look at re-integrating the bits into the parent repo. which one would this be? architect/cli? architect/architect?

both! we want to support local install of `architect/architect` (current best practice) and global install of `architect/cli` (the future default for quickstart)

> any interest in continuous deployment? i.e. on a merge to master, if tests pass on master, automation will tag the repo and publish to npm

I'm personally ok with the deployment remaining a human with 2FA setup problem but @ryanblock  has been exploring this so we can dual publish to npm and github (ryan pls chime in)

> any interest in setting up greenkeeper on these repos?

I'm into it

> https://github.com/architect/arc-parser has a name of @architect/parser. should we make the repo name line up with the package name? seems like the other repos follow this convention too. so i suggesting renaming the repo arc-parser to just parser

# 👍 

> stretch goal: whatever the 'master' repo is, add a set of integration tests to it

yep! def need to do this too

**Comment by filmaj** [comment]
If there's anything else to add just keep piling on in here!

**Comment by filmaj** [comment]
I think this is done!

**Comment by brianleroux** [comment]
fuck ya!
