### ISSUE TITLE
npx create throws PolicyLengthExceededException after running many times

### ISSUE THREAD

**Issue by jkarsrud** [architect/architect#399]
After running `npx create` for HTTP lambdas many times, AWS starts throwing `PolicyLengthExceededException`s because the API Gateway resource limit is reached (20kB/20480 bytes). This seems to happen because Arc adds new, unique api gateway lambda invoke permissions on every create. The culprit seems to be these lines;

https://github.com/architect/architect/blob/9f8ea93429083fe6048b29f1961fc7f17e8a17af/src/create/aws/create-http-route/create-route/02-setup-request.js#L99-L112

**Comment by brianleroux** [comment]
fixed in 6! try it here https://gist.github.com/brianleroux/63983d51be7cb053e6463eb07cf480e2

WIP docs: https://arc.begin.com
