### ISSUE TITLE
Deploy http.delete is deployed on patch

### ISSUE THREAD

**Issue by webselect** [architect/architect#401]
**Describe the bug**
When i deploy, my @http.delete is deploying on my @http.patch
So 2 of my function are bad.

> ∙●∙ Deploying src/http/delete-api-v1-segments-000SegmentId Installing dependencies in src/shared
> ✓ Success! Deployed 1 Lambdas in 2.171s
> 
> src/http/delete-api-v1-segments-000SegmentId ... lion-api-staging-patch-api-v1-segments ... 0.23 mb
>

**Comment by webselect** [comment]
Tested with 4.5.6 and 5.0.0 and 5.9.3 and still have the same issue.

**Comment by ryanblock** [comment]
Check to see if you did a copy/paste of the `package[-lock].json` files, the package names are keyed on during deploy.

**Comment by webselect** [comment]
It was exactly this.
Thanks

**Comment by ryanblock** [comment]
Great! (In future versions I believe we won't be doing that anymore.)
