### ISSUE TITLE
Standardize lambda name generation between create and deploy commands to use app name

### ISSUE THREAD

**Issue by ian** [architect/architect#403]
**Describe the bug**
There is a bug where a difference in app name and the name specified in a handler's package.json can create a bricked project deployment.  The deploy name seems to be generated from the package.json while the name used to create comes from app.  Deploys will fail since the lambda doesn't exist but creates will fail because the lambda exists.

The name should be generated as ${appName}-${stage}-${method}-${formattedPath}

**To Reproduce**
1. Create a new project named firstName
2. Add a route get /
3. Deploy to AWS
4. Change the app name to secondName
5. Deploy again

**Expected behavior**
it's expected that the name of the lambda function is always generated the same way

**Screenshots**

<img width="541" alt="59622878-64dcec80-90f8-11e9-90af-a1a07470cca9" src="https://user-images.githubusercontent.com/19853/59966801-fed0da80-94e6-11e9-9e93-f623981f43b4.png">

**Comment by ryanblock** [comment]
Will take a look, which version of Architect was this with?

**Comment by ian** [comment]
Sorry, I should have included:5.9.4  





On Mon, Jun 17, 2019 3:53 PM, Ryan Block notifications@github.com  wrote:
Will take a look, which version of Architect was this with?

**Comment by ian** [comment]
As a followup, the pubsub example will do the above.   A staging deploy is clearly deploying production, as seen in the screenshow.


<img width="541" alt="Screen Shot 2019-06-17 at 12 05 51 PM" src="https://user-images.githubusercontent.com/19853/59622878-64dcec80-90f8-11e9-90af-a1a07470cca9.png">

**Comment by ryanblock** [comment]
Hm, alright. For reference, which example project did you use with this?

**Comment by ian** [comment]
I'm really letting you down on the details, sorry.
It's arc-example-events-pubsub

**Comment by ryanblock** [comment]
All good! We need to add more questions to the bug template. :)

**Comment by ryanblock** [comment]
Following your steps to repro, I was unable to reproduce here:
![image](https://user-images.githubusercontent.com/200964/59635844-03704a00-9107-11e9-9372-6efff9153f87.png)
However, I found lots of other issues in that repo; creating it in Arc 4 and 5, neither worked. My sense is that this example needs to be taken offline until fixed up.

Out of curiosity, if you create a fresh project, are you seeing the same behavior?

**Comment by ian** [comment]
Let me try but I should say that I changed a few things and it's working now. 
Not sure which, but you know how that goes.
Also to note, I have a another project that is completely failing deploys but
without any indication.  It actually says that the lambda is updated (both
staging and prod) but the code and node_modules dir are still old files.  Not
sure if you've seen this before but it's what led me down this rabbit hole.
I am wondering if something is failing during deploy and it gives us a false
positive.  





On Mon, Jun 17, 2019 9:03 PM, Ryan Block notifications@github.com  wrote:
Following your steps to repro, I was unable to reproduce here:

However, I found lots of other issues in that repo; creating it in Arc 4 and 5,
neither worked. My sense is that this example needs to be taken offline until
fixed up.

Out of curiosity, if you create a fresh project, are you seeing the same
behavior?

**Comment by ian** [comment]
Closing this till I have a better example

**Comment by ryanblock** [comment]
Deploy is generally one of the most stable parts of Architect. But there are definitely a few subtle / non-obvious things one can do to make it go a bit haywire.

> Also to note, I have a another project that is completely failing deploys but without any indication.  It actually says that the lambda is updated (both staging and prod) but the code and node_modules dir are still old files.  Not sure if you've seen this before but it's what led me down this rabbit hole.

Haven't seen this before, are the credentials correct and consistent? Are the package file names all correct in the individual functions?

**Comment by ian** [comment]
Seeing this same behavior again.  The odd thing is that both staging and production lambdas report delpoyed after a `npx deploy staging` but the code isn't updating.  All output looks like the deploy is successful.

New code:

![Screen Shot 2019-06-19 at 10 25 21 PM](https://user-images.githubusercontent.com/19853/59816321-45ed7e80-92e1-11e9-81ad-117894bbaf9f.png)

What's up on AWS

![Screen Shot 2019-06-19 at 10 26 59 PM](https://user-images.githubusercontent.com/19853/59816352-61f12000-92e1-11e9-9718-3fdb2b68003b.png)

Both lambdas report being updated

![Screen Shot 2019-06-19 at 10 27 47 PM](https://user-images.githubusercontent.com/19853/59816385-7b926780-92e1-11e9-965e-0ea5fb45413a.png)

Deploy reports success

![Screen Shot 2019-06-19 at 10 28 20 PM](https://user-images.githubusercontent.com/19853/59816411-9e248080-92e1-11e9-98f3-c97dafe75e9a.png)

Something's not right here.  What additional information could be helpful?

**Comment by ian** [comment]
I figured out the problem after a lot of console.logs.  I changed the name of the project later but the a package.json still had the old `name` set.  I guess the lambda names are not dynamically generated, it uses the name from the package.json?  

This was failing silently and triggering a re-create, which I guess uses a dynamically generated name and they were misaligning.  

Not sure if/how you'd want to support this but just FYI

**Comment by ryanblock** [comment]
Makes sense. This is an issue we need to resolve. Can you re-title and re-scope this issue? The concern is: deploy/create is keyed on package.json names that are created from app names, and we need to sever that relationship.

Thanks!

**Comment by ian** [comment]
@ryanblock updated

**Comment by brianleroux** [comment]
no longer have a dep on package.json in architect 6.x

quickstart https://gist.github.com/brianleroux/63983d51be7cb053e6463eb07cf480e2

wip docs: https://arc.begin.com
