### ISSUE TITLE
Transpiling and/or bundling via plugin during deploy step

### ISSUE THREAD

**Issue by rschweizer** [architect/architect#405]
How would I go about transpiling and bundling my function code in Architect?

What I would like to achieve is to transpile arc functions written in TypeScript – and if possible also bundle – and deploy the resulting code instead of the source files.

So far, I have found https://github.com/architect/architect/issues/127 in which the `build` script is the recommended way to achieve something similar. I also looked into https://github.com/architect/arc-plugin-node-prune and https://github.com/austinkelleher/arc-plugin-marko, that both hook into `beforeDeploy` to alter some uploaded artifacts.

I was wondering, if it were possible to build a plugin to individually transpile and possibly bundle my arc functions prior to deployment without leaving produced artifacts in the directory structure. Latter could probably be easily achieved by just cleaning up afterwards. So, currently I am investigating into transpiling the code `beforeDeploy` and cleaning the artifacts out `afterDeploy` (<- does this hook exist?).

Is bundling even possible with the way Architect works and provides the `arc` helper functions? Any recommendations, thoughts or even ideas how to achieve the above? Any hints are greatly appreciated! 🍻

**Comment by brianleroux** [comment]
Hi @rschweizer ! We blindly upload code in `src/http/functionname` so you could make that a compile target before uploading. (eg `npm run build && npx deploy`)

`architect/functions` and `architect/data` are vanilla node modules so they should bundle but we have no opinions on how you achieve that (given there are literally dozens of ways to do it). 

in 6.x we will provide a happy path for doing this! I'll leave this open to remind myself to update you when that code lands.

**Comment by ryanblock** [comment]
Just a note: possibly going to add this as feature in 6.x (macros)

**Comment by rschweizer** [comment]
@ryanblock @brianleroux Let me know, if I can help!

**Comment by brianleroux** [comment]
demo macro! plan to write a blog to go with this… 🔜
 
https://github.com/brianleroux/arc-macro-src-folder

**Comment by brianleroux** [comment]
this is pretty extensively documented from a few perspectives now at https://blog.begin.com ❤️
