### ISSUE TITLE
Cannot connect to local database

### ISSUE THREAD

**Issue by ckingbailey** [architect/architect#409]
When running locally using `npx sandbox` I get "ResourceNotFoundException: Requested resource not found" for any attempt to connect to local database using @architect/data. The lower level functions `_name`, `_db`, and `_doc` do not throw this error, but `_doc` does not retrieve anything from the local database.

**To Reproduce**
.arc file:
```
@app
apidebug

@http
get /
get /emails

@tables
emails
  email *String
  name **String
```

On the command line do:
```
$ npm init -y
$ npm i @architect/architect
$ npx create`
```

src/http/get-emails:
```
const data = require('@architect/data')

exports.handler = async function http(req) {
  let msg
  try {
    console.log(data.emails)
    const emails = await data.emails.scan({})
    msg = JSON.stringify(emails)
  } catch (er) {
    console.error(er)
    msg = er
  }
  return {
    headers: {'content-type': 'text/html; charset=utf8'},
    body: `<h1>${msg}</h1>`
  }
}
```

Run (personal information replaced with "...")
```
npx sandbox
         app ⌁ apidebug
      region ⌁ us-west-2
     profile ⌁ ...
     version ⌁ Architect 5.9.18
         cwd ⌁ /.../api-debug

✓ Found Architect manifest, starting up
✓ Project files hydrated into functions
✓ @tables created in local database
✓ @events and @queues ready on local event bus
✓ Loaded routes:
    get / ................................. get-index
    get /emails ........................... get-emails

✓ Sandbox started in 308ms
✈︎ Local environment ready!

    http://localhost:3333
```

Visit localhost:3333/emails.
Error thrown and logged (local file structure replaced with "..." for my privacy):
```
{ ResourceNotFoundException: Requested resource not found
    at Request.extractError (/.../api-debug/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/.../api-debug/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/.../api-debug/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/.../api-debug/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/.../api-debug/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/.../api-debug/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /.../api-debug/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/.../api-debug/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/.../api-debug/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/.../api-debug/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Requested resource not found',
  code: 'ResourceNotFoundException',
  time: 2019-07-09T21:39:02.980Z,
  requestId: 'OI9SJFQ0T6GR3NVEG8FPAKTBO3VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 38.43783869002362 }
```

**Expected behavior**
When other developers in my org do the above, they get an empty array as response.

This is a pared down example from a larger project. Other developers at my company are running the project without issue. This and other projects built using Architect are deployed and in use by our company with no problems connecting to DynamoDB in production. This appears to be an issue only in local development. Others who have tried to reproduce this issue have had no luck.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser: Firefox 67 and Chrome 75
 - Node version 10.16.0
 - npm/npx version 6.9.0

**Some additional possibly salient data**
While sandbox is running, I do `lsof -i -nP` and see a couple of Node processes:
```
node      20540 ckingbailey   23u  IPv6 0x2d39e254f73070cf      0t0  TCP *:5000 (LISTEN)
node      20540 ckingbailey   27u  IPv6 0x2d39e254ee0a99cf      0t0  TCP *:3333 (LISTEN)
```

Visiting localhost:5000, I see:
```
healthy: dynamodb.us-east-1.amazonaws.com 
```

I also tried connecting to the database using Arc's _doc aws-sdk interface, like:
```
const data = require('@architect/data')

exports.handler = async function http(req) {
  const TableName = 'emails'
  let msg
  try {
    const emails = await data._doc.scan({ TableName })
    console.log(emails)
    msg = JSON.stringify(emails.body)
  } catch (er) {
    console.error(er)
    msg = er
  }
  return {
    headers: {'content-type': 'text/html; charset=utf8'},
    body: `<h1>${msg}</h1>`
  }
}
```

Without sharing the whole big ol' response, I believe the important bits are:
```
  operation: 'scan',
  params: { TableName: 'emails' },
  httpRequest:
   HttpRequest {
     method: 'POST',
     path: '/',
     headers: { 'User-Agent': 'aws-sdk-nodejs/2.490.0 darwin/v10.16.0' },
     body: '',
     endpoint:
      Endpoint {
        protocol: 'https:',
        host: 'dynamodb.us-west-2.amazonaws.com',
        port: 443,
        hostname: 'dynamodb.us-west-2.amazonaws.com',
        pathname: '/',
        path: '/',
        href: 'https://dynamodb.us-west-2.amazonaws.com/',
        constructor: [Function] },
     region: 'us-west-2',
     _userAgent: 'aws-sdk-nodejs/2.490.0 darwin/v10.16.0' },
```

and
```
  response:
   Response {
     request: [Circular],
     data: null,
     error: null,
     retryCount: 0,
     redirectCount: 0,
     httpResponse:
      HttpResponse {
        statusCode: undefined,
        headers: {},
        body: undefined,
        streaming: false,
        stream: null },
     maxRetries: 10,
     maxRedirects: 10,
     nextPage: [Function] },
```

I thought it notable that the request body appears to be empty, and the response is completely empty, lacking a status code or any headers.

**Comment by ryanblock** [comment]
Hmm, generally when you see the dreaded `ResourceNotFoundException: Requested resource not found` error, that means your local Architect function is trying to connect to a remote database it does not have access to. Are you kicking up `sandbox` with any env vars in use others may not be using? (Or vice versa, are your colleagues using `sandbox` with env vars that you aren't using?) Also, are other folks running a different version than you, by chance? (Just looking for vectors by which to isolate this issue.)

**Comment by ckingbailey** [comment]
A remote to which do not have access, ok, that is something I should look deeper into.
The one env var I use that others do not is `ARC_LOCAL=true`, but I've tried `put` and `scan` operations with and without that env var set and I get the same error either way.
Everyone is using a couple of env vars `AWS_PROFILE` and `AWS_REGION` to point to a profile containing their credentials. I suppose it's possible others have access to the cloud DynamoDB and I do not. I thought `sandbox` was running a local Dynamo-like instance. Is it possible I need permissions on the local instance?

**Comment by ryanblock** [comment]
Def do not need permissions for accessing locally.`ARC_LOCAL` is a bit black magic-y, one of the things is reset your local environment to operate in `testing`, but allow for a `NODE_ENV` of not-`testing`, which enables you to work locally while accessing remote databases. But if the credentials are not set and configured, it will fail to connect. So let's try removing `ARC_LOCAL` and see if that helps?

**Comment by ckingbailey** [comment]
That may have done it!
I did not know about the necessity of that feature. Sorry, I see now it's the docs, but I never got there coz others in my org are not using `npx env`. Their env vars seem to be getting picked up straight from `process.env`.
More testing happening now. I'll report back.
Thanks for your help on this.

**Comment by aaronhans** [comment]
Thanks so much @ryanblock! I work with Colin and we were pretty confused by this. Really appreciate your troubleshooting tip here.

Also the architect project in general is fantastic. I have been evangelizing it for awhile, love the increasing feature set and approachability.

Thank you!

**Comment by ryanblock** [comment]
Sweet! Sorry you got bit there, that flag was undocumented (but it shouldn't be!) – I wasn't aware many folks were attempting to use `ARC_LOCAL`, so will make sure in the next round of docs we include some info on that!
