### ISSUE TITLE
Architect 6 release + Arc 5 LTS: plans, feedback, & questions

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#410]
I'm really stoked to share that within the next couple of weeks we'll be releasing Architect 6, easily the largest set of improvements to Architect in its history. A few of the highlights:

- Provisioning and resource creation is now fully CloudFormation-based – this means AWS, not Architect, is responsible for generating your application's resources, providing (among other things):
  - Faster, more deterministic app resource creation in many cases (especially for large changes to application infrastructure)
  - Only the cloud resources that need to exist will exist (i.e. automatic resource pruning)
  - A significantly tighter security profile and true least privilege role policies
- Architect's core workflows are now broken out into far more maintainable independent modules (see: [Sandbox](https://github.com/architect/sandbox), [Hydrate](https://github.com/architect/hydrate), etc.)
- Architect Functions releases for [Ruby](https://github.com/architect/arc-functions-ruby) and [Python](https://github.com/architect/arc-functions-python)!
- New automatic service discovery layer
- Fully rewritten docs site ([arc.codes branch here](https://github.com/architect/arc.codes/tree/v4)), including a (forthcoming) migration / upgrade guide from 5-6

While the underlying Architect project structure and `.arc` format will not undergo any changes with this release, the cloud infrastructure provisioning changes made by Architect 6 may have a few potentially breaking changes (which are worth getting into soon and separately). But we hope that for most folks this will a drop-in replacement.

That said, due to the nature of these changes and our desire to **not** break folks, **we intend to place Architect 5 into LTS and continue its maintenance**. (More on that below!)

## A few questions we'd like your feedback on:

- Architect 6 has been in development in a separate repo at [`@architect/cli`](https://github.com/architect/cli), but this work will need to be mainlined back into [`@architect/architect`](https://github.com/architect/architect)
  - Insofar as you have a preference, would you prefer we move Architect 5 into a separate repo (i.e. `@architect/architect-5`, `@architect/legacy`, etc.?), or maintain it in a branch of the main repo (or do something else)?
  - Considerations of separate repos vs. branches include: issues, docs, etc.
  - In terms of NPM, Architect 6 will become `@architect/architect@latest`, while Architect 5, wherever it lives, will continue to be published as `@architect/architect@5.x`
- This is the first time we've put a version of Architect into LTS; how long do you feel we should commit to supporting LTS releases?
-  Arc 4.x was `Yeti`, Arc 5.x is `Catalope`, which cryptozoological animal shall we pick this time? (The only rule is no human-hybrids.) 👹

Of course, anything else you'd like to provide feedback on, or have us consider, we're all ears!

---

> Additional reference
> Arc 6 master issue https://github.com/architect/architect/issues/404
> arc.codes Arc 6 master issue: https://github.com/architect/arc.codes/issues/114
> arc.codes Arc 6 branch: https://github.com/architect/arc.codes/tree/v4

**Comment by alexdilley** [comment]
Was going to say `Unicorn` – arc 6 is full of promise! – but I'm not sure that's a cryptid. Hows about `Nessie`?

**Comment by brianleroux** [comment]
`ogopogo` is the famous lake monster cryptid in BC, Canada 

https://en.wikipedia.org/wiki/Ogopogo 

# 🐉

**Comment by joshgillies** [comment]
`yowie` commonly known as a chocolate treat with surprise toy inside, is also a cryptid similar to that of a Yeti in Australian folklore.

https://en.wikipedia.org/wiki/Yowie

**Comment by ryanblock** [comment]
These are some excellent cryptids.

Ok, to briefly turn the conversation to how we handle handle Arc 5 - 6 repo transition – before returning to cryptids, ofc – having given this more thought, I think Arc 5 should be transitioned into a new, separate repo.

More specifically:
- Take the current repo at `@architect/architect` and copy it, and all of its git history, to a new repo (for sake of conversation `github.com/architect/architect-5`, but open to names!)
  - Important: retain its git history!
- Overwrite `github.com/architect/architect` with the contents of `github.com/architect/cli`
  - Remove anything not present in `cli`, ofc
  - Ideally retain `cli`'s history, but not absolutely necessary imo
- Result:
 - `npm @architect/architect@5.x` is published from `github.com/architect/architect-5`
 - `npm @architect/architect@latest` is published from `github.com/architect/architect`
 - Binary dists compiled from `github.com/architect/architect`

Reasoning:
- Working in a long-lived branch sucks
- Minor, but this approach doesn't laden Arc's git history with additional work in an LTS branch that will never be merged back to master
- Eventually when we retire 5, it seems like a better choice to me to have an archived repo than a deleted branch (and all that work potentially gone forever)
- Related, a separate repo should be easier to use / refer to much later (if necessary)

Still completely amenable to other perspectives on this though!

**Comment by mikemaccana** [comment]
> Insofar as you have a preference, would you prefer we move Architect 5 into a separate repo (i.e. @architect/architect-5, @architect/legacy, etc.?), or maintain it in a branch of the main repo (or do something else)?

Branch please. Shared history, it seems like that's thee best way to compare code if we need to when migrating. Issues with 5 that aren't relevant to 6 should be closed.

> This is the first time we've put a version of Architect into LTS; how long do you feel we should commit to supporting LTS releases?

Depends on migration considerations for your biggest commercial customer.

> Arc 4.x was Yeti, Arc 5.x is Catalope, which cryptozoological animal shall we pick this time? (The only rule is no human-hybrids.) 👹

I got really confused and read this as saying cantaloupe melons were mythical. Chimera?

**Comment by mikemaccana** [comment]
**Suggested addition**: new release is good time to make an official architect Twitter account.

Eg, check out https://twitter.com/goserverless has 17K followers, https://twitter.com/zeithq nearly 30K.

**Comment by ryanblock** [comment]
Absolutely true. I think we didn't do this before because I couldn't find a decent name, so I moved onto other stuff – what shall it be? (Note: `@architect` is taken.) Would you like to help keep it up to date?

I'd prefer not to go with `@architectjs` or anything that put JS front and center, as that's an implementation detail, and 6 will make large strides in multi-runtime support.

Super open to other ideas! (Remember, it has to be 15 chars or less.)

**Comment by ryanblock** [comment]
Hey @kborchers! Did I hear correctly you created an Architect Twitter account back in the day?

**Comment by mikemaccana** [comment]
arcserverless is nice. 

 - architect is taken
 - architectserverless is too long
 - I think 'serverless' being included helps people who might use serverless.com / zeit / etc discover arc

**Comment by kborchers** [comment]
The account that currently exists is https://twitter.com/arc_fns

**Comment by mikemaccana** [comment]
Also if we want the Twitter account to be active, we can all retweet the Arc 6 announcement from it (a bunch of people retweeting the same thing at the same time gets the Twitter feed algo's attention)

Personally I'd 'rename `arc_fns` to `arcserverless` or `architectserverless`  (project name is architect, and it does more than just functions) and then start tweeting out all the new hotness.

**Comment by kborchers** [comment]
I agree that a name change would be good as the current name was chosen early in the project's life. I would probably choose `arcserverless` for brevity over `architectserverless` but I'd be fine with either. @ryanblock I'm happy to make changes if my login still works, but in any case we should get it changed and start using it.

**Comment by mikemaccana** [comment]
Yeah I think `arcserverless` is nicer too. We all call it arc for short anyway so 👍🏼

**Comment by ryanblock** [comment]
https://twitter.com/arcserverless
