### ISSUE TITLE
Adoption of OpenJS Foundation Code of Conduct

### ISSUE THREAD

**Issue by kborchers** [architect/architect#414]
As the OpenJSF CPC finalizes the project on-boarding process which existing and new projects will go through to ensure all projects follow appropriate foundation guidance, I am [working Architect through that process](https://github.com/openjs-foundation/cross-project-council/issues/270) and one of the checklist items is that the project adopt the [OpenJSF Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/master/CODE_OF_CONDUCT.md). In general, this currently means adopting the [Contributor Covenant v1.4.1](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md). There is an additional proposal being discussed for further CoC enforcement and escalation guidelines which you can view in [its current form](https://github.com/openjs-foundation/cross-project-council/blob/master/proposals/stage-1/CODE_OF_CONDUCT/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md) as a stage 1 proposal.

What I would like to discuss here is if you have any questions, concerns, or objections to this change of the CoC as adoption of the foundation CoC is an important requirement of the on-boarding process and once it is clear that this change is acceptable to the project, I would like to submit the appropriate PRs to accomplish that change and proceed with the on-boarding process.

**Comment by ryanblock** [comment]
For reference, our current CoC here: https://github.com/architect/architect/blob/master/.github/code_of_conduct.md (In this case, Begin community is intended to extend the Architect community.)

<3 CC and I'm not seeing any incompatibilities, but unless we're allowed to define and extend our own, I'd definitely appreciate additional escalation and enforcement guidelines. A toothless CoC isn't much of a CoC, imo, and active community management is something we're quite serious about!

**Comment by kborchers** [comment]
@ryanblock I definitely agree and once the additional guidelines and policies are finalized I will pass them along for review. Thanks!

**Comment by ryanblock** [comment]
FYI / update: for now I'm (manually) syncing all our repos' boilerplate out of here: https://github.com/architect/boilerplate/tree/master/.github

**Comment by defionscode** [comment]
This was a little tricky to find. I think the CoC might need to be manually added to the root of this repo?

**Comment by ryanblock** [comment]
For GitHub to pick it up and use it, CoCs have to have a special folder/name: https://github.com/architect/architect/blob/master/.github/code_of_conduct.md

Example:
![image](https://user-images.githubusercontent.com/200964/74269206-fd466380-4cbd-11ea-9cd8-1c712d7a23ab.png)
