### ISSUE TITLE
Weird issue with deploy

### ISSUE THREAD

**Issue by buffpojken** [architect/architect#415]
**Describe the bug**
When using the .arc-file below, and creating - everything get's properly created. However, when deploying, only the lambda ```phonetree-staging-post-message-000idx``` gets updated as evidenced by the screenshot below. The lambda ```phonetree-staging-post-start``` somehow gets confused and tries to update ```phonetree-staging-get-start``` as evidenced by the terminal screenshot below which is then labelled as "creating..." (since it doesn't exist).

This persists across both AWS regions (tested in eu-north-1 and eu-west-1) and across multiple ```npx inventory nuke``` and re-installs of architect.

**To Reproduce**
1. Use the attached .arc-file and arc@5.9.23 on node 10.15.3. 
2. Run ```npx create```
3. Change message in ```phonetree-staging-post-start```. 
4. Try to update via ```npx deploy```

**Expected behavior**
I expect ```phonetree-staging-post-start``` to update correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - arc@5.9.23

<img width="1111" alt="Screenshot 2019-07-31 at 18 00 55" src="https://user-images.githubusercontent.com/47125/62227984-2b68f380-b3bd-11e9-9e4c-caeeb2fe32fb.png">

.arc:
```
@aws
region eu-west-1
profile default

@app
phonetree

@http 
post /start
post /message/:idx

@tables
phonetree
  phone *String
  date **Number
```

AWS Console:
<img width="958" alt="Screenshot 2019-07-31 at 18 06 42" src="https://user-images.githubusercontent.com/47125/62228505-12147700-b3be-11e9-9f42-bbf262bcef3c.png">

**Comment by buffpojken** [comment]
Just to confirm that all is created properly, here's a screenshot of terminal output from running ```npx create```, a text change in function and ```npx deploy``` straight after one another.

<img width="692" alt="Screenshot 2019-07-31 at 18 45 28" src="https://user-images.githubusercontent.com/47125/62231052-84d42100-b3c3-11e9-801f-ac91f484b2dc.png">

**Comment by ryanblock** [comment]
This almost always happens when one copy/pastes a function dir and doesn't change the package[-lock].json `name` fields to match the new function name.

It's an obscure and infrequent bug that will be resolved in the next version of Architect! In the mean time, make sure the name fields correspond to the function name so they can be keyed directly during deploy.

**Comment by buffpojken** [comment]
That was indeed the case and worked perfectly once I updated the name in ```package-lock.json```. Many thanks for the quick pointer!

**Comment by ryanblock** [comment]
Sorry you got bit by that, it's an old wart that would be high level of effort to fix – not something one would ever expect to occur, but also infrequent. Should be gone in Arc 6 though!

**Comment by buffpojken** [comment]
No worries, the superquick reply cleared it up at once! Looking forward to taking Arc 6 for a spin!
