### ISSUE TITLE
arc init runtime support

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#428]
Architect now supports Ruby and Python but you need to set the `runtime` property in `.arc` or `.arc-config` to generate corresponding code. We should add support for the following invocation pattern:

- `arc init runtime ruby`
- `arc init runtime python`
- `arc init runtime node` (default)

**Comment by ryanblock** [comment]
Did you or someone patch this?

**Comment by brianleroux** [comment]
oh maybe its gone again! I def added it to the orig version of init
