### ISSUE TITLE
Reimplement `destroy` (infra / stack deletion; formerly called `nuke`)

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#430]
**Is your feature request related to a problem? Please describe.**
`npx inventory --nuke` no longer exists in Architect 6; it should be brought back to make it easier to destroy stacks.

**Describe the solution you'd like**
By default, a `destroy` command does not (and should not) touch data stores (`@tables` / DynamoDB, `@static` / S3); I'd propose additional flags would enable that. Examples:
- `npx arc destroy` - destroys infra
- `npx arc destroy --tables` - destroys infra & Dynamo tables
- `npx arc destroy --static` - destroys infra & S3 contents and buckets
- `npx arc destroy --tables --static` - destroys infra & Dynamo tables & S3 contents and buckets

**Describe alternatives you've considered**
Doing this manually in the AWS console – it's not good.

**Comment by ryanblock** [comment]
Note to update docs:
- https://arc.codes/guides/upgrade
- https://arc.codes/reference/cli/destroy (new)

**Comment by brianleroux** [comment]
check out github.com/architect/destroy ✨
