### ISSUE TITLE
Pass options to macros

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#433]
This might already be supported, but in case it isn't, it would be nice to pass in options to macros.  For example, I wrote a macro to give my lambda function permissions to another s3 bucket, but I'd like to be pass in the bucket and read/write access so it could be more reusable

**Comment by brianleroux** [comment]
You can add config to the `.arc` manifest file! 

```
@app
myapp

@macros
mymacro

@mything
key somevalue
```

```javascript
// mymacro.js
module.exports= function (arc, cfn, stage) {
console.log(arc.mything)
// logs [['key', 'somevalue']]
}
```

**Comment by jgallen23** [comment]
thanks, that'll work
