### ISSUE TITLE
CAPABILITY_AUTO_EXPAND

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#436]
I'm writing a macro that pulls in a serverless application, but when I try to run it I get:

```
Requires capabilities : [CAPABILITY_AUTO_EXPAND]
```

Here is my macro: https://github.com/firstandthird/arc-macro-lambda-slack

According to https://stackoverflow.com/questions/53543397/use-capability-auto-expand-for-nested-stacks-on-cloudformation, I need to pass CAPABILITY_AUTO_EXPAND when deploying.

What I'm doing is writing two macros, one to subscribe to all lambda logs and another to read logs and pass any errors on to slack.  It works perfectly if I have the slack lambda locally and owned by arc, but I'd like to be able to reference a shared resource so I don't have to include in my codebase.

**Comment by jgallen23** [comment]
as a workaround, I just include the serverless function and point to s3 bucket: https://github.com/firstandthird/arc-macro-lambda-slack/blob/master/index.js#L2

**Comment by brianleroux** [comment]
yesh, remember this… so we should be able to add that flag / just need to see what happens if we pass it without nested stacks (if you want to try just fork `@architect/deploy` and install it local/globally with `npm i -g .` and then you can trial changes by running `arc-deploy`)

**Comment by brianleroux** [comment]
just added to the latest architect/deploy cmd by default; thx for your patience!
