### ISSUE TITLE
Feature request: low pri - way to install dependencies for `shared` into each lambda

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#486]
I have a few modules in `shared` that depend on various npm modules.In

 - In `sandbox` they get them from the project's `node_modules`
 - After `arc deploy` they're missing, since they're not in the individual lambda's `node_modules`

Right now I have a little script which goes and adds things to the `package.json` of every lambda, and runs `npm i`:

```powershell
$packageName = 'http-status-codes'
$packageVersion = '^1.3.2'

function set-dependency(${file}, ${packageName}, ${packageVersion}) {
  write-output "---------------------------------------------------"
  write-output "Working on ${file}, setting ${packageName} to ${packageVersion}"   
  $packageJSON = get-content $file | convertfrom-json
  $packageJSON.dependencies | Add-Member -Force -Type NoteProperty -Name $packageName -Value $packageVersion
  $packageJSON | ConvertTo-Json -depth 100 | set-content $file
}

$startDir = Get-Location;
@('http', 'events', 'ws') | foreach-object {
  Set-Location $startDir
  $topLevelDir = ${PSItem}
  get-childitem "src/${topLevelDir}" | foreach-object { 
    $lambdaDir = ${PSItem}
    $packageJSONFile = "${lambdaDir}\package.json" 
    if ( -Not (Test-Path ${packageJSONFile} -PathType Leaf)) {
      write-output "Skipping non existent file ${packageJSONFile}"  
      return
    }
      
    set-dependency $packageJSONFile ${packageName} ${packageVersion}
    remove-item "${lambdaDir}\package-lock.json" -ErrorAction SilentlyContinue
    remove-item "${lambdaDir}\npm-shrinkwrap.json" -ErrorAction SilentlyContinue
    Set-Location ${lambdaDir}
    npm i
  } 
}
Set-Location $startDir
```

From Slack it seems like others are doing the same. It could be nice to have a way to do this that comes with arc. Or better yet, detect what modules things in `shared` use and add them automatically.

**Comment by brianleroux** [comment]
we have this feature! if `hydrate` discovers a `src/shared/package.json` it will honor it / should run before deploy and sandbox

<img width="826" alt="Screen Shot 2019-11-29 at 11 23 26 AM" src="https://user-images.githubusercontent.com/990/69887206-b3dba000-129a-11ea-822b-320902c1b7f1.png">
