### ISSUE TITLE
`arc deploy production ` disables CloudFront distribution, taking site down

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#492]
(this may be fixed by the `@domain` work but heads up anyway)

`arc deploy production ` disables CloudFront distribution, it has to be enabled again. @Ian on Slack and I have seen the same thing:

**Describe the issue**

My site has been up for a few days, but after I do a deploy, `arc deploy production `, CloudFront distribution is disabled, it has to be enabled again.

Before a deploy:

![image](https://user-images.githubusercontent.com/172594/66931297-cd4bc400-f02d-11e9-9a74-fc07c8e8d52f.png)

After a deploy

![image](https://user-images.githubusercontent.com/172594/66931272-c45af280-f02d-11e9-85fa-fde1b087779e.png)

It's not a big deal to re-enable (just a couple of clicks), but it does take the site down.

Arc 6.0.18

**Comment by brianleroux** [comment]
I was unable to reproduce this…however I can see how it can happen. If you disable or comment out `@cdn` we disable (then remove) the corresponding cloudfront distributions with the `deploy` command.
