### ISSUE TITLE
Add LF User to GitHub Org

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [architect/architect#493]
**Is your feature request related to a problem? Please describe.**
This is a request for access.

**Describe the solution you'd like**
Please add `jpalmerLinuxFoundation` as a member of the Architect Organization (`https://github.com/architect/`) to support efforts in adopting EasyCLA.

**Describe alternatives you've considered**
I've attempted to request the [EasyCLA](https://lfcla.com/) app be installed, but it appears that I must be a member of the organization to do so. Once I send the request, please review and approve it. Once installed, there is more prep required. Installing the app will **NOT** automatically enforce CLA checks (please consult with Brian Warner if you have concerns/questions).

**Comment by ryanblock** [comment]
Just sent invitation to org!
