### ISSUE TITLE
nesting resources failing

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#531]
apig w >100 routes will fail

**Comment by jkarsrud** [comment]
We experienced this with 32 routes defined in our `.arc`-file, but the total number of generated resources was > 100. Might be useful to know.

**Comment by brianleroux** [comment]
diggin' into this rn

**Comment by brianleroux** [comment]
can confirm 32 routes repros (but weirdly 30 creates 67 resources!) 

will report back asap

**Comment by brianleroux** [comment]
Ok … this is more of a bandaide than a fix but I don't want y'all to be blocked. Our nesting strategy was deliberately conservative but I've now relaxed it so you should be able to get …way more routes. The max we can allow would be just under 100 before nesting resource (of which we have to do after 200 resources) which is the real bug I need to fix here!

**Comment by brianleroux** [comment]
published in `@architect/architect@6.0.24`

**Comment by ksjogo** [comment]
Isn't this just pushing the bug format by defaulting to the initial strategy longer?
I was using patch-package for now to just disable the > 100/200 one.

**Comment by brianleroux** [comment]
What's patch-package ? (And yes it is... revisiting this over the holidays. Think we will want a new strategy for nesting that takes DNS into account)

**Comment by ksjogo** [comment]
Easiest way to fix stuff like this in upstream node_modules without relying on a release or fork: https://www.npmjs.com/package/patch-package
