### ISSUE TITLE
`npx hydrate` fails on Windows

### ISSUE THREAD

**Issue by jessehattabaugh** [architect/architect#533]
`npx hydrate` emits an error

**Steps to reproduce the behavior:**
1. clone [this repo](https://github.com/architect-examples/arc-example-ws)
2. run `npm i && npx hydrate`

**Expected behavior**
Hydration to be performed and no error message

**Screenshots**
![image](https://user-images.githubusercontent.com/17991/69751748-983e9100-1104-11ea-9e31-0fb3e91dad02.png)

**Desktop**
Please complete the following information (if appropriate):
 - OS: Windows 10
 - Browser: VSCode, and cmd.exe
 - Version: 6.0.20

**Additional context**
I have cloned the repo in the same way that I have cloned other repos, the repo is located in my home dir, so I should have permission to access the directory. It appears that `hydrate` is using `mkdir` which likely does not work in Windows shell. The NPM package `mkdirp` could be used to overcome this.

**Comment by ryanblock** [comment]
Thanks! The `hydrate` module doesn't do any directory creation, and is pretty well tested on Windows. (But that's not to say we don't have a bug, of course.)

Can you try updating to Arc 6.0.23 and see if that's still happening?

**Comment by jessehattabaugh** [comment]
Upgraded to 6.0.23, error still occurring
![image](https://user-images.githubusercontent.com/17991/69753406-65969780-1108-11ea-8301-5199c3eeeb53.png)

**Comment by jessehattabaugh** [comment]
I just added the following script to the package.json `"hydrate": "arc hydrate"`. Hydrate runs successfully this way. Perhaps this has something to do with `npx`?

**Comment by ryanblock** [comment]
`npx arc hydrate` is the correct command, unless Architect is installed globally (in which case it's just `arc hydrate`). But now that you mention it, `npx hydrate` shouldn't really be working at all, that was phased out.

So without using package.json / `npm run`, just try `npx arc hydrate` and lmk how that goes?

**Comment by jessehattabaugh** [comment]
`npx arc hydrate` works as well. Thank you!
