### ISSUE TITLE
Logs not pulling logs for `src/ws/*`

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#538]
**Describe the issue**
As reported by @jessehattabaugh, logs aren't able to be accessed for `src/ws/*` functions.

**Comment by austinkelleher** [comment]
I fixed this issue here: https://github.com/architect/logs/pull/99 /cc @ryanblock @brianleroux 

I'm going to close this issue and track the bug separately in the `logs` repo. Here is the corresponding issue: https://github.com/architect/logs/issues/98

**Comment by ryanblock** [comment]
👏👏👏 Thanks @austinkelleher!
