### ISSUE TITLE
binary builds and downloads for linux/mac/windows

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#556]
Currently we prompt developers to install Architect with `npm i -g @architect/architect`. It is the easiest and fastest way to get started. However, we would also recommend developers locally install the cli and use `npx` if its a predominantly Node based project. 

Using a global install with Node is pretty normal and probably fine but also not ideal for Ruby and Python developers. We should have binary downloads an option for them. We explored using https://www.npmjs.com/package/@zeit/ncc for this and seemed to be feasible. 

We'd need to decide a few things:
- Where do we host the binaries? Probably on Github?
- We will need to sign the generated binaries. Where are we going to keep the signingkeys and/or how will they be generated? (GitHub actions?)

**Comment by ryanblock** [comment]
> Where do we host the binaries? Probably on Github?

I also assume GitHub but we can also publish them to `download.arc.codes` (or something) to for optics

> We will need to sign the generated binaries. Where are we going to keep the signing keys and/or how will they be generated? (GitHub actions?)

Yeah, I think we'd either store them in GitHub Secrets (and publish via GH Actions), or on AWS (with necessary creds to access them in GH Secrets).
