### ISSUE TITLE
Add concept of 'stage' to architect/package

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#557]
And remove intrernal macros depending on that info existing at that time. (By adding to pkg)

**Comment by ryparker** [comment]
Is this related to the API gateway `stage` that is created on every arc deploy?

**Comment by brianleroux** [comment]
No thats a bug in CloudFormation. There are workarounds but I'll probably just migrate us to the new API Gateway HTTP api types which does not exibit this behavior. (HTTP apis still in preview so not suitable for production use yet)

**Comment by brianleroux** [comment]
(Migration will be backwards compatible.)

OH! And the reason for this issue is to add the ability for the packager to know the env concept of `staging` and `production`.
