### ISSUE TITLE
Prototype HTTP APIs for API Gateway to replace REST APIs

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#576]
(have a macro for this! just need to tidy it up for a prerelease to get community feedback and testing)

**Comment by defionscode** [comment]
Not sure if the title is literal, but for us, a replacement would not be ideal. I think it makes sense to support it but given that it's in `beta` and doesn't support AWS WAF, I'd rather see as an opt-in macro.

**Comment by brianleroux** [comment]
Yeah we won't force this until we totally have vetted it. Definitely optin 🙏

**Comment by brianleroux** [comment]
https://GitHub.com/architect/macro-http-api
