### ISSUE TITLE
add support for credential_process in ~/.aws/credentials

### ISSUE THREAD

**Issue by RandomEtc** [architect/architect#582]
**Is your feature request related to a problem? Please describe.**
We'd like to use `credential_process` to supply our AWS key/secret. This doesn't currently work in architect, it seems to require the presence of access_id (or similar).

**Describe the solution you'd like**
Architect's credential handling should use the AWS SDK's support for `credential_process`, here: https://github.com/srchase/aws-sdk-js/blob/master/lib/credentials/process_credentials.js

**Describe alternatives you've considered**
There doesn't appear to be a workaround unless we change how we handle credentials on our side.

**Additional context or notes**
Chatted briefly with @brianleroux about this on the architect slack in `#help`. 

I'm not super familiar with architect or the AWS SDK, but my recommendation would be to reduce the amount of detection in architect and not to [hard-code `SharedIniFileCredentials`](https://github.com/architect/utils/blob/master/banner/init-aws.js#L35). It looks like the AWS SDK supports "chained" credentials already and includes `SharedIniFileCredentials` and `ProcessCredentials` in [the default provider chain](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html#defaultProviders-property).

**Comment by defionscode** [comment]
Looking at the code, I think I agree with your assessment. There no _need_ to manually handle creds. It _should_ just work. Perhaps the dummy creds are needed but not really anything else.

**Comment by ryanblock** [comment]
Looks like this should be live now in `1.4.3-RC.0` courtesy of @defionscode!

**Comment by defionscode** [comment]
this can probably be closed now
