### ISSUE TITLE
Sandboxed queued items don't complete if they take too long

### ISSUE THREAD

**Issue by stuartlangridge** [architect/architect#593]
**Describe the issue**
When testing in the sandbox, a queued item may not complete if it takes too long.

**Steps to reproduce**

`.arc` (relevant parts):
```
@http
get /

@queues
somequeue
```

`src/http/get-index/index.js`:
```
let arc = require('@architect/functions')
exports.handler = async function http (req) {
    await arc.queues.publish({
        name: 'somequeue',
        payload: {whatever: "blah"},
    })

  return {
    headers: {'content-type': 'text/html; charset=utf8'},
    body: "done!"
  }
}
```
`src/queues/somequeue/index.js`
```
function awaitableTimeout(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }

exports.handler = async function queue (event) {
    console.log("begin worker", JSON.stringify(event));
    await awaitableTimeout(5000);
    console.log("end worker", JSON.stringify(event));
    return
}
```

If the timeout in the queue worker is set to something short, such as 5ms or even 500ms, then both the "begin worker" and "end worker" lines are executed and their output appears in the stdout of the sandbox. However, with the timeout set to 5000ms, the "begin worker" line runs but the "end worker" line doesn't.

**Expected behavior**
Either workers run to completion, or if there's a timeout for workers then that could be made clear in the documentation. (Or I've misunderstood how the queueing stuff is supposed to work, which is possible.)

**Comment by ryanblock** [comment]
Sandbox follows Lambda defaults: 5s execution time and the process dies. To override this timeout length, please use `.arc-config`'s `timeout` setting within your function: https://arc.codes/reference/arc-config/timeout
