### ISSUE TITLE
Incompatibility with AWS SAM CLI sam local invoke

### ISSUE THREAD

**Issue by achen530** [architect/architect#594]
I recently inherited a project that is using several different versions of architect (mostly 5.8/5.9). It's mostly used for our data pipeline that consists of Lambdas + SQS + S3. In particular, we use a lot of `arc.queues.subscribe`, and I've been trying to test the handler code locally. The previous engineer often ended up copy-pasting the code into an http function which he'd deploy to test and I was hoping for a better way. There wasn't much documentation on if this was possible with `arc sandbox` so I started to see if I could use `sam local invoke` for this. (Note for reference, I'm now trying out https://github.com/brianleroux/arc-example-test-queues).

The code file I was testing looks something like this:

```
const arc = require('@architect/functions');

let putObjectToS3 = require('@architect/shared/s3-put');
let processFiles = require('@architect/shared/process-files');
let deleteObjectFromS3 = require('@architect/shared/s3-delete');

async function handler(record, callback) {
  let objectKey = record.Records[0].s3.object.key;
  let srcBucketName = record.Records[0].s3.bucket.name;
  // .. do stuff
  callback();
}

exports.handler = arc.queues.subscribe(handler);
```

I was referring to tutorials/documentation [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging.html) and [here](https://www.moesif.com/blog/technical/serverless/debug-lambda-functions-locally-with-the-sam-cli-and-vscode/), and ran into a couple of snags.

1. In the sam.yaml exported by Architect, the CodeUri points at S3, which sam local invoke cannot handle. I made a copy of the yaml and pointed to the local source code.
2. It was not able to require code in @architect/shared. I worked around this by copying those directly into the lambda code directory.
3. (NOTE: I'm now pretty sure this issue was from an error in my code, because I was also upgrading Architect from 5 to 6, so you can probably ignore this but I'm leaving it here for posterity). Finally I got weird JSON parse errors. 
`ERROR	Invoke Error	{"errorType":"SyntaxError","errorMessage":"Unexpected token u in JSON at position 0","stack":["SyntaxError: Unexpected token u in JSON at position 0","    at JSON.parse (<anonymous>)","    at Promise.all.event.Records.map (/var/task/node_modules/@architect/functions/src/queues/subscribe.js:26:29)","    at Array.map (<anonymous>)","    at Runtime.lambda [as handler] (/var/task/node_modules/@architect/functions/src/queues/subscribe.js:24:46)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}`
I believe it's because my event handler takes in different parameters than sam local invoke is expecting. I think they're expecting event (JSON) and context (JSON), while architect expects event (JSON) and callback (function). So it was throwing up from trying to parse a function (or undefined?) as JSON.

**Comment by brianleroux** [comment]
couple of things to try/know! 
- generating sam is an Architect 6 feature but should still work! (and you'll probably want to migrate there eventually too) if you run `arc package` it will generate `sam.json` which should have all local paths (`sam.yaml` gets created by running `arc deploy` … or invoking the aws cli directly)
- if you run `npx arc-hydrate` (or add `arc-hydrate` to your npm scripts in package.json and run from there) it will copy src/shared into the lambdas

**Comment by ryanblock** [comment]
This has been dormant for quite a while, please let us know if there's something here to fix!
