### ISSUE TITLE
Fingerprinting and fonts don't play nice

### ISSUE THREAD

**Issue by dawnerd** [architect/architect#602]
This might be intended behavior but I'm running into an issue with a couple different fixes but wanted to check in here first.

Arc version:
```
"@architect/architect": "^6.1.0"
```

Our `.arc` file contains:

```
@static
fingerprint true
```

We have a public folder that looks like:

![image](https://user-images.githubusercontent.com/24781/72488218-307ffa80-37c5-11ea-8a8d-fadec1ae9a8f.png)

A request to the font (which 404s) looks like: `/_static/fonts/proxima/2F3F3C_2_0.woff2`

And in s3:

![image](https://user-images.githubusercontent.com/24781/72488313-71780f00-37c5-11ea-99db-fc36c7f72190.png)

So I'm not sure what the best solution is. I suppose we can add a step in our webpack build to replace out the filename but that seems like more of a workaround than a real solution.

Maybe it should be handled when it proxies the request?

**Comment by ryanblock** [comment]
Hey there! A couple of possible solutions here ready to go:

1) If you're calling fingerprinted assets from a doc being proxied through Arc (e.g. `@static` + NO `@http get /` + `public/index.html`) you can use [Arc's template syntax](https://github.com/architect/functions/blob/master/src/http/proxy/templatize.js#L7-L8) in your HTML docs:
  - `${STATIC('path/filename.ext')}` or `${arc.static('path/filename.ext')}` will be replaced inline with the fingerprinted filename
  - This is stable and officially supported, but under-documented!

2) Use the `@static ignore` setting:
```
@static
fingerprint true
ignore
  .woff
  .woff2
```
Ignore completely ignores those files though, so if you go that route, upload them first to your bucket.

Does either of these help / solve things for you?

**Comment by ryanblock** [comment]
Gonna close for now, but please let me know if we still haven't hit the mark yet!
