### ISSUE TITLE
Consolidate issues from child repos into `architect/architect`

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#620]
It has become too confusing and easy to miss issues. We (meaning myself and @brianleroux) decided all Architect issues should be consolidated into `architect/architect`.

Checklist:
- [ ] Migrate all existing issues from the project's child repos
  - [ ] `arc.codes`
    - [ ] open issues
    - [ ] closed issues
  - [x] `create`
    - [x] open issues
    - [ ] closed issues
  - [x] `deploy`
    - [x] open issues
    - [ ] closed issues
  - [x] `env`
    - [ ] open issues
    - [ ] closed issues
  - [x] `hydrate`
    - [ ] open issues
    - [ ] closed issues
  - [x] `logs`
    - [ ] open issues
    - [ ] closed issues
  - [x] `package`
    - [ ] open issues
    - [ ] closed issues
  - [x] `parser`
    - [ ] open issues
    - [ ] closed issues
  - [x] `repl`
    - [ ] open issues
    - [ ] closed issues
  - [x] `sandbox`
    - [x] open issues
    - [ ] closed issues
  - [x] `utils`
    - [x] open issues
    - [ ] closed issues
- [ ] Disable issues on said repos
- [x] Add per-repo labels

---

NOT doing these:

- `functions-python`
- `functions-ruby`
- `functions`

**Comment by tbeseda** [comment]
Just double checked these. 
Only the `functions-deno|ruby|python)` and arc.codes repos still have /issues. I checked the appropriate boxes above

**Comment by tbeseda** [comment]
Most have been moved.
