### ISSUE TITLE
`QUIET` / `--quiet` / `quiet: true` should be respected across all modules

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#621]
Currently we are suppressing logging with the quiet flag for some, but not all modules. We should extend this to all modules and circumstances.

This includes setting the `QUIET` env var, the `--quiet` CLI flag, and any `quiet: true` params where appropriate.

**Comment by konsumer** [comment]
I also think a global env-var should be at the very least prefixed, like `ARC_QUIET`, but any entry-point function (like sanbbox.start()`) should also have options that can override env-vars.

I am a big fan of using object-destructuring & defaults:

```
const { ARC_QUIET = false } = process.env

// later

function start(quiet=ARC_QUIET){}
```

this will set defaults at the level of pulling out the env-var, as well as at the function level, so you can override it on a 1-off basis.

**Comment by konsumer** [comment]
one subtle prob with env-vars in general is that they are all strings.

so `ARC_QUIET=false arc sandbox` resolves to `"false"`, which type-coerces to `true`.

**Comment by konsumer** [comment]
Since function defaults are resolved at runtime, this might holding on to a value instead of reference to the env-var, so it might work better like this:

```js
function start(quiet = process.env.ARC_QUIET) {}
```

this only really matters because we might change the env-var before start is called, but after the import.

**Comment by ryanblock** [comment]
The env var problem described in `ARC_QUIET=false arc sandbox` is certainly not unique to us or this project – I'm personally not sweating that scenario fwiw. But it's good to note, and I pity anyone who generally goes around trying to set `false` as env var values in bash.

**Comment by konsumer** [comment]
> The env var problem described in `ARC_QUIET=false` arc sandbox is certainly not unique to us 

Yeh, for sure, just calling it out as a gotcha. I have noticed in examples using `QUIET=true arch sandbox`, so wanted to make sure you were aware of  `QUIET=false arch sandbox` not doing what one might expect. I think the typical way to work around this is `ARC_QUIET=""` which resolves to false.

```
!!""
false
```

**Comment by ryanblock** [comment]
Will ship in `1.6.0`!
