### ISSUE TITLE
Link to "Working with multiple AWS accounts" broken

### ISSUE THREAD

**Issue by rmuellerjr** [architect/architect#624]
From the page; https://arc.codes/quickstart, the link (in the title) is broken.

**Comment by ryanblock** [comment]
Ugh. Please feel free to patch and remove from https://github.com/architect/arc.codes/

See also: https://github.com/architect/arc.codes/issues/193

**Comment by tbeseda** [comment]
This link is no longer present in Quick Start and there's now a doc that elaborates on detailed AWS setup.
