### ISSUE TITLE
dirty deploy of single functions

### ISSUE THREAD

**Issue by filmaj** [architect/architect#625]

**Comment by filmaj** [comment]
I'm playing around with implementing this.

Any desires on what the CLI for this would look like? Pass in the local path to the lambda as the final argument, like `arc deploy dirty src/http/get-index` ? Or allow for the path argument to be in any position (which would probably require us to validate unix and windows path args and make sure the path exists and matches a lambda that arc recognizes)? I would think that the interface would be pretty much identical to that of `arc logs`.

Thoughts?

**Comment by ryanblock** [comment]
Personally I like just `arc deploy {folder}`, easy enough. I wonder if we should add --production tho, good reason not to, but I have used it many times to quickly patch a customer issue. I think net net I’m pro prod flag, even given the risks.

**Comment by ryanblock** [comment]
Also <3 thanks for looking at this Fil!

**Comment by filmaj** [comment]
While codepatching production lambdas may not be a good habit to build, it can come in handy. I don't think arc-the-tool should be prescriptive on that. I think we should allow it.

I do like `arc deploy {folder}`, though it doesn't fit in neatly with `arc deploy dirty`. The `dirty` label adds confusion, I think, as then I think it begs the question of "what is a `clean` deploy?" But perhaps that's a separate discussion.

I'll start poking away at this and we can always tweak the interface at review time once the PR is up.

**Comment by ryanblock** [comment]
Yeah, I don’t think the dirty flag is helpful. We can just be clear in our console logging that deploying single Lambdae will cause drift and will be overwritten by future deploys. 

Related, had some very nice experiences with yargs lately, I’m down to look at incorporating that instead of all this bespoke CLI flag logic we’ve been accumulating.

**Comment by filmaj** [comment]
Should I try to include a swap over to yargs, then, when addressing this, or leave that as a separate exercise?

**Comment by brianleroux** [comment]
I'm not into these libs at all and would prefer that come in a stand alone PR so evaluate

**Comment by filmaj** [comment]
Posted an attempted at a PR for this over in https://github.com/architect/deploy/pull/222

**Comment by brianleroux** [comment]
merged in architect/deploy@1.7 ! 🎉
