### ISSUE TITLE
woff2 files don't have cache headers

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#627]
We have some custom fonts in our public directory that get pushed out with our deployment, but they don't seem to get expires headers set like the other assets

**Comment by ryanblock** [comment]
I'm not sure if this is still an issue, and looking over the code in our static asset deployer (at least that's happening these days) I'm not seeing any clear bugs, but one thing I'd advise is using `@static fingerprint true`. Closing for now, but please do reopen if we've got something to fix!
