### ISSUE TITLE
Static and Macro bucket confusion

### ISSUE THREAD

**Issue by clintjhill** [architect/architect#629]
**Describe the issue**
If a project includes both `static` and `macro` pragma, and that macro creates an S3 bucket, it is possible for the macro bucket to be confused as the static bucket and publishing to S3 goes in the wrong bucket.

**Steps to reproduce**
1. Create an `.arc` file with:
```
@app
arc-app

@static
folder ../arc-app/dist

@macros
upload-bucket
```
2. In the macro `src/macros/upload-bucket.js` create the following:
```
function resources(arc, cfn, stage) {

  cfn.Resources.Upload = {
    Type: 'AWS::S3::Bucket',
    Properties: {
      BucketName: 'upload-bucket'
    }
  };

  return cfn;
}
module.exports = function uploads(arc, cfn, stage) {
  cfn = resources(arc, cfn, stage);
  return cfn;
}
```
3. Perform `arc deploy`
4. Go to the static bucket and find it's empty
5. Go to custom bucket `upload-bucket` and find the static files have been published there

**Expected behavior**
Publishing to S3 for the static files should be specific to the StaticBucket set as the resource for static files.

**Comment by ryanblock** [comment]
Yikes, this has sat open too long, it shipped in [Deploy 1.6.1](https://github.com/architect/deploy/blob/master/changelog.md#161-2020-04-16). Thanks again, @clintjhill!
