### ISSUE TITLE
inconsistencies in sandbox sub-apis

### ISSUE THREAD

**Issue by filmaj** [architect/architect#631]
if you take a look at the readme i added in architect/sandbox#8, you'll note that `events.start` and `db.start` are the same in that they both take a callback as a parameter _and_ return an object containing a `close()` method that shuts servers down. The callbacks for these methods fire once the servers are up. To me this is a little awkward as I think we should consolidate: either use return values or use callbacks. Using both feels weird. I think for an async API, we should instead pass a handle to the server `close()` method in the callback.

Another inconsistency is that `http.start` doesn't return anything - but uses a callback. However, to close the http server, you invoke `http.close`! So `http` has its own "singleton" style API, but `events` and `db` don't (even though both events and db are also implemented in the same singleton style).

Would be nice to decide on a single approach and make the API consistent.

**Comment by ryanblock** [comment]
This was fixed in Sandbox 2.0 / Arc 7!
