### ISSUE TITLE
Deps are shared

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#637]
1. route A has dependency lodash installed and in package.json
2. route B requires lodash, but its not in package.json or installed locally, 
3. route B works in the sandbox
4. when you deploy, route B crashes because lodash is missing.  (expected)

This has got us a few times when we forget to add a package.json file before `npm i`

Arc 6.0.14

**Comment by ryanblock** [comment]
Hmm, oddly I somehow must have missed this issue. Bearing in mind this is a function of Node's module resolution system, what's the preferred remedy?

**Comment by jgallen23** [comment]
I'm not sure the remedy, we just run into the issue a fair amount.  In the sandbox, are the functions run in a separate VM context?  Would that solve it?

**Comment by ryanblock** [comment]
How it works in a nutshell:
- An event comes in via the Sandbox HTTP server, WebSocket server, event bus, etc.
- Sandbox figures out which Lambda to execute, which runtime to use, how the Lambda is configured, etc.
- Sandbox's runtime handler then minimizes your code and passes it off for execution (see: https://github.com/architect/sandbox/blob/ports/src/invoke-lambda/run-in-node.js#L12)
- Sandbox's process spawner then executes your code (in Node, for example, it's done as a [node eval](https://nodejs.org/api/cli.html#cli_e_eval_script) via a [childprocess.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) call) and returns the result (see: https://github.com/architect/sandbox/blob/ports/src/invoke-lambda/spawn.js#L121-L148)

Thus, in your case Hode is just doing its Node thing: when it can't find the module it's looking for upon execution, it follows its [module resolution algorithm](https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-nodejs-resolves-modules), which traverses down the filesystem in search of the referenced module. Hence, the possibility of getting a false positive.

I'm open to ideas on how to short circuit or work around this – I just ask that you please bear in mind we are highly wary of overwriting core built-in Node functionality, such as its module system.

**Comment by ryanblock** [comment]
Hey, good news, this was actually solved in Architect 8.4 with the addition of Lambda treeshaking!
