### ISSUE TITLE
Env vars with @ are broken in sandbox

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#638]
If an env var has an `@` in it, only the first part is returned

**Steps to reproduce**
1. `arc env testing EMAIL bob@bob.com`
2. `console.log(process.env.EMAIL)` in route
3. `bob` is outputted in the console
4. deploy and add env var to staging
5. `bob@bob.com` is in cloudwatch logs

Arc 6.0.14

**Comment by ryanblock** [comment]
Update: should be resolved when we migrate Sandbox to Parser 2.0, which hopefully will be soon!

**Comment by ryanblock** [comment]
Fixed be released today in `6.2.5`!
