### ISSUE TITLE
🔥🔥🔥🤘🏿🤘🏾🤘🏽🤘🏼🤘🏻🔥🔥🔥

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#666]
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
🔥🔥🔥6️⃣6️⃣🔥🔥🔥6️⃣6️⃣🔥🔥🔥6️⃣6️⃣🔥🔥🔥
🔥🔥6️⃣🔥🔥🔥🔥6️⃣🔥🔥🔥🔥6️⃣🔥🔥🔥🔥🔥
🔥🔥6️⃣6️⃣6️⃣🔥🔥6️⃣6️⃣6️⃣🔥🔥6️⃣6️⃣6️⃣🔥🔥🔥
🔥🔥6️⃣🔥🔥6️⃣🔥6️⃣🔥🔥6️⃣🔥6️⃣🔥🔥6️⃣🔥🔥
🔥🔥6️⃣🔥🔥6️⃣🔥6️⃣🔥🔥6️⃣🔥6️⃣🔥🔥6️⃣🔥🔥
🔥🔥🔥6️⃣6️⃣🔥🔥🔥6️⃣6️⃣🔥🔥🔥6️⃣6️⃣🔥🔥🔥
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by filmaj** [comment]
😆

**Comment by ryanblock** [comment]
<img src="https://media.giphy.com/media/77f2SrKYNOnYs/giphy.gif">

**Comment by filmaj** [comment]
I always had a feeling Elmo had a darker side to him

**Comment by brianleroux** [comment]
<h1 style=font-size:3em>😈</h1>
