### ISSUE TITLE
Using (or not) package-lock.json

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#680]
We've begun piecemeal removing `package-lock.json`, with @brianleroux recently citing the following link re. lockfile (non-)use:
- https://github.com/sindresorhus/ama/issues/479
- https://www.twilio.com/blog/lockfiles-nodejs

My own conclusions: `package-lock.json` provides no benefit in published packages, but remains necessary for deterministic deployments of actual Architect project app repos. So official Architect packages could stand to shed `package-lock.json`, while `https://github.com/architect-examples` should keep their lockfiles.

That said, in a world constantly creeping entropy, I like to fend off instability with whatever determinism I can find. Some alternative ideas:
- **Swap out `package-lock.json` for `npm-shrinkwrap.json`** – theoretically solves the issue of npm ignoring the lockfile for published modules adding the determinism of a lockfile to our packages, but we still pay a penalty in dep updating noise, git pack size, etc., and it's **[officially warned against for libraries](https://docs.npmjs.com/files/shrinkwrap.json#description)**
  - Further: I'm not sure this is a meaningful real-world issue? Architect has been downloaded and used quite a bit, and I'm unaware of >= second-order dependency mismatches presenting issues to us or our users
- **Dependency version pinning** – we started pinning first-level dependencies in `@architect/architect` [6.0.11 last September](https://github.com/architect/architect/blob/02348d5fbbdc51d7fbe66cea677d1ba739c7a04f/package.json#L44-L53); I like this approach, and I'd suggest every official production Architect package should only be allowed to have version-pinned `dependencies` (`devDependencies` are fine to be ranges)

Thoughts?

**Comment by brianleroux** [comment]
yeah agree on the app vs package boundary. also like the idea of pinning core packages.

**Comment by ryanblock** [comment]
Here's an example of how this would look (using `save-exact=true`): https://github.com/architect/utils/pull/83/files

**Comment by ryanblock** [comment]
Has me thinking further: should we pin all `dependencies`, or only version pin `@architect/*` packages within other Architect packages?

**Comment by konsumer** [comment]
I have bitten a few times by breaking changes that resolved within the default semver boundary (mostly were google packages, coincidentally, like all the interdependent @material packages and the protobuf/grpc stuff.) I was relieved when package-lock started tracking the stuff I had to shrinkwrap all the time. For examples, I agree we should package-lock, and as you said pin & ignore/opt-out for libs (because package-lock is ignored, anyway.) I like pinning all deps for libs, so you can be really sure what version people are using, but it also makes keeping clean `npm audit`s require more update/publishes.

**Comment by ryanblock** [comment]
After giving this some further consideration, I'm thinking we're going to start rolling out with the following `.npmrc` to all packages:

```
package-lock=false
save-prefix=~
```

This will ensure all packages' core deps are patch-only (no minors); Dependabot should help manage everything else, and majors and minors will be ensured to only be rolled up into proper Architect releases.

Otherwise: devdeps are still fine to use `^`, and `package-lock.json` will no longer be checked in (of course).

Big ups to my old buddy [@celly for his thoughts on this](https://twitter.com/Celly/status/1228367160755572737) as well!

**Comment by ryanblock** [comment]
Will be retired in `6.2.5`, hopefully shipping today!
