### ISSUE TITLE
Module Import Issue - Session Reading Does Not Work

### ISSUE THREAD

**Issue by itsUnsmart** [architect/architect#687]
The `@architect/functions` package will not get required in lambda. (It works locally!)

I have a file in my shared called `helpers.js` this file contains a function called `readSession` it looks like this: 
(It was modified to only read the session after having issues trying to read other stuff like auth) 

(Edit I also tried moving `const arc = require('@architect/functions')` to be outside the function same result, completely lost here)
```
module.exports.readSession = async (req) => {
    try {
        console.log('Inside readSession')
        const arc = require('@architect/functions')
        console.log('Required arc/functions')
        let session = await arc.http.session.read(req)
        console.log('Read the user\'s session')

        return Promise.resolve(session)
    } catch (error) {
        console.error(error.message || error, 'readSession Error')
        return Promise.resolve({ status: false, error })
    }
}
```

In a get route I have setup for `/auth/check` it looks like so:

```
exports.handler = async function http(req) {
    const body = {}

    try {
        const response = await require('@architect/shared/helpers').readSession(
            req
        )

        body.status = 200
        body.session = response
    } catch (error) {
        body.status = 500
        body.error = error
    }

    return {
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(body)
    }
}
```

I always get an error when going to this route that looks like so:
```
{
"message": "Internal server error"
}
```

And in the cloudwatch logs what I get is:
`Inside readSession` then the function times out... it never requires the `@architect/functions` module.

**Expected behavior**
A clear and concise description of what you expected to happen

The file should get required and resolve with the users session.

What do I need to do to get this to work?

Edit again:
The function works just fine if I just npm install aws-sdk and arc/functions and copy over the function... but that defeats the purpose of the shared folder and I want to be able to update that function in only one spot.

**Comment by brianleroux** [comment]
eh…uh! I'm not sure I can visualize things based on this description. Is it possible for you to link me the broken repo? we can def figure out what is messed up and fix this. think its just a misunderstanding on how the paths work.

**Comment by brianleroux** [comment]
chatted on twitter and is resolved so closing / don't hesitate to reopen if you're having issues again! cheers 🚀

**Comment by itsUnsmart** [comment]
This is happening to me again. Honestly no clue how to fix it as it just started working again. I will add you to my git repo as it is private.

The issue is with the `get /auth/check` route.

Logs I get in cloud watch:
```
START RequestId: 37d53741-ba6a-43f5-96d0-19a9d92b53b5 Version: $LATEST
2020-03-02T06:39:10.917Z 37d53741-ba6a-43f5-96d0-19a9d92b53b5 INFO Check Auth
2020-03-02T06:39:10.919Z 37d53741-ba6a-43f5-96d0-19a9d92b53b5 INFO require arc functions
END RequestId: 37d53741-ba6a-43f5-96d0-19a9d92b53b5
REPORT RequestId: 37d53741-ba6a-43f5-96d0-19a9d92b53b5 Duration: 5004.68 ms Billed Duration: 5000 ms Memory Size: 128 MB Max Memory Used: 89 MB Init Duration: 116.88 ms
2020-03-02T06:39:15.918Z 37d53741-ba6a-43f5-96d0-19a9d92b53b5 Task timed out after 5.00 seconds
```

It works just fine when in the sandbox mode.

**Comment by brianleroux** [comment]
saw the app you invited me to but its pretty big…can you reduce a test case for me?

**Comment by itsUnsmart** [comment]
I had made a test of this yes, but the test does work even though it is setup basically exactly the same.

Test: https://github.com/itsUnsmart/testArc/

I have no idea what to do to debug this issue as they are setup basically exactly the same.

The only files that matter in my large project is `/http/get-auth-check/index.js` and `/shared/helpers.js` (specifically the checkAuth function). 
index: https://github.com/itsUnsmart/sp/blob/master/src/http/get-auth-check/index.js
helper: https://github.com/itsUnsmart/sp/blob/master/src/shared/helpers.js

We can assume the user has no auth session so the helper checkAuth should skip the entire if session.auth block. However, the checkAuth function is only reach the line to require `@architect/functions` before it stops working, so it is not even reaching the part to read the users session.

Based on the fact the test works I would think I am doing something wrong in my main repo but I honestly have no clue where I am doing anything wrong as the uploaded function seems to be exactly as it should (I have attached the uploaded zip retrieved from s3).

Here is what it uploaded: https://easyupload.io/7vco2q

**Comment by itsUnsmart** [comment]
Also recently I installed linux to dual boot on my main machine, and when getting everything set back up on the linux side of my machine trying to deploy I get a deploy failed at updating cloudformation deployment. Does not give anything really into any errors so not sure if maybe this is the issue now there is something wrong deploying.

**Comment by itsUnsmart** [comment]
Okay I have fixed the problem now fully... I had to move the requires to be top level and not inside of functions.
