### ISSUE TITLE
Static asset fingerprinting directive cannot be at the top of the @static section in Architect 5.x

### ISSUE THREAD

**Issue by toothbrush** [architect/architect#714]
## Description
I tried to enable `fingerprint true` in an existing Architect-based project.  Initially, i was baffled, because when i tried to deploy, i received errors about not finding an S3 bucket.  It turned out that moving the `fingerprint true` directive to the bottom of the `@static` section of `.arc` solved the issue.

### Steps to reproduce
1. Grab a working Architect project with `.arc` for example:
```
@app
myproj

@http
get /
get /faces
get /faces/:userId

@static
staging myproj-staging
production myproj-production
```
2. Add the `fingerprint` directive at the top of the `@static` section, for example:
```
...
@static
fingerprint true
staging myproj-staging
production myproj-production
```
3. Try to deploy your app with `arc-deploy`.
4. See mysterious errors such as these:
```
> myproj@2.0.0 deploy /Users/paul/src/myproj
> npm run arc-deploy && arc-env verify
        app ⌁ myproj
     region ⌁ us-west-2
    profile ⌁ undefined
    version ⌁ 5.9.37
✓ Static asset fingerpringing enabled
✓ Orphaned file pruning disabled
/Users/paul/src/myproj/node_modules/aws-sdk/lib/util.js:983
      return str && str.indexOf('arn:') === 0 && str.split(':').length >= 6;
```

### Expected behavior
I expect the static assets to be fingerprinted.

### Workaround

A workaround is to put the directive at the end of the section, e.g.,
```
...
@static
staging myproj-staging
production myproj-production
fingerprint true
```

**Comment by ryanblock** [comment]
Architect `6.2.5` does not exhibit this behavior, but confirmed that it replicates in Architect `5.x` – will look into this, but please note that version is in critical maintenance fixes only, so it won't be at the top of the heap. Thanks for reporting @toothbrush!
