### ISSUE TITLE
Intercepting outgoing http requests with nock library

### ISSUE THREAD

**Issue by leftieFriele** [architect/architect#723]
I am trying to use the [nock](https://github.com/nock/nock) library to intercept out outgoing HTTP requests in a HTTP Function, but I am having no luck in getting it to replace the outgoing HTTP request as it is supposed to. 
This approach works in other contexts so I was thinking there is something in `arc` which makes this not work.

**Steps to reproduce**
.arc
```
@app
myApp

@http
post /someroute/path
```
HTTP function
```
const arc = require('@architect/functions')
const fetch = require('node-fetch')

exports.handler = arc.http.async(handler)
async function handler (req, context) {
  try {
    const r = await fetch('http://iamanurl.com/lol')
    return {
      statusCode: r.status,
      body: req.body.object,
      type: 'text/html'
    }
  } catch (e) {
    console.error(e)
    return {
      statusCode: 204
    }
  }
}
````
I have this test written with [mocha](https://mochajs.org/)
```
const sandbox = require('@architect/sandbox')
const assert = require('assert')
const nock = require('nock')
const { describe, it, before, after } = require('mocha')
const fetch = require('node-fetch')

describe('Post Create', () => {
  let end
  before(async () => {
    end = await sandbox.start()
  })
  after(() => {
    end()
  })
  describe('test case', () => {
    it('Should return 500', async () => {
      nock('http://somehost.com').get('/lol').reply(500)

      const response = await fetch('http://localhost:3333/someroute/path', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ object: 'value' })
      })
      assert.strictEqual(response.status, 500)
    })
  })
})
```

**Expected behavior**
I was expecting the test to pass, as I have configured nock to mock the outgoing request. However, the fetch throws an error (see below) and the test does not return with the mocked request status code.
```
FetchError: request to http://iamanurl.com/lol failed, reason: getaddrinfo ENOTFOUND iamanurl.com
    at ClientRequest.<anonymous> (/Users/*******/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:478:20)
    at Socket.socketErrorListener (_http_client.js:407:9)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:478:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'request to http://iamanurl.com/lol failed, reason: getaddrinfo ENOTFOUND iamanurl.com',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```
**Desktop**
Please complete the following information (if appropriate):
 - OS: Mac
 - Arc Version 6.2.4

**Comment by leftieFriele** [comment]
I read through some of the sandbox code and I think that the reason why nock can not intercept the requests is that the http function is spawned as a child_process. 

What I ended up doing was to change my unit-test into testing the `handler` function directly with a mocked Request object similar as to what is done in the unit tests for Sandbox.

**Comment by ryanblock** [comment]
I'm wondering if we should potentially have an API to do this, what do you think?
