### ISSUE TITLE
Sandbox watcher for`.arc` file generates expected directory structure

### ISSUE THREAD

**Issue by trevoro** [architect/architect#732]
When running `arc sandbox` I typically have an editor open in another window. If I make any changes to the `.arc` file which describes all the routes then it would be nice if the sandbox could optionally generate the directory structure which arc would normally generate if you re-ran `arc sandbox` or `arc init`. This way, when doing development a change to the `.arc` file could automatically create any new directories which arc would expect and would generate anyway on successive executions of `arc`. 

I recognize this might not be desired behaviour for all users. Not sure if this is good _default_ behaviour but we could have a flag or some setting in a config file ignored by `.gitignore` that would let you set your local development behaviour. With an opt-in flag, usage would be something like

```
$ arc sandbox --generate
``` 

I can wrap this in another process to watch the .arc file but that has bad ergonomics.

[See Slack Conversation](https://architecture-as-text.slack.com/archives/C6BGT0D08/p1584634488370100)

**Comment by ryanblock** [comment]
Thinking I’m going to do some watcher work today and make this default enabled with a new config file that will let you disable, eg:
```
// .sandboxrc.js
module.exports = {
  autoInit: false
}
``` 
Wdyt?

**Comment by trevoro** [comment]
+1 to the native JS config format. The only thing I'm thinking about are the trade-offs between  `.sandboxrc.js` vs `.arcrc.js` with a section for `sandbox`. That way it's clear where config settings would go in the future and would avoid a rename. YNGNI might apply here but.. its one more line.

```
// .arcrc.js
module.exports = { 
  sandbox: {
    autoInit: false
  }
}
```

Just food for thought!

**Comment by ryanblock** [comment]
I'm actually working through two competing approaches, the one above, and actually adding this into the `.arc` file as config there:
```arc
@sandbox
autoInit false

startup
  path/to/file/to/execute.js
  another/path/to/file.js

watch
  public

ignore
  node_modules

run
  watcher/script/to/execute.js
```
Personally, I think all this stuff should live in the .arc file, but here's a use case I'm thinking of.

- Alice is a backend dev and is working locally on a new feature; they need to run script (`scripts/alice-dev.js`) every time file `src/shared/foo.js` changes
  - Also, Alice does not like having sandbox auto init new files
- Bob is a frontend dev and is working on a different part of the codebase; they don't need to run any scripts at this time
  - Also, Bob does like having sandbox auto init new files, and wants it to do that

In this scenario, a `.sandboxrc` that isn't checked in means they can both work as they please. This config in `.arc` (or anything checked in) means teammates are forced to use the same local workflows.

Thoughts?

**Comment by ryanblock** [comment]
Just bumping this!

**Comment by trevoro** [comment]
Hey,

Yep I think we're tracking the same thing just with a different `.dotfile` naming convention. I was thinking of a`.arcrc` which would contain all local developer config and that you would include that in your .`gitignore` file. That way it could have global config like what you've written but in a separate file. At the end of the day it doesn't matter too much <<cliche naming difficulty reference>>. 

On the structure of your config I like it. I think the only thing I'm pondering are the defaults. Does one make 'autoinit false' the default if not defined, or is it true?

**Comment by ryanblock** [comment]
Hmm, that's a really good idea. May also present some issues, but I dig it.

I think to the original thrust of this issue: autoInit should prob be false (imo).

**Comment by ryanblock** [comment]
This has been a great thread, thank you @trevoro! Moving this into https://github.com/architect/architect/issues/763
