### ISSUE TITLE
Architect 6 should respect @static staging + production

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#733]
**Describe the issue**
Architect 6 does not respect `@static staging / production` values, and instead allows them to be created and managed by CloudFormation.

That may be fine on the surface but those buckets may already exist and be attached to existing domains, workflows, etc.; if specified, Architect should attempt to use them instead of creating new buckets.

**Comment by brianleroux** [comment]
This was a deliberate breaking change. We don't want to use non cfn infra in arc 6 and greater. Too many edge cases.
