### ISSUE TITLE
.arc-env does not support emails

### ISSUE THREAD

**Issue by Stegosource** [architect/architect#737]
**Describe the issue**
The `.arc-env` file causes the app to crash if there is an email. Specifically, if there is an @ symbol:
```
Error: .arc-env parse error
PragmaSyntaxError: pragma "@stegosource.com" has illegal character(s)
```

**Steps to reproduce**
1. Add an env variable to `.arc-env` and assign it to an email address.
2. `npm start`

**Expected behavior**
App should begin and make variable available.

**Comment by Stegosource** [comment]
Actually, I got things to work by wrapping the email in double-quotes. This was confusing from the docs because the exmaple provided is:
```
# example .arc-env
@testing 
GLOBAL asdfasdf

@staging
GLOBAL_KEY val
```

So is this a bug with the @symbol assigned to a value? Or does every String type need to be in quotes?

**Comment by ryanblock** [comment]
Good news, fix for this just went out! Please update Sandbox (and it’s dependencies), then double quote any offending env vars.

**Comment by ryanblock** [comment]
Sorry, just saw your second message. Yes, some special characters are reserved by the parser, including @.

**Comment by Stegosource** [comment]
Thanks @ryanblock. So do all strings need to be wrapped in quotes? Because I also had an unexpected env variable that logged out as `NaN`. I'm sorry but I don't remember what I had set it to. I think it was just dummy data `1234567890`.

**Comment by ryanblock** [comment]
Not sure I entirely follow, but `1234567890` would be NaN because env vars are always coerced to strings.

**Comment by Stegosource** [comment]
Ah ok. That explains it. I didn't see that explained in the docs so wasn't sure. 
So to summarize:

- All env variables are coerced to Strings
- variables containing special characters should be wrapped in quotes.

**Comment by ryanblock** [comment]
That's right!

Fwiw env vars coerced to strings is not an Architect thing, that's just generally true of *nix, and I assume Windows as well. Might still be worth calling out in docs though!

**Comment by Stegosource** [comment]
Yeah, fair point. I've seen that before, but whenever I look at a new project I try to omit any assumptions and take things at face value. Sometimes it helps, sometimes it does not. For the docs, it may make sense to mention it for anyone that has not come across it before. Or maybe I'm just a special case :)
Well thank you for your help on this.
