### ISSUE TITLE
Arc 6.3.2 returns ECONNRESET on failure to load module

### ISSUE THREAD

**Issue by leftieFriele** [architect/architect#739]
**Describe the issue**
Upgrading to arc 6.3.2 error loading modules in a HTTP Function the request is hung up and arc does not return a HTTP 500 error as it used to do.

**Steps to reproduce**
1. Upgrade to arc version 6.3.2
2. Import an non-existing module in a http function
3. Start arc sandbox
3. Send a request to the function
4. The function fails with
```
request to http://localhost:3333/ failed, reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET"
```

**Expected behavior**

Expects arc to return a HTTP 500 and a log message to appear in the sandbox console with something like this:
`Error: Cannot find module '@architect/shared/lib/some-invalid-module'`

**Comment by ryanblock** [comment]
This is in production AWS infra too, or only in Sandbox?

**Comment by ryanblock** [comment]
Fwiw this does not reproduce for me:

**Comment by leftieFriele** [comment]
I have only gotten this error with sandbox.
I forgot one piece of information, which is that the route which produces the error is a `POST`, `GET` requests works as expected.
Here is the stack trace:
```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:452:3)
    at onwrite (_stream_writable.js:473:7)
    at internal/streams/destroy.js:60:7
    at Socket._destroy (net.js:664:5)
    at Socket.destroy (internal/streams/destroy.js:55:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:88:12) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by ryanblock** [comment]
I still need more information, posting is fine for me. What file is being posted, and in what format? Can you paste in the form and handler code?

**Comment by ryanblock** [comment]
Closing for now, please let me know if you get repro steps and this issue is still valid!
