### ISSUE TITLE
only invalidate cloudfront if @cdn in .arc

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#745]
I have a macro that creates a cloudfront distribution and I am not using the @cdn pragma, but arc fires an invalidation request to the entire distribution no matter what.

Issue is in this code: https://github.com/architect/deploy/blob/master/src/sam/02-after/03-maybe-invalidate.js.  Needs to check if arc.cdn exists

**Comment by jgallen23** [comment]
It also appears to disable my cloudfront on deployment

**Comment by brianleroux** [comment]
Hey sorry about this, can you share the macro ?

**Comment by jgallen23** [comment]
creating a simple image upload/optimize app.

Here's the macro:

```module.exports = function(arc, cloudformation, stage) {
  cloudformation.Resources.ImageHandlerDistribution = {
    Type: 'AWS::CloudFront::Distribution',
    Properties: {
      DistributionConfig: {
        Origins: [{
          DomainName: { 'Fn::Sub': '${MicroS3Upload}.execute-api.${AWS::Region}.amazonaws.com' },
          Id: { Ref: 'MicroS3Upload' },
          OriginPath: '/media',
          CustomOriginConfig: {
            HTTPSPort: 443,
            OriginProtocolPolicy: 'https-only',
            OriginSSLProtocols: ['TLSv1', 'TLSv1.1', 'TLSv1.2']
          }
        }],
        Enabled: true,
        HttpVersion: 'http2',
        Comment: 'S3 Upload Image handler distribution',
        DefaultCacheBehavior: {
          AllowedMethods: ['GET', 'HEAD'],
          TargetOriginId: { 'Fn::Sub': '${MicroS3Upload}' },
          ForwardedValues: {
            QueryString: false,
            Headers: ['Origin', 'Accept'],
            Cookies: { Forward: 'none' }
          },
          ViewerProtocolPolicy: 'https-only'
        },
        CustomErrorResponses: [
          {
            ErrorCode: 500,
            ErrorCachingMinTTL: 10
          },
          {
            ErrorCode: 501,
            ErrorCachingMinTTL: 10
          },
          {
            ErrorCode: 502,
            ErrorCachingMinTTL: 10
          },
          {
            ErrorCode: 503,
            ErrorCachingMinTTL: 10
          },
          {
            ErrorCode: 504,
            ErrorCachingMinTTL: 10
          }
        ],
        PriceClass: 'PriceClass_All',
      }
    }
  };
  cloudformation.Outputs.mediaDistribution = {
    Description: 'Media endpoint',
    Value: {
      'Fn::Sub': 'https://${ImageHandlerDistribution.DomainName}'
    }
  };

  //console.log(JSON.stringify(cloudformation, null, 2));
  //throw new Error();
  return cloudformation;
};```

**Comment by brianleroux** [comment]
hm. ok we have a chicken and egg problem here ! if you have `@http` defined and _do not_ have `@cdn` defined we'll delete any cdn distribution that uses that origin [1] … I'm debating if we just remove `@cdn` from architect altogether but that'd require a major bump. =/ open to suggestions here!

[1] https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/reads.js#L30

**Comment by jgallen23** [comment]
What about moving `@cdn` to a macro?  A quick, non-major, workaround is to have something like `@no-cdn` or `@cdn-disabled` or something like that to skip that after step.

**Comment by brianleroux** [comment]
def will be moving the networking stuff around (I think a sep stack for architect 7 given things like cdns and dns don't change much) … open to adding a flag to disable in the meantime. cc @ryanblock for thoughts

**Comment by cdn** [comment]
> def will be moving the networking stuff around (I think a sep stack for architect 7 given things like cdns and dns don't change much) …

You’re right, I don’t change very much :-)

**Comment by brianleroux** [comment]
sorry for the noise cdn! 😬

**Comment by jgallen23** [comment]
@brianleroux happy to submit a PR for a flag to disable - preference on naming convention?

**Comment by brianleroux** [comment]
yes, thanks thats appreciated, how about a flag under `@aws` ?

```
@aws 
cdn false
```

**Comment by jgallen23** [comment]
does this seem like the right place for the check? https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/index.js#L39  Just return early if cdn false?

**Comment by brianleroux** [comment]
yep that'd do it!
