### ISSUE TITLE
@events does not deploy to aws (possible issue with http-api macro?)

### ISSUE THREAD

**Issue by itsUnsmart** [architect/architect#748]
**Describe the issue**
A clear and concise description of the bug

I recently added an event to my arc file and everything works just fine locally as expected however when deploying I get thrown an error saying: "Resource with id [SomeEventHere] is invalid. property Topic not defined for resource of type HttpApi"

I am using the http api macro and the fact it says "Topic not defined for resource of type HttpApi" leads me to believe it may be an issue with that, as arc sandbox ignores the macro or at least does not conform to the same standard that the http api does.

**Steps to reproduce**
4. See error that says '....'

add the architect/macro-http-api macro 
add an event try to push to aws

**Expected behavior**
A clear and concise description of what you expected to happen

It should push up to aws with the event

**Comment by ryanblock** [comment]
HTTP API macro is deprecated and HTTP APIs were made the default in Arc 7, this issue should no longer occur. Please let us know if you see anything wonky!
