### ISSUE TITLE
static s3 uploading to the wrong bucket

### ISSUE THREAD

**Issue by jgallen23** [architect/architect#750]
we have a macro that creates an s3 bucket to allow for users to upload images.  You can see the macro here: https://github.com/firstandthird/arc-macro-s3-bucket.  The problem is when you also have static assets to upload, it uploads to the s3 bucket created in the macro instead of the static assets

![Screenshot 2020-04-01 at 12 13 00 PM](https://user-images.githubusercontent.com/27936/78181131-ba308300-7418-11ea-97ad-c53f6fbb615e.png)

After changing the name of my resource to zArcS3Bucket:
![Screenshot 2020-04-01 at 12 13 29 PM](https://user-images.githubusercontent.com/27936/78181185-c7e60880-7418-11ea-9f85-7f865d617ffa.png)

it worked:
![Screenshot 2020-04-01 at 12 13 17 PM](https://user-images.githubusercontent.com/27936/78181197-cb798f80-7418-11ea-84ec-7d6e3f322a39.png)

Probably best to have the static uploader look for the specific bucket rather than traversing the cloudformation for the first s3 bucket

**Comment by ryanblock** [comment]
Got it, this makes sense!
