### ISSUE TITLE
Support @http options

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#760]
**Describe the issue**
Today, one cannot create a function to handle HTTP `options` preflight requests; those instead wind up falling back to `get /` to be handled for all endpoints.

That's probably fine for many cases, but likely anyone being mindful of how they handle CORS preflight requests will want to set up an actual proper `options` endpoint.

It'd probably look like this:
```
@http
get     /foo # src/http/get-foo
put     /foo # src/http/put-foo
options /foo # [new!] src/http/options-foo
```

**Comment by Stegosource** [comment]
First question I have is, do all `OPTIONS` requests go through the root URL? Or will this allow for configuring on a per-route basis?

If this allows for per-route, then would it still allow for a catch-all at the root?

I think the scenario I would like to avoid is having to configure an `OPTIONS` handler for every route that needs it.

**Comment by ryanblock** [comment]
Right now how it works is:
- The root is greedy
- Thus, if you receive an HTTP request for a method and/or path that your project doesn't have, it goes to root
- And since we don't have support for creating `options` functions, that means all `options` requests go to root

If we add support for `options` functions, root would still catch all unhandled requests.

Of course, if we think the best answer is: "just handle CORS in `get /`", I am more than fine to not write a bunch of new code to support `options`! ✨

**Comment by Stegosource** [comment]
Well, if Im the first person to run into this, then I think the simplest solution is to solve it in the docs. What we have now works perfectly fine, and I dont forsee the need to customize options on a per-route basis. That may change one day, but I dont think it makes sense to tackle that problem before it's a problem.

**Comment by ryanblock** [comment]
Hard to say if you're the first to run into it, tbh! We do get questions about CORS pretty frequently, but I think that's more to do with CORS tbh, because CORS is CORS, and literally we're all plagued by it. Solving with docs is def a thing we need to do either way!

**Comment by Stegosource** [comment]
Yeah. I've made a couple small edits, but I'd like to get a better grip on things and then start contributing more. In any case, hopefully some of the discussion here will help folks that DuckDuckGo it.

**Comment by krimple** [comment]
Can we re-open this to tighten up the deploy to check the same level as sandbox?

**Comment by ryanblock** [comment]
Sorry, I don't know what that means, can you please break that down a bit more?

**Comment by krimple** [comment]
So I see that when you do arc deploy, it doesn't catch the bad @http options entry. It deploys a lambda, maps it to OPTIONS in the path (so / is not greedy with OPTIONS then). But when running arc sandbox, it flags it and fails with options being invalid for a path with substitution parameters.

**Comment by krimple** [comment]
I can create this as another issue if you want, Ryan. Whatever makes sense.

**Comment by ryanblock** [comment]
Sure, that'd probably help, with detailed steps to reproduce!

**Comment by krimple** [comment]
ok, will do.
