### ISSUE TITLE
Allow for modifiers in route config

### ISSUE THREAD

**Issue by thedersen** [architect/architect#765]
**Is your feature request related to a problem? Please describe.**
When writing a macro to add/extend behaviour (e.g. auth) on some of the routes, it is a bit cumbersome to have to repeat the configuration for the routes in a new pragma.

**Describe the solution you'd like**
Here is an example of a proposed syntax to allow for modifiers per route:
```
@app
my-super-secure-app

@jwt
issuer https://example.oauth.com/
audience https://example.com,https://example2.com
scopes read:foo,write:foo

@http
get /
get /foo --jwt
get /bar --jwt read:bar,... --modifier

@macros
architect/macro-http-api #Required until HTTP APIs are default in arc
arc-macro-jwt
```

Atm, this works fine when deploying, but sandbox complains about schema validation errors and won't start..

**Describe alternatives you've considered**
The alternative is of course to somehow duplicate the routes in the custom pragma, but then you have at least two places to update..

**Additional context or notes**
Here is a macro where I implemented this solution (using the [yargs-parser](https://www.npmjs.com/package/yargs-parser)): https://github.com/thedersen/arc-macro-jwt

**Comment by ryanblock** [comment]
I don't have any strong opinion about this approach, but it seems like it opens up a lot of potential complexity and vectors for issues in validation.

May I instead suggest doing it all in a single custom pragma (e.g. `@http-params`), and that you perform a first pass of just the `{method} {path}` parts of the entries in that pragma against `@architect/package` (to get the cloudformation), and then augment the remaining modifiers with your macro?

**Comment by thedersen** [comment]
No strong options here either, just think it should be easier than current solution:)

I think what you suggest would cause sandbox to stop working since it needs the route config in @http?

Also, this could potentially be an issue if you use more than one macro that modifies @http. 

What if you relax validation a little bit and only validate what is required by arc, and just ignore if there is more config in .arc? Possibly you could show a warning, but that might not be necessary.

**Comment by ryanblock** [comment]
Fair point about sandbox. What about custom pragmas in .arc-config files? As the name suggests, that’s the convention for adding per function/route configuration.

**Comment by thedersen** [comment]
Yes, of course! I'll try that. Thanks for your help:)

**Comment by ryanblock** [comment]
No problem! Macros don’t currently have a built in way of reading the arc configs out and aggregating them (that’s something that Deploy does deeper down, though, if you want to see that code). lmk if you come up with a nice way to do that or feel you need an API!

**Comment by brianleroux** [comment]
Mention this but you can have `@http` as is (without extras) and add a new pragma `@params` which is a copy paste of the current http pragma. Some duplication but sandbox and pragma would work as this is additive. Into exploring extension to "core" pragmas but this is a good workaround for now.

**Comment by thedersen** [comment]
Shouldn’t be a problem reading the file and pass the content to the parser. I’ll let you know if I run into any issues👍
