### ISSUE TITLE
Make Websocket RouteSelectionExpression consistent between AWS & sandbox

### ISSUE THREAD

**Issue by mawdesley** [architect/architect#768]
**Is your feature request related to a problem? Please describe.**
When running `arc sandbox` `RouteSelectionExpression` is set to `$request.body.action`, but when running `arc deploy` the cloud formation template sets it to `$request.body.message`.

This means that code which works in test, doesn't work in staging/prod. It's pretty confusing if, like me, you're new to lambda.

**Describe the solution you'd like**
Ideally I'd like `RouteSelectionExpression` in the cloudformation template to default to `$request.body.action`.

**Describe alternatives you've considered**
Currently I'm using this macro as a work around:

```
module.exports = (arc, cloudFormation, stage)  => {
    cloudFormation.Resources.WS.Properties.RouteSelectionExpression = "$request.body.action";
    return cloudFormation;
}
```

**Additional context or notes**
I'm pretty new to this, so apologies if this issue is due to some stupid mistake on my end.

Cheers!

**Comment by ryanblock** [comment]
Thanks @mawdesley – no need for the preemptive apologies, there's almost no such thing as a stupid mistake in AWS land, we're all beginners when it comes to this level of complexity.

What would be helpful for me to better diagnose would be to have specific steps to reproduce the issue – the above outlines a solution.

Thanks!

**Comment by mawdesley** [comment]
In this example I'm not using the workaround described above.

In my `.arc` file I've specified websocket handlers with a `customEndpoint` route:
```
@ws
customEndpoint
```

In the client side code, I'm connecting to the websocket gateway and attempting to hit the `customEndpoint` lambda:

```javascript
let ws = new WebSocket(WEBSOCKET_URI);

 ws.onopen = () => {
      ws.send(JSON.stringify({action: "customEndpoint"}));
 }
```

The above works perfectly when ran locally with `arc sandbox`, but on AWS these messages arrive at the `$default` lambda instead.

AWS is expecting the route key to be the `message` rather than `action` property, if I change the client code to the below, it works on AWS, but not in sandbox mode:
```javascript
let ws = new WebSocket(WEBSOCKET_URI);

 ws.onopen = () => {
      ws.send(JSON.stringify({message: "customEndpoint"}));
 }
```

It would be possible to send both `message` and `action` properties, i.e. `{ message: "customEndpoint", action: "customEndpoint" }`, but that feels a bit icky.

Hope this helps, let me know if you need any more details!

**Comment by ryanblock** [comment]
Got it, thanks! Will take a look ASAP, sounds pretty straightforward.

**Comment by tbeseda** [comment]
Note from maintainer's call: need to make an effort to reproduce

**Comment by MartinRamm** [comment]
I just ran into this issue. A reproducible example is available under https://github.com/MartinRamm/architect-issue-768

The issue is the mismatch between https://github.com/architect/package/blob/main/src/visitors/ws/index.js#L19 and https://github.com/architect/sandbox/blob/main/src/http/register-websocket/connection.js#L22.

**Comment by ryanblock** [comment]
Patched here: https://github.com/architect/package/pull/166/commits/7842ca1d8b7d2fd48716b3fb9661590a094885d8
