### ISSUE TITLE
Problem with Windows + @static fingerprint true + deploy

### ISSUE THREAD

**Issue by bbarthel** [architect/architect#782]
**Describe the issue**
static.json does not get uploaded to s3 and returns error:

Error on headObject request MissingRequiredParameter: Missing required key 'Key' in params
    at ParamValidator.fail 

**Steps to reproduce**
Steps to reproduce the behavior (Windows):
1. arc deploy static --verbose

**Expected behavior**
No errors and all files are uploaded, including static.json

**Comment by ryanblock** [comment]
Yikes, this can got kicked down the road. It'll be released today in `8.0.1`!
