### ISSUE TITLE
Enabling DB Table Encryption Throws Error

### ISSUE THREAD

**Issue by m-butler** [architect/architect#785]
**Describe the issue**
I've enabled encryption on my table via `encrypt: true` but i'm getting an error which kills the sandbox process.

**Steps to reproduce**
1. Add `encrypt: true` to your .arc file under you table declaration
2. Run `arc sandbox`
3. See the error

**Expected behavior**
The sandbox environment should start, serve local database, and allow for local development

**Desktop**
 - OS: MacOs 10.15.4
 - Version 6.3.5

**Additional context**
I previous had my tables set without encryption and just recently added the encrypt declaration. Would that make a difference?

Also, I tried removing all tables, running arc sandbox to clear the data, then adding them back again, but the issue still remains.

Here is the error:
`
<project>/node_modules/aws-sdk/lib/request.js:31
throw err;
 Error [TypeError]: attr[k].replace is not a function
<project>/node_modules/@architect/sandbox/src/db/create-table/_get-attribute-definitions.js:6:38 at Array.forEach (<anonymous>) ...
`

**Comment by m-butler** [comment]
Can someone shed some light on this for me?

According to the ARC encryption section: 
> By default tables are not encrypted

According to the AWS docs [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption.usagenotes.html):

> Server-side encryption at rest is enabled on all DynamoDB table data and cannot be disabled.

If this is the case what encryption is the ARC documentation referring to or is it just out of date?

**Comment by ryanblock** [comment]
Sorry, extremely slammed this week, will check back on this ASAP!

**Comment by filmaj** [comment]
I can confirm this problem as well.

It looks to me like sandbox can't handle `encrypt` attributes set up in a `.arc` file. Looks like sandbox only ever expects either key names of `String` or `Number` under an `@tables` pragma definition (see [here](https://github.com/architect/sandbox/blob/master/src/db/create-table/_get-attribute-definitions.js#L6)).

This code seems to be identical to code used in architect/package for creating the CloudFormation JSON defining the entire app infra (see [here](https://github.com/architect/package/blob/master/src/visitors/tables/get-attribute-definitions.js)) - with one exception: [architect/package runs a `clean` on attributes passed in to `get-attribute-definitions`](https://github.com/architect/package/blob/master/src/visitors/tables/index.js#L37). That seems to be the key missing piece here as [`clean` ignores `encrypt` when pulling out attribute names and types](https://github.com/architect/package/blob/master/src/visitors/tables/clean.js#L6).

The resolution here, I think, is sandbox needs similar `clean` code.

**Comment by filmaj** [comment]
Actually my bad, sandbox does have a [`clean`](https://github.com/architect/sandbox/blob/master/src/db/create-table/_remove-ttl-and-lambda.js), but it is missing ignoring the `encrypt` parameter.

**Comment by filmaj** [comment]
BTW I `npm link`ed the PR I sent to sandbox to fix this issue (open at https://github.com/architect/sandbox/pull/340), ran it locally, confirmed it works.

If you want to give it a shot, you can `npm install --save filmaj/sandbox#encrypt-db-sandbox-fix` and then run `sandbox` or `./node_modules/.bin/sandbox`.

**Comment by m-butler** [comment]
@filmaj great thanks. Can anyone chime in on my question above though? 

> Can someone shed some light on this for me?
> 
> According to the ARC encryption section:
> 
> > By default tables are not encrypted
> 
> According to the AWS docs [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption.usagenotes.html):
> 
> > Server-side encryption at rest is enabled on all DynamoDB table data and cannot be disabled.
> 
> If this is the case what encryption is the ARC documentation referring to or is it just out of date?

**Comment by filmaj** [comment]
Yeah, looks to me like encryption at rest is enabled by default by AWS using an AWS-owned key.

[Here](https://github.com/architect/package/blob/master/src/visitors/tables/index.js#L49-L56) is how the DB properties are set before arc deploys it out to AWS. If you look at the [CloudFormation docs on these properties](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html) (scroll down to `SSEEnabled`), it says:

> Indicates whether server-side encryption is done using an AWS managed CMK or an AWS owned CMK. If enabled (true), server-side encryption type is set to KMS and an AWS managed CMK is used (AWS KMS charges apply). If disabled (false) or not specified, server-side encryption is set to AWS owned CMK.

So if you don't set `encrypt`, encryption is still enabled (AWS default) at rest, the key is AWS owned, and no additional charges apply. If you do set `encrypt`, you have the option of specifying which key is used for encryption and an additional AWS KMS charge will apply.

**Comment by m-butler** [comment]
Doesn't that make `encrypt true` totally obsolete then? If someone specifies `encrypt someValue` then we know they're using a custom, self-managed key. The current docs just add to the confusion IMO. However, those are getting refreshed from what i've seen, correct?

(btw, loving Architect. Thanks for everyone's hard work that put it together! 🙂)

**Comment by filmaj** [comment]
Yes I think you are correct, `encrypt true` is on by default and really only `encrypt <some-ARN>` is valid. Docs need updating for sure! One of these upcoming days this week I'll do a big cleanup and put some time into the docs.
