### ISSUE TITLE
@scheduled function cannot have the same name as the @app

### ISSUE THREAD

**Issue by orthagonal** [architect/architect#798]
**Describe the issue**
If you have a @scheduled event that has the same name as your @app, the Resources will conflict and you will get weird errors when you deploy.

**Steps to reproduce**
1. create a .arc project
2. give your app a name with @app
3. create a @scheduled event and give it the exact same name.
4. See error that says something like: '_**Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 3. Resource with id [GetIndex] is invalid. Event with id [GetIndexEvent] is invalid. RestApiId property of Api event must reference a valid resource in the same template. Resource with id [GetManual] is invalid. Event with id [GetManualEvent] is invalid. RestApiId property of Api event must reference a valid resource in the same template. Resource with id [GetTest] is invalid. Event with id [GetTestEvent] is invalid. RestApiId property of Api event must reference a valid resource in the same template.**_
'

**Expected behavior**
Not that.

**Comment by brianleroux** [comment]
Hmm. This does not reproduce with the following `.arc` file:

```
@app
bug

@scheduled
bug rate(1 day)
```

I was able to successfully deploy w Architect 6.3.2. The errors look like something to do with API Gateway ?

**Comment by ryanblock** [comment]
@orthagonal can you please paste your entire .arc file?

**Comment by orthagonal** [comment]
.arc:
**@app
healthcheck

@aws
profile ft
region us-east-1

@http
get /manual
get /test

@scheduled
healthcheck rate(5 minutes)

@macros
arc-s3-bucket
arc-macro-lambda-slack
arc-macro-logs

@logs
subscriptionFunction LambdaSlackHandler
subscriptionFilter ?error ?notice ?timeout ?"timed out"
retention 14

@s3**


Dependencies for those macros are:

  **"dependencies": {
    "@architect/architect": "^6.3.5",
    "arc-macro-lambda-slack": "^4.1.1",
    "arc-macro-logs": "^2.0.0",
    "arc-s3-bucket": "^2.2.0"
  },**


So it may be something in the macros that is interfering.

**Comment by jzohrab** [comment]
fyi I had the same error occur when an `event` and a `scheduled` thing were named the same.  Mentioned in slack, https://architecture-as-text.slack.com/archives/C6BGT0D08/p1593448589441800.  .arc file was

```
@events
reports                 # Generate reports
...

@scheduled
reports rate(12 hours)  # Fire event to regenerate reports
```

**Comment by jzohrab** [comment]
@orthagonal - how did you manage to get your deployment unstuck?  I'm considering doing a deploy with completely renamed objects, and then re-deploying with the proper names.

**Comment by ryanblock** [comment]
Closing in favor of https://github.com/architect/architect/issues/897
