### ISSUE TITLE
RFC: make app.arc the default project manifest file (instead of .arc)

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#805]
Dotfiles are usually configuration files one is ok with having hidden – they don't change often, and seeing them all the time in your project would just adds clutter. Obvious examples include: `.gitignore` and `.env` – they're there when you need them, but out of the way when you don't, which is almost all of the time. Set it and forget it.

However, in an Architect project, the manifest is a core application file. As your app grows and changes, so too does your project manifest – like any key project manifest. This is probably why we sometimes use the metaphor of ".arc is like package.json, but for your cloud infra". (`package.json` is, of course, not a hidden dotfile.)

We open sourced with `.arc` in 2017; in 2018 we [added `app.arc` file format support](https://github.com/architect/architect/issues/239), and have since added `arc.yaml`, `arc.json`, and `arc.toml` support.

We will continue support every each these formats (and filenames) for the life of the project; that will not change.

This issue is to propose the updating the default filename that Architect uses for new Architect apps, in examples, etc. to the more findable `app.arc`, instead of the less findable `.arc`.

yaml, json, and toml users are already used to their Architect manifests not being dotfiles; this would now extend by default to new projects using `app.arc`.

And again, of course, anyone who wants to use `.arc` as their filename can do so – we will support that filename forever.

**Customer impact**
None; nothing changes for current projects; new projects gain a more easily findable project manifest

**Code impact**
Essentially none; when creating a new project, we just write `app.arc` instead of `.arc`; I'd guess almost all of the change surface area would be in updating this line: https://github.com/architect/create/blob/master/src/bootstrap/_arc-template.js#L21

**Docs impact**
Moderate but should be fairly straightforward; easy to factor into https://github.com/architect/arc.codes.next right now though.

Thoughts?

**Comment by filmaj** [comment]
Sounds fine to me!

**Comment by brianleroux** [comment]
Yeah I'm into it!

**Comment by ryanblock** [comment]
Shipped in Create `1.1.0` and Architect `6.5.0`!
