### ISSUE TITLE
“You must specify a region,” even with region set

### ISSUE THREAD

**Issue by kennethormandy** [architect/architect#823]
**Describe the issue**
I’ve been getting an error where I’m told “You must specify a region,” even though I’ve set a region, and the Architect CLI output shows that correctly.

**Steps to reproduce**
Steps to reproduce the behaviour:

1. Configure `us-east-1` region in `~/.aws/config` and `.arc`
2. Run `arc deploy`
3. Output shows the region is `us-east-1`
4. The CloudFormation is created, but with a `ROLLBACK_COMPLETE` notice, and comes back with an error: “You must specify a region. You can also configure your region by running "aws configure".”
5. Delete the CloudFormation in the AWS console. You get a different error if you try and deploy again without doing that.
6. Delete the corresponding S3 buckets created as part of the failed deploy as well. The S3 buckets was listed as being on `ca-centra-1`, even thought I had specified `us-east-1`

To move forward past this point, I had to change the region from `us-east-1` to `ca-central-1`. Now, the deploy completes successfully, but I can’t deploy it on the region I’d expect.

## Expected

**Expected behavior**
The CloudFormation and S3 bucket are both successfully created in the `us-east-1` region.

**Screenshots**
If applicable, add screenshots to help explain your problem

<img width="982" alt="Screenshot 2020-05-20 09 39 07" src="https://user-images.githubusercontent.com/1581276/82485775-c936c780-9a90-11ea-809a-fb4c50de407f.png">

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS 10.12
 - Version: Architect 6.4.0

**Additional context**
Add any other context or notes about the problem here

Here is the error from Architect:

```
Uploading to abc.template  7280 / 7280.0  (100.00%)
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name SampleFunctionsStaging
```

If you run that command, you get:

```
You must specify a region. You can also configure your region by running "aws configure".
```

Here is the error you get if you try to re-deploy without manually deleting the CloudFormation first, although I only hit this because I didn’t understand what went wrong the first time around:

```
An error occurred (ValidationError) when calling the CreateChangeSet operation:
Stack:arn:aws:cloudformation:us-east-1:111:stack/SampleFunctionsStaging/aaa-111
is in ROLLBACK_COMPLETE state and can not be updated.
```

`.arc` file:

```
@app
sample-functions

@http
get /

@events
parse-file

@aws
region us-east-1
profile sample-functions
```

The deploy worked after changing `us-east-1` to `ca-central-1`.

It’s entirely possible there is something simple related to AWS regions or profile config I’m misunderstanding, so this might not be a bug. That said, to me it seems like the CloudFormation is being created in the correct region, but the corresponding S3 bucket is being created in the wrong region, possibly my account default region? Thanks for the help!

**Comment by filmaj** [comment]
Hi @kennethormandy, long time no chat 😄

As a quick sanity check: do you have an AWS region specified as environment variables? Maybe `AWS_REGION` or `AWS_DEFAULT_REGION` ? Maybe see what the output of `env | grep -i aws` is to check?

**Comment by kennethormandy** [comment]
Hey @filmaj! 👋

Yes that’s it. 🤦 Apparently I had those environment variables hard-coded into my `.bash_profile`, I don’t know why. Thanks so much for the quick fix.

Clearly that’s my mistake. If there’s any takeaway, seeing that listed as the region in the output would have made me realize there was a mismatch, but it’s also understandable if that only shows what is set in your `.arc` file. Thank you again!

**Comment by filmaj** [comment]
I think we could document that little extra bit on arc.codes, too, in the setup (maybe as an aside somewhere). Or link to the AWS docs on how regions are set (cli flags, env vars, AWS config) and how their precedence works (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html).

And this exact same thing happened to me as well when I got started with arc, so that's why it popped into my head!
