### ISSUE TITLE
Support for POST fallback for PUT and DELETE methods

### ISSUE THREAD

**Issue by andybee** [architect/architect#826]
**Is your feature request related to a problem? Please describe.**
Common practice for RESTful APIs is to use PUT and DELETE methods. When building a web front end around those same methods, because HTML doesn't allow a form to use methods other than GET or POST, it's common to use a hidden value in the form to infer an "alternate" method for the request, then send it over POST.

**Describe the solution you'd like**
It would be great if you could enable a mode (and this should definitely be optional rather than default) on a route that allowed it to be defined as PUT or DELETE and create the Lambda handler as usual, but setup Sandbox and API Gateway with a POST and PUT/DELETE route to the same Lambda function.

Ideally, if the PUT/DELETE route could modify the event before running the function to have the correct method in the event payload, that would be great, but I realise that could be quite a complicated API Gateway route setup and also stop the move to the simpler "HTTP" Gateway.

**Describe alternatives you've considered**
If you could define `any` as a @http route this would allow you to achieve similar when observing the incoming method. For cleaner code it would be useful if you could do something like:

```
@http
get /foo
any /foo
```

To produce a `get-foo` and `any-foo` Lambda function, so each function can keep it's scope tight.

**Comment by ryanblock** [comment]
Thank you, Andy! I’m wondering: is the current greedy root too coarse? Can you speak to that a bit more?

**Comment by andybee** [comment]
I guess that could work, but I love the separation of concerns with functions focussing on their tight scope so well, so I'm reluctant to start dumping more logic in to that root function.

Because I'm focussing on a web front-end rather than an HTTP API at the moment, I've just setup the POST endpoint for now (with a method override in already) so that this might get fixed in the future.

As my scope starts to creep, might this be something I can tackle in the future with a macro?

**Comment by ryanblock** [comment]
In theory this could be a macro, but I'm not sure about the implications as hydrate and other operations that run before macros utilize our app inventory system, which would look for things in certain places. Sounds like maybe we should roll this issue into https://github.com/architect/architect/issues/806 ?

**Comment by andybee** [comment]
Good shout, I think that potentially covers my use case and happy to try and consolidate the issue to focus attention.
