### ISSUE TITLE
Architect schema validation error

### ISSUE THREAD

**Issue by andybee** [architect/architect#829]
**Describe the issue**
As per the [docs](https://arc.codes/reference/arc/static), I'm trying to ignore a specific file from being deployed from the `/public` directory, but it's throwing a schema validation when starting Sandbox.

**Steps to reproduce**
1. Add the following from the documentation example to `.arc`
```
@static
ignore
  .tar.gz
  tmp
  user
```

2. Run `arc sandbox`
3. See error that says
```
× Error: Architect schema validation error
  @static invalid setting: "ignore"
```

**Expected behavior**
Sandbox should start and ignore deploying the `.eslintrc.json` file.

**Comment by filmaj** [comment]
Can confirm, gonna take a look

**Comment by filmaj** [comment]
Looks like the arc file you pasted above somehow invalidates the [parser's schema](https://github.com/architect/parser/blob/master/schema.json). I'm not familiar with JSON schemas so it'll take me a bit 😄 

In digging around in the parser code and testing locally, there is an unreported parsing error of "Cannot read property '0' of null" getting swallowed up in the [schema validation try/catch](https://github.com/architect/parser/blob/master/src/compat/validate.js#L39-L40).

I need to step out for the rest of the day but I'll see if I can get to the root of it tomorrow.

**Comment by ryanblock** [comment]
Yeah, I remember writing that error swallowing – I think was a byproduct of handling unpredictable datasets with AJV / JSON schema validation.

In any event, ignore should absolutely be respected!

**Comment by filmaj** [comment]
Still trying to figure this one out, slowly learning JSON schemas... here's the parsed arc JSON representation of the above `.arc` file, looking at just the `arc.static` property:

```
[ { ignore: [ '.tar.gz', 'tmp', 'user' ] } ]
```

... and here's the error returned by the JSON schema validator:

```
[
  {
    keyword: 'type',
    dataPath: '.static[0]',
    schemaPath: '#/properties/static/items/type',
    params: { type: 'array' },
    message: 'should be array'
  }
]
```

If I change the `.arc` file to match the example from https://arc.codes/reference/arc/static to:

```
@app
init

@static
fingerprint true
ignore
  .tar.gz
  tmp
  user
```

Then the parsed `arc.static` JSON representation looks like:

```
[ [ 'fingerprint', true ], { ignore: [ '.tar.gz', 'tmp', 'user' ] } ]
```

... and the schema validation error is:

```
[
  {
    keyword: 'type',
    dataPath: '.static[1]',
    schemaPath: '#/properties/static/items/type',
    params: { type: 'array' },
    message: 'should be array'
  }
]
```

Looks like it doesn't like the `ignore` setting to be represented as an object. I need to dig in further to learn more about how JSON schemas are written up to be able to suggest how to change the schema. Will continue digging into it...

**Comment by filmaj** [comment]
So I _think_ the issue is with the [schema for the `static`](https://github.com/architect/parser/blob/master/schema.json#L133-L185):

```
    "static": {
      "$id": "#/properties/static",
      "title": "@static",
      "description": "Static asset & S3 configuration",
      "uniqueItems": true,
      "type": [
        "array",
        "object"
      ],
      "maxItems": 6,
      "items": {
        "type": "array",
        "items": [
          {
            "type": "string",
            "enum": [
              "folder",
              "fingerprint",
              "ignore",
              "spa",
              "staging",
              "production"
            ]
          },
          {
            "type": [
              "string",
              "boolean",
              "array",
              "object"
            ]
          }
        ]
      },
      "properties": {
        "folder": {
          "type": "string"
        },
        "fingerprint": {
          "type": "boolean"
        },
        "ignore": {
          "type": [
            "string",
            "object",
            "array"
          ]
        },
        "spa": {
          "type": "boolean"
        }
      }
    },
```

The definition above allows for `static` to be either an array or object - but what we expect is that `static` will _always_ be an array. Instead, the validation of static 'settings' should include validating that they can be objects. It looks to me like we should move the object validation bits from the top-level `static` schema and move that into the `items` validation inside the `static` schema.

Playing around with that, I was able to resolve the issue. I'll issue a PR shortly.
