### ISSUE TITLE
Unable to deploy lambda with layers

### ISSUE THREAD

**Issue by jessrosenfield** [architect/architect#852]
**Describe the issue**
When running deploy of a scheduled lambda with the following `.arc-config`
```
@aws
runtime nodejs10.x
timeout 900
layers
  arn:aws:lambda:us-west-2:764866452798:layer:chrome-aws-lambda:8
```
The deploy fails for `ResourcesStatusReason` 
```
"ResourceStatusReason": "1 validation error detected: Value '[0]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+)] (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: da85e269-9e08-47a7-b797-3cd7665b8d5a)",
```
and the cloudformation output is `ResourceProperties` contains:
```
\"Layers\":[\"0\"]
```

When changing to
```
@aws
runtime nodejs10.x
timeout 900
layer arn:aws:lambda:us-west-2:764866452798:layer:chrome-aws-lambda:8
```
The deploy succeeds but `Layers` is not present in the resulting `ResourceProperties`, and the resulting lambda as visible in the AWS console has no layers.

**Steps to reproduce**
1. Make a scheduled lambda function
2. Use the above arc configs for the lambda (with it scheduled in the .arc file)
3. Run arc deploy

**Expected behavior**
The lambda has the layer arn:aws:lambda:us-west-2:764866452798:layer:chrome-aws-lambda:8

**Additional context**
Used node v10.19.0, architect 6.4.0

**Comment by brianleroux** [comment]
Hi thx for reporting! Confirmed and reproducing the first bug but not the second. 

Can you confirm the layer is in the same region as the code you are deploying? 

Another idea, can you check the layer has permission to be added by trying to manually add in the console?

**Comment by jessrosenfield** [comment]
Hi Brian, I've confirmed that the layer is in the same region as my project and have successfully  added (and removed) the layer manually.

**Comment by brianleroux** [comment]
Weird, hm, ok…is the arn public for me to try ?

**Comment by jessrosenfield** [comment]
Yep! I got it here: https://github.com/shelfio/chrome-aws-lambda-layer

**Comment by brianleroux** [comment]
Ok, dope, quick update! Thx =) Got it working w inline syntax and `AWS_REGION=us-west-2 arc deploy` to deploy:

<img width="797" alt="Screen Shot 2020-06-08 at 5 58 19 PM" src="https://user-images.githubusercontent.com/990/84094480-c35a4500-a9b1-11ea-94bd-7cde80d91506.png">

<img width="1120" alt="Screen Shot 2020-06-08 at 5 57 59 PM" src="https://user-images.githubusercontent.com/990/84094484-c48b7200-a9b1-11ea-99d8-6e7add8424df.png">

(What version and command args are you using to deploy?)

**Comment by ryanblock** [comment]
I’m aware of the issue, it’s an unexpected breaking change in the way the new parser parses arrays, I discovered this bug independently last week! Should be able to patch shortly.

**Comment by brianleroux** [comment]
@jessrosenfield note for the working example on one line it's `layers` not `layer` (I will be adding this alias today also)

**Comment by jessrosenfield** [comment]
Thanks, one line worked! I used `layer` after referencing this note in the changelog: https://github.com/architect/architect/blob/master/changelog.md#added-31

**Comment by jessrosenfield** [comment]
@brianleroux however, when running a dirty deploy with 
```
@aws
runtime nodejs10.x
timeout 900
layers arn:aws:lambda:us-west-2:764866452798:layer:chrome-aws-lambda:8
```
I get 
```
× Error: Expected params.Layers to be an Array
```

**Comment by ryanblock** [comment]
Please stand by, fix in progress! Looking at this code, we've def got some issues to work out.

**Comment by ryanblock** [comment]
Hey @jessrosenfield, thanks again for bringing this to our attention, I think we've had some flux over the best way to handle layers (and other settings), so I rewrote the whole thing that handles that configuration and locked it up in tests: https://github.com/architect/package/pull/84

Now testing, would love your eyes on this! Aiming to ship to production today, tomorrow latest.

**Comment by ryanblock** [comment]
Patched and released in `6.4.1`! Thanks again for your patience, @jessrosenfield.

**Comment by ryanblock** [comment]
Oh and to be clear, all of the following layer syntaxes are respected:
```layer $ARN
layer $ARN
layer $ARN
layers
  $ARN
  $ARN
  $ARN
layers $ARN
layers $ARN
layers $ARN
layer
  $ARN
  $ARN
  $ARN

**Comment by jessrosenfield** [comment]
Wow, thanks so much for such a speedy patch!
