### ISSUE TITLE
Consider adding support for Pipfile and Pipfile.lock

### ISSUE THREAD

**Issue by filmaj** [architect/architect#862]
More info: https://stackoverflow.com/questions/46330327/please-explain-the-usage-of-pipfile-and-pipfile-lock

Not sure what other arc modules would need to add support for different dependency management tooling... `architect/package`? Or perhaps only hydrate? That's a nice separation of concerns if its only this repo!

**Comment by brianleroux** [comment]
closing; tho we are open to getting a PR for this the AWS advice/behavior/happy path for SAM apps (which Architect generates) is `requirements.txt`

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html
