### ISSUE TITLE
Add credentials params for all Architect module API methods that make AWS SDK calls

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#865]
In doing some work this week on Deploy, I realized that we have a number of Architect modules that make AWS SDK calls, but that rely on credential instantiation via environment (which is accomplished via `utils/banner`).

That is not in line with how a module API call would be made, so we should ensure all Architect modules that have a published API and that make AWS SDK calls should accept `credentials` and `region` params, and that those modules instantiate those properly.

**Comment by filmaj** [comment]
Yes please, `banner` doing what it does makes my eye twitch!

**Comment by tbeseda** [comment]
Potentially out of scope. depending on future dev by aws-sdk 3.
