### ISSUE TITLE
RFC: static asset templating

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#874]
# Summary
[summary]: #summary

If you have enabled fingerprinting in your `.arc` you can access the fingerprinted value from text assets with the following syntax: `${arc.static('/path/to/asset.js')}`. The current implementation looks like JavaScript but it is really just a straight string replace. This RFC explores changing this implementation for a forwards compatible opt in to any templating language. 

# Motivation
[motivation]: #motivation

Static assets require fingerprinting once they are deployed. We can't control caching behavior over the internet so have to assume, and indeed encourage, long cache times for static assets to get the best performance. But we cannot cache `index.js` forever! Eventually that file will need to be updated. This is why we fingerprint static assets (eg `index-3s32a.js`) and cache those. If the code changes then so does the fingerprint and the cache is invalidated.  

Recently we added automatic redirecting to fingerprinted files from source paths `/js/foo.js` will automatically 302 over to `/js/foo-23xs3a.js` which solves the problem cleanly. However, we may want the entry file to use the fingerprinted value instead of the source value to save a 302 redirect request/response hop. To achieve this we can use the syntax `${arc.static("/js/foo.js")}`, and to be clear this works today, but we want to improve this capability with a more complete templating capability as hinted by the original syntax chosen. 

What use cases does it support? 

The prototype implementation swapped our string replace with a bundled version of lodash.template. This gave us string interpolation with the same syntax as above, as well as evaluation and html escaping with EJS style blocks. Pretty sweet. However dangerous as that syntax could impact real js and json files too. Rather than wholesale string replacing on text I think its likely we'd want to restrict templating to HTML documents only. Certainly have seen other formats templated but never liked it. If we need to start modifying source dynamically I think we should use proper parsers and transpilation/codemod techniques. 

What is the expected outcome?

Templating becomes opt-in, HTML documents only and supports multiple formats. We'll start with lodash but could see adding HAML, Pug, EJS, Mustache, Handlebars, Nunucks. I could see two ways of doing this. 

1. We could modify the `.arc` file with additional syntax:

```arc
@app
myapp

@static 
fingerprint true
templating lodash|mustache|?
```

2. We could make it based on file extension (like many static site generators do).

- `.html` &rarr; no templating
- `.lodash.html` lodash templating

(etc)

Bonus of this approach: we could support more than templating library simultaneously

**Comment by ryanblock** [comment]
I am (potentially) into extension mangling, but only if they correspond to what's in the `@static templating` setting – that can't be easily auto-configured without a ton of bug vectors (e.g. although it could be inferred, which would win if `/index.njk` and `/index.lodash.html` were present?), as well as incurring an S3 hit to do discovery on which files are present. IMO the templating should be a deterministic state set at deploy time.

**Comment by brianleroux** [comment]
think we'd want one or the other but not both…it's already a syntax opt-in we don't want to add configuration _and_ convention! ideally we choose. rules can be simple rather than broad: any extension dot html that matches gets templated. (Eg. `.lodash.html` is the only the way to get it to template that file and thats it.) what I like about this approach is the ability to mix/match multiple types and the arcfile doesn't get even more static options. if we do choose to add to the arc think it would be a global opt-in… (eg. all `.html` gets lodash templated if that is what you set)
