### ISSUE TITLE
Hardcoded DynamoDB region must be configurable

### ISSUE THREAD

**Issue by exalted** [architect/architect#887]
**Describe the issue**

Hardcoded region value (`us-west-2`) in https://github.com/architect/sandbox/blob/4549d955df5681a460d7e383e3ca2e303df4109f/src/db/_get-db-client.js#L26
is a problem when using [NoSQL Workbench for Amazon DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.html) to connect to a local DynamoDB server (i.e. `dynamodb-local`) since NoSQL Workbench will generate a file such as `<aws_access_key_id>_<region>.db` where `region` will be `localhost` when connecting to localhost.

I think `region`'s value should be taken from usual places such as `AWS_REGION` environment variable, `~/.aws/*` configuration files, `region` setting in `@aws` pragma in `.arc` file, etc.

My current workaround is to change the npm installed code manually to `let region = 'localhost'`, and it's not ideal.

**Steps to reproduce**
4. See error that says '....'

**Expected behavior**
A clear and concise description of what you expected to happen

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):

**Mobile**
Please complete the following information (if appropriate):

**Additional context**
Add any other context or notes about the problem here

**Comment by ryanblock** [comment]
You definitely wouldn't want to set your Architect project manifest's `@aws region` to `localhost` as you'd never be able to deploy. I can see making that line `let region = process.env.AWS_REGION || 'us-west-2'`, though – would that work?

**Comment by exalted** [comment]
If that's all it takes, it works for me!

**Comment by exalted** [comment]
How about setting `region = localhost` in `~/.aws/*` files? Any thoughts?

**Comment by ryanblock** [comment]
That would likely work to populate AWS_REGION env var, but again, anything you do in any hard configuration may result in unintended side effects if you are deploying from your machine. Since that's local AWS config it's less dangerous than doing it in your `app.arc` file, though.

Feel free to try the above approach locally and PR if it works for you!

**Comment by exalted** [comment]
Agreed not touching `app.arc` file 👍 and I totally agree on changing `region =` hardcoded value with `let region = process.env.AWS_REGION || 'us-west-2'`.

Will create the PR after having fiddled a bit.
