### ISSUE TITLE
Inconsistent static site behaviour between Sandbox and AWS deployment

### ISSUE THREAD

**Issue by andybee** [architect/architect#894]
When developing locally without an HTTP `/` endpoint declared in `.arc`, Sandbox maps `/public` to the root level, so you can build a static website inside `/public` and observe at `http://localhost:3333`.

This behaviour includes being able to request `http://localhost:3333/foo` and it being mapped to `/public/foo/index.html`.

However, once deployed, this behaviour results in the root index page being returned - presumably as a form of 404 capture where I have not defined a specific 404 error page.

Unless I'm mistaken, either Sandbox shouldn't behave this way or the deployment has a bug in not recognising index.html inside directories? Either way, the inconsistency feels like an issue to address so it doesn't catch people out during development.

**Comment by ryanblock** [comment]
Sorry, I’m not following. Can you please re post with the template repro steps and description of the issue?

**Comment by andybee** [comment]
My bad, in attempting to replicate this in an example project I realise Sandbox and deployment are consistent in that neither will map `/foo` to `public/foo/index.html` - both just return `public/index.html` only.

What's the easiest way of generating `/foo` as a static site path? Write the HTML straight to a file with that name? Does that cause issue in deployment with getting S3 to put the right (text/html) MIME type?

**Comment by ryanblock** [comment]
On my phone rn but try the following setting: @static spa false

**Comment by andybee** [comment]
That works, thanks!
