### ISSUE TITLE
@scheduled function can't have the same name as @events function (Architect 6.4.0)

### ISSUE THREAD

**Issue by jzohrab** [architect/architect#897]
**Describe the issue**

My `.arc` file had the following:

```
@events
reports     # Generate reports
```

I then added a scheduled item to call the event, looking like this:

```
@events
reports     # Generate reports
@scheduled
reports rate(2 hours)
```

When it ran, architect appeared to get confused, and one lambda overwrote the other.  When I checked the Lambda dashboard in AWS, only the scheduled lambda showed up (there was only one lambda `LiStaging-Reports-ETCETC`, and its code was that of the `scheduled` one.  This deploy was successful, but it shouldn't have been!

To attempt to fix it, I changed my .arc file so the scheduled one was named differently:

```
@events
reports     # Generate reports
@scheduled
gen-reports rate(2 hours)
```

When I did this, architect failed during deploy:

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Update of resource type is not permitted. The new template modifies resource type of the following resources: [ReportsReportsEvent]

    at ChildProcess.<anonymous> (/home/runner/work/li/li/node_modules/@architect/deploy/src/sam/spawn.js:23:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

To solve this problem, I followed Ryan Block's suggestion:

* comment out the reports function under events
* deploy to staging from local
* remove comment for that function, and redeploy

After these steps, there were two separate lambdas in AWS.

```
$ npx arc version
      Version: Architect 6.4.0
```

**Comment by ryanblock** [comment]
Fixed for new projects (but not existing ones due to CloudFormation constraints) in 8.3.0!
