### ISSUE TITLE
Sandbox proxy route behaves differently to AWS

### ISSUE THREAD

**Issue by andybee** [architect/architect#900]
With the following `.arc`:
```
@http
get  /
```

Sandbox route `/` accepts any method (e.g. `POST /` will respond). Once deployed, API Gateway has a resource `GET /` which overrides the later proxy resource's ability to capture any other method on `/` and so something like `POST /` won't work.

That behaviour makes sense, so I believe Sandbox should only accept requests to `/` with the methods defined in `.arc` if `/` is defined.

**Comment by ryanblock** [comment]
Patched in `6.5.3`. This behavior differs in AWS between REST and HTTP APIs, so I'll be revisiting this soon enough as we get ready to ship https://github.com/architect/architect/milestone/5
