### ISSUE TITLE
Sandbox key listener for rehydrating functions

### ISSUE THREAD

**Issue by andybee** [architect/architect#902]
I'm currently using `npm link` to test a local package inside `shared`. I understand that this is fragile and won't work once deployed, but it's speeding up local development until such a time that I need to create a "proper" private package and add it to a `package.json` inside `shared`.

The main issue with regard to Sandbox when using this approach is that writes to files that are symlinked aren't picked up by the file watcher and so rehydration of my functions doesn't occur to copy changes to all the functions.

I don't believe this functionality should change, but it would nice if there was a keypress listener within Sandbox so I could give it focus and tap, for example 'r' to force rehydration without having to restart Sandbox.

**Comment by ryanblock** [comment]
Good news, Sandbox hooks are in the works! https://github.com/architect/architect/issues/763
Would this work?

**Comment by andybee** [comment]
Ah, I've just realised reading that the reason the watcher probably doesn't pick up the changes is because those changes occur inside `node_modules` and presumably that's "blocked"? So if I understand correctly, with these config changes, I could force the watcher to pay attention to `node_modules` when I'm using a symlinked local package...?

**Comment by ryanblock** [comment]
May depend, we could and perhaps should enable that. Or at least enable that in src/shared and src/views. Idk, very open to ideas, use cases for this system are great and will influence how I’ll build this out in 6.7!

**Comment by ryanblock** [comment]
Hey, check out Sandbox `v1.13.0-RC.0` (`npm i @architect/sandbox@RC`), just added support for this!
  - Press `shift` + `H` to rehydrate all shared files
  - Press `shift` + `S` to rehydrate src/shared
  - Press `shift` + `V` to rehydrate src/views

**Comment by andybee** [comment]
Tested with a linked module and it works like a dream! Thanks.

As an aside, it's specifically a symbolic link that stops the watcher, I tried a few different odd scenarios and all triggered the watcher apart from updating a symbolically linked file inside `shared` or `view`.

I wonder if the watcher just sees the "source" path to the modified file, not the symbolically linked? Either way, I don't think it's something that should be fixed (it's not a safe way to do what I wanted to do).

**Comment by ryanblock** [comment]
Circling back to this, I didn't realize symlinks stop the watcher – what's the behavior?

Related, if you debug the watcher as it's working, in your local Sandbox install log out `event` and `filename` from this line: https://github.com/architect/sandbox/blob/master/src/cli/index.js#L116

**Comment by andybee** [comment]
Steps to reproduce:

1. Symlink a folder or file in to `shared`. In reality this will be a location outside of `src` (or at least, outside `shared`, which becomes important).
2. Make changes to the directory or file that is symlinked, no rehydration will trigger.
3. Restart Sandbox (forcing a rehydration) and `shared` is rehydrated in all functions with the symlinked file(s).

I added the console.log where you suggested and spotted the issue, watcher gets the original path, not the symlinked one, as suspected. This line therefore is false:

https://github.com/architect/sandbox/blob/08dc03e80ec9e1a81fd68027e98954ca29cd27f8/src/cli/index.js#L186

**Comment by ryanblock** [comment]
Got it – so how do you think we should handle that, if at all? `filename.endsWith('/src/shared')`?

**Comment by andybee** [comment]
Not sure, sorry. If you can't get the destination path I'm not sure what you could base the decision on?

**Comment by ryanblock** [comment]
This released to mainline today in `6.5.4`!
