### ISSUE TITLE
Making SNS calls directly with aws-sdk client to sandbox fails

### ISSUE THREAD

**Issue by vvo** [architect/architect#911]
**Describe the issue**
Hi there, in my setup, I am trying to use aws-sdk (js-v3) to directly make calls instead of architect/functions.

For example this way:

```js
import { SNS } from "@aws-sdk/client-sns";

async function run() {
  const client = new SNS({
    apiVersion: "2010-03-31",
    endpoint: "http://localhost:5301/events",
  });

  await client.publish({
    TopicArn: "slack-sync",
    MessageStructure: "json",
    Message: { hello: "world!" },
  });
}

run();
```

But this fails with:

```txt
         undefined:1
arc    | Message=%5Bobject%20Object%5D&MessageStructure=json&TopicArn=slack-sync&Action=Publish&Version=2010-03-31
arc    | ^
arc    |
arc    | SyntaxError: Unexpected token M in JSON at position 0
arc    |     at JSON.parse (<anonymous>)
arc    |     at IncomingMessage.<anonymous> (/Users/vvo/.config/yarn/global/node_modules/@architect/sandbox/src/events/index.js:26:28)
arc    |     at IncomingMessage.emit (events.js:327:22)
arc    |     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
arc    |     at endReadableNT (_stream_readable.js:1221:12)
arc    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Because it seems the sandbox and architect functions are linked implementation wise.

I guess I will have to use architect/functions but not sure how to use it outside of src/, I'll see!

PS: What is the idea behind architect/functions? It seems we can make calls directly using aws-sdk-js-v3 so it feels like added complexity BUT I am completely new to architect and aws so take this feedback with a gigantic mountain of salt.

**Comment by ryanblock** [comment]
A few things to note:
- AWS-SDK v3 is not a production release, and is not ready for production use (see: https://github.com/aws/aws-sdk-js-v3)
- AWS-SDK v3 is not bundled with Sandbox and is not available in Lambda, only AWS-SDK is
- As such, we don't officially support AWS-SDK v3 (yet!)
- FWIW, it looks like your message payload is a JS object, and not JSON-serialized, which is probably part of your problem

There's no dependency or link between Architect Functions and Sandbox; the idea behind Functions is to provide a runtime helper library for production AWS environments that smooths out some of the rough edges of working with AWS. It's entirely optional (and can be used in non-Architect projects as well).
