### ISSUE TITLE
env vars with special characters not correctly encoded in .arc-env

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#914]
if a user adds an env var with special characters we need to quote them when we write .arc-env to disk. the simplest solution here is to quote ALL env vars in `.arc-env` to ensure they are strings (which all env vars are!)

**Comment by ryanblock** [comment]
Added conditional quoting in https://github.com/architect/env/commit/577917397aad178ec9c338330448d2a2821a0b34

**Comment by ryanblock** [comment]
Released in `6.5.4`!
