### ISSUE TITLE
Error when Running a Query Using a Table Index

### ISSUE THREAD

**Issue by neilhoff** [architect/architect#917]
**Describe the issue**
I am trying to query using an index but keep getting this error:

`ValidationException: Query condition missed key schema element: trackID`

**Steps to reproduce**

Here is my .arc file

```
@tables
skytracks
  trackID *String
  _ttl TTL

@indexes
skytracks
  skyTrackType *String
```

Here is the relevant piece of the http get handler:

```
const skyTrackType = req.queryStringParameters.skytracktype
const data = await arc.tables()
const trackingData = await data.skytracks.query({
      KeyConditionExpression: `skyTrackType = :skyTrackType`,
      ExpressionAttributeValues: {
        ':skyTrackType': skyTrackType
      }
    })
```

**Expected behavior**
Return data

**Screenshots**
![image](https://user-images.githubusercontent.com/1918319/87426249-867f0080-c5a4-11ea-8089-c6e8e9aaf669.png)

**Desktop**
 - OS: Windows 10
 - Version: Architect 6.4.1

**Notes**

It feels like the index query is incorrect.

According to [AWS documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.Indexes.QueryAndScan.html) you need to have a key of IndexName with the name of the index in order to query it.
![image](https://user-images.githubusercontent.com/1918319/87426943-a19e4000-c5a5-11ea-8add-47e101a5c146.png)

How do you name an index? 

Is something missing from my .arc file?

**Comment by neilhoff** [comment]
I deployed to staging and logged into the DynamoDB to see the created name:

`skyTrackType-index`

I added `IndexName: 'skyTrackType-index'` to the query object and it worked.

It looks like the naming convention for indexes is:

`fieldname-Index`

**Comment by brianleroux** [comment]
Sorry Neil! This sounds like a bug. The naming convention is most def should be `app-index` but something must've changed. =/

**Comment by neilhoff** [comment]
I am new to DynamoDB. I apologize if this is an obvious question.

How can you have multiple indexes on the same table if each is named `app-index`?

**Comment by brianleroux** [comment]
sorry just in the middle of debugging something else and did not carefully read hte issue. we do not key on appname but rather the attribute of the index. so if you had the following arcfile

```
@tables
cats
  catID *String

@indexes
cats 
  owner *String

cats
  email *String
```
the indices would be `email-index` and `owner-index` respectively
