### ISSUE TITLE
Should catch defining a path-parameter based route at root level as an error prior to attempting to deploy to AWS

### ISSUE THREAD

**Issue by andybee** [architect/architect#928]
**Describe the issue**

Defining a route with a path parameter at the root level, the route will work locally within Sandbox but always fail when deploying to AWS. This is because the `{proxy+}` index handler prevents any other root-level path-parameter routes at root level.

Whilst it makes perfect sense for this behaviour, it would be preferred to catch this error much earlier on in development rather than only discovering it on deployment.

@ryanblock suggested this is a regression from the behaviour of v5.x.

**Steps to reproduce**

1. Create a new project with the following `.arc` snippet:
```
@http
get /
get /:slug
```
2. `arc sandbox` - the project will start as normal.
3. `arc deploy` - the project will fail to deploy to AWS with a CloudFormation error. Closer inspection of that error reveals API Gateway failed to create the route.

**Expected behaviour**

On launching Sandbox I'd expect some form of validation error when Architect first parses the HTTP section of `.arc`. Ideally this would be fatal and prevent you starting Sandbox. Effectively by not doing this, Sandbox's behaviour is differing from API Gateway.

Additionally, the same check should be run during the deployment stage so we could catch the same issue prior to hydration/building/uploading and request a CloudFormation deployment as none of those additional activities will work if this issue is not resolved.

**Comment by tbeseda** [comment]
Note from 10/21 maintainer call: This issue is definitely ongoing and part of a larger piece of work.

Sandbox needs an HTTP AST that can validate the route tree and match the AWS behavior.

Closing in favor of #977
