### ISSUE TITLE
Get Sandbox to delay response whilst hydration in progress

### ISSUE THREAD

**Issue by andybee** [architect/architect#933]
**Is your feature request related to a problem? Please describe.**
On larger projects, if you're quick on the browser refresh button, you can ask Sandbox to load a page before the hydration process has finished and therefore there's a good chance you'll see some kind of package import error where the old shared folder has been cleared but the new version yet to be copied in.

**Describe the solution you'd like**
One idea is that Sandbox becomes aware of the hydration process being "in play" and holds incoming requests until such a time that it's complete. For most tiny projects you'd never notice this behaviour and for larger ones, I'd much rather the delay on a page request than it blow up on me. Before working out what was going on the first time, I'd wasted a few minutes trying to work out what in my shared code's change had caused an import to stop working.

**Describe alternatives you've considered**
Being patient and watching the console until it's finished.

**Comment by filmaj** [comment]
Wondering about the same thing here, does the new symlinking fix or at least alleviate this issue?

**Comment by ryanblock** [comment]
This should no longer be an issue (unless symlinking is disabled). I feel ok to close this if you do, @andybee!

**Comment by andybee** [comment]
As with #934 I'm happy to close this for now as I'm confident the move to symlink has avoided the issues identified in the original request. Once I do finally migrate the project that exposes both issues I'll be sure to come back and try and provide any further info if I still have a problem.
