### ISSUE TITLE
CPU peaks/fans spin up when working in `shared` on larger projects

### ISSUE THREAD

**Issue by andybee** [architect/architect#934]
**Describe the issue**
I can be a touch trigger-happy on CMD+S when working on code and, truth be told, probably do it way more often than I should.

On mid-to-large sized Architect projects bashing this too frequently when working in the `shared` folder causes the fans on my relatively new well spec'ed MacBook to spin up. I'm uncertain if this genuinely a bug with the hydration process running more than once and fighting itself, or just a case that once you have 2, 3, 4 hydrations run sequentially it peaks the CPU long enough that the CPU temperature creeps up.

**Steps to reproduce**
1. Open a large (many handlers) Architect project which also uses a shared directory.
2. Run Sandbox.
3. Write to a file in shared in relatively quick succession.

**Expected behavior**
Working on any sized project shouldn't cause big enough CPU spikes that warrant the fan to spin up.

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS 10.15.6

**Comment by andybee** [comment]
Depending on what the cause is, I can think of a couple of possible solutions but all are likely to creep in to the "is this too much effort?" category:

- Hold off on changes to `shared` trigger hydration. First change happens instantly, if a subsequent one comes in within a second, hold off 1s, another, hold off 2s, etc. etc. etc. up to a maximum latency of, say, 30 seconds? Probably needs to be configurable and maybe even default to off.
- Disable hydration based on file writes to shared and instead "hydrate on demand" - when a request for a handler comes in (request handling checks shared is in sync, if not, updates it, then runs the request).

**Comment by filmaj** [comment]
Hey @andybee, I know it's been a while since you filed this, but did the new sandbox default of using symlinks for hydrating `src/shared` help at all here?

**Comment by andybee** [comment]
In all honesty I've not had chance to flip the offending project over to the latest version.

I'm confident the recent changes will resolve the issue, so happy to close this for now and will return to it if, once migrated, this still proves to be an issue.
