### ISSUE TITLE
Add "targeted sharing"

### ISSUE THREAD

**Issue by jzohrab** [architect/architect#945]
**Description**

I have a project where I wanted to create a fairly large "shared" item with some npm packages to model a fundamental domain concept, but I only needed that shared item in two or three lambdas, not across everything.  A "targeted shared" feature would have been very nice to have.

**Possible solution**

It would be great if I could create a subfolder under `src/shared`, with its own packages etc, and specify that this object should only be copied to specified targets.  This could be done with a file in the subfolder, or a master file at the top level of src/shared that gives instructions/restrictions.  hydration could parse this file and use it to override the hydration globbing (or however it's done).

e.g., `src/shared/targets.json`:

```
[
  { directory: "relative/to/src/shared/something", targets: [ "events/a", "events/b" ] },
  { directory: "thing2", targets: [ "http/*" ] }
]
```

If a directory isn't listed in targets, it's just copied everywhere.  If the directory listed, or target, doesn't exist where expected, it should throw.

Then in `events/a/index.json`, the `something` would be referenced as a regular shared file.

I would imagine that each target could potentially have its own node_modules etc, which would get copied as usual.

**Comment by ryanblock** [comment]
We've heard requests for this in the past, I think it may be a bit of a config-heavy and potentially brittle way to share code. That said, it can absolutely be done as a macro (and Sandbox startup script).

However, `@architect/inventory` (rolling in Arc 7-series) will allow multiple functions to target the same folder, so in theory if you create a function with a lot of shared code and only a little unique business logic between the various callers, you could point all those Lambdas at the same folder. Would something like that possibly work?

**Comment by jzohrab** [comment]
inventory might work, do you have a link with docs?

I don't think it's too config-heavy, it feels like the minimum spec that would meet the request.  Re brittleness, if there is a simple check that both source and destination exist, it could suffice.  It's no more brittle than a regular makefile (which can get hairy).

Macros and startup scripts could work just as well, but they wouldn't have the advantage of auto-hydrating the way that hydrate does.  I assume that users would want to keep auto-hydrate of shared code.

I can set up my own watchers, or just have a build step that copies everything where needed, but this felt like a natural extension to arc.  If you'd prefer to keep arc much lighter, then perhaps all that this needs is a note in the doc to say that this feature is out-of-scope for arc, and give examples on how to manage it (build steps, custom watchers, etc).

**Comment by tbeseda** [comment]
This should be a part of the Hydrate API
