### ISSUE TITLE
Broken "Multiple AWS Accounts"-link in documentation

### ISSUE THREAD

**Issue by Abszissex** [architect/architect#966]
**Describe the issue**
The link on the website https://arc.codes/reference/arc/aws  for the "Multiple AWS Accounts" documentation is broken.

**Steps to reproduce**
1. Go to https://arc.codes/reference/arc/aws
2. Click on **Multiple AWS Accounts**
3. See error that says **404 error: NoSuchKey**

**Expected behavior**
A website with the correct documentation is being displayed

**Screenshots**
Click:
![image](https://user-images.githubusercontent.com/4190798/94358012-0bef5880-009e-11eb-938e-49e6dc34b1d7.png)
Error page:
![image](https://user-images.githubusercontent.com/4190798/94358016-13aefd00-009e-11eb-8b15-ffe1de1b98aa.png)

**Comment by tbeseda** [comment]
Thanks for the report. The Quick Start has changed since this was filed. There's now a new doc explaining more detailed AWS setup.
