### ISSUE TITLE
Arc deploy removing @static entry from app.arc

### ISSUE THREAD

**Issue by kristoferjoseph** [architect/architect#971]
**Describe the issue**
When running `arc deploy` the needed `@static` pragma is being removed causing generated static assets to not be found in the deployed app

**Steps to reproduce**
  -  open app.arc
  - notice the @static pragma with a folder set to build
  - leave the app.arc file open
  - on the command line run npm run deploy
  - notice the @static pragma has been removed during the deploy
  - This causes the deployed app to fail because it is looking in the wrong folder for the needed generated static assets.

Here is a repo that reproduces the issue:
https://github.com/kristoferjoseph/arc-deploy-issue-001

**Expected behavior**
Expected behavior is that the `@static` pragma settings are maintained so that the app can find it's static assets

**Screenshots**
Before running `arc deploy`
<img width="262" alt="Screen Shot 2020-09-30 at 11 03 18 AM" src="https://user-images.githubusercontent.com/76308/94722792-a0f78900-030c-11eb-8049-c6effed66a2a.png">

After running `arc deploy`
<img width="287" alt="Screen Shot 2020-09-30 at 11 04 11 AM" src="https://user-images.githubusercontent.com/76308/94722838-b7054980-030c-11eb-8926-bd5e9e5d675b.png">

**additional context**
A user reported this issue while trying out migrating a begin app to arc deploy

**Comment by brianleroux** [comment]
think this got fixed in `7.0.5`

**Comment by kristoferjoseph** [comment]
Can confirm Fixed in `7.0.5`
