### ISSUE TITLE
RFC: breaking change to improve the default behavior of `get /`

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#973]
Currently, `@http get /` acts as a greedy catchall at the root – any requests not specifically caught by other routes get forwarded to your `src/http/get-index` handler. For example:
```
@http
get /
get /foo
```
- `get` requests to `/` go to `get /`
- `get` requests to `/foo` go to `get /foo`
- `post` requests to `/foo` go to `get /`
- `get` requests to `/bar` go to `get /`
- etc..

Over time, we've heard a lot of feedback related to confusion as to why `get /` is special and magical in this way. The decision behind this behavior made partly because earlier in Architect's life:
- We did not have support for greedy routes (where a single handler can greedily capture all requests underneath its current path)
- We did not yet have support for wildcard (`any`) http methods (where a single handler is responsible for any / all http methods)
- We frequently heard the feedback that we needed an easy way to build SPAs, and also that we ought to some way to backstop requests not caught by existing routes (presumably the same feedback that led AWS to add `$default` support in `HTTP` APIs).

Now the landscape has changed! As of this week's latest RC, we now have support for:
- New catchall syntax, ex: `get /*` (which captures all get requests beneath root)
- New `any`, `options`, and `head` methods, ex: `any /` (which captures all HTTP methods to `/`)

Combining the two – `any /*` – gets us the current `get /` greedy catchall behavior. This gives us the opportunity to make `get /` literal, and allow folks to opt into that behavior by defining `any /*`.

Doing so would be a breaking change, albeit a minor one. The upgrade path would be: **if** you use `get /` **and** you rely on `get /` to do more than just handle `get` requests to `/`, then you **must**:
- Change `@http` `get /` to `any /*`
- Rename your `src/http/get-index` folder to `src/http/any-catchall`

### Customer impact

Minor; generally this should address very common feedback making `get /` behave as people would expect. Remediation for the breaking change would be to change a folder name.

#### Sandbox

The Sandbox 2.0 refactor included a decent amount of work around `HTTP` APIs use of `$default`, which I'll need to refactor. I'd say the Sandbox work will be the meatiest portion of this change. Not sure how long it'll take, but Sandbox is now so extremely surrounded in tests I'm not sweating it.

#### Package & deploy

This is, on its surface, a quick change for Package and Deploy, and most of the work is already done. However, I think this change should be backwards compatible to ease folks migrating from Arc 6 directly to Arc 8, and that means adding support for catchall `*` syntax and `any` syntax to deploy, so that's going to add some work I wasn't expecting to do. Should be too bad, but it'll take a bit of time.

#### Everything else

Likely no (or only minor) impact.

### Docs impact

Minor, mostly additive.

That's it. I'd appreciate feedback on this change (and a corresponding bump to Architect 8)!

**Comment by brianleroux** [comment]
++ for Architect 8.x

**Comment by ryanblock** [comment]
Forgot to add the change impacts... adding now!

**Comment by kristoferjoseph** [comment]
I am normally against any kind of breaking change, but this one makes a lot of sense.

**Comment by filmaj** [comment]
It feels like a necessary and positive change for me, though I am also loathe to introduce breaking changes. 

How do conflicting combinations of HTTP verb and path parameters interact or take precedence? e.g. `any /*` and `post /api/user/:id`, or `any /api/*` and `post /api/`?

**Comment by ryanblock** [comment]
@filmaj short answer: conflicting combinations are dealt with in AWS by API Gateway (examples below), and in Sandbox by order in Arc manifest (until I at some point get around to the gnarly work of emulating their route fallthrough logic, which is intense). Anyway, assuming:
```
@http
any /*
post /api/user/:id
```
- `post` requests to `/api/user/whatever` hit `post /api/user/:id`

**Comment by ryanblock** [comment]
@kristoferjoseph super agree. I've been thinking of ways to do this that wouldn't be breaking, and I just can't come up with anything, unfortunately.

**Comment by brianleroux** [comment]
we could be additive and create a new code path for opt in. a few ways to do that. new pragma (`@https` for example) or a new flag under `@aws` like `catchall implicit|explicit` but…I think this just adds more confusion and would create MORE work to migrate not only our examples but userland. (vs the relatively small amount of work to rename `get-index` to `any-catchall`.)

**Comment by ryanblock** [comment]
Mainlined and released tonight as `8.0`!
