### ISSUE TITLE
Add ability to name GSIs in app.arc manifest

### ISSUE THREAD

**Issue by anatomic** [architect/architect#974]
**Is your feature request related to a problem? Please describe.**
As discussed on slack: https://architecture-as-text.slack.com/archives/CMK98634P/p1602001793126100 it would be great to be able to provide names for indexes as an optional override to the default naming convention. This would help with single table design patterns etc. where secondary indexes are a more common occurance

**Describe the solution you'd like**
Opt in to naming of an index by providing and extra attribute in the manifest:

```
@indexes
my-table
  email *String EmailIndex

my-table
  role *String UserRoleIndex
```

**Describe alternatives you've considered**
Could maybe look at naming the index after the attribute used for the partition key?

**Comment by ryanblock** [comment]
This customization makes sense, I can see adding this to Inventory.

**Comment by ryanblock** [comment]
Thinking about this further, I'm thinking the format should be a bit more explicit:
```
@indexes
my-table
  email *String
  name EmailIndex

my-table
  role *String
  name UserRoleIndex
```

This also fits with the more verbose format support we're adding in Inventory this year. wdyt?

**Comment by filmaj** [comment]
This would be great!

**Comment by anatomic** [comment]
Apologies that this has sat untouched for so long, but I've had a bit of time to look into it again and have updated the PR (+ created another into `inventory`) that would hopefully address this. Feel free to close if you don't think this is a requirement any more though!

**Comment by filmaj** [comment]
The architect 8.4.10 is now available on npm and includes this feature. I also added documentation for this in architect/arc.codes#331 - it's live at https://arc.codes/docs/en/reference/app.arc/indexes

Thanks @anatomic !
