### ISSUE TITLE
pathParameters missing from request payload

### ISSUE THREAD

**Issue by kristoferjoseph** [architect/architect#983]
## tl;dr
Using an http api with path parameters and the catchall parameters are missing in the request payload

## repro steps
arc file
```
@app
test-001

@http
/:param/*
```

## Expected
navigating to `/thing/stuff`
Expected request pathParameters:
`pathParameters: { param: 'things', proxy: 'stuff' }

navigating to `/thing/stuff/raccoons`
Expected request pathParameters:
`pathParameters: { param: 'things', proxy: 'stuff/raccoons' }

## Actual
navigating to `/thing/stuff`
Actual request pathParameters:
`pathParameters: { proxy: 'stuff' }

navigating to `/thing/stuff/raccoons`
results in a 404 response

**Comment by ryanblock** [comment]
Fixed in `8.0.3`!
