### ISSUE TITLE
Arc Deploy Issue using 8.0.3

### ISSUE THREAD

**Issue by jericopulvera** [architect/architect#986]
**Describe the issue**
Stack traces of the issue does not show. when running describe-stack-events.

**Steps to reproduce**
1. Deploy initial state of the project.
2. Update the primary key of your table.
3. Deploy again.

**Expected behavior**
Deployment is finished.

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):
 - OS: MacOS Mojave

**Additional context**
running aws cloudformation describe-stack-events --stack-name VgApiStaging did not show anything

**Comment by ryanblock** [comment]
Removed image from your issue, as it displayed you catting your private AWS key. YOU MUST NOW CYCLE THAT KEY IMMEDIATELY.

Re. the issue, please follow the issue template above, post your arc file and any macros being used.

**Comment by jericopulvera** [comment]
@ryanblock thank you!

I updated the issue. It would be helpful to have a reference on some of the things that can cause a deploy failure.

**Comment by ryanblock** [comment]
That's not really possible, there are an infinite number of things that could cause AWS to reject your CloudFormation deploy. (Under the hood, Architect just ships AWS CloudFormation.) I can help further when you share your `app.arc` file before and after.

**Comment by jericopulvera** [comment]
I think I'm good. aws cloudformation command just uses my default key that's why it's not showing any stack traces since I deployed the app in different profile.

Thanks for the help.
