### ISSUE TITLE
`arc deploy` of SPA prints out incorrect URL

### ISSUE THREAD

**Issue by filmaj** [architect/architect#992]
**Describe the issue**
The static-only bucket, SPA style app, after deploying with `arc deploy`, prints a slightly-wrong URL...

I'm using arc 8.1.

**Steps to reproduce**

```➜ cat app.arc
@app
blahblah

@static
folder dist
```

`dist` contains an `index.html`. The end of `arc deploy` looks like:

```
✓ Hydrate Finished checks, nothing to hydrate
⚬ Deploy Created deployment templates
✓ Deploy Generated CloudFormation deployment
✓ Deploy Deployed & built infrastructure
✓ Success! Deployed app in 13.659 seconds

    http://blahblah.s3-website-us-east-2.amazonaws.com

⚬ Deploy Deploying static assets...
✓ Deploy Skipped 5 files (already up to date)
```

The link ends up with a DNS resolution issue. Hmm...

**Expected behavior**
Turns out the URL is wrong, arc prints it out like so:

    http://blahblah.s3-website-us-east-2.amazonaws.com

... but should be like this:

    http://blahblah.s3-website.us-east-2.amazonaws.com

**Comment by ryanblock** [comment]
See: https://github.com/architect/package/blob/main/src/visitors/static/index.js#L3-L20
