### ISSUE TITLE
bodyParser ignores non base64 encoded json

### ISSUE THREAD

**Issue by mawdesley** [architect/architect#997]
**Describe the issue**
The `bodyParser` helper ignores any body which isn't base64 encoded.

**Steps to reproduce**
Example repo with steps to reproduce: https://github.com/mawdesley/arc-body-parser-issue

**Expected behavior**
```
 curl -d '{"foo": "bar"}'  -H 'Content-Type: application/json;charset=UTF-8 Accept: application/json' http://localhost:3333/
```

When I make the above curl request to the local sandbox or a lambda deployed to aws, the raw `request.body` arriving at the handler is a string `'{"foo": "bar"}'`. When passed through `bodyParser`, I would expect the result to be an object representation of that string. However, `bodyParser` is actually just returning the string representation.

Looking through the code it appears that if `request.isBase64Encoded === false`, no parsing is attempted at all

https://github.com/architect/functions/blob/791b57de62ef9ff4c8c589a30585b1870bf5e28b/src/http/helpers/body-parser.js#L19-L26

**Desktop**
Please complete the following information (if appropriate):
 - OS: MacOS High Sierra 10.13.6
 - Arc version: 8.2.1
 - Arc/functions version: 3.13.4
 - Node version: 12.13.0

**Additional context**
Happy to submit a fix if you can confirm that this is a bug and i'm not just doing something really stupid (it's been a long day 😅 )

**Comment by filmaj** [comment]
Yeah I have the same issue (I use this slightly differently - using the `http.async` help from arc/functions - but it ends up going through the same code path).

I will +1 that I find this behaviour odd as well and have the same expectations as @mawdesley. In all of my routes I basically `JSON.parse` stuff one more time even though arc should be parsing it for me. Glad to hear I'm not the only one who scratches their head at this!

What does everyone else think?

**Comment by ryanblock** [comment]
Ah, this is a great find, thank you! In `HTTP` API payloads with the Lambda v2.0 signature the default behavior for dealing with JSON bodies is unique, and it looks like I didn't add a switch for that. Please stand by as I investigate further!

**Comment by ryanblock** [comment]
Patched here, will be out in a few mins. https://github.com/architect/functions/pull/298 Thanks again for the heads up @mawdesley!
